JOBS: exportar especialidades
andes/api pull request #1027
Opened 2020-07-03 17:40 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-32
 
### Funcionalidad desarrollada 
1. Se agrega job para exportar a sql los profesionales con su especialidad

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si https://gist.github.com/juuliotero/91ef8aa60d6efe04f52f4bfd03ae1475
- [ ] No

2020-09-24 18:01 UTC, liquid36 commented
@kroce @silviroa Con esto que va a pasar?

2020-10-16 16:41 UTC, martinebucarey commented
> @kroce @silviroa Con esto que va a pasar?

Subí modificación tanto en el job como el la query para que antes de exportar llame a la ruta delete para borrar los existentes y se agrega el param fecha=new Date() para que la query haga un match solo con los profesionales actualizados/creados en el dia (El job se correría diariamente).

2020-10-20 14:31 UTC, kroce requested changes
Agregaría en la tabla sql la fecha de actualización del registro

2020-10-20 18:13 UTC, martinebucarey commented
> Agregaría en la tabla sql la fecha de actualización del registro

Hecho

2020-10-28 13:12 UTC, kroce approved these changes

2020-10-28 13:16 UTC, condorpiedra approved these changes

2020-10-28 13:17 UTC, merged