Permisos: nuevos permisos para modulo visualizacion de informacion
andes/api pull request #1091
Opened 2020-09-02 18:21 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-53

### Funcionalidad desarrollada 

1. Se agregan como hijos del permiso visualizacionInformacion reportes  y dashboards con sus descendientes
2. Se agrega el permiso biQueries como hijo del permiso visualizacionInformacion.
3. Se crea Script para actualizar los permisos existentes dada la nueva organización.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

[actualizacionPermisosInformacion.txt](https://github.com/andes/api/files/5163862/actualizacionPermisosInformacion.txt)

Ejecutar en shell de mongo.
El script realiza una búsqueda por toda la colección AuthUsers y verifica si en cada organización que tenga el usuario posee permisos para reportes o dashboard, en caso de que así sea modifica el permiso agregándole la palabra "visualizacionInformacion:" por delante para que funcione de manera correcta con la modificación actual.

2020-09-10 13:00 UTC, kroce requested changes
Sugiero realizar todos los cambios de la BD en un único script (dentro de la carpeta scripts)

2020-09-10 16:26 UTC, martinebucarey commented
> Sugiero realizar todos los cambios de la BD en un único script (dentro de la carpeta scripts)

Hecho

2020-09-11 13:33 UTC, kroce approved these changes

2020-09-11 13:41 UTC, palita1991 approved these changes

2020-09-11 14:17 UTC, merged