GDU: perfiles:write visibility restricted
andes/api pull request #1093
Opened 2020-09-03 14:16 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/GDU-22
### Funcionalidad desarrollada 

1. perfiles:write visibility restricted
2. 
3. 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/GDU-22
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-09-15 15:21 UTC, liquid36 commented
BUILD NUMBER: [1805](http://condorpiedra.andes.gob.ar:85/1805/mochawesome.html)
TEST START: 2020-09-15T15:21:41.864Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-16 13:24 UTC, kroce requested changes
No tendría sentido el nivel write, dejaría el permiso de perfiles en el mismo nivel del read y write. Si se habilita, lo q se habilita es la edicion. 
![Captura de pantalla -2020-09-16 10-29-59](https://user-images.githubusercontent.com/18030170/93344074-a54d7d80-f807-11ea-93ea-a49767a69539.png)

2020-09-16 15:48 UTC, plammel commented
> No tendría sentido el nivel write, dejaría el permiso de perfiles en el mismo nivel del read y write. Si se habilita, lo q se habilita es la edicion.
> ![Captura de pantalla -2020-09-16 10-29-59](https://user-images.githubusercontent.com/18030170/93344074-a54d7d80-f807-11ea-93ea-a49767a69539.png)

Hecho!

2020-09-16 17:24 UTC, liquid36 commented
BUILD NUMBER: [1820](http://condorpiedra.andes.gob.ar:85/1820/mochawesome.html)
TEST START: 2020-09-16T17:24:18.583Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-16 17:28 UTC, palita1991 approved these changes

2020-09-22 13:22 UTC, kroce requested changes
@plammel fijate que en las rutas de perfiles está verificando por el permiso usuarios:perfiles:write

2020-09-22 16:01 UTC, plammel commented
> @plammel fijate que en las rutas de perfiles está verificando por el permiso usuarios:perfiles:write

Actualizado!

2020-09-23 12:39 UTC, kroce approved these changes

2020-09-23 12:59 UTC, palita1991 approved these changes

2020-09-23 13:01 UTC, merged