MPI - Job para actualización de datos en pacientes validados
andes/api pull request #1098
Opened 2020-09-04 12:40 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-137

### Funcionalidad desarrollada 

1. Tarea que busca 500 pacientes que no hayan sido actualizados en los ultimos 2 meses y actualiza su foto, dirección legal y fecha de fallecimiento contra renaper.
2. Corrección de logs en mpi corrector job.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-09-08 17:53 UTC, condorpiedra requested changes

2020-09-08 17:53 UTC, condorpiedra commented on core/mpi/controller/updateValidados.ts
> +import { log as andesLog } from '@andes/log';
Actualizar a la nueva versión de logs (versión 2.0.0)

2020-09-08 18:00 UTC, liquid36 commented
BUILD NUMBER: 1718
TEST START: 2020-09-08T18:00:19.199Z
TOTAL: 299
SUCCESS: 295
FAIL: 0
SKIPPED: 4

2020-09-30 19:51 UTC, liquid36 commented
BUILD NUMBER: [2008](http://condorpiedra.andes.gob.ar:85/2008/mochawesome.html)
TEST START: 2020-09-30T19:51:02.832Z
TOTAL: 301
SUCCESS: 301
FAIL: -1
SKIPPED: 1

2020-10-01 14:45 UTC, liquid36 commented on core/mpi/controller/updateValidados.ts
> +        let pacientes = await paciente.find({ updatedAt: { $lte: fechaDesde } }).limit(limit);
1. No hay indice por fecha updateAt
2. Haría un sort así garantizamos el orden.
3. Crearía un campo nuevo tipo 'validadoAt' , sino es de nunca acabar. Cuando validadas un paciente lo vuelve a poner en cola porque se actualiza la fecha updateAt. 
4. No tiene control si es validado, tratar de validar un temporal no se si esta bien. Lo mismo con los inactivos.

2020-10-05 18:35 UTC, condorpiedra commented on core/mpi/controller/updateValidados.ts
> +        let pacientes = await paciente.find({ updatedAt: { $lte: fechaDesde } }).limit(limit);
- Se cambia filtro de pacientes a actualizar de acuerdo a validado, activo y updateAt.  Se crea índice correspondiente. 
- Agrega las opciones de sort y limit.  
- Agrega el campo validadoAt pero no se utiliza como condición en el job, ya que lo que se buscar es una verificación periódica de la colección paciente para detectar fallecidos o actualizaciones de sus datos básicos, que se pueden realizar en cualquier momento.
-Utiliza las nuevas rutas de pacientes

2020-10-07 19:16 UTC, liquid36 commented on core/mpi/controller/updateValidados.ts
> +        await logUpdateValidados.error('update-validados-error', err, userScheduler);
ojo con esto, el -ok y el -error están de mas. Para algo se usa el .info y el .error.

2020-10-15 17:30 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2208](http://condorpiedra.andes.gob.ar:85/2208/mochawesome.html)
CYPRESS RUN: [1390](https://dashboard.cypress.io/projects/xr7gft/runs/1390/specs)
TEST START: 2020-10-15T17:30:10.974Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-16 15:17 UTC, MCele approved these changes

2020-10-16 15:25 UTC, condorpiedra commented on core/mpi/controller/updateValidados.ts
> +        await logUpdateValidados.error('update-validados-error', err, userScheduler);
se quitan los logs

2020-10-16 15:27 UTC, condorpiedra approved these changes

2020-10-16 15:43 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2230](http://condorpiedra.andes.gob.ar:85/2230/mochawesome.html)
CYPRESS RUN: [1411](https://dashboard.cypress.io/projects/xr7gft/runs/1411/specs)
TEST START: 2020-10-16T15:42:58.937Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-16 15:55 UTC, merged