MPI - Modificaciones en importación de nacidos vivos
andes/api pull request #1102
Opened 2020-09-08 11:57 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-236

### Funcionalidad desarrollada 

1. Se modificó la carga del bebe y su relación con el tutor teniendo en cuenta la posibilidad de que el primero podría estar ya registrado como paciente temporal e incluso existir la relación con el tutor.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-09-08 17:50 UTC, condorpiedra requested changes

2020-09-08 17:50 UTC, condorpiedra commented on core/mpi/jobs/nacimientosProcess.ts
> +import { logNacimiento } from '../mpi.log';
Debería ser hacer referencia a pacientes

2020-09-15 14:17 UTC, liquid36 commented
BUILD NUMBER: [1802](http://condorpiedra.andes.gob.ar:85/1802/mochawesome.html)
TEST START: 2020-09-15T14:16:48.117Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-16 16:20 UTC, condorpiedra approved these changes

2020-09-16 17:36 UTC, MCele approved these changes

2020-09-16 17:37 UTC, merged