GDU: incluye email y teléfono a usuario de ldap
andes/api pull request #1107
Opened 2020-09-15 13:37 UTC by plammel

### Requerimiento

### Funcionalidad desarrollada 

1.  incluye email y teléfono a usuario de ldap al conectarse.
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-09-18 18:43 UTC, liquid36 commented
BUILD NUMBER: [1860](http://condorpiedra.andes.gob.ar:85/1860/mochawesome.html)
TEST START: 2020-09-18T18:42:54.075Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-21 13:04 UTC, sychus reviewed
Propongo usar authentication.andes.gob.ar ya que resuelve todo esto.

2020-09-22 18:30 UTC, sychus approved these changes
El código parece correcto, me quedaría hacer unos test. :-)

2020-09-23 13:11 UTC, sychus requested changes
@plammel si bien el proceso que hiciste está todo bien. En el llamado a la función como el objeto que devuelve es un array, no se está actualizando bien authUser (nombre y apellido en la BD)

2020-09-23 17:25 UTC, plammel commented
> @plammel si bien el proceso que hiciste está todo bien. En el llamado a la función como el objeto que devuelve es un array, no se está actualizando bien authUser (nombre y apellido en la BD)

Actualizado!

2020-09-24 21:03 UTC, sychus requested changes
@plammel encontre un tema importante que hay que resolver. En el caso que el servidor esté caido o no se encuentre falla y no entra por caché. Para solucionarlo se podría hacer lo siguiente:
async function authAlive() {
    try {
        const url = `${configPrivate.hosts.authenticationAndes}/alive`;
        const options = {
            url,
            method: 'GET',
            json: true
        };
        return await handleHttpRequest(options);
    } catch (err) {
        return null (o algo más lindo... :-))
    }
}
Luego en el if(await alive()) va a detectar el null (o la mejora que le pongas) entonces ahí si entra en la cache y va perfecto.
Con eso estaríamos para  hacerle alto test!! y meterlo a prod. ;-)

2020-09-24 21:03 UTC, sychus commented on auth/ldap.controller.ts
> +const isReachable = require('is-reachable');
no lo usamos mas me parece...

2020-09-24 21:04 UTC, sychus commented on auth/ldap.controller.ts
> +const isReachable = require('is-reachable');
recomiendo también que hagas un rebase porque actualizaron algunas librerías y sino te tira algunos palos que nada que ver.

2020-09-25 13:35 UTC, plammel commented on auth/ldap.controller.ts
> +const isReachable = require('is-reachable');
> no lo usamos mas me parece...

`isReachable` se está usando en la función `getUserInfo`. Si no se usa esta función tampoco, borramos el archivo de controller directamente.

2020-09-28 11:49 UTC, sychus approved these changes
Copado... quedaría hacerle unos cuantos test.

2020-10-01 14:29 UTC, liquid36 commented
BUILD NUMBER: [2013](http://condorpiedra.andes.gob.ar:85/2013/mochawesome.html)
TEST START: 2020-10-01T14:28:19.910Z
TOTAL: 66
SUCCESS: 5
FAIL: 61
SKIPPED: 0

2020-10-03 04:40 UTC, sychus commented
@plammel revisarias el tema de la falla de los test?

2020-10-09 15:18 UTC, liquid36 commented
BUILD NUMBER: [2151](http://condorpiedra.andes.gob.ar:85/2151/mochawesome.html)
TEST START: 2020-10-09T15:18:01.166Z
TOTAL: 301
SUCCESS: 286
FAIL: 15
SKIPPED: 0

2020-10-09 17:16 UTC, liquid36 commented
BUILD NUMBER: [2156](http://condorpiedra.andes.gob.ar:85/2156/mochawesome.html)
TEST START: 2020-10-09T17:16:26.438Z
TOTAL: 301
SUCCESS: 285
FAIL: 16
SKIPPED: 0

2020-10-09 17:30 UTC, liquid36 commented
BUILD NUMBER: [2158](http://condorpiedra.andes.gob.ar:85/2158/mochawesome.html)
TEST START: 2020-10-09T17:30:40.987Z
TOTAL: 301
SUCCESS: 286
FAIL: 15
SKIPPED: 0

2020-10-14 14:41 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2185](http://condorpiedra.andes.gob.ar:85/2185/mochawesome.html)
CYPRESS RUN: [1371](https://dashboard.cypress.io/projects/xr7gft/runs/1371/specs)
TEST START: 2020-10-14T14:41:42.692Z
TOTAL: 305
SUCCESS: 286
FAIL: 19
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-15 13:40 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2197](http://condorpiedra.andes.gob.ar:85/2197/mochawesome.html)
CYPRESS RUN: [1379](https://dashboard.cypress.io/projects/xr7gft/runs/1379/specs)
TEST START: 2020-10-15T13:40:07.705Z
TOTAL: 305
SUCCESS: 288
FAIL: 17
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-15 14:06 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2199](http://condorpiedra.andes.gob.ar:85/2199/mochawesome.html)
CYPRESS RUN: [1381](https://dashboard.cypress.io/projects/xr7gft/runs/1381/specs)
TEST START: 2020-10-15T14:05:49.728Z
TOTAL: 305
SUCCESS: 289
FAIL: 16
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-16 13:29 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2225](http://condorpiedra.andes.gob.ar:85/2225/mochawesome.html)
CYPRESS RUN: [1407](https://dashboard.cypress.io/projects/xr7gft/runs/1407/specs)
TEST START: 2020-10-16T13:29:11.352Z
TOTAL: 275
SUCCESS: 274
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-19 13:25 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2248](http://condorpiedra.andes.gob.ar:85/2248/mochawesome.html)
CYPRESS RUN: [1426](https://dashboard.cypress.io/projects/xr7gft/runs/1426/specs)
TEST START: 2020-10-19T13:24:53.663Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2021-01-13 17:25 UTC, liquid36 commented
@sychus Tus chicos de plataforma tiene todo preparado para modo producción de esto? Hay que incorporar los ultimos cambios en ese MS o que onda?

2021-01-14 00:06 UTC, sychus commented
> @sychus Tus chicos de plataforma tiene todo preparado para modo producción de esto? Hay que incorporar los ultimos cambios en ese MS o que onda?

Sí el microservicio esta arriba. Tendriamos q probarlo en demo

2021-07-14 11:24 UTC, closed without merging