MISC: refactor pdf PUCO
andes/api pull request #1111
Opened 2020-09-17 18:40 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MISC-72
### Funcionalidad desarrollada 

1. Refactor de descarga de constancia de PUCO.

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/MISC-72
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-09-17 18:42 UTC, plammel commented
Falta ajustar alto del header 
![image](https://user-images.githubusercontent.com/25707055/93513503-55041780-f8fc-11ea-8607-1d6a344ec423.png)

2020-09-18 18:34 UTC, liquid36 commented
BUILD NUMBER: [1858](http://condorpiedra.andes.gob.ar:85/1858/mochawesome.html)
TEST START: 2020-09-18T18:34:44.500Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-24 14:42 UTC, palita1991 requested changes
@plammel 
1)Revisar conflictos
2) Detalles que vi en el pdf:
- Al imprimir la constatación, en el titulo no se ve la palabra **"PUCO"** como en DEMO
![image](https://user-images.githubusercontent.com/30004190/94159915-7ca63300-fe5a-11ea-8f05-d94fd7b5085c.png)
**DEMO**
![image](https://user-images.githubusercontent.com/30004190/94160213-c7c04600-fe5a-11ea-9d9f-1ec3549ea04b.png)

- También al imprimir la constatación, en la fecha de verificación el mes está en ingles.

![image](https://user-images.githubusercontent.com/30004190/94159596-1c16f600-fe5a-11ea-8843-9c8be8cda17b.png)

2020-09-24 16:09 UTC, plammel commented
> @plammel
> 1)Revisar conflictos
> 2) Detalles que vi en el pdf:
> 
> * Al imprimir la constatación, en el titulo no se ve la palabra **"PUCO"** como en DEMO
>   ![image](https://user-images.githubusercontent.com/30004190/94159915-7ca63300-fe5a-11ea-8f05-d94fd7b5085c.png)
>   **DEMO**
>   ![image](https://user-images.githubusercontent.com/30004190/94160213-c7c04600-fe5a-11ea-9d9f-1ec3549ea04b.png)
> * También al imprimir la constatación, en la fecha de verificación el mes está en ingles.
> 
> ![image](https://user-images.githubusercontent.com/30004190/94159596-1c16f600-fe5a-11ea-8843-9c8be8cda17b.png)

Correcciones hechas!

2020-09-24 17:03 UTC, liquid36 commented
BUILD NUMBER: [1952](http://condorpiedra.andes.gob.ar:85/1952/mochawesome.html)
TEST START: 2020-09-24T17:02:53.404Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-09-24 17:28 UTC, palita1991 approved these changes

2020-09-25 14:50 UTC, kroce approved these changes

2020-09-25 14:52 UTC, merged