MPI: migracion de CDAs a core_v2
andes/api pull request #1112
Opened 2020-09-18 14:27 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MPI-227
### Funcionalidad desarrollada 

1. migracion de CDAs a core_v2 
2. 
3. 

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/MPI-227
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2020-09-18 17:13 UTC, liquid36 commented
BUILD NUMBER: [1855](http://condorpiedra.andes.gob.ar:85/1855/mochawesome.html)
TEST START: 2020-09-18T17:12:34.513Z
TOTAL: 173
SUCCESS: 151
FAIL: 21
SKIPPED: 1

2020-09-18 17:30 UTC, liquid36 commented
BUILD NUMBER: [1856](http://condorpiedra.andes.gob.ar:85/1856/mochawesome.html)
TEST START: 2020-09-18T17:30:31.556Z
TOTAL: 297
SUCCESS: 297
FAIL: -1
SKIPPED: 1

2020-10-05 18:47 UTC, condorpiedra requested changes

2020-10-05 18:47 UTC, condorpiedra commented on modules/cda/controller/CDAPatient.ts
> +            const realPac = await Paciente.findById(dataPaciente.id);
Cambiar por PacienteCtr.findById

2020-10-05 18:47 UTC, condorpiedra commented on modules/cda/controller/CDAPatient.ts
> +                const query = await Paciente.find({
Cambiar por PacienteCtr.search(

2020-10-05 18:47 UTC, condorpiedra commented on modules/cda/controller/CDAPatient.ts
> +import { PacienteCtr } from '../../../core-v2/mpi/paciente/paciente.routes';
Está dos veces importado

2020-10-15 17:46 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2210](http://condorpiedra.andes.gob.ar:85/2210/mochawesome.html)
CYPRESS RUN: [1392](https://dashboard.cypress.io/projects/xr7gft/runs/1392/specs)
TEST START: 2020-10-15T17:46:03.300Z
TOTAL: 322
SUCCESS: 315
FAIL: 7
SKIPPED: 0

2020-10-15 20:25 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2218](http://condorpiedra.andes.gob.ar:85/2218/mochawesome.html)
CYPRESS RUN: [1400](https://dashboard.cypress.io/projects/xr7gft/runs/1400/specs)
TEST START: 2020-10-15T20:25:20.953Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-30 12:56 UTC, liquid36 approved these changes

2020-10-30 14:10 UTC, merged