RUP: migración recursos paciente a core v2
andes/api pull request #1113
Opened 2020-09-18 18:13 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MPI-229
### Funcionalidad desarrollada 

1. migración recursos paciente a core v2
2. 
3. 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MPI-229
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-09-20 04:12 UTC, sychus approved these changes

2020-09-28 17:30 UTC, liquid36 requested changes

2020-09-28 17:30 UTC, liquid36 commented on modules/rup/routes/hudsExtras.ts
> +import { Paciente } from '../../../core-v2/mpi/paciente/paciente.schema';
Esta mal acceder directo al schema desde un modulo fuera de MPI. Por algo están los controladores.

2020-09-28 17:30 UTC, liquid36 commented on modules/rup/routes/hudsExtras.ts
> +    Paciente.findById(pacienteId).then(async paciente => {
Aprovecha y cambiar async/await.

2020-09-29 18:18 UTC, liquid36 commented
BUILD NUMBER: [1988](http://condorpiedra.andes.gob.ar:85/1988/mochawesome.html)
TEST START: 2020-09-29T18:18:36.008Z
TOTAL: 301
SUCCESS: 299
FAIL: 1
SKIPPED: 1

2020-10-08 14:12 UTC, liquid36 requested changes
los cambios iban para todos los archivos, el que te señale era uno de ejemplo

2020-10-15 20:18 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2217](http://condorpiedra.andes.gob.ar:85/2217/mochawesome.html)
CYPRESS RUN: [1399](https://dashboard.cypress.io/projects/xr7gft/runs/1399/specs)
TEST START: 2020-10-15T20:18:05.157Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-30 11:03 UTC, liquid36 approved these changes

2020-10-30 14:06 UTC, merged