RUP - Inicio de prestación para turno con múltiples profesionales
andes/api pull request #1132
Opened 2020-10-01 18:46 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-193

### Funcionalidad desarrollada 

1. Verifica que no exista una prestación asociada al turno. De ser asi devuelve error.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-10-02 16:50 UTC, liquid36 commented
BUILD NUMBER: [2037](http://condorpiedra.andes.gob.ar:85/2037/mochawesome.html)
TEST START: 2020-10-02T16:50:14.815Z
TOTAL: 311
SUCCESS: 311
FAIL: 0
SKIPPED: 0

2020-10-02 16:55 UTC, palita1991 requested changes
Revisión en paralelo con dos distintos profesionales
1) Profesional 1 inicio prestación
2) Profesional 2 quizo iniciar prestación, salió el cartel de que ya estaba iniciada la misma (Lo cual es correcto)
3) Luego de que el profesional 1 guardó y validó la prestación, al acceder a la HUDS del paciente se puede observar en el tab "Accesos a la HUDS"  que aunque solo un profesional fue el que inicio la prestación, salen como que ambos accedieron por consulta de medicina general. 
![image](https://user-images.githubusercontent.com/30004190/94948725-25d1d680-04b6-11eb-952f-45447b51499d.png)

2020-10-05 14:10 UTC, liquid36 commented
BUILD NUMBER: [2054](http://condorpiedra.andes.gob.ar:85/2054/mochawesome.html)
TEST START: 2020-10-05T14:10:16.918Z
TOTAL: 312
SUCCESS: 312
FAIL: 0
SKIPPED: 0

2020-10-05 14:54 UTC, negro89 commented
> Revisión en paralelo con dos distintos profesionales
> 
> 1. Profesional 1 inicio prestación
> 2. Profesional 2 quizo iniciar prestación, salió el cartel de que ya estaba iniciada la misma (Lo cual es correcto)
> 3. Luego de que el profesional 1 guardó y validó la prestación, al acceder a la HUDS del paciente se puede observar en el tab "Accesos a la HUDS"  que aunque solo un profesional fue el que inicio la prestación, salen como que ambos accedieron por consulta de medicina general.
>    ![image](https://user-images.githubusercontent.com/30004190/94948725-25d1d680-04b6-11eb-952f-45447b51499d.png)

Resuelto en app !

2020-10-05 17:24 UTC, palita1991 commented
> Revisión en paralelo con dos distintos profesionales
> 
> 1. Profesional 1 inicio prestación
> 2. Profesional 2 quizo iniciar prestación, salió el cartel de que ya estaba iniciada la misma (Lo cual es correcto)
> 3. Luego de que el profesional 1 guardó y validó la prestación, al acceder a la HUDS del paciente se puede observar en el tab "Accesos a la HUDS"  que aunque solo un profesional fue el que inicio la prestación, salen como que ambos accedieron por consulta de medicina general.
>    ![image](https://user-images.githubusercontent.com/30004190/94948725-25d1d680-04b6-11eb-952f-45447b51499d.png)

Resuelto

2020-10-06 11:51 UTC, palita1991 approved these changes

2020-10-09 16:28 UTC, juuliotero approved these changes

2020-11-05 18:13 UTC, liquid36 approved these changes

2020-11-05 18:21 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2540](http://condorpiedra.andes.gob.ar:85/2540/mochawesome.html)
CYPRESS RUN: [1699](https://dashboard.cypress.io/projects/xr7gft/runs/1699/specs)
TEST START: 2020-11-05T18:21:20.295Z
TOTAL: 317
SUCCESS: 316
FAIL: 1
SKIPPED: 0

2020-11-05 18:32 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2541](http://condorpiedra.andes.gob.ar:85/2541/mochawesome.html)
CYPRESS RUN: [1700](https://dashboard.cypress.io/projects/xr7gft/runs/1700/specs)
TEST START: 2020-11-05T18:32:40.950Z
TOTAL: 335
SUCCESS: 335
FAIL: 0
SKIPPED: 0

2020-11-06 13:26 UTC, merged