MISC: unificacion de makeFs
andes/api pull request #1139
Opened 2020-10-06 16:17 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MISC-97
### Funcionalidad desarrollada 

1. Unifica la funcionalidad de `mongoose-gridfs` en un único archivo

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MISC-97
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-10-09 15:29 UTC, liquid36 commented
BUILD NUMBER: [2153](http://condorpiedra.andes.gob.ar:85/2153/mochawesome.html)
TEST START: 2020-10-09T15:29:22.975Z
TOTAL: 318
SUCCESS: 317
FAIL: 1
SKIPPED: 0

2020-10-09 17:23 UTC, liquid36 commented
BUILD NUMBER: [2157](http://condorpiedra.andes.gob.ar:85/2157/mochawesome.html)
TEST START: 2020-10-09T17:23:33.015Z
TOTAL: 317
SUCCESS: 317
FAIL: 0
SKIPPED: 0

2020-10-20 23:05 UTC, liquid36 requested changes
Tener en cuenta que CDA, Novedades y COM utilizan archivos.

2020-10-21 15:27 UTC, liquid36 commented
Y matriculaciones

2020-10-21 17:57 UTC, plammel commented
> Tener en cuenta que CDA, Novedades y COM utilizan archivos.

Al alcance de este PR solo comprende la magración del `RupStore` de RUP. Los stores de los demás módulos se irán reemplazando progresivamente.

2020-11-05 18:43 UTC, liquid36 approved these changes

2020-11-06 13:17 UTC, merged