DESCARGAS - generación de formulario recupero de costo
andes/api pull request #1142
Opened 2020-10-07 11:36 UTC by rodrigokokot

### Requerimiento

### Funcionalidad desarrollada 

1.  A partir de una solicitud tipo post, se genera un formulario pdf con los datos enviados para el recupero de costo

### UserStories llegó a completarse

- [ ] Si
- [X] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

Datos a enviar en solicitud post. Ej:
  ```
{   
    "efector": "HOSPITAL DR. ALFREDO RIZO ESPARZA",
    "efectorCodigoSisa": "123456789012345",
    "nombre": "PACIENTE NOMBRE",
    "dni": "11111111",
    "sexo": "masculino",
    "edad": "37 años",
    "horaInicio": "02/10/2020 VIE.",
    "tipoPrestacion": "Consulta de clínica médica",
    "obraSocial": "OSP,
    "codigoOs": "111111"
}
  ```

2020-10-08 12:16 UTC, liquid36 requested changes
Buenas! Tomaron de ejemplo una forma de generar PDF obsoleta. Hace dos semanas subio el último refactor

Les dejo Pull request asociados al cambio: 

https://github.com/andes/api/pull/982
https://github.com/andes/api/pull/1111
https://github.com/andes/api/pull/1008

2020-10-13 16:14 UTC, liquid36 approved these changes
Aplique un pequeño cambio en el nombre de la ruta, todo lo demás bien.

2020-10-13 16:15 UTC, liquid36 commented
Pregunta: 
![image](https://user-images.githubusercontent.com/3813270/95887330-16744800-0d56-11eb-8030-db0326d8b6f2.png)

Ustedes lo ven así? Lo voy a probar en nuestro servidores, puede ser mi versión local.

2020-10-19 12:31 UTC, Sebassss approved these changes

2020-10-21 13:22 UTC, merged