Job para actualizar bebes sin dni y obtener modificaciones
andes/api pull request #1145
Opened 2020-10-08 14:46 UTC by MCele

### Requerimiento

Se agrega en el job de nacidos actualización de bebés sin dni y obtener modificaciones por fecha
https://proyectos.andes.gob.ar/browse/MPI-251

### Funcionalidad desarrollada 

Se agrega en el job de nacidos:
1.  actualización de bebés sin dni que contendan el número de certificado Renaper obtenido de la importación de los nacidos,
2.  una importación de todos los pacientes que fueron modificados en la fecha actual y se los actualiza de acuerdo al dato de cetificado renaper.

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-10-08 17:06 UTC, GaboCancellieri commented on core/mpi/jobs/nacimientosProcess.ts
> +    if (resultado && resultado.validado) {
este if quizá abarca mucho código, puede simplificarse negándo la condicion y adentro directamente poner un return para salir.

2020-10-08 17:28 UTC, liquid36 commented
BUILD NUMBER: [2134](http://condorpiedra.andes.gob.ar:85/2134/mochawesome.html)
TEST START: 2020-10-08T17:28:25.796Z
TOTAL: 302
SUCCESS: 302
FAIL: 0
SKIPPED: 0

2020-10-13 16:22 UTC, MCele commented on core/mpi/jobs/nacimientosProcess.ts
> +    if (resultado && resultado.validado) {
gracias por la sugerencia, ahí quedó el cambio!

2020-10-16 17:55 UTC, condorpiedra requested changes
Las funciones agregarDocumentosFaltantes y obtenerModificaciones hacen prácticamente lo mismo.  Sería ideal unificarlas para no repetir código.

2020-10-30 16:17 UTC, condorpiedra approved these changes

2020-10-30 16:34 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2468](http://condorpiedra.andes.gob.ar:85/2468/mochawesome.html)
CYPRESS RUN: [1632](https://dashboard.cypress.io/projects/xr7gft/runs/1632/specs)
TEST START: 2020-10-30T16:34:08.684Z
TOTAL: 333
SUCCESS: 333
FAIL: 0
SKIPPED: 0

2020-10-30 16:35 UTC, merged