MPI - script para actualizar foto/fotoId de pacientes
andes/api pull request #1146
Opened 2020-10-08 19:30 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-259

### Funcionalidad desarrollada 

1. Inserta atributo fotoId a pacientes que posean foto.
2. Actualiza foto de pacientes reemplazando el string de la imagen por el id de la foto del paciente relacionado.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No
Ejecutar job node jobs/manual.js core/mpi/jobs/updateFotoJob.js
**NOTA**: Relacionado con PR https://github.com/andes/api/pull/1143

2020-10-09 13:55 UTC, liquid36 commented
BUILD NUMBER: [2145](http://condorpiedra.andes.gob.ar:85/2145/mochawesome.html)
TEST START: 2020-10-09T13:55:46.534Z
TOTAL: 316
SUCCESS: 316
FAIL: 0
SKIPPED: 0

2020-10-16 13:40 UTC, condorpiedra requested changes

2020-10-16 13:40 UTC, condorpiedra commented on core/mpi/schemas/paciente.ts
> +    fotoId: String,
fotoId debería se un objectId

2020-10-16 13:40 UTC, condorpiedra commented on core/mpi/controller/updateFoto.ts
> +                for (let rel of pac.relaciones) {
Habria que actualizar todos los lugares donde el paciente es una relación y sólo el campo fotoId

2020-10-20 16:06 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2272](http://condorpiedra.andes.gob.ar:85/2272/mochawesome.html)
CYPRESS RUN: [1447](https://dashboard.cypress.io/projects/xr7gft/runs/1447/specs)
TEST START: 2020-10-20T16:06:08.400Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-20 17:26 UTC, MCele approved these changes

2020-10-21 12:16 UTC, condorpiedra approved these changes

2020-10-21 12:16 UTC, merged