CIT: incluye fuera de agendas a historial de citas
andes/api pull request #1155
Opened 2020-10-16 17:14 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-76
### Funcionalidad desarrollada 

1. incluye fuera de agendas a historial de citas

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/CIT-76
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-10-16 17:32 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2234](http://condorpiedra.andes.gob.ar:85/2234/mochawesome.html)
CYPRESS RUN: [1414](https://dashboard.cypress.io/projects/xr7gft/runs/1414/specs)
TEST START: 2020-10-16T17:31:54.038Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-19 11:50 UTC, juuliotero commented on modules/rup/controllers/prestacion.ts
> +export async function getFueraAgendasByPaciente(pacienteId) {
La función debería ser más general, para poder usarse en otros casos y no sea tan específica al caso de prestaciones fuera de agenda.

2020-10-19 11:50 UTC, juuliotero commented on modules/rup/controllers/prestacion.ts
> +export async function getHistorialFueraAgendas(pacienteId) {
está función _getHistorialFueraDeAgenda_ debería estar en un lugar más propio a CITAS y no en el controller de prestación

2020-10-19 12:16 UTC, juuliotero commented on modules/rup/controllers/prestacion.ts
> +export async function getHistorialFueraAgendas(pacienteId) {
En el caso de que la prestación de inicie desde una solicitud, queda el inicio como 'top', no 'fuera-agenda', pero

2020-10-21 11:26 UTC, juuliotero approved these changes

2020-10-21 11:29 UTC, palita1991 approved these changes

2020-10-21 13:55 UTC, liquid36 requested changes

2020-10-21 13:55 UTC, liquid36 commented on modules/turnos/controller/historialCitasController/historialCitasController.ts
> +        $or: [
Las prestaciones fuera de agenda son los que no tienen 'solicitud.turno'. La variable inicio de prestacion es para detectar desde donde arranca una prestación. 
Ese $or como esta no va a funcionar en producción.

2020-10-21 14:15 UTC, kroce requested changes
Sugiero limitar el historial en el tiempo. En principio que muestre solo lo de los últimos 6 meses.

2020-11-11 15:20 UTC, kroce requested changes
no están los cambios sugeridos

2020-11-16 13:48 UTC, kroce commented on modules/turnos/controller/historialCitasController/historialCitasController.ts
> +        $or: [
Se quitó el or

2020-11-16 13:49 UTC, kroce approved these changes

2020-11-16 14:22 UTC, merged