ObraSocial: se loguea codigoPuco de obra social no existente
andes/api pull request #1158
Opened 2020-10-19 13:48 UTC by MCele

### Requerimiento

Se loguea codigo de la obra social que viene de puco, no existente en la colección de obras sociales.
https://proyectos.andes.gob.ar/browse/MISC-100

### Funcionalidad desarrollada 

1. Se handlea el error de obras sociales que se traen de Puco y que no están en la colección de obra social, y se loggea el código para identificar las faltantes.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-10-19 16:27 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2252](http://condorpiedra.andes.gob.ar:85/2252/mochawesome.html)
CYPRESS RUN: [1430](https://dashboard.cypress.io/projects/xr7gft/runs/1430/specs)
TEST START: 2020-10-19T16:27:24.031Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

2020-10-19 17:09 UTC, liquid36 requested changes

2020-10-19 17:09 UTC, liquid36 commented on modules/turnos/citasLog.ts
> +export const obraSocialLog = new Logger({ connection: Connections.logs, module: 'citas', type: 'obra-social', application: 'andes', bucketBy: 'h' });
Este logger debería estar en la carpeta de obra Social, y el module es `obraSocial`

2020-10-19 17:09 UTC, liquid36 commented on modules/obraSocial/routes/obraSocial.ts
> +                        obraSocialLog.error('Error falta cargar obra social en su coleccion', { codigoPuco: rta[i].codigoOS }, null, userScheduler);
el primer argumento es la acción que se ejecuto. Con la función `error` ya estamos indicando que es un error. 

Sería algo mas apropiado algo así:
```suggestion
                        obraSocialLog.error('find', { codigoPuco: rta[i].codigoOS }, null, userScheduler);
```

2020-10-20 12:44 UTC, MCele commented on modules/obraSocial/routes/obraSocial.ts
> +                        obraSocialLog.error('Error falta cargar obra social en su coleccion', { codigoPuco: rta[i].codigoOS }, null, userScheduler);
Es verdad, lo corrijo gracias!

2020-10-20 19:00 UTC, MCele commented on modules/turnos/citasLog.ts
> +export const obraSocialLog = new Logger({ connection: Connections.logs, module: 'citas', type: 'obra-social', application: 'andes', bucketBy: 'h' });
corregido!

2020-10-20 19:07 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2282](http://condorpiedra.andes.gob.ar:85/2282/mochawesome.html)
CYPRESS RUN: [1455](https://dashboard.cypress.io/projects/xr7gft/runs/1455/specs)
TEST START: 2020-10-20T19:07:29.341Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-21 11:06 UTC, liquid36 approved these changes

2020-10-21 11:54 UTC, liquid36 reviewed
Agregue interfaces y formatie el codigo para que se entienda mejor.

2020-10-21 13:25 UTC, merged