VISUALIZACION DE INFORMACION: Exportar HUDS
andes/api pull request #1161
Opened 2020-10-20 17:02 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/PRIV-52

### Funcionalidad desarrollada 

1. Se agrega permiso con visibility: 'restricted' para exportar HUDS. 
2. Agrego rutas para obtener descargas pendientes, obtener y crear peticiones de huds de un paciente.
3. Se agrega al robosender la opción para crear el archivo zip que contenga la huds de un paciente solicitada.
4. Se agrega exportHudsLog donde quedará registrada cada petición de descarga.
5. Se agrega librería archiver para crear zip.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2020-10-20 18:48 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [2280](http://condorpiedra.andes.gob.ar:85/2280/mochawesome.html)
CYPRESS RUN: [1453](https://dashboard.cypress.io/projects/xr7gft/runs/1453/specs)
TEST START: 2020-10-20T18:47:51.559Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

2020-10-30 13:27 UTC, liquid36 requested changes

2020-10-30 13:27 UTC, liquid36 commented on modules/descargas/routes/descargas.ts
> +        data.stream.on('data', (data2) => {
```suggestion
        data.stream.pipe(res);
```

2020-11-05 17:47 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [2538](http://condorpiedra.andes.gob.ar:85/2538/mochawesome.html)
CYPRESS RUN: [1697](https://dashboard.cypress.io/projects/xr7gft/runs/1697/specs)
TEST START: 2020-11-05T17:47:25.772Z
TOTAL: 335
SUCCESS: 335
FAIL: 0
SKIPPED: 0

2020-11-10 12:41 UTC, liquid36 requested changes

2020-11-10 12:41 UTC, liquid36 commented on modules/descargas/routes/descargas.ts
> +    if (req.body.pacienteId) {
Todo esto me parece que no va más.

2020-11-10 12:41 UTC, liquid36 commented on utils/exportHuds/exportHudsController.ts
> +                // tslint:disable-next-line: no-shadowed-variable
Negativo, estas cositas no valen. Tenes que cambiar los nombres de vartiables y sino se te ocurre un nombre mejor refactorizarlo en funciones mas chicas.

2020-11-10 12:41 UTC, liquid36 commented on utils/exportHuds/exportHudsController.ts
> +                archive.file(`${archivo}`, { name: `${nombreArchivo} - ${fechaArchivo}.pdf` });
Cambiaría el orden para que queda ordenado por fecha. 

```suggestion
                archive.file(`${archivo}`, { name: `${fechaArchivo} - ${nombreArchivo}.pdf` });
```

2020-11-10 12:41 UTC, liquid36 commented on modules/descargas/routes/descargas.ts
> +router.get('/pendientes', async (req, res, next) => {
Insisto con llevar esto a otro lado, y ser mas RestFull

GET /exportar-huds -> listado de peticiones
POST  /exportar-huds -> mandar a procesar
POST  /exportar-huds/:id -> obtner archivo

Que quede en el modulo "descarga" pero con ese prefix y en otro archivo.

2020-11-10 12:41 UTC, liquid36 commented on utils/roboSender/roboSender.ts
> +function changeState(env, newState, exp?) {
```suggestion
function changeState(env, newState) {
```

no va mas eso

2020-11-10 12:41 UTC, liquid36 commented on modules/descargas/routes/descargas.ts
> +router.get('/pendientes', async (req, res, next) => {
Estas rutas debería tener el chequeo de permisos.

2020-11-10 12:41 UTC, liquid36 commented on utils/exportHuds/exportHudsController.ts
> +        const prestaciones: any = await Prestacion.find(query);
```suggestion
        const prestaciones: IPrestacion[] = await Prestacion.find(query);
```

2020-11-10 13:02 UTC, liquid36 requested changes

2020-11-10 13:02 UTC, liquid36 commented on utils/exportHuds/exportHudsController.ts
> +                let informe = new InformeRUP(prestacion.id, null, peticionExport.user);
A esto le pondria un try...catch por si falla la generacion de un PDF y le agregaría un log en caso de falla.

```
exportHudsLog.error(...)
```

2020-11-18 15:30 UTC, liquid36 approved these changes
queda definir el tema del permiso

2020-11-18 16:47 UTC, martinebucarey commented
> queda definir el tema del permiso

Listo, paso el permiso a la huds

2020-11-19 12:15 UTC, kroce approved these changes

2020-11-19 12:24 UTC, merged