feat(webhook): agrega ruta para notificación
andes/api pull request #1167
Opened 2020-10-27 11:43 UTC by condorpiedra

### Requerimiento
Agrega ruta para permitir realizar notificaciones a pacientes

TODO: queda pendiente utilizar los subrecursos de pacientes, en la ruta implementada a fin de desacoplar la asignación del contacto

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [X] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-10-27 12:02 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2361](http://condorpiedra.andes.gob.ar:85/2361/mochawesome.html)
CYPRESS RUN: [1528](https://dashboard.cypress.io/projects/xr7gft/runs/1528/specs)
TEST START: 2020-10-27T12:01:52.809Z
TOTAL: 284
SUCCESS: 265
FAIL: 19
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-10-27 12:03 UTC, liquid36 requested changes

2020-10-27 12:03 UTC, liquid36 commented on modules/webhook/webhook.routes.ts
> +        query.fechaNacimiento = moment(query.fechaNacimiento, 'DD/MM/YYYY').format('YYYY-MM-DD') || null;
Yo diría que al revés, pero como opine el resto.  Capaz dejarlo listo para ambos formato.

2020-10-27 12:03 UTC, liquid36 commented on modules/webhook/webhook.routes.ts
> +        throw new PatientNotFound();
Con los pacientes que no existen que vamos hacer?

2020-10-27 12:03 UTC, liquid36 commented on modules/webhook/webhook.routes.ts
> +        throw new PatientNotFound();
Si usas try...catch diractamente devolve el error con next(), sino ponele arriba el asyncHandler.

2020-10-27 12:39 UTC, condorpiedra commented on modules/webhook/webhook.routes.ts
> +            const paciente = await post(req, res);
Se cambia este post por una función del controller

2020-10-27 12:41 UTC, condorpiedra commented on modules/webhook/webhook.routes.ts
> +        throw new PatientNotFound();
Quita  throw new PatientNotFound(); Los pacientes que no existen se crean como temporales excepto aquellos que no tienen documento, ya que sería imposible matchearlos para obtener sus laboratorios

2020-10-27 12:45 UTC, sychus approved these changes

2020-10-27 12:45 UTC, sychus commented on modules/webhook/webhook.routes.ts
> +        query.fechaNacimiento = moment(query.fechaNacimiento, 'DD/MM/YYYY').format('YYYY-MM-DD') || null;
@liquid36 que cosa al reves?

2020-10-27 12:46 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2362](http://condorpiedra.andes.gob.ar:85/2362/mochawesome.html)
CYPRESS RUN: [1529](https://dashboard.cypress.io/projects/xr7gft/runs/1529/specs)
TEST START: 2020-10-27T12:45:51.030Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-10-27 15:06 UTC, liquid36 commented on modules/webhook/webhook.routes.ts
> +        query.fechaNacimiento = moment(query.fechaNacimiento, 'DD/MM/YYYY').format('YYYY-MM-DD') || null;
El formato de la fecha. 'DD/MM/YYYY'

2020-10-27 16:44 UTC, sychus approved these changes
Ya lo había aprobado! :-)

2020-10-28 15:15 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2394](http://condorpiedra.andes.gob.ar:85/2394/mochawesome.html)
CYPRESS RUN: [1561](https://dashboard.cypress.io/projects/xr7gft/runs/1561/specs)
TEST START: 2020-10-28T15:15:30.993Z
TOTAL: 329
SUCCESS: 324
FAIL: 5
SKIPPED: 0

2020-10-28 17:00 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2404](http://condorpiedra.andes.gob.ar:85/2404/mochawesome.html)
CYPRESS RUN: [1571](https://dashboard.cypress.io/projects/xr7gft/runs/1571/specs)
TEST START: 2020-10-28T17:00:11.860Z
TOTAL: 324
SUCCESS: 323
FAIL: 1
SKIPPED: 0

2020-10-28 17:22 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2407](http://condorpiedra.andes.gob.ar:85/2407/mochawesome.html)
CYPRESS RUN: [1574](https://dashboard.cypress.io/projects/xr7gft/runs/1574/specs)
TEST START: 2020-10-28T17:22:43.241Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-10-28 17:28 UTC, merged