MPI - Logueo de reporte de errores en datos de pacientes
andes/api pull request #1171
Opened 2020-10-29 15:14 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-279

### Funcionalidad desarrollada 

1. Se crea nuevo evento donde se verifica si hubo cambio en el campo 'reportarError' de paciente
2. Se traslada actualización de georreferencia a este nuevo evento

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-10-29 15:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2431](http://condorpiedra.andes.gob.ar:85/2431/mochawesome.html)
CYPRESS RUN: [1598](https://dashboard.cypress.io/projects/xr7gft/runs/1598/specs)
TEST START: 2020-10-29T15:47:55.346Z
TOTAL: 329
SUCCESS: 329
FAIL: 0
SKIPPED: 0

2020-11-05 14:22 UTC, condorpiedra requested changes

2020-11-05 14:22 UTC, condorpiedra commented on core/mpi/controller/paciente.ts
> +                actualizarGeoReferencia(patientUpdated, patientRequest);
Falta un await

2020-11-05 18:22 UTC, liquid36 requested changes

2020-11-05 18:22 UTC, liquid36 commented on core/mpi/controller/paciente.ts
> +        EventCore.emitAsync('mpi:patient:update', pacienteOriginal, pacienteObj);
OJO porque están cambiando la lógica de los demás eventos que se subscriben. Vease webhook.

2020-11-10 16:13 UTC, condorpiedra approved these changes

2020-11-10 16:17 UTC, MCele approved these changes

2020-11-10 16:22 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2562](http://condorpiedra.andes.gob.ar:85/2562/mochawesome.html)
CYPRESS RUN: [1721](https://dashboard.cypress.io/projects/xr7gft/runs/1721/specs)
TEST START: 2020-11-10T16:22:00.561Z
TOTAL: 318
SUCCESS: 317
FAIL: 1
SKIPPED: 0

2020-11-10 16:27 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2563](http://condorpiedra.andes.gob.ar:85/2563/mochawesome.html)
CYPRESS RUN: [1722](https://dashboard.cypress.io/projects/xr7gft/runs/1722/specs)
TEST START: 2020-11-10T16:25:20.731Z
TOTAL: 19
SUCCESS: 19
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-11-10 16:34 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2564](http://condorpiedra.andes.gob.ar:85/2564/mochawesome.html)
CYPRESS RUN: [1723](https://dashboard.cypress.io/projects/xr7gft/runs/1723/specs)
TEST START: 2020-11-10T16:34:28.665Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-10 17:46 UTC, merged