MPI - Script para pacientes con fotoId pero sin foto
andes/api pull request #1175
Opened 2020-11-02 19:06 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-281

### Funcionalidad desarrollada 

1. Borra campo fotoId de los pacientes que lo posean pero no tengan foto

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-03 10:40 UTC, condorpiedra requested changes
Debería ser un script no un job

2020-11-03 18:14 UTC, negro89 commented
> Debería ser un script no un job

corregido

2020-11-04 19:22 UTC, MCele approved these changes

2020-11-05 14:07 UTC, condorpiedra approved these changes

2020-11-05 14:09 UTC, merged