MPI - Elimina rutas de auditoria en api de paciente
andes/api pull request #1180
Opened 2020-11-05 13:46 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-283

### Funcionalidad desarrollada 

1. Elimina rutas de auditoria en api de paciente

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-05 14:03 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2532](http://condorpiedra.andes.gob.ar:85/2532/mochawesome.html)
CYPRESS RUN: [1692](https://dashboard.cypress.io/projects/xr7gft/runs/1692/specs)
TEST START: 2020-11-05T13:59:24.182Z
TOTAL: 335
SUCCESS: 328
FAIL: 7
SKIPPED: 0

2020-11-05 15:03 UTC, condorpiedra requested changes

2020-11-05 15:03 UTC, condorpiedra commented on core/mpi/routes/paciente.ts
>  router.get('/pacientes/inactivos/', async (req, res, next) => {
Esta ruta se está utilizando en algún lugar?

2020-11-06 12:11 UTC, negro89 commented on core/mpi/routes/paciente.ts
>  router.get('/pacientes/inactivos/', async (req, res, next) => {
no, se suma a las eliminadas entonces

2020-11-06 13:04 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2544](http://condorpiedra.andes.gob.ar:85/2544/mochawesome.html)
CYPRESS RUN: [1703](https://dashboard.cypress.io/projects/xr7gft/runs/1703/specs)
TEST START: 2020-11-06T12:59:40.567Z
TOTAL: 80
SUCCESS: 0
FAIL: 80
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-11-06 14:13 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2547](http://condorpiedra.andes.gob.ar:85/2547/mochawesome.html)
CYPRESS RUN: [1706](https://dashboard.cypress.io/projects/xr7gft/runs/1706/specs)
TEST START: 2020-11-06T14:09:04.008Z
TOTAL: 336
SUCCESS: 330
FAIL: 6
SKIPPED: 0

2020-11-06 16:36 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2551](http://condorpiedra.andes.gob.ar:85/2551/mochawesome.html)
CYPRESS RUN: [1710](https://dashboard.cypress.io/projects/xr7gft/runs/1710/specs)
TEST START: 2020-11-06T16:35:48.249Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-13 17:09 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2605](http://condorpiedra.andes.gob.ar:85/2605/mochawesome.html)
CYPRESS RUN: [1763](https://dashboard.cypress.io/projects/xr7gft/runs/1763/specs)
TEST START: 2020-11-13T17:09:27.680Z
TOTAL: 338
SUCCESS: 338
FAIL: 0
SKIPPED: 0

2020-11-13 17:14 UTC, MCele approved these changes

2020-11-13 17:24 UTC, condorpiedra approved these changes

2020-11-13 17:24 UTC, merged