MPI - Script para eliminar foto de relaciones del paciente
andes/api pull request #1184
Opened 2020-11-05 18:41 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-282

### Funcionalidad desarrollada 

1. Script que elimina el atributo 'foto' de las relaciones de los pacientes, en caso de exisitir

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-10 17:10 UTC, sychus reviewed
No veo necesario hacer update por cada paciente.

2020-11-10 17:10 UTC, sychus commented on scripts/deleteFoto.ts
> +            await updatePaciente(pac, data, dataLog);
No sería mejor hacer el update solo para borrar la foto? sino que no haga nada.

2020-11-10 17:15 UTC, condorpiedra commented on scripts/deleteFoto.ts
> +            await updatePaciente(pac, data, dataLog);
Eso hace porque está filtrando los que tienen foto en la relacion

2020-11-17 11:35 UTC, condorpiedra requested changes

2020-11-17 11:35 UTC, condorpiedra commented on scripts/deleteFoto.ts
> +import { updatePaciente } from '../core/mpi/controller/paciente';
utilizar las nuevas rutas de pacientes

2020-11-17 13:14 UTC, negro89 commented on scripts/deleteFoto.ts
> +import { updatePaciente } from '../core/mpi/controller/paciente';
> utilizar las nuevas rutas de pacientes

actualizado!

2020-11-18 18:51 UTC, MCele approved these changes

2020-11-18 18:59 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2682](http://condorpiedra.andes.gob.ar:85/2682/mochawesome.html)
CYPRESS RUN: [1834](https://dashboard.cypress.io/projects/xr7gft/runs/1834/specs)
TEST START: 2020-11-18T18:59:07.215Z
TOTAL: 338
SUCCESS: 338
FAIL: 0
SKIPPED: 0

2020-11-18 19:01 UTC, condorpiedra approved these changes

2020-11-18 19:02 UTC, merged