Descargas: descarga reporte arancelamiento
andes/api pull request #1187
Opened 2020-11-10 20:29 UTC by plammel

### Requerimiento

### Funcionalidad desarrollada 
https://proyectos.andes.gob.ar/browse/CIT-86

1.  Archivos de descarga para reporte de Recupero
2. 
3. 

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/CIT-86
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2020-11-10 20:54 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [2569](http://condorpiedra.andes.gob.ar:85/2569/mochawesome.html)
CYPRESS RUN: [1728](https://dashboard.cypress.io/projects/xr7gft/runs/1728/specs)
TEST START: 2020-11-10T20:54:03.737Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-11 10:56 UTC, condorpiedra requested changes

2020-11-11 10:56 UTC, condorpiedra commented on core/tm/routes/profesional.ts
> -router.get('/profesionales/firma', Auth.authenticate(), async (req: any, res, next) => {
Esta ruta tiene que quedar ya que se utiliza en otras apps

2020-11-11 11:12 UTC, plammel commented on core/tm/routes/profesional.ts
> -router.get('/profesionales/firma', Auth.authenticate(), async (req: any, res, next) => {
Restaurada!

2020-11-25 15:11 UTC, MCele commented
Falla la petición a la api al intentar descargar el arancelamiento para algunos profesionales, puntualmente se noto en los casos de que el profesional no contenga un array en el campo matriculacion de formacionGrado
 Se observa un error en la consola
![errorConsola](https://user-images.githubusercontent.com/19591224/100244683-fe2b4780-2f15-11eb-99cf-fdce17693e00.png)

2020-11-26 17:19 UTC, MCele approved these changes

2020-11-30 18:44 UTC, palita1991 approved these changes

2020-12-04 02:33 UTC, condorpiedra approved these changes

2020-12-04 15:17 UTC, merged