MPI - Actualiza controller de paciente en rutas mobile
andes/api pull request #1193
Opened 2020-11-12 17:52 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-288

### Funcionalidad desarrollada 

1. Reemplaza controller viejo de pacientes en api de mobileApp

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-12 18:15 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2590](http://condorpiedra.andes.gob.ar:85/2590/mochawesome.html)
CYPRESS RUN: [1749](https://dashboard.cypress.io/projects/xr7gft/runs/1749/specs)
TEST START: 2020-11-12T18:15:40.840Z
TOTAL: 336
SUCCESS: 336
FAIL: 0
SKIPPED: 0

2020-11-13 13:57 UTC, condorpiedra requested changes
Revisar los webhooks asociados al evento mpi:patient:update

2020-11-13 13:57 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +            throw new PatientNotFound();
No es necesario si se usa try catch

2020-11-13 13:57 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +            return next(err);
Devolver el mismo error

2020-11-13 13:57 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +            const resultado: any = await findById(pacientes[index].id);
Se pueden proyectar los campos con el campo options

2020-11-19 14:06 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2693](http://condorpiedra.andes.gob.ar:85/2693/mochawesome.html)
CYPRESS RUN: [1845](https://dashboard.cypress.io/projects/xr7gft/runs/1845/specs)
TEST START: 2020-11-19T14:05:20.359Z
TOTAL: 87
SUCCESS: 0
FAIL: 87
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-11-19 14:43 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2696](http://condorpiedra.andes.gob.ar:85/2696/mochawesome.html)
CYPRESS RUN: [1848](https://dashboard.cypress.io/projects/xr7gft/runs/1848/specs)
TEST START: 2020-11-19T14:43:35.670Z
TOTAL: 344
SUCCESS: 343
FAIL: 1
SKIPPED: 0

2020-11-20 12:57 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2715](http://condorpiedra.andes.gob.ar:85/2715/mochawesome.html)
CYPRESS RUN: [1866](https://dashboard.cypress.io/projects/xr7gft/runs/1866/specs)
TEST START: 2020-11-20T12:57:18.406Z
TOTAL: 349
SUCCESS: 347
FAIL: 2
SKIPPED: 0

2020-11-20 13:14 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2718](http://condorpiedra.andes.gob.ar:85/2718/mochawesome.html)
CYPRESS RUN: [1867](https://dashboard.cypress.io/projects/xr7gft/runs/1867/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-11-20 13:20 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2719](http://condorpiedra.andes.gob.ar:85/2719/mochawesome.html)
CYPRESS RUN: [1867](https://dashboard.cypress.io/projects/xr7gft/runs/1867/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-11-20 13:36 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2720](http://condorpiedra.andes.gob.ar:85/2720/mochawesome.html)
CYPRESS RUN: [1868](https://dashboard.cypress.io/projects/xr7gft/runs/1868/specs)
TEST START: 2020-11-20T13:36:24.149Z
TOTAL: 349
SUCCESS: 349
FAIL: 0
SKIPPED: 0

2020-11-25 14:30 UTC, condorpiedra requested changes

2020-11-25 14:30 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +        const relacion = await findById(req.query.id);
Devuelve el paciente completo

2020-11-25 14:30 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +                EventCore.emitAsync('mpi:patient:update', updated);
No es necesario realizar los emitAsync

2020-11-25 14:30 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +                EventCore.emitAsync('mpi:patient:update', updated);
No es necesario emitir el evento

2020-12-01 16:21 UTC, MCele approved these changes

2020-12-01 16:33 UTC, condorpiedra approved these changes

2020-12-01 16:35 UTC, merged