MPI - Tokens de paciente para búsqueda
andes/api pull request #1196
Opened 2020-11-13 19:57 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-294

### Funcionalidad desarrollada 

1. Elimina tildes, 'ñ's y dieresis de cadenas para búsqueda multimatch
2. Script para actualizar tokens de pacientes en DB

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-25 17:55 UTC, MCele requested changes
Para mantener una consistencia de las búsquedas de pacientes el mismo comportamiento debería tener la búsqueda "search"

2020-11-25 18:21 UTC, negro89 commented
> Para mantener una consistencia de las búsquedas de pacientes el mismo comportamiento debería tener la búsqueda "search"

hecho!

2020-12-03 20:06 UTC, MCele approved these changes

2020-12-16 17:37 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2897](http://condorpiedra.andes.gob.ar:85/2897/mochawesome.html)
CYPRESS RUN: [2031](https://dashboard.cypress.io/projects/xr7gft/runs/2031/specs)
TEST START: 2020-12-16T17:36:47.227Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-16 19:07 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2905](http://condorpiedra.andes.gob.ar:85/2905/mochawesome.html)
CYPRESS RUN: [2039](https://dashboard.cypress.io/projects/xr7gft/runs/2039/specs)
TEST START: 2020-12-16T19:07:03.726Z
TOTAL: 355
SUCCESS: 348
FAIL: 7
SKIPPED: 0

2020-12-17 14:11 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2918](http://condorpiedra.andes.gob.ar:85/2918/mochawesome.html)
CYPRESS RUN: [2051](https://dashboard.cypress.io/projects/xr7gft/runs/2051/specs)
TEST START: 2020-12-17T14:11:38.036Z
TOTAL: 337
SUCCESS: 327
FAIL: 10
SKIPPED: 0

2020-12-18 15:43 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2935](http://condorpiedra.andes.gob.ar:85/2935/mochawesome.html)
CYPRESS RUN: [2068](https://dashboard.cypress.io/projects/xr7gft/runs/2068/specs)
TEST START: 2020-12-18T15:43:28.195Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2020-12-29 16:20 UTC, liquid36 approved these changes

2020-12-29 16:37 UTC, liquid36 commented
Quedo el scripts corrido en test

2021-01-08 15:40 UTC, merged