feat(moni): rutas para verificar estado de fa
andes/api pull request #1197
Opened 2020-11-13 19:58 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MONIT-37

### Funcionalidad desarrollada 

1. Se crean rutas para verificacion de estado de servicios renaper y sisa

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-16 14:53 UTC, condorpiedra requested changes

2020-11-16 14:53 UTC, condorpiedra commented on core-v2/mpi/validacion/validacion.routes.ts
> +    const url = `${sisaConfig.url}&usuario=${sisaConfig.username}&clave=${sisaConfig.password}`;
Completar la url con los datos necesarios para realizar la consulta

2020-11-16 14:53 UTC, condorpiedra commented on core-v2/mpi/validacion/validacion.routes.ts
> +    return (response === 200) ? res.json(true) : res.json(false);
Evitar devolver booleanos en las respuestas

2020-11-16 16:22 UTC, negro89 commented on core-v2/mpi/validacion/validacion.routes.ts
> +    return (response === 200) ? res.json(true) : res.json(false);
corregido!

2020-12-04 16:52 UTC, MCele approved these changes

2020-12-11 19:02 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2860](http://condorpiedra.andes.gob.ar:85/2860/mochawesome.html)
CYPRESS RUN: [1996](https://dashboard.cypress.io/projects/xr7gft/runs/1996/specs)
TEST START: 2020-12-11T19:01:53.463Z
TOTAL: 353
SUCCESS: 352
FAIL: 1
SKIPPED: 0

2020-12-14 15:10 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2868](http://condorpiedra.andes.gob.ar:85/2868/mochawesome.html)
CYPRESS RUN: [2003](https://dashboard.cypress.io/projects/xr7gft/runs/2003/specs)
TEST START: 2020-12-14T15:10:16.267Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2020-12-16 15:20 UTC, condorpiedra approved these changes

2020-12-16 15:28 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [2894](http://condorpiedra.andes.gob.ar:85/2894/mochawesome.html)
CYPRESS RUN: [2029](https://dashboard.cypress.io/projects/xr7gft/runs/2029/specs)
TEST START: 2020-12-16T15:28:12.632Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

2020-12-16 15:34 UTC, merged