MPI - Actualiza controller de paciente en jobs
andes/api pull request #1204
Opened 2020-11-19 20:46 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-299

### Funcionalidad desarrollada 

1. Reemplaza uso de controller viejo de paciente

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-11-27 10:57 UTC, condorpiedra requested changes

2020-11-27 10:57 UTC, condorpiedra commented on core/mpi/controller/mpiCorrector.ts
> +        const pacientesReportados = await Paciente.find(condicion);
Utilizar las funciones del controlador

2020-11-27 10:57 UTC, condorpiedra commented on core/mpi/controller/regexChecker.ts
> +        let cursor = await Paciente.find({ $or: [{ nombre: { $regex: regtest } }, { apellido: { $regex: regtest }, estado: 'validado' }] }).limit(100).cursor();
Utilizar las funciones del controller de Paciente, no el esquema

2020-11-27 10:57 UTC, condorpiedra commented on core/mpi/controller/regexChecker.ts
> +            let pacienteAndes = new Paciente(pac.toObject());
Utilizar update del controller

2020-11-27 17:28 UTC, negro89 commented on core/mpi/controller/regexChecker.ts
> +            let pacienteAndes = new Paciente(pac.toObject());
Todo corregidoo

2020-12-03 17:26 UTC, MCele approved these changes

2020-12-03 17:30 UTC, condorpiedra approved these changes

2020-12-03 17:32 UTC, merged