COM: refactor de adjuntar archivos
andes/api pull request #1214
Opened 2020-12-02 12:38 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/COM-45
https://proyectos.andes.gob.ar/browse/COM-42

### Funcionalidad desarrollada 
1. Poder eliminar archivos de andesDrive
2. Guardar archivos del COM en andesDrive
3. Leer archivos del COM de andesDrive 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-12-02 14:45 UTC, palita1991 approved these changes

2020-12-03 13:36 UTC, liquid36 commented on packages/drive/file-descriptor/schemas.ts
>  export let FileDescriptorSchema: Schema = new Schema({
Un primer pedido que no quedo escrito en la US. Agregale el audit plugin así sabemos que usuario cargo el archivo y a que hora.

2020-12-04 09:27 UTC, sychus requested changes
Simplemente corregir usar async await en lugar de callback, de esta manera no tener mezclado el código (awaits y callbacks).

2020-12-04 09:27 UTC, sychus commented on modules/centroOperativoMedico/derivaciones.routes.ts
> +        readFile(req.params.id).then((data: any) => {
readFile es una promise, yo usaría await en vez de callback

2020-12-04 17:12 UTC, juuliotero commented on modules/centroOperativoMedico/derivaciones.routes.ts
> +        readFile(req.params.id).then((data: any) => {
listo!

2020-12-04 17:12 UTC, juuliotero commented on packages/drive/file-descriptor/schemas.ts
>  export let FileDescriptorSchema: Schema = new Schema({
Quedó agregado

2020-12-10 17:40 UTC, liquid36 approved these changes

2020-12-11 11:31 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2853](http://condorpiedra.andes.gob.ar:85/2853/mochawesome.html)
CYPRESS RUN: [1989](https://dashboard.cypress.io/projects/xr7gft/runs/1989/specs)
TEST START: 2020-12-11T11:30:52.708Z
TOTAL: 354
SUCCESS: 351
FAIL: 3
SKIPPED: 0

2020-12-11 13:24 UTC, merged