TM: rutas adjuntar titulo profesional
andes/api pull request #1216
Opened 2020-12-03 14:11 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MAT-32

### Funcionalidad desarrollada 

1. Incluye rutas para POST y GET de títulos de formación de profesional.
2. 
3. 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MAT-32
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2020-12-16 11:17 UTC, liquid36 requested changes

2020-12-16 11:17 UTC, liquid36 commented on core/tm/routes/profesional.ts
> +router.get('/profesionales/titulo/:id', async (req, res, errHandler) => {
Andes Drive ya viene con su propio GET de archivos, no es necesario crear nuevas rutas. 

https://github.com/andes/api/blob/master/packages%2Fdrive%2Fdrive.ts#L55

2020-12-16 16:58 UTC, liquid36 approved these changes

2020-12-16 17:46 UTC, palita1991 approved these changes

2020-12-18 16:22 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2938](http://condorpiedra.andes.gob.ar:85/2938/mochawesome.html)
CYPRESS RUN: [2071](https://dashboard.cypress.io/projects/xr7gft/runs/2071/specs)
TEST START: 2020-12-18T16:22:33.267Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2021-01-04 16:26 UTC, condorpiedra requested changes
@plammel habría que realizar un script para agregarle el _id a las formaciones de Grado o posgrado o bien realizar la búsqueda por profesional y código de profesión que es un valor único dentro del arreglo

2021-01-05 12:20 UTC, plammel commented
> @plammel habría que realizar un script para agregarle el _id a las formaciones de Grado o posgrado o bien realizar la búsqueda por profesional y código de profesión que es un valor único dentro del arreglo

Se cambió la búsqueda por código de profesión.

2021-01-05 13:48 UTC, condorpiedra approved these changes

2021-01-05 14:58 UTC, merged