MPI - Actualiza job 'updateValidados'
andes/api pull request #1231
Opened 2020-12-17 15:01 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-317

### Funcionalidad desarrollada 

1- Actualiza validación de pacientes a renaperV3
2- Agrega actualización de georeferencia

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2020-12-17 15:05 UTC, condorpiedra requested changes

2020-12-17 15:05 UTC, condorpiedra commented on core/mpi/controller/updateValidados.ts
> +            pacientesValidados.push(await renaperv3({ documento: pac.documento, sexo: pac.sexo }, busInteroperabilidad, renaperToAndes));
Utilizar validar

2020-12-17 15:05 UTC, condorpiedra commented on core/mpi/controller/updateValidados.ts
> +import { renaperv3, renaperToAndes } from '@andes/fuentes-autenticas';
cambiar renaperv3 en validar

2020-12-17 15:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2925](http://condorpiedra.andes.gob.ar:85/2925/mochawesome.html)
CYPRESS RUN: [2058](https://dashboard.cypress.io/projects/xr7gft/runs/2058/specs)
TEST START: 2020-12-17T15:19:37.605Z
TOTAL: 355
SUCCESS: 355
FAIL: 0
SKIPPED: 0

2020-12-17 16:02 UTC, negro89 commented on core/mpi/controller/updateValidados.ts
> +import { renaperv3, renaperToAndes } from '@andes/fuentes-autenticas';
corregido!

2020-12-17 16:14 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [2928](http://condorpiedra.andes.gob.ar:85/2928/mochawesome.html)
CYPRESS RUN: [2061](https://dashboard.cypress.io/projects/xr7gft/runs/2061/specs)
TEST START: 2020-12-17T16:14:36.147Z
TOTAL: 324
SUCCESS: 319
FAIL: 5
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-18 16:01 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [2937](http://condorpiedra.andes.gob.ar:85/2937/mochawesome.html)
CYPRESS RUN: [2070](https://dashboard.cypress.io/projects/xr7gft/runs/2070/specs)
TEST START: 2020-12-18T16:01:18.691Z
TOTAL: 353
SUCCESS: 351
FAIL: 2
SKIPPED: 0

2021-01-04 19:07 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3000](http://condorpiedra.andes.gob.ar:85/3000/mochawesome.html)
CYPRESS RUN: [2129](https://dashboard.cypress.io/projects/xr7gft/runs/2129/specs)
TEST START: 2021-01-04T19:07:09.226Z
TOTAL: 353
SUCCESS: 350
FAIL: 3
SKIPPED: 0

2021-01-04 19:18 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3001](http://condorpiedra.andes.gob.ar:85/3001/mochawesome.html)
CYPRESS RUN: [2130](https://dashboard.cypress.io/projects/xr7gft/runs/2130/specs)
TEST START: 2021-01-04T19:18:16.269Z
TOTAL: 353
SUCCESS: 352
FAIL: 1
SKIPPED: 0

2021-01-04 19:37 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3002](http://condorpiedra.andes.gob.ar:85/3002/mochawesome.html)
CYPRESS RUN: [2131](https://dashboard.cypress.io/projects/xr7gft/runs/2131/specs)
TEST START: 2021-01-04T19:36:51.280Z
TOTAL: 353
SUCCESS: 348
FAIL: 5
SKIPPED: 0

2021-01-05 11:30 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3004](http://condorpiedra.andes.gob.ar:85/3004/mochawesome.html)
CYPRESS RUN: [2133](https://dashboard.cypress.io/projects/xr7gft/runs/2133/specs)
TEST START: 2021-01-05T11:29:48.677Z
TOTAL: 353
SUCCESS: 350
FAIL: 3
SKIPPED: 0

2021-01-05 15:57 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3013](http://condorpiedra.andes.gob.ar:85/3013/mochawesome.html)
CYPRESS RUN: [2140](https://dashboard.cypress.io/projects/xr7gft/runs/2140/specs)
TEST START: 2021-01-05T15:56:54.233Z
TOTAL: 353
SUCCESS: 352
FAIL: 1
SKIPPED: 0

2021-01-05 18:01 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3019](http://condorpiedra.andes.gob.ar:85/3019/mochawesome.html)
CYPRESS RUN: [2146](https://dashboard.cypress.io/projects/xr7gft/runs/2146/specs)
TEST START: 2021-01-05T18:00:49.633Z
TOTAL: 353
SUCCESS: 352
FAIL: 1
SKIPPED: 0

2021-01-05 18:39 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3021](http://condorpiedra.andes.gob.ar:85/3021/mochawesome.html)
CYPRESS RUN: [2148](https://dashboard.cypress.io/projects/xr7gft/runs/2148/specs)
TEST START: 2021-01-05T18:39:30.463Z
TOTAL: 353
SUCCESS: 352
FAIL: 1
SKIPPED: 0

2021-01-05 18:46 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3022](http://condorpiedra.andes.gob.ar:85/3022/mochawesome.html)
CYPRESS RUN: [2149](https://dashboard.cypress.io/projects/xr7gft/runs/2149/specs)
TEST START: 2021-01-05T18:46:12.859Z
TOTAL: 6
SUCCESS: 5
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-05 18:51 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3023](http://condorpiedra.andes.gob.ar:85/3023/mochawesome.html)
CYPRESS RUN: [2150](https://dashboard.cypress.io/projects/xr7gft/runs/2150/specs)
TEST START: 2021-01-05T18:50:57.186Z
TOTAL: 6
SUCCESS: 6
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-05 19:00 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3024](http://condorpiedra.andes.gob.ar:85/3024/mochawesome.html)
CYPRESS RUN: [2151](https://dashboard.cypress.io/projects/xr7gft/runs/2151/specs)
TEST START: 2021-01-05T19:00:28.959Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2021-01-06 16:01 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3029](http://condorpiedra.andes.gob.ar:85/3029/mochawesome.html)
CYPRESS RUN: [2156](https://dashboard.cypress.io/projects/xr7gft/runs/2156/specs)
TEST START: 2021-01-06T16:01:14.997Z
TOTAL: 353
SUCCESS: 352
FAIL: 1
SKIPPED: 0

2021-01-06 16:17 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3031](http://condorpiedra.andes.gob.ar:85/3031/mochawesome.html)
CYPRESS RUN: [2158](https://dashboard.cypress.io/projects/xr7gft/runs/2158/specs)
TEST START: 2021-01-06T16:17:33.540Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2021-01-06 16:46 UTC, MCele approved these changes

2021-01-06 16:53 UTC, condorpiedra approved these changes

2021-01-06 16:54 UTC, merged