feat(login): Permite realizar el cambio de contraseña para usuarios externos a oneLogin
andes/api pull request #1233
Opened 2020-12-21 18:11 UTC by sychus

- Setea un token de validación para los usuarios que sean externos al sistema oneLogin.
- Realiza el reset de la contraseña para los usuario externos al sistema oneLogin.
- Realiza modificaciones en authUsers, de manera de poder continuar utilizando este esquema para los permisos de usuario.
- Agrega template para la notificación realizada por robosender vía email.

### Requerimiento
Permitir el login y actualización de password de más de 200 usuarios externos para el proceso de vacunación.
### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2020-12-22 13:00 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2947](http://condorpiedra.andes.gob.ar:85/2947/mochawesome.html)
CYPRESS RUN: [2080](https://dashboard.cypress.io/projects/xr7gft/runs/2080/specs)
TEST START: 2020-12-22T13:00:34.541Z
TOTAL: 226
SUCCESS: 187
FAIL: 39
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-22 16:48 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [2950](http://condorpiedra.andes.gob.ar:85/2950/mochawesome.html)
CYPRESS RUN: [2083](https://dashboard.cypress.io/projects/xr7gft/runs/2083/specs)
TEST START: 2020-12-22T16:47:43.277Z
TOTAL: 303
SUCCESS: 298
FAIL: 5
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2020-12-22 17:11 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [2951](http://condorpiedra.andes.gob.ar:85/2951/mochawesome.html)
CYPRESS RUN: [2084](https://dashboard.cypress.io/projects/xr7gft/runs/2084/specs)
TEST START: 2020-12-22T17:10:42.899Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2020-12-23 18:10 UTC, liquid36 requested changes

2020-12-29 10:48 UTC, sychus commented on auth/auth.controller.ts
> +        throw new CustomError(error, 500);
ok

2020-12-29 10:49 UTC, sychus commented on auth/auth.controller.ts
> +        let usuario = await AuthUsers.findOne({ validationToken: token });
ok

2020-12-29 10:49 UTC, sychus commented on auth/routes/routes.ts
> +router.post('/getValidationTokenAndNotify', async (req, res, next) => {
estaba como set, pero me había quedado mal el nombre tanto acá como en la llamada al servicio en la app. Good Catch!

2020-12-29 10:50 UTC, sychus commented on config.private.ts.example
> +export const MAIN_DOMAIN = {
ok

2020-12-29 10:52 UTC, sychus commented on auth/auth.controller.ts
> +            const htmlToSend = await renderHTML('emails/layout.html', extras); // render del html genérico
La propuesta del partial inline me parece que implicaría meter el código del template de recover-password en el layout directamente, de este modo impediría poder rehusar el template del recovery en otro layout. De esta forma siempre podemos usar el mismo recover-password independiente del layout no?

2020-12-29 11:02 UTC, sychus commented on auth/routes/routes.ts
> +            result ? res.json({status: 'ok'}) : res.json({status: 404});
En realidad lo que sucede en este caso es que no es un error, sino que como el token no existe es un nuevo usuario o un usuario de onelogin. Con lo cual se lo debe redireccionar desde la app. Modifico el código para enviar algo más legible.

2020-12-29 11:14 UTC, liquid36 commented on auth/auth.controller.ts
> +            const htmlToSend = await renderHTML('emails/layout.html', extras); // render del html genérico
En el código del layout.html, donde esta:
```
{{ <partial }}
```

lo cambias por 

```
{{> @partial-block }}
```


Luego, en recover-password: 

```
{{#> layout }}
el contenido de mi recovery password
{{/layout}}

```

Y en el código,  en vez de registrar (_registerPartialTemplate_) cada vez el template que necestias, lo haces una salo vez cuando levanta la API con el **Layout** base. A futuro podría haber dos o tres mas templates bases. 

Es lo más cercano a una componente angular.

2020-12-30 21:41 UTC, sychus commented on auth/auth.controller.ts
> +            const htmlToSend = await renderHTML('emails/layout.html', extras); // render del html genérico
Tuve problemas con la sentencia @partial-block porque no encuentra el template. Hice una modificación que funciona bien y realizo la carga del layout template al inicio, pero usando "partial".

2021-01-04 18:02 UTC, liquid36 commented on auth/auth.controller.ts
> +            const htmlToSend = await renderHTML('emails/recover-password.html', extras);
Hice el ajuste.

2021-01-04 18:05 UTC, liquid36 commented on auth/auth.controller.ts
> +        if (usuario && usuario.tipo === 'temporal' && usuario.email) {
Una última duda, en el login se chequea la variable __authMethod__, tiene alguna relación con __tipo__?

2021-01-04 18:05 UTC, liquid36 approved these changes

2021-01-04 18:05 UTC, liquid36 approved these changes

2021-01-04 18:36 UTC, sychus commented on auth/auth.controller.ts
> +            const htmlToSend = await renderHTML('emails/recover-password.html', extras);
ahhh hiciste render... no te había entendido eso... yo estaba intentando con el register :-(

2021-01-04 18:37 UTC, sychus commented on auth/auth.controller.ts
> +        if (usuario && usuario.tipo === 'temporal' && usuario.email) {
es sólo para filtrar el envío de la clave pero nada del auth. :-)

2021-01-07 15:17 UTC, kroce approved these changes

2021-01-07 15:19 UTC, merged