Interoperabilidad vacuna covid19 con Nomivac
andes/api pull request #1235
Opened 2020-12-27 16:10 UTC by sychus

- Permite realizar el envío a nomivac en función de los datos cargados en la prestación de vacunación covid19
- Se almacena los datos en los logs sobre lo que se envió y las respuestas de nomivac.
- Cuando se invoque desde un job en forma automática, se deberá enviar una varible de entorno HORAS con la cantidad de horas que se quiera tomar hacia atrás.
- Se realiza control (filtro) en authUser para el login. Ya que debería tomar los usuarios activos.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2020-12-27 16:10 UTC, sychus commented
> Utilizar handleHttpRequest en vez de node-fetch para evitar agregar una nueva librería a la api

Si correcto, se realizó el cambio!

2020-12-27 16:11 UTC, sychus commented
> El proceso debería correr cada una hora. en este caso cada vez que se ejecute va a tomar el día completo

Me habían quedado sin querer los setHours, ya fueron quitados

2020-12-27 16:48 UTC, silviroa requested changes

2020-12-27 16:48 UTC, silviroa commented on jobs/exportCovid19.ts
> +            }
Este group no debería hacer falta... se supone que van a cargar un registro por cada dosis

2020-12-27 18:14 UTC, condorpiedra approved these changes

2020-12-27 18:50 UTC, kroce approved these changes

2020-12-27 21:20 UTC, sychus commented on jobs/exportCovid19.ts
> +            }
solved

2020-12-28 10:59 UTC, liquid36 requested changes

2020-12-28 10:59 UTC, liquid36 commented on jobs/exportCovid19.ts
> +    const start = moment(new Date()).subtract(horas, 'h').format('YYYY-MM-DD HH:mm:ss');
```suggestion
    const start = moment().subtract(horas, 'h').toDate();
```

2020-12-28 10:59 UTC, liquid36 commented on jobs/exportCovid19.ts
> +                    $gte: new Date(start), $lte: new Date(end)
```suggestion
                    $gte: start, $lte: end
```

2020-12-28 10:59 UTC, liquid36 commented on jobs/exportCovid19.ts
> +        },
```suggestion
        { $unwind: '$organizacion'}
```

Mongo aplica optimizaciones cuando hay un lookup seguido de un unwind.

2020-12-28 10:59 UTC, liquid36 commented on jobs/exportCovid19.ts
> +            $sort: {
¿Es necesario ordenar?

2020-12-28 10:59 UTC, liquid36 commented on jobs/exportCovid19.ts
> +        { $project: {
No tiene mucho sentido dos project seguidos.

2020-12-28 10:59 UTC, liquid36 commented on core/log/schemas/logExportaInformacion.ts
> +export let InformacionExportada = mongoose.model('informacionExportada', informacionExportadaSchema, 'informacionExportada');
¿Info exportada de que?
```suggestion
export let InformacionExportada = mongoose.model('nomivacInformacionExportada', informacionExportadaSchema, 'nomivacInformacionExportada');
```

¿Porque no se uso el sistema de logs?

2020-12-28 18:00 UTC, condorpiedra commented
Se reemplaza PR por este https://github.com/andes/api/pull/1236

2020-12-28 18:00 UTC, closed without merging