MPI: se agregan controles varios
andes/api pull request #1244
Opened 2021-01-07 16:47 UTC by MCele

### Requerimiento

Se agregan varios controles
### Funcionalidad desarrollada 

1. Se agrega try-catch en validar para handlear error de cuando el servicio no está disponible
2. Se agregan controles en job updateValidados
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-01-07 18:55 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3043](http://condorpiedra.andes.gob.ar:85/3043/mochawesome.html)
CYPRESS RUN: [2170](https://dashboard.cypress.io/projects/xr7gft/runs/2170/specs)
TEST START: 2021-01-07T18:55:34.388Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-08 01:23 UTC, sychus requested changes

2021-01-08 01:23 UTC, sychus commented on core-v2/mpi/validacion/validacion.controller.ts
> +    } catch (e) { }
el catch debería devolver un error.

2021-01-08 01:23 UTC, sychus commented on core-v2/mpi/validacion/validacion.controller.ts
>      return null;
Luego.. este return ya no sería alcanzable

2021-01-08 01:23 UTC, sychus commented on core/mpi/controller/updateValidados.ts
> +                if (data.direccion[0].ubicacion.localidad && (!data.direccion[0].georeferencia || (data.direccion.length > 0 && data.direccion[0].georeferencia === null))) {
!data.direccion[0].georeferencia pero tambien como data.direccion[0].georeferencia === null ?, ponerlo de una sola manera sino es confuso.

2021-01-08 01:23 UTC, sychus commented on core/mpi/controller/updateValidados.ts
> +                    const dir = data.direccion[0].valor + ', ' + localidad + ', ' + provincia;
reemplazar por : const dir = `${data.direccion[0].valor} , ${localidad}, ${provincia}` para evitar tanta comilla

2021-01-13 11:24 UTC, condorpiedra approved these changes

2021-01-13 12:45 UTC, palita1991 approved these changes

2021-01-13 16:25 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3076](http://condorpiedra.andes.gob.ar:85/3076/mochawesome.html)
CYPRESS RUN: [2203](https://dashboard.cypress.io/projects/xr7gft/runs/2203/specs)
TEST START: 2021-01-13T16:24:27.130Z
TOTAL: 351
SUCCESS: 342
FAIL: 9
SKIPPED: 0

2021-01-13 16:47 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3078](http://condorpiedra.andes.gob.ar:85/3078/mochawesome.html)
CYPRESS RUN: [2205](https://dashboard.cypress.io/projects/xr7gft/runs/2205/specs)
TEST START: 2021-01-13T16:46:31.520Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-13 16:51 UTC, merged