MAT: actualización export sisa profesional
andes/api pull request #1248
Opened 2021-01-12 13:59 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MAT-42
### Funcionalidad desarrollada 

1. Se reordenaron los atributos de json de exportación de profesional a sisa de acuerdo a https://sisa.msal.gov.ar/sisadoc/docs/050102/refeps_ws_024.jsp
2. Se agregaron nuevos campos `ID_ORIGEN_EMITE` con valor `''` y `CP` con valor  `'8300'` correspondiente al código postal de la provincia de Neuquén. 
3. Se removieron los siguientes campos, por no ser consumidos por el webservice de SISA:
    * ID_PROFESIONAL
    * ID_PROFESIONAL_PROFESION
    * ID_PROFESIONAL_MATRICULA
    * SSS
    * SSS_CERTIFICADO
    * SSS_FECHA
    * ID_SSS_PROVINCIA
    * ID_SSS_PROVINCIA2
    * ID_SSS_PROVINCIA3
    * CUIL
    * FALLECIDO
    * FECHA_FALLECIDO 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MAT-42
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-01-12 22:25 UTC, sychus commented
@plammel 8300 es el código postal de neuquén capital no de la provincia. Ojo porque cada localidad tiene su código postal.

2021-01-12 22:29 UTC, sychus requested changes

2021-01-12 22:29 UTC, sychus commented on core/tm/routes/profesional.ts
> +        profesionalSisa['HABILITADO'] = 'SI';
ojota que puede haber alguno no habilitado (es decir en false)

2021-01-12 22:29 UTC, sychus commented on core/tm/routes/profesional.ts
> +        profesionalSisa['CP'] = '8300';
ojo aca.. depende de la localidad

2021-01-14 13:11 UTC, plammel commented
No corresponde

2021-01-14 13:11 UTC, closed without merging