TM: busca profesión por código
andes/api pull request #1250
Opened 2021-01-14 15:28 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/MAT-42
### Funcionalidad desarrollada 

1. Incluye filtro por código en búsqueda de profesión
2. 
3. 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MAT-42
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-01-14 17:21 UTC, liquid36 requested changes

2021-01-14 17:21 UTC, liquid36 commented on core/tm/routes/profesion.ts
> +        profesion.find({ codigo: req.query.codigo }).exec((error, data) => {
el `.exec` esta más que deprecado.

2021-01-14 18:50 UTC, plammel commented on core/tm/routes/profesion.ts
> +        profesion.find({ codigo: req.query.codigo }).exec((error, data) => {
Removido!

2021-01-14 19:11 UTC, liquid36 requested changes

2021-01-14 19:11 UTC, liquid36 commented on core/tm/routes/profesion.ts
> +        profesion.find({ codigo: req.query.codigo }, (error, data) => {
Era un llamado de atención a seguir las guías de desarrollo. 

```suggestion
        const profesion = await profesion.find({ codigo: req.query.codigo });
```

Acomodar de ser posible todo el archivo, son dos minutos

2021-01-20 16:51 UTC, liquid36 approved these changes

2021-01-20 17:08 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3101](http://condorpiedra.andes.gob.ar:85/3101/mochawesome.html)
CYPRESS RUN: [2227](https://dashboard.cypress.io/projects/xr7gft/runs/2227/specs)
TEST START: 2021-01-20T17:07:02.924Z
TOTAL: 351
SUCCESS: 349
FAIL: 2
SKIPPED: 0

2021-01-20 17:16 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3102](http://condorpiedra.andes.gob.ar:85/3102/mochawesome.html)
CYPRESS RUN: [2228](https://dashboard.cypress.io/projects/xr7gft/runs/2228/specs)
TEST START: 2021-01-20T17:15:26.353Z
TOTAL: 351
SUCCESS: 349
FAIL: 2
SKIPPED: 0

2021-01-20 17:24 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3103](http://condorpiedra.andes.gob.ar:85/3103/mochawesome.html)
CYPRESS RUN: [2229](https://dashboard.cypress.io/projects/xr7gft/runs/2229/specs)
TEST START: 2021-01-20T17:23:15.880Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-25 15:40 UTC, sychus requested changes

2021-01-25 15:40 UTC, sychus commented on core/tm/routes/profesion.ts
> +}));
Que pasaría si el find falla?, debería tener un try catch y handlearlo no?. Por otra parte, si no encuentra nadam no debería devolver un status.code 404 ?

2021-01-25 15:40 UTC, sychus commented on core/tm/routes/profesion.ts
> +}));
idem anterior

2021-01-25 16:26 UTC, liquid36 commented on core/tm/routes/profesion.ts
> +}));
asyncHandler hace su trabajo.

2021-01-25 16:26 UTC, liquid36 commented on core/tm/routes/profesion.ts
> +}));
idem anterior

2021-01-25 18:03 UTC, sychus commented on core/tm/routes/profesion.ts
> +}));
gracias! ahí revise el paquete y vi como lo maneja!!! perdón por el feedback incorrecto!

2021-01-25 18:04 UTC, sychus approved these changes

2021-02-01 17:50 UTC, merged