PRIV-62:  CDA al exportar HUDS
andes/api pull request #1251
Opened 2021-01-15 12:25 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/PRIV-62

### Funcionalidad desarrollada 

1. Se realiza un refactor en el modulo cda pasando al controller la lógica que se encontraba en el archivo route.
2. Se agrega a exportHuds la búsqueda de los registros de un paciente en CDAFiles.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-01-15 12:39 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3086](http://condorpiedra.andes.gob.ar:85/3086/mochawesome.html)
CYPRESS RUN: [2212](https://dashboard.cypress.io/projects/xr7gft/runs/2212/specs)
TEST START: 2021-01-15T12:38:51.886Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-16 00:06 UTC, sychus requested changes
Van algunos detallecitos!

2021-01-16 00:06 UTC, sychus commented on modules/cda/routes/cda.ts
> +        return next(ex); // poner error lindo
Ojo ac
acá capaz q convenga poner un next(500). Ese comentario me quedo cuando modifique lo del controller. Como para seguir la línea del tipo de errores.

2021-01-16 00:06 UTC, sychus commented on modules/huds/export-huds/exportHuds.controller.ts
> +            } // Caso en el que no hay prestaciones, devuelvo el zip vacio
porque no usar async await acá? ya que getCda es una promise.

2021-01-18 11:59 UTC, liquid36 requested changes

2021-01-18 11:59 UTC, liquid36 commented on modules/huds/export-huds/exportHuds.controller.ts
> +                    archive.append(fileCda.stream, { name: params.name });
Habría que poner un nombre más descriptivo. Fecha + prestacion.

2021-01-18 17:43 UTC, martinebucarey commented on modules/cda/routes/cda.ts
> +        return next(ex); // poner error lindo
Modificado

2021-01-18 17:44 UTC, martinebucarey commented on modules/huds/export-huds/exportHuds.controller.ts
> +            } // Caso en el que no hay prestaciones, devuelvo el zip vacio
en un primer momento no me funcionaba y me cerraba el archivo antes de meter los pdf (por lo visto estaba haciendo algo mal) ahora hice un nuevo refactor y quedo todo eso en 6 lineas con await.GRACIAS!!

2021-01-18 17:44 UTC, martinebucarey commented on modules/huds/export-huds/exportHuds.controller.ts
> +                    archive.append(fileCda.stream, { name: params.name });
Modificado, le pongo como nombre la prestacion y fecha de cada cda

2021-01-19 03:31 UTC, sychus approved these changes

2021-01-19 11:51 UTC, palita1991 approved these changes

2021-01-29 15:12 UTC, liquid36 approved these changes

2021-02-01 17:33 UTC, merged