feat(CITAS): se agrega permiso soloLectura
andes/api pull request #1256
Opened 2021-01-20 16:35 UTC by waltergarrido

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-103
### Funcionalidad desarrollada 

1. se agrega permiso soloLectura en punto de inicio y gestor de agendas
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [X] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-01-20 16:47 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3099](http://condorpiedra.andes.gob.ar:85/3099/mochawesome.html)
CYPRESS RUN: [2225](https://dashboard.cypress.io/projects/xr7gft/runs/2225/specs)
TEST START: 2021-01-20T16:46:35.888Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-21 11:39 UTC, liquid36 requested changes

2021-01-21 11:39 UTC, liquid36 commented on auth/permisos.ts
> +                    { key: 'READ', title: 'Solo Lectura', comment: 'ver agenda publicada', type: 'boolean' }
Mover arriba de todo así en el gestor de usuarios se ve primero.

```suggestion
                    { key: 'read', title: 'Ver agendas', comment: 'ver agenda publicada', type: 'boolean' }
```

2021-01-21 11:39 UTC, liquid36 commented on auth/permisos.ts
> +                    { key: 'READ', title: 'Solo Lectura', type: 'boolean' }
Mover arriba de todo así en el gestor de usuarios se ve primero.

```suggestion
                    { key: 'read', title: 'Ver turnos', type: 'boolean' }
```

2021-01-21 13:58 UTC, waltergarrido commented on auth/permisos.ts
> +                    { key: 'READ', title: 'Solo Lectura', comment: 'ver agenda publicada', type: 'boolean' }
@corregido

2021-01-21 13:59 UTC, waltergarrido commented on auth/permisos.ts
> +                    { key: 'READ', title: 'Solo Lectura', type: 'boolean' }
@liquid36 corregido

2021-01-26 14:31 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3123](http://condorpiedra.andes.gob.ar:85/3123/mochawesome.html)
CYPRESS RUN: [2249](https://dashboard.cypress.io/projects/xr7gft/runs/2249/specs)
TEST START: 2021-01-26T14:30:11.402Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

2021-01-27 11:31 UTC, palita1991 approved these changes

2021-02-18 16:41 UTC, merged