feat(mpi): documentos paciente
andes/api pull request #1259
Opened 2021-01-26 19:28 UTC by waltergarrido

### Requerimiento

https://proyectos.andes.gob.ar/browse/MPI-312
### Funcionalidad desarrollada 

1. se agrega pestaña para visualizar documentos adjuntos 
2. se agrega lista de documentos adjuntos en paciente detalle
3. 

### UserStories llegó a completarse

- [ ] Si
- [] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-01-27 13:28 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3139](http://condorpiedra.andes.gob.ar:85/3139/mochawesome.html)
CYPRESS RUN: [2264](https://dashboard.cypress.io/projects/xr7gft/runs/2264/specs)
TEST START: 2021-01-27T13:27:07.422Z
TOTAL: 354
SUCCESS: 347
FAIL: 7
SKIPPED: 0

2021-01-27 16:44 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3143](http://condorpiedra.andes.gob.ar:85/3143/mochawesome.html)
CYPRESS RUN: [2268](https://dashboard.cypress.io/projects/xr7gft/runs/2268/specs)
TEST START: 2021-01-27T16:43:09.371Z
TOTAL: 354
SUCCESS: 352
FAIL: 2
SKIPPED: 0

2021-01-27 16:58 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3144](http://condorpiedra.andes.gob.ar:85/3144/mochawesome.html)
CYPRESS RUN: [2269](https://dashboard.cypress.io/projects/xr7gft/runs/2269/specs)
TEST START: 2021-01-27T16:57:15.084Z
TOTAL: 354
SUCCESS: 330
FAIL: 24
SKIPPED: 0

2021-01-27 17:24 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3146](http://condorpiedra.andes.gob.ar:85/3146/mochawesome.html)
CYPRESS RUN: [2271](https://dashboard.cypress.io/projects/xr7gft/runs/2271/specs)
TEST START: 2021-01-27T17:23:38.466Z
TOTAL: 354
SUCCESS: 328
FAIL: 26
SKIPPED: 0

2021-01-28 12:03 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3150](http://condorpiedra.andes.gob.ar:85/3150/mochawesome.html)
CYPRESS RUN: [2275](https://dashboard.cypress.io/projects/xr7gft/runs/2275/specs)
TEST START: 2021-01-28T12:01:54.345Z
TOTAL: 354
SUCCESS: 326
FAIL: 28
SKIPPED: 0

2021-01-28 12:15 UTC, MCele approved these changes

2021-01-28 12:31 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3152](http://condorpiedra.andes.gob.ar:85/3152/mochawesome.html)
CYPRESS RUN: [2277](https://dashboard.cypress.io/projects/xr7gft/runs/2277/specs)
TEST START: 2021-01-28T12:30:24.441Z
TOTAL: 354
SUCCESS: 326
FAIL: 28
SKIPPED: 0

2021-01-28 15:38 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3157](http://condorpiedra.andes.gob.ar:85/3157/mochawesome.html)
CYPRESS RUN: [2282](https://dashboard.cypress.io/projects/xr7gft/runs/2282/specs)
TEST START: 2021-01-28T15:37:40.211Z
TOTAL: 327
SUCCESS: 316
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-28 17:06 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3159](http://condorpiedra.andes.gob.ar:85/3159/mochawesome.html)
CYPRESS RUN: [2284](https://dashboard.cypress.io/projects/xr7gft/runs/2284/specs)
TEST START: 2021-01-28T17:05:43.010Z
TOTAL: 5
SUCCESS: 5
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-28 17:29 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3161](http://condorpiedra.andes.gob.ar:85/3161/mochawesome.html)
CYPRESS RUN: [2286](https://dashboard.cypress.io/projects/xr7gft/runs/2286/specs)
TEST START: 2021-01-28T17:28:34.767Z
TOTAL: 354
SUCCESS: 353
FAIL: 1
SKIPPED: 0

2021-01-28 17:37 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3162](http://condorpiedra.andes.gob.ar:85/3162/mochawesome.html)
CYPRESS RUN: [2287](https://dashboard.cypress.io/projects/xr7gft/runs/2287/specs)
TEST START: 2021-01-28T17:35:06.789Z
TOTAL: 17
SUCCESS: 16
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-29 11:29 UTC, sychus requested changes

2021-01-29 11:29 UTC, sychus commented on auth/permisos.ts
> +                    { key: 'documentacionPermiso', title: 'Modificar documentos adjuntos', type: 'boolean' }
```suggestion
                    { key: 'documentacion', title: 'Modificar documentos adjuntos', type: 'boolean' }
```

2021-01-29 11:29 UTC, sychus commented on core-v2/mpi/paciente/paciente.schema.ts
> +    }]
Sugiero hacer el schema de documento separado. Y luego documentos: [documentosSchema]

2021-01-29 14:20 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3178](http://condorpiedra.andes.gob.ar:85/3178/mochawesome.html)
CYPRESS RUN: [2302](https://dashboard.cypress.io/projects/xr7gft/runs/2302/specs)
TEST START: 2021-01-29T14:17:42.922Z
TOTAL: 17
SUCCESS: 16
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-29 15:03 UTC, waltergarrido commented on auth/permisos.ts
> +                    { key: 'documentacionPermiso', title: 'Modificar documentos adjuntos', type: 'boolean' }
@sychus corregido

2021-01-29 15:03 UTC, waltergarrido commented on core-v2/mpi/paciente/paciente.schema.ts
> +    }]
@sychus corregido

2021-02-08 18:31 UTC, plammel requested changes

2021-02-08 18:31 UTC, plammel commented on core-v2/mpi/paciente/paciente.schema.ts
> +    }]
Se creó el schema de adjuntos, pero aún falta reemplazarlo en el atributo `documentos` de `paciente.schema.ts` del core-v2
```suggestion
       documentos: [documentoAdjuntoSchema]
```
También sugiero nombrar la constante `documentoAdjuntoSchema` en mayúscula: DocumentoAdjuntoSchema

2021-02-08 18:31 UTC, plammel commented on core/tm/schemas/documentoAdjunto.ts
> +const documentoAdjuntoSchema = new mongoose.Schema({
```suggestion
const DocumentoAdjuntoSchema = new mongoose.Schema({
```

2021-02-19 11:26 UTC, sychus reviewed
@waltergarrido sugiero finalizar estas pocas tareas pendientes así ya queda terminado! gracias

2021-02-19 12:15 UTC, waltergarrido commented on core-v2/mpi/paciente/paciente.schema.ts
> +    }]
@plammel  corregido

2021-02-19 12:16 UTC, waltergarrido commented on core/tm/schemas/documentoAdjunto.ts
> +const documentoAdjuntoSchema = new mongoose.Schema({
@plammel corregido

2021-02-19 21:13 UTC, sychus approved these changes

2021-02-22 12:08 UTC, condorpiedra approved these changes

2021-02-23 14:17 UTC, liquid36 approved these changes

2021-02-23 14:47 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3419](http://condorpiedra.andes.gob.ar:85/3419/mochawesome.html)
CYPRESS RUN: [2516](https://dashboard.cypress.io/projects/xr7gft/runs/2516/specs)
TEST START: 2021-02-23T14:46:35.221Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-23 15:51 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3420](http://condorpiedra.andes.gob.ar:85/3420/mochawesome.html)
CYPRESS RUN: [2517](https://dashboard.cypress.io/projects/xr7gft/runs/2517/specs)
TEST START: 2021-02-23T15:41:12.215Z
TOTAL: 251
SUCCESS: 219
FAIL: 31
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-23 15:53 UTC, plammel approved these changes

2021-02-23 16:11 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3421](http://condorpiedra.andes.gob.ar:85/3421/mochawesome.html)
CYPRESS RUN: [2518](https://dashboard.cypress.io/projects/xr7gft/runs/2518/specs)
TEST START: 2021-02-23T16:10:42.290Z
TOTAL: 344
SUCCESS: 339
FAIL: 4
SKIPPED: 1

2021-02-23 17:35 UTC, palita1991 approved these changes

2021-02-23 17:43 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3425](http://condorpiedra.andes.gob.ar:85/3425/mochawesome.html)
CYPRESS RUN: [2522](https://dashboard.cypress.io/projects/xr7gft/runs/2522/specs)
TEST START: 2021-02-23T17:42:44.433Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-23 17:57 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3426](http://condorpiedra.andes.gob.ar:85/3426/mochawesome.html)
CYPRESS RUN: [2523](https://dashboard.cypress.io/projects/xr7gft/runs/2523/specs)
TEST START: 2021-02-23T17:56:20.405Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-25 15:35 UTC, MCele approved these changes

2021-03-02 14:32 UTC, merged