feat(COM): verifica organizacion destino en POST derivaciones
andes/api pull request #1260
Opened 2021-01-27 14:24 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/COM-51
https://proyectos.andes.gob.ar/browse/COM-55
### Funcionalidad desarrollada 

1. Verifica en el POST de derivaciones, que la organización que cambia de estado es la misma que la organización destino
2. 
3. 

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/COM-55
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-01-28 11:13 UTC, liquid36 requested changes

2021-01-28 11:13 UTC, liquid36 commented on modules/centroOperativoMedico/derivaciones.routes.ts
> +                const esCOM = ((await Organizacion.findById(organizacion)) as any).esCOM;
El schema organización ya tiene interfaz, agregar esCOM a la misma. 
Además, todo apretado en una misma linea de código se hace difícil de entender.

2021-01-28 19:21 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3165](http://condorpiedra.andes.gob.ar:85/3165/mochawesome.html)
CYPRESS RUN: [2290](https://dashboard.cypress.io/projects/xr7gft/runs/2290/specs)
TEST START: 2021-01-28T19:19:58.694Z
TOTAL: 323
SUCCESS: 318
FAIL: 5
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-01-29 14:58 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3180](http://condorpiedra.andes.gob.ar:85/3180/mochawesome.html)
CYPRESS RUN: [2304](https://dashboard.cypress.io/projects/xr7gft/runs/2304/specs)
TEST START: 2021-01-29T14:48:17.281Z
TOTAL: 315
SUCCESS: 303
FAIL: 12
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-02-02 14:04 UTC, liquid36 approved these changes

2021-02-02 16:38 UTC, sychus approved these changes

2021-02-02 18:03 UTC, palita1991 approved these changes

2021-02-02 18:15 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3201](http://condorpiedra.andes.gob.ar:85/3201/mochawesome.html)
CYPRESS RUN: [2323](https://dashboard.cypress.io/projects/xr7gft/runs/2323/specs)
TEST START: 2021-02-02T18:14:40.031Z
TOTAL: 336
SUCCESS: 333
FAIL: 3
SKIPPED: 0

2021-02-03 11:09 UTC, kroce commented
Fallan los tests del com con este cambio, habría que revisar que pasó @plammel

2021-02-04 15:22 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3211](http://condorpiedra.andes.gob.ar:85/3211/mochawesome.html)
CYPRESS RUN: [2333](https://dashboard.cypress.io/projects/xr7gft/runs/2333/specs)
TEST START: 2021-02-04T15:21:32.544Z
TOTAL: 354
SUCCESS: 354
FAIL: 0
SKIPPED: 0

2021-02-11 12:05 UTC, palita1991 commented
@plammel recordar arreglar los conflictos

2021-02-18 13:47 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3350](http://condorpiedra.andes.gob.ar:85/3350/mochawesome.html)
CYPRESS RUN: [2456](https://dashboard.cypress.io/projects/xr7gft/runs/2456/specs)
TEST START: 2021-02-18T13:37:34.852Z
TOTAL: 358
SUCCESS: 350
FAIL: 7
SKIPPED: 1

2021-02-18 14:34 UTC, liquid36 commented on modules/centroOperativoMedico/derivaciones.routes.ts
>              if (nuevoEstado.estado) {
Esta muy confuso este endpoint, que llegue como parámetro `estado.estado`

2021-02-18 14:54 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3355](http://condorpiedra.andes.gob.ar:85/3355/mochawesome.html)
CYPRESS RUN: [2461](https://dashboard.cypress.io/projects/xr7gft/runs/2461/specs)
TEST START: 2021-02-18T14:52:55.641Z
TOTAL: 358
SUCCESS: 356
FAIL: 1
SKIPPED: 1

2021-02-18 15:44 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3358](http://condorpiedra.andes.gob.ar:85/3358/mochawesome.html)
CYPRESS RUN: [2462](https://dashboard.cypress.io/projects/xr7gft/runs/2462/specs)
TEST START: 2021-02-18T15:43:42.208Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-18 15:53 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3359](http://condorpiedra.andes.gob.ar:85/3359/mochawesome.html)
CYPRESS RUN: [2463](https://dashboard.cypress.io/projects/xr7gft/runs/2463/specs)
TEST START: 2021-02-18T15:52:43.696Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-18 16:51 UTC, merged