MPI - Agrupa jobs en core-v2/mpi
andes/api pull request #1274
Opened 2021-02-09 18:42 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-326

### Funcionalidad desarrollada 

1. Se reagrupan los jobs de mpi en una sola ubicación

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-02-11 15:39 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3301](http://condorpiedra.andes.gob.ar:85/3301/mochawesome.html)
CYPRESS RUN: [2416](https://dashboard.cypress.io/projects/xr7gft/runs/2416/specs)
TEST START: 2021-02-11T15:28:49.705Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-11 16:02 UTC, liquid36 approved these changes

2021-02-11 16:08 UTC, condorpiedra requested changes
El job pecasConsolidadoJob.ts debe estar en job porque se eliminó?

2021-02-11 18:16 UTC, negro89 commented
> El job pecasConsolidadoJob.ts debe estar en jobs porque se eliminó?

Por error! ya está corregido @condorpiedra

2021-02-11 18:21 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3305](http://condorpiedra.andes.gob.ar:85/3305/mochawesome.html)
CYPRESS RUN: [2419](https://dashboard.cypress.io/projects/xr7gft/runs/2419/specs)
TEST START: 2021-02-11T18:20:44.551Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-22 11:59 UTC, condorpiedra requested changes

2021-02-22 11:59 UTC, condorpiedra commented on core-v2/mpi/jobs/nacimientosProcess.ts
> +import { paciente } from '../../../core/mpi/schemas/paciente';
Debería importar de core-v2, y utilizar el controller

2021-02-22 11:59 UTC, condorpiedra commented on core-v2/mpi/jobs/mpiCorrector.ts
> +import { mpiCorrectorLog } from '../../../core/mpi/mpi.log';
Debería estar en core-v2

2021-02-22 11:59 UTC, condorpiedra commented on core-v2/mpi/jobs/updateFoto.ts
> +import { paciente } from '../../../core/mpi/schemas/paciente';
Hay que utilizar los controladores de corev2 o bien el schema de corev2

2021-03-23 16:15 UTC, plammel commented on core-v2/mpi/jobs/importarNacimientosJob.ts
> +import { importarDocumentosAsignados } from './nacimientosProcess';
```suggestion
import { importarNacimientos, importarDocumentosAsignados } from './nacimientosProcess';
```

2021-03-26 17:40 UTC, negro89 commented on core-v2/mpi/jobs/importarNacimientosJob.ts
> +import { importarDocumentosAsignados } from './nacimientosProcess';
hechooo

2021-04-09 15:42 UTC, condorpiedra approved these changes

2021-04-09 15:42 UTC, merged