Refactor(RUP): informe-pdf se agrega implementación de VacunasComponent
andes/api pull request #1277
Opened 2021-02-17 15:08 UTC by waltergarrido

### Requerimiento

https://proyectos.andes.gob.ar/browse/RUP-239
### Funcionalidad desarrollada 

1. se implementa vacunasComponent  para generar su informe-pdf.
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [X] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-02-17 15:40 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [3332](http://condorpiedra.andes.gob.ar:85/3332/mochawesome.html)
CYPRESS RUN: [2443](https://dashboard.cypress.io/projects/xr7gft/runs/2443/specs)
TEST START: 2021-02-17T15:29:27.014Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-17 18:04 UTC, liquid36 requested changes
Tanto el Vacunador y el Laboratorio son opcionales. Si no se carga nada da un error en la API.

2021-02-17 18:04 UTC, liquid36 commented on modules/descargas/informe-rup/elementos-rup/vacuna.component.ts
> +</br>
Los elementos **div**, **seccion** ya generan un salto de linea. En ese caso no es necesario incorporar el elemento **br** (break line).

2021-02-17 19:16 UTC, waltergarrido commented on modules/descargas/informe-rup/elementos-rup/vacuna.component.ts
> +</br>
@liquid36 corregido.

2021-02-18 10:57 UTC, liquid36 approved these changes

2021-02-18 11:27 UTC, palita1991 approved these changes

2021-02-18 11:39 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [3337](http://condorpiedra.andes.gob.ar:85/3337/mochawesome.html)
CYPRESS RUN: [2446](https://dashboard.cypress.io/projects/xr7gft/runs/2446/specs)
TEST START: 2021-02-18T11:29:14.329Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-18 13:00 UTC, merged