AM: permitir que familiar actualice datos del paciente
andes/api pull request #1280
Opened 2021-02-18 15:09 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-89

### Funcionalidad desarrollada 
1. Permitir que un familiar pueda actualizar datos del paciente

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-02-23 11:13 UTC, condorpiedra requested changes

2021-02-23 11:13 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +    if (index <= 0) {
Si index es menor que 0 y esFamiliar da falso la ruta no devuelve resultado

2021-02-23 12:23 UTC, juuliotero commented on modules/mobileApp/routes/paciente.ts
> +    if (index <= 0) {
En ese caso la ruta devuelve { message: 'unauthorized' }

2021-02-24 13:49 UTC, plammel approved these changes

2021-02-24 16:22 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3437](http://condorpiedra.andes.gob.ar:85/3437/mochawesome.html)
CYPRESS RUN: [2532](https://dashboard.cypress.io/projects/xr7gft/runs/2532/specs)
TEST START: 2021-02-24T16:20:55.977Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-02-24 18:17 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3446](http://condorpiedra.andes.gob.ar:85/3446/mochawesome.html)
CYPRESS RUN: [2541](https://dashboard.cypress.io/projects/xr7gft/runs/2541/specs)
TEST START: 2021-02-24T18:16:37.597Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-25 11:41 UTC, liquid36 approved these changes

2021-04-13 17:28 UTC, merged