AM: permitir consultar laboratorios de familiares
andes/api pull request #1281
Opened 2021-02-19 19:36 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-52

### Funcionalidad desarrollada 
1. Habilita la consulta de laboratorios de familiares

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-02-23 11:14 UTC, liquid36 requested changes

2021-02-23 11:14 UTC, liquid36 commented on modules/mobileApp/routes/paciente.ts
> +    if (index <= 0) {
Entiendo que acá debería ser menor estricto, para el caso en que el paciente no se encuentra.  El cero es una posición valida.

2021-02-23 11:14 UTC, liquid36 commented on modules/mobileApp/routes/paciente.ts
> +    const index = (req as any).user.pacientes.findIndex(item => item.id === idPaciente);
Castear a any de esta forma se puede evitar de la siguiente manera:

Tipando `req` en la declaración de argumentos de la función: 
```
router.get('/laboratorios/(:id)', async (req: any, res, next) => {
```

2021-02-23 11:16 UTC, condorpiedra requested changes

2021-02-23 11:16 UTC, condorpiedra commented on modules/mobileApp/routes/paciente.ts
> +    if (index >= 0 || esFamiliar) {
Si el index es menor a 0 y esFamiliar es falso la ruta no devuelve resultado

2021-02-23 12:26 UTC, juuliotero commented on modules/mobileApp/routes/paciente.ts
> +    if (index >= 0 || esFamiliar) {
corregido

2021-02-23 12:26 UTC, juuliotero commented on modules/mobileApp/routes/paciente.ts
> +    const index = (req as any).user.pacientes.findIndex(item => item.id === idPaciente);
corregido

2021-02-23 12:26 UTC, juuliotero commented on modules/mobileApp/routes/paciente.ts
> +    if (index <= 0) {
corregido

2021-02-24 13:44 UTC, plammel approved these changes

2021-02-24 16:00 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3435](http://condorpiedra.andes.gob.ar:85/3435/mochawesome.html)
CYPRESS RUN: [2530](https://dashboard.cypress.io/projects/xr7gft/runs/2530/specs)
TEST START: 2021-02-24T15:59:30.631Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-25 11:30 UTC, liquid36 approved these changes

2021-03-01 18:18 UTC, sychus approved these changes

2021-04-14 13:55 UTC, merged