Se corrgien bugs  al guardar pacientes obtenidos del Registro Civil
andes/api pull request #1282
Opened 2021-02-23 11:58 UTC by MCele

### Requerimiento

Se corrigen bugs en el job de importarNacimientos

### Funcionalidad desarrollada 

1.se corrige  bug al guardar progenitor/a sin campo fotoId
2. se corrige bug al guardar el tipo de relación en progenitor e hijo

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-02-23 12:10 UTC, condorpiedra requested changes

2021-02-23 12:10 UTC, condorpiedra commented on core/mpi/jobs/nacimientosProcess.ts
> +            relacion: progenitor[0],
cambiar search por findOne

2021-02-23 18:27 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [3427](http://condorpiedra.andes.gob.ar:85/3427/mochawesome.html)
CYPRESS RUN: [2524](https://dashboard.cypress.io/projects/xr7gft/runs/2524/specs)
TEST START: 2021-02-23T18:25:51.983Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-02-24 13:32 UTC, plammel requested changes

2021-02-24 13:32 UTC, plammel commented on core/mpi/jobs/nacimientosProcess.ts
> +        console.log(error);
Remover console

2021-02-24 13:32 UTC, plammel commented on core/mpi/jobs/nacimientosProcess.ts
> +    dataPaciente.fotoId = !(resultado.foto.length > 0) ? null :
```suggestion
    dataPaciente.fotoId = !resultado.foto.length ? null :
```

2021-02-24 15:37 UTC, juuliotero requested changes

2021-02-24 15:37 UTC, juuliotero commented on core/mpi/jobs/nacimientosProcess.ts
> +    const rela = (relaciones: any[], id) => ((relaciones?.length) ? relaciones.some(rel => rel.referencia.toString() === id.toString()) : null);
podría cambiarse el nombre de la variable a una más descriptiva

2021-02-24 16:59 UTC, andrrrl requested changes
Pavaditas nomás, se ve muy prolijo todo!

2021-02-24 16:59 UTC, andrrrl commented on core/mpi/jobs/nacimientosProcess.ts
> +        console.log(error);
console.log detected diría @martinebucarey

2021-02-24 16:59 UTC, andrrrl commented on core/mpi/jobs/nacimientosProcess.ts
> +        const pacientesFound = await PacienteCtr.search({ documento: resultadoParse.mama.documento, sexo: 'femenino', activo: true }, { limit: 1 }, userScheduler as any);
Se podría poner un objeto/key por línea para mejorar la legibilidad (evitar líneas largas)

2021-02-24 16:59 UTC, andrrrl commented on core/mpi/jobs/nacimientosProcess.ts
> +    const rela = (relaciones: any[], id) => ((relaciones?.length) ? relaciones.some(rel => rel.referencia.toString() === id.toString()) : null);
Se podría usar un nombre más descriptivo, quizá `hayRelacion()`

2021-02-24 17:00 UTC, liquid36 commented on core/mpi/jobs/nacimientosProcess.ts
> +        console.log(error);
No me roben mis frases de Tazas

2021-03-11 11:42 UTC, condorpiedra approved these changes

2021-03-11 11:53 UTC, merged