COM: Envío comprobante derivación x mail
andes/api pull request #1285
Opened 2021-02-25 17:54 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/COM-61
### Funcionalidad desarrollada 

1. Cuando se finaliza una derivación con organización destino, se envía un mail con el comprobante de derivación
2. 
3. 

### UserStories llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/COM-61

- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si
Antes de mergear, crear configuración en CENTRO OPERATIVO MEDIDO:
`{
        "emails" : [ 
            {
                "nombre" : "recupero",
                "email" : "auditoriamedica.subsesalud@gmail.com"
            }
        ]
    }` 
TABLAS MAESTRAS / ORGANIZACIONES / CENTRO OPERATIVO MEDIDO / CONFIGURACIONES
![image](https://user-images.githubusercontent.com/25707055/109195460-4e19e480-7779-11eb-9f23-b596fbd09add.png)

 
- [ ] No

2021-02-26 12:38 UTC, negro89 approved these changes

2021-02-26 12:39 UTC, negro89 commented
Codigo ok!

2021-02-26 12:42 UTC, waltergarrido commented
sugerencia del titulo cambiar x -> por .

2021-02-26 14:33 UTC, andrrrl requested changes
:1234:

2021-02-26 14:33 UTC, andrrrl commented on core/tm/interfaces/IOrganizacion.ts
>      esCOM: Boolean;
Al menos en `typescript` se prefiere usar el tipo `string` por sobre el wrapper `String`. Lo mismo con Boolean/boolean, Number/number... 
```suggestion
            email: string,
            nombre: string
        }]
    };
    esCOM: boolean;
```

2021-02-26 14:33 UTC, andrrrl commented on utils/roboSender/sendEmail.ts
> -    html: string;
Estaban bien los tipos acá :sweat_smile: 
Se puede pispear los docs de typescript para ver que su uso es siempre con tipos primitivos (string/number/boolean) https://www.typescriptlang.org/docs/handbook/interfaces.html#our-first-interface

2021-03-01 18:08 UTC, sychus approved these changes

2021-03-02 12:38 UTC, martinebucarey approved these changes

2021-03-09 11:21 UTC, andrrrl approved these changes

2021-03-09 13:44 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3541](http://condorpiedra.andes.gob.ar:85/3541/mochawesome.html)
CYPRESS RUN: [2631](https://dashboard.cypress.io/projects/xr7gft/runs/2631/specs)
TEST START: 2021-03-09T13:43:20.926Z
TOTAL: 363
SUCCESS: 360
FAIL: 3
SKIPPED: 0

2021-03-09 17:03 UTC, kroce commented
@sychus Anduvo bien pero fallaron algunos tests

2021-03-16 18:47 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3582](http://condorpiedra.andes.gob.ar:85/3582/mochawesome.html)
CYPRESS RUN: [2665](https://dashboard.cypress.io/projects/xr7gft/runs/2665/specs)
TEST START: 2021-03-16T18:46:03.509Z
TOTAL: 292
SUCCESS: 263
FAIL: 29
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-22 13:50 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3624](http://condorpiedra.andes.gob.ar:85/3624/mochawesome.html)
CYPRESS RUN: [2705](https://dashboard.cypress.io/projects/xr7gft/runs/2705/specs)
TEST START: 2021-03-22T13:48:53.524Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-22 16:32 UTC, merged