feat(Inscripcion vacunas): agrega recurso
andes/api pull request #1286
Opened 2021-02-26 18:46 UTC by condorpiedra

### Requerimiento
Agrega recurso para la inscripción de la vacunación de Covid 19

### Funcionalidad desarrollada 

1. Verifica los datos del inscripto con Renaper
2. Realiza las verificaciones correspondientes de acuerdo al grupo en que se inscribe
3. Persiste los datos del paciente en caso que se pueda validar al inscripto
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-01 18:06 UTC, sychus reviewed
No creo q sea el mejor camino este...

2021-03-01 18:06 UTC, sychus commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +        enum: ['mayores60', 'personal-salud', 'personal-seguridad', 'docentes', 'otros']
mmm no me cierra que sea un enumerado, tal vez podríamos usar alguna colección q además de esta clasificación tenga alguna otra cosa que nos sirva (un query apuntando a la fuente de datos o algo asi). De esa forma no tendríamos que compilar el código si aparece una categoría nueva a vacunar (el tema de otros... lo sacaría)

2021-03-01 18:06 UTC, sychus commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +export const InscripcionVacuna = model('inscripcion-vacuna', InscripcionVacunaSchema, 'inscripcion-vacunas');
Es correcto que todos los campos sean iguales para todos los tipos de "vacunados" ?

2021-03-01 18:22 UTC, juuliotero commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +        enum: ['mayores60', 'personal-salud', 'personal-seguridad', 'docentes', 'otros']
Estaría bueno esto, del lado de la app también cada grupo tiene un descripción que es la que se visualiza en el select, podría sacar el dato de la colección

2021-03-01 19:14 UTC, condorpiedra commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +export const InscripcionVacuna = model('inscripcion-vacuna', InscripcionVacunaSchema, 'inscripcion-vacunas');
si por esta versión

2021-03-01 19:14 UTC, condorpiedra commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +        enum: ['mayores60', 'personal-salud', 'personal-seguridad', 'docentes', 'otros']
Está pensado para una próxima versión

2021-03-02 09:51 UTC, condorpiedra commented
> No creo q sea el mejor camino este...

¿En qué sentido? ¿que significa?

2021-03-02 09:52 UTC, condorpiedra commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +        enum: ['mayores60', 'personal-salud', 'personal-seguridad', 'docentes', 'otros']
Se agrega grupo poblacional y se muestra en la app

2021-03-02 23:56 UTC, sychus approved these changes
El código está ok

2021-03-03 11:09 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3482](http://condorpiedra.andes.gob.ar:85/3482/mochawesome.html)
CYPRESS RUN: [2576](https://dashboard.cypress.io/projects/xr7gft/runs/2576/specs)
TEST START: 2021-03-03T11:08:39.917Z
TOTAL: 358
SUCCESS: 357
FAIL: 0
SKIPPED: 1

2021-03-03 14:54 UTC, juuliotero requested changes

2021-03-03 14:54 UTC, juuliotero commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                if ((req.body.tieneTramite && inscriptoValidado.idTramite !== tramite) ||
Si la persona marco que no tiene número de trámite, entra por acá.

2021-03-03 15:09 UTC, condorpiedra commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                if ((req.body.tieneTramite && inscriptoValidado.idTramite !== tramite) ||
Si es así, por si marcó pero en realidad su documento tiene número de trámite corresponde realizarle la verificación del mismo

2021-03-03 16:38 UTC, juuliotero commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                if ((req.body.tieneTramite && inscriptoValidado.idTramite !== tramite) ||
Por ahí podría mostrarse otro mensaje para ese caso para que sea más claro, como para dar más información al usuario de qué pasó.

2021-03-04 13:03 UTC, andrrrl commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                if ((req.body.tieneTramite && inscriptoValidado.idTramite !== tramite) ||
Si, coincido con @juuliotero, creo que puede abarcar más situaciones:
- Si tiene 90 años y extravió el DNI, se le va a negar la vacuna?
- Si el número de trámite es ilegible o el usuario no lo encuentra, se le va a negar la vacuna?
- En esos casos, qué se le ofrece al usuario como alternativa? (llamá a tal nro, dirigite a tal lugar, etc)

2021-03-04 13:44 UTC, juuliotero approved these changes

2021-03-04 14:10 UTC, palita1991 approved these changes

2021-03-04 14:15 UTC, merged