feat(VAC): rutas para certificado de vacunacion covid
andes/api pull request #1291
Opened 2021-03-08 16:00 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/VAC-3
### Funcionalidad desarrollada 

1. Ruta de validación de profesional
2. POST de creación de profesional 
3. PUT `/usuarios/:usuario/organizaciones/permisos`

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si: Registro de organización "Subsecretaria de Salud", agregar atributo `subsecretariaSalud: true`
- [ ] No

2021-03-08 17:53 UTC, sychus approved these changes
Ver el detalle del findone

2021-03-08 17:53 UTC, sychus commented on core/tm/routes/profesional.ts
> +        return res.json(profesionales.length ? profesionales[0] : { errMsg: `El profesional no se encuentra registrado en Andes.` });
No conviene haear un findOne ?

2021-03-08 19:03 UTC, plammel commented on core/tm/routes/profesional.ts
> +        return res.json(profesionales.length ? profesionales[0] : { errMsg: `El profesional no se encuentra registrado en Andes.` });
listo!

2021-03-09 16:13 UTC, negro89 approved these changes

2021-03-09 16:13 UTC, negro89 commented on auth/auth.controller.ts
> +    user.email = data.email;
Unica sugerencia, quizas convertir a minúsculas para evitar problemas de matcheo futuros!

2021-03-10 17:52 UTC, palita1991 approved these changes

2021-03-11 11:12 UTC, liquid36 requested changes
¿En que contesto se usan estos endpoints?

2021-03-11 11:12 UTC, liquid36 commented on core/tm/routes/profesional.ts
> +        return res.json(profesional ? profesional : { errMsg: `El profesional no se encuentra registrado en Andes.` });
En vez de devolver **errMsg**, hya que llamar a la función **next** para que devuelve un codígo de erro 400. 

Idem en el **else**.

2021-03-15 17:14 UTC, liquid36 requested changes

2021-03-15 17:50 UTC, plammel commented on core/tm/routes/profesional.ts
> +        const token = Auth.generateUserTokenTemporaly(documento, req.body.permisos, '59380153db8e90fe4602ec02');
corregido

2021-03-16 14:39 UTC, plammel commented on modules/gestor-usuarios/usuarios.routes.ts
> +UsuariosRouter.put('/usuarios/:usuario/organizaciones/permisos', Auth.authenticate(), async (req, res, next) => {
Se cambió la asignación de permisos por request a asignación por proceso background según tipo de permiso, tanto para `UsuariosRouter.put('/usuarios/:usuario/organizaciones/permisos'` como para `const token = Auth.generateUserTokenTemporaly`

2021-03-16 15:32 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3574](http://condorpiedra.andes.gob.ar:85/3574/mochawesome.html)
CYPRESS RUN: [2657](https://dashboard.cypress.io/projects/xr7gft/runs/2657/specs)
TEST START: 2021-03-16T15:30:51.040Z
TOTAL: 366
SUCCESS: 363
FAIL: 3
SKIPPED: 0

2021-03-16 15:46 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3575](http://condorpiedra.andes.gob.ar:85/3575/mochawesome.html)
CYPRESS RUN: [2658](https://dashboard.cypress.io/projects/xr7gft/runs/2658/specs)
TEST START: 2021-03-16T15:45:37.067Z
TOTAL: 366
SUCCESS: 363
FAIL: 3
SKIPPED: 0

2021-03-16 17:38 UTC, sychus approved these changes
ok

2021-03-16 18:09 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3578](http://condorpiedra.andes.gob.ar:85/3578/mochawesome.html)
CYPRESS RUN: [2661](https://dashboard.cypress.io/projects/xr7gft/runs/2661/specs)
TEST START: 2021-03-16T18:08:10.155Z
TOTAL: 316
SUCCESS: 302
FAIL: 14
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-16 18:21 UTC, MCele commented on core/tm/routes/profesional.ts
> +        const profesional = await Profesional.findOne({ documento, sexo: regexSexo });
por ahí a modo de sugerencia y, considerando que hay profesionales duplicados por doble cargar desde la app de andes y matriculaciones, se podría realizar un "find" u otra búsqueda por "documento" y "sexo", y si existiera más de un profesional con esos datos, priorizar el que se cargó desde matriculaciones (profesionalMatriculado:true)

2021-03-16 18:35 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3581](http://condorpiedra.andes.gob.ar:85/3581/mochawesome.html)
CYPRESS RUN: [2664](https://dashboard.cypress.io/projects/xr7gft/runs/2664/specs)
TEST START: 2021-03-16T18:34:26.476Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-03-16 18:37 UTC, plammel commented on core/tm/routes/profesional.ts
> +        const profesional = await Profesional.findOne({ documento, sexo: regexSexo });
@martinebucarey @sychus

2021-03-17 15:21 UTC, MCele approved these changes

2021-03-17 15:28 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [3586](http://condorpiedra.andes.gob.ar:85/3586/mochawesome.html)
CYPRESS RUN: [2669](https://dashboard.cypress.io/projects/xr7gft/runs/2669/specs)
TEST START: 2021-03-17T15:27:02.040Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-03-17 18:01 UTC, condorpiedra requested changes

2021-03-17 18:01 UTC, condorpiedra commented on auth/auth.controller.ts
> +            const subsecretaria = await Organizacion.findOne({ subsecretariaSalud: true });
Para que serviría esta propiedad?.  Debería tener un nombre mas representativo para tomar una organización por defecto, debido a que la app se utiliza en otras provincias

2021-03-17 18:10 UTC, sychus commented on auth/auth.controller.ts
> +            const subsecretaria = await Organizacion.findOne({ subsecretariaSalud: true });
@condorpiedra esto es para darle permisos a las personas que no tienen efector asociado (mayormente serán del privado). Por otra parte, los que si tengan se les asignara en todos sus efectores

2021-03-17 18:13 UTC, sychus approved these changes

2021-03-19 15:31 UTC, kroce commented on auth/auth.controller.ts
> +            const subsecretaria = await Organizacion.findOne({ subsecretariaSalud: true });
cambiado por "matriculacion"

2021-03-19 17:46 UTC, merged