AM: permitir el registro de nuevos paciente desde la app
andes/api pull request #1292
Opened 2021-03-08 16:57 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-129

### Funcionalidad desarrollada 
1. Se suma ruta para registro de pacientes desde la app
2. Se eliminan imports sin uso

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-09 15:30 UTC, negro89 approved these changes

2021-03-09 15:30 UTC, negro89 commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +        if (!inscripto) {
Creo que idealmente todo el contenido de este 'if' podría ser una función dentro de un controller. Para dejar mas limpia la ruta (Solo a modo de sugerencia).

2021-03-11 14:55 UTC, waltergarrido approved these changes

2021-03-15 12:30 UTC, liquid36 requested changes

2021-03-15 12:30 UTC, liquid36 commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +async function validarToken(token) {
Llevar esta lógica al Auth Class (auth/auth.class.ts) y armar un middleware. 

```
router.post('/registro', Auth.captcha(), async (req: any, res, next) => {
```

2021-03-15 19:47 UTC, juuliotero commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +async function validarToken(token) {
Se armó el middleware, y se aplicó también en la ruta de inscripcion-vacunas

2021-03-23 16:08 UTC, plammel commented on auth/auth.class.ts
> +                    if (recaptcha === null || recaptcha === undefined) {
```suggestion
                    if (!recaptcha) {
```

2021-03-23 16:11 UTC, plammel commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +        if (!inscripto) {
Concuerdo

2021-03-25 17:55 UTC, juuliotero commented on auth/auth.class.ts
> +                    if (recaptcha === null || recaptcha === undefined) {
corregido

2021-04-16 14:11 UTC, plammel approved these changes

2021-04-16 17:23 UTC, plammel reviewed
Resolver conflictos

2021-04-21 13:12 UTC, liquid36 requested changes
faltaría un detalle

2021-04-21 13:12 UTC, liquid36 commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +            const paciente = await findOrCreate(inscriptoValidado, req);
```suggestion
            await extractFoto(inscriptoValidado, req);
            const paciente = await findOrCreate(inscriptoValidado, req);
```

2021-04-21 13:15 UTC, kroce requested changes

2021-04-21 13:15 UTC, kroce commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +            const inscriptoValidado = await validar(documento, sexo);
```suggestion
            const pacientValidado = await validar(documento, sexo);
```

2021-04-21 13:18 UTC, juuliotero commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +            const paciente = await findOrCreate(inscriptoValidado, req);
listo

2021-04-21 13:18 UTC, liquid36 commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +                const value = await matching(inscriptoValidado, req.body);
Si se pisa los datos con los de Renaper siempre va a dar el matching correcto. 

Ademas matching no es una función asincronica.

2021-04-21 13:18 UTC, juuliotero commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +            const inscriptoValidado = await validar(documento, sexo);
listo

2021-04-21 13:23 UTC, juuliotero commented on modules/mobileApp/auth_routes/autenticacionApp.ts
> +                const value = await matching(inscriptoValidado, req.body);
listo

2021-04-21 16:08 UTC, liquid36 approved these changes

2021-04-21 16:36 UTC, kroce approved these changes

2021-04-22 11:31 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3826](http://condorpiedra.andes.gob.ar:85/3826/mochawesome.html)
CYPRESS RUN: [2889](https://dashboard.cypress.io/projects/xr7gft/runs/2889/specs)
TEST START: 2021-04-22T11:18:42.030Z
TOTAL: 366
SUCCESS: 361
FAIL: 5
SKIPPED: 0

2021-04-22 12:30 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3829](http://condorpiedra.andes.gob.ar:85/3829/mochawesome.html)
CYPRESS RUN: [2892](https://dashboard.cypress.io/projects/xr7gft/runs/2892/specs)
TEST START: 2021-04-22T12:26:37.814Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-22 12:31 UTC, merged