VAC: consulta de estado de inscripción para vacunación
andes/api pull request #1294
Opened 2021-03-09 18:14 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-8

### Funcionalidad desarrollada 
1. Devuelve un objeto vacío si no encuentra una inscripción

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-10 18:19 UTC, palita1991 approved these changes

2021-03-11 16:08 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [3552](http://condorpiedra.andes.gob.ar:85/3552/mochawesome.html)
CYPRESS RUN: [2640](https://dashboard.cypress.io/projects/xr7gft/runs/2640/specs)
TEST START: 2021-03-11T16:06:38.675Z
TOTAL: 319
SUCCESS: 308
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-11 16:52 UTC, liquid36 requested changes

2021-03-11 16:52 UTC, liquid36 commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                return res.json({});
Acá habría que devolver un código de error. y su correspondiente hadler en la app.

2021-03-11 18:49 UTC, juuliotero commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                return res.json({});
corregido

2021-03-12 16:02 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3566](http://condorpiedra.andes.gob.ar:85/3566/mochawesome.html)
CYPRESS RUN: [2649](https://dashboard.cypress.io/projects/xr7gft/runs/2649/specs)
TEST START: 2021-03-12T16:01:01.854Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-15 16:22 UTC, plammel approved these changes

2021-03-22 16:26 UTC, kroce requested changes
La ruta devuelve información del paciente que no corresponde, como el numero de trámite y algunos otros datos que no irían. (morbilidades, etc)

2021-03-23 11:03 UTC, juuliotero commented
> La ruta devuelve información del paciente que no corresponde, como el numero de trámite y algunos otros datos que no irían. (morbilidades, etc)

Ahora devuelve solo 4 datos de la inscripción: documento - estado - fechaRegistro - fechaVacunacion

2021-03-26 15:40 UTC, palita1991 approved these changes

2021-03-26 17:59 UTC, kroce approved these changes

2021-03-26 17:59 UTC, merged