VAC: script para actualizar estado de vacunación en inscripciones
andes/api pull request #1295
Opened 2021-03-10 17:15 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-9

### Funcionalidad desarrollada 
1. Script para actualizar la fecha de vacunación y el id de prestación en las inscripciones a vacunas.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-11 18:33 UTC, waltergarrido requested changes

2021-03-11 18:33 UTC, waltergarrido commented on scripts/VAC-9.ts
> +            if (prestaciones.length) {
if(prestaciones.length>0) para controlar que no sea vació.

2021-03-11 20:25 UTC, juuliotero commented on scripts/VAC-9.ts
> +            if (prestaciones.length) {
Si el find() no encuentra valores que coincidan con los parámetros devuelve [], por lo que prestaciones.length va a ser 0. Y el 0 evalúa a false en javascript.

2021-03-11 20:48 UTC, waltergarrido approved these changes

2021-03-12 11:31 UTC, sychus approved these changes
Sugerencia: Realizar la prueba del script en la base de mongo que es copia idéntica de producción.

2021-03-12 11:31 UTC, sychus commented on scripts/VAC-9.ts
> +// Recorre todas las derivaciones y sus adjuntos migrando aquellos que no se encuentran en el  drive
```suggestion
// Recorre todas las prestaciones de vacuna y agrega la fecha e id en la colección de inscripción.
```

2021-03-12 16:22 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3567](http://condorpiedra.andes.gob.ar:85/3567/mochawesome.html)
CYPRESS RUN: [2650](https://dashboard.cypress.io/projects/xr7gft/runs/2650/specs)
TEST START: 2021-03-12T16:21:11.771Z
TOTAL: 327
SUCCESS: 318
FAIL: 9
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-12 17:12 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3568](http://condorpiedra.andes.gob.ar:85/3568/mochawesome.html)
CYPRESS RUN: [2651](https://dashboard.cypress.io/projects/xr7gft/runs/2651/specs)
TEST START: 2021-03-12T17:11:08.008Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-15 16:19 UTC, plammel approved these changes

2021-03-15 16:19 UTC, plammel commented on scripts/VAC-9.ts
> +                    return;
Suguiero utilizar el andesLog en catch de error para registrar si falló algun save. Probablemente no sea necesario si ya se testeó en la db copia de PROD, pero no estaría demás.

2021-03-22 12:06 UTC, merged