VAC: nueva ruta para exportar vacunas
andes/api pull request #1300
Opened 2021-03-17 15:28 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-136

### Funcionalidad desarrollada 
1. Separar las funciones del job exportCovid19 en un controllador, para poder reutilizarlas en una ruta.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-17 15:44 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3588](http://condorpiedra.andes.gob.ar:85/3588/mochawesome.html)
CYPRESS RUN: [2670](https://dashboard.cypress.io/projects/xr7gft/runs/2670/specs)
TEST START: 2021-03-17T15:43:47.886Z
TOTAL: 363
SUCCESS: 361
FAIL: 2
SKIPPED: 0

2021-03-17 15:54 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3589](http://condorpiedra.andes.gob.ar:85/3589/mochawesome.html)
CYPRESS RUN: [2671](https://dashboard.cypress.io/projects/xr7gft/runs/2671/specs)
TEST START: 2021-03-17T15:53:39.177Z
TOTAL: 363
SUCCESS: 361
FAIL: 2
SKIPPED: 0

2021-03-17 16:14 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3591](http://condorpiedra.andes.gob.ar:85/3591/mochawesome.html)
CYPRESS RUN: [2673](https://dashboard.cypress.io/projects/xr7gft/runs/2673/specs)
TEST START: 2021-03-17T16:12:02.592Z
TOTAL: 7
SUCCESS: 7
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-03-17 16:50 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [3593](http://condorpiedra.andes.gob.ar:85/3593/mochawesome.html)
CYPRESS RUN: [2675](https://dashboard.cypress.io/projects/xr7gft/runs/2675/specs)
TEST START: 2021-03-17T16:49:07.808Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-22 13:16 UTC, condorpiedra submitted a review, later dismissed

2021-03-22 13:16 UTC, condorpiedra commented on modules/vacunas/controller/vacunas.controller.ts
> +        const match = new Matching();
Para realizar el matcheo de personas utilizar la funcion  matching de '../core-v2/mpi/paciente/paciente.controller';

2021-03-25 12:00 UTC, sychus commented on modules/vacunas/controller/vacunas.controller.ts
> +                referenciaSistemaProvincial: '32342'   // faltaría ver bien que es esto, aunque no es obligatorio
Este es un código de sisa que hace referencia a Nosotros (no va a cambiar). De todas formas podría sacarse de acá y guardarse en alguna variable de entorno o archivito de conf.

2021-03-25 12:02 UTC, sychus commented on modules/vacunas/routes/vacunas.ts
> +        return res.json(500);
Acá se debe usar next del error

2021-03-25 12:03 UTC, sychus requested changes
ver tema next

2021-03-25 17:23 UTC, juuliotero commented on modules/vacunas/controller/vacunas.controller.ts
> +        const match = new Matching();
listo

2021-03-25 17:23 UTC, juuliotero commented on modules/vacunas/routes/vacunas.ts
> +        return res.json(500);
Corregido

2021-03-31 04:35 UTC, sychus approved these changes

2021-04-07 16:43 UTC, kroce approved these changes

2021-04-07 16:54 UTC, merged