RUP - Refactor de búsquedas de conceptos de la Huds
andes/api pull request #1304
Opened 2021-03-18 18:05 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-243

### Funcionalidad desarrollada 

1. Pasa logica de busqueda de huds desde ruta a controller
2. Nueva ruta para obtener huds de paciente desde mobile-app

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-18 18:13 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3601](http://condorpiedra.andes.gob.ar:85/3601/mochawesome.html)
CYPRESS RUN: [2682](https://dashboard.cypress.io/projects/xr7gft/runs/2682/specs)
TEST START: 2021-03-18T18:12:45.124Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-22 17:25 UTC, plammel requested changes

2021-03-22 17:25 UTC, plammel commented on modules/rup/controllers/prestacion.ts
> +export async function hudsPaciente(id, estado, idPrestacion, deadline, expresion, valor) {
Algunas observaciones y sugerencias:
- Parece que hay un problema que se viene arrastrando de la implementación anterior: Habría que controlar se esté recibiendo el `expresion` antes de realizar la búsqueda de prestaciones, porque en caso de no recibirlo se realiza la búsqueda de prestaciones en vano. (nótese que en la implementación anterior si no recibía `expresion` la ruta nisiquiera respondía) https://github.com/andes/api/blob/e15e59acd51747d0b435e1865e6a81db44a68595/modules/rup/routes/prestacion.ts#L65
- Sugiero pasar directamente el `req` como pámetro a la función `hudsPaciente` y obtener los datos dentro de la misma, para evitar pasarle tantos parámetros en el llamado (práctica aconsejable)
https://github.com/andes/api/blob/b71490242e9c6d6268c622810e4122c5bd878295/modules/rup/routes/prestacion.ts#L51

- En lugar de retornar `{ prestaciones, huds }`, sugiero retornar simplemente `huds`. En `null` si la búsqueda de prestaciones retorna null  (`!prestaciones`) y responder `return res.status(404).send('Paciente no encontrado')` en ese caso.

- Validar el length de `prestaciones` antes de llamar `SnomedCtr.getConceptByExpression`, ya que si el array está vació, se habrá realizado la búsqueda de conceptos en vano.

2021-03-22 17:25 UTC, plammel commented on modules/mobileApp/routes/prestacion.routes.ts
> +    const valor = req.query.valor || undefined;
¿Es necesaria la asignación `undefined` a los parametros? Si no se reciben estos datos, de todas maneras serán evaluados como `false`.

2021-03-22 17:35 UTC, liquid36 commented on modules/rup/controllers/prestacion.ts
> +export async function hudsPaciente(id, estado, idPrestacion, deadline, expresion, valor) {
La parte del req no es aconsejable, porque lo hace 100% dependiente del Request. No se podría usar desde otro endpoint o desde algún proceso en background. 
Los REQ no deberían pasar a más profundidad que la función de express. Salvo que se necesita para el loggin. (tema a resolver) .

Lo ideal que sea un objeto con campos obligatorios y opcionales. Y agregarle interfaces.

2021-03-23 10:46 UTC, liquid36 commented
Hay que resolver conflictos

2021-03-29 17:29 UTC, juuliotero requested changes
Si uno manda un id de paciente que no corresponda a un ObjectId, devuelve el error 'Turno no encontrado'. Esto se venía arrastrando de antes, pero por ahí estaría bueno cambiar el mensaje con este PR.

2021-03-29 19:48 UTC, negro89 commented
Corregido!

2021-04-09 13:09 UTC, liquid36 approved these changes

2021-04-09 13:23 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3735](http://condorpiedra.andes.gob.ar:85/3735/mochawesome.html)
CYPRESS RUN: [2803](https://dashboard.cypress.io/projects/xr7gft/runs/2803/specs)
TEST START: 2021-04-09T13:20:41.771Z
TOTAL: 363
SUCCESS: 361
FAIL: 2
SKIPPED: 0

2021-04-09 13:32 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3736](http://condorpiedra.andes.gob.ar:85/3736/mochawesome.html)
CYPRESS RUN: [2804](https://dashboard.cypress.io/projects/xr7gft/runs/2804/specs)
TEST START: 2021-04-09T13:29:53.928Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-04-09 13:34 UTC, merged