mpi: se agregan controles por foto null al validar con renaper
andes/api pull request #1309
Opened 2021-03-22 11:48 UTC by MCele

### Requerimiento

Se agregan controles por foto null al validar con renaper , ya que si el paciente se trae de renaper con foto null se lo debe validar con sisa

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-03-22 16:32 UTC, plammel requested changes

2021-03-22 16:32 UTC, plammel commented on core-v2/mpi/validacion/validacion.controller.ts
> +                ciudadanoRenaper = null;
Revisar este control: si la persona encontrada no tiene foto, evita que se valide ese dato inexistente; pero también anula la asignación de estado y dirección. ¿Es este el comportamiento deseado?.
De igual manera anula la asignación de dirección a `ciudadanoSisa` en la línea 53: https://github.com/andes/api/blob/82e4ed7bbd7c9b03715f5c78deff1e82d483e0ca/core-v2/mpi/validacion/validacion.controller.ts#L53

2021-03-22 17:34 UTC, plammel commented
OJO! @MCele  posible duplicación con https://github.com/andes/api/pull/1303

2021-03-22 19:08 UTC, MCele commented
> OJO! @MCele posible duplicación con #1303

Si lo vi luego de hacer el PR. Pero lo tiene que revisa @condorpiedra  para evaluar si lo cerramos.

2021-04-13 16:34 UTC, condorpiedra commented
Funcionalidad contemplada en PR https://github.com/andes/api/pull/1303/files

2021-04-13 16:34 UTC, closed without merging