VAC - Agrega filtro por fecha de registro
andes/api pull request #1325
Opened 2021-03-31 15:31 UTC by negro89

### Requerimiento
Poder filtrar por fecha de registro en el listado
Poder filtrar segun pacientes vacunados

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-03-31 15:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [3694](http://condorpiedra.andes.gob.ar:85/3694/mochawesome.html)
CYPRESS RUN: [2765](https://dashboard.cypress.io/projects/xr7gft/runs/2765/specs)
TEST START: 2021-03-31T15:45:19.116Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

2021-03-31 16:42 UTC, liquid36 requested changes

2021-03-31 16:42 UTC, liquid36 commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +        fechaDesde: {
ResourceBase tiene sus metodos de busuqeda de fecha: 

Ejemplo:
https://github.com/andes/api/blob/master/modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts#L11

https://github.com/andes/app/blob/master/src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts#L35

2021-04-06 11:22 UTC, sychus approved these changes

2021-04-07 19:44 UTC, negro89 commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +        fechaDesde: {
Corregido!

2021-04-14 11:54 UTC, condorpiedra approved these changes

2021-04-14 11:55 UTC, merged