VAC: Nueva inscripción
andes/api pull request #1332
Opened 2021-04-08 11:35 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-28

### Funcionalidad desarrollada 
1. Cambio de nombre de ruta post para registro público
2. Se habilita el post de ResourceBase

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-04-15 10:15 UTC, JSantarelli commented
Un detalle, el checkbox de "he recibido otra vacuna..." tiende a quedar en la misma línea que el elemento previo. Una posible solución momentánea sería agregar `class="d-block"` al elemento en cuestión (los `plex-bool` no cuentan con dicha propiedad).

![checkbox-inline](https://user-images.githubusercontent.com/5895886/114853160-e3b91400-9db9-11eb-8fee-eeecceac4e32.PNG)

2021-04-15 12:28 UTC, juuliotero commented
> Un detalle, el checkbox de "he recibido otra vacuna..." tiende a quedar en la misma línea que el elemento previo. Una posible solución momentánea sería agregar `class="d-block"` al elemento en cuestión (los `plex-bool` no cuentan con dicha propiedad).
> 
> ![checkbox-inline](https://user-images.githubusercontent.com/5895886/114853160-e3b91400-9db9-11eb-8fee-eeecceac4e32.PNG)

Corregido!

2021-04-15 14:13 UTC, palita1991 requested changes
@juuliotero Cada vez que ingreso al listado me sale ese error que puede ser?
![image](https://user-images.githubusercontent.com/30004190/114883801-9e0d4300-9ddb-11eb-8202-f409697964c4.png)

2021-04-15 19:33 UTC, condorpiedra commented
> @juuliotero Cada vez que ingreso al listado me sale ese error que puede ser?
> ![image](https://user-images.githubusercontent.com/30004190/114883801-9e0d4300-9ddb-11eb-8202-f409697964c4.png)

El problema estaba en el formato de la fecha que se enviaba desde la app.  Ya se corrigió, pero como la rama no estaba rebasada seguía apareciendo. Si es posible tratar de reproducirlo nuevamente.

2021-04-16 13:38 UTC, palita1991 commented
> > @juuliotero Cada vez que ingreso al listado me sale ese error que puede ser?
> > ![image](https://user-images.githubusercontent.com/30004190/114883801-9e0d4300-9ddb-11eb-8202-f409697964c4.png)
> 
> El problema estaba en el formato de la fecha que se enviaba desde la app. Ya se corrigió, pero como la rama no estaba rebasada seguía apareciendo. Si es posible tratar de reproducirlo nuevamente.

@condorpiedra actualice ambas ramitas y me sigue apareciendo, no se que será

2021-04-22 16:01 UTC, palita1991 approved these changes

2021-04-22 16:06 UTC, condorpiedra approved these changes

2021-04-22 16:06 UTC, merged