Fix en job que finaliza antes de lo esperado
andes/api pull request #1339
Opened 2021-04-13 15:57 UTC by MCele

### Requerimiento

Fix ya que el job importarnacimientos finaliza antes de lo esperado y sólo se ejecutaba la primera parte

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-04-13 16:31 UTC, sychus requested changes
importarNacimientos(done) Si quito el done entonces este parámetro no es necesario

2021-04-13 16:32 UTC, sychus commented
@MCele en el archivo importarNacimeintosJob.ts la fecha está comentada esto está bien? y en caso que no vaya comentada no debería ir por parámetro a algún método?

2021-04-15 14:30 UTC, MCele commented
> @MCele en el archivo importarNacimeintosJob.ts la fecha está comentada esto está bien? y en caso que no vaya comentada no debería ir por parámetro a algún método?

La fecha que toma por defecto es la actual al momento de ejecutarlo. Lo comentado es por si se desea correrlo de forma manual para alguna fecha particular. Por ejemplo, para pruebas locales o, de ser necesario, algún caso particular en el que se cortó la ejecución en determinada fecha y no se pudo completar el proceso.

2021-04-15 16:26 UTC, MCele commented
> importarNacimientos(done) Si quito el done entonces este parámetro no es necesario

resuelto!

2021-04-15 16:59 UTC, liquid36 approved these changes

2021-04-15 18:43 UTC, sychus approved these changes
💯

2021-04-16 11:50 UTC, merged