VAC: filtro por certificado en listado de inscripciones
andes/api pull request #1341
Opened 2021-04-14 15:52 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-36

### Funcionalidad desarrollada 
1. Nuevo filtro por tieneCertificado

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-04-16 17:44 UTC, plammel requested changes

2021-04-16 17:44 UTC, plammel commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +        tieneCertificado: {
Validar que el parámetro tiene `tieneCertificado` sea un booleano valido, ya que si no lo es puede hacer una consulta mal formada
![image](https://user-images.githubusercontent.com/25707055/115063597-2534e680-9ec2-11eb-9bf6-2096d5d61e1e.png)

2021-04-19 18:31 UTC, juuliotero commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +        tieneCertificado: {
El control lo está haciendo mongoose, por eso devuelve un error.

2021-04-19 18:47 UTC, plammel approved these changes

2021-04-20 12:11 UTC, kroce requested changes
@juuliotero los certificados se generan solo para el grupo con factores de riesgo. En el resto de los grupos esta columna debería aparecer sin la X

2021-04-20 13:10 UTC, kroce approved these changes

2021-04-20 13:12 UTC, merged