feat(COM): se verifica si tiene un email asociado para auditoria de com
andes/api pull request #1347
Opened 2021-04-16 22:24 UTC by sychus

### Funcionalidad desarrollada 

1. Se realiza control por si el COM no tiene email asociado.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-04-16 22:29 UTC, condorpiedra requested changes

2021-04-16 22:29 UTC, condorpiedra commented on modules/centroOperativoMedico/derivaciones.routes.ts
>                  if (isPacienteDestino && organizacion.esCOM) {
verificar si tiene configuraciones y el array de emails:  org.configuraciones && org.configuraciones.emails

2021-04-16 22:33 UTC, sychus commented on modules/centroOperativoMedico/derivaciones.routes.ts
>                  if (isPacienteDestino && organizacion.esCOM) {
esta verificado con el "?". Lo probe para ambos casos y funciona ok.

2021-04-16 22:45 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3794](http://condorpiedra.andes.gob.ar:85/3794/mochawesome.html)
CYPRESS RUN: [2859](https://dashboard.cypress.io/projects/xr7gft/runs/2859/specs)
TEST START: 2021-04-16T22:42:42.020Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-19 14:06 UTC, plammel requested changes

2021-04-19 14:06 UTC, plammel commented on modules/centroOperativoMedico/derivaciones.routes.ts
> +                if (isPacienteDestino && organizacion.esCOM && organizacion.configuraciones.emails) {
```suggestion
                if (isPacienteDestino && organizacion.esCOM && organizacion.configuraciones?.emails) {
```

2021-04-20 11:56 UTC, sychus commented on modules/centroOperativoMedico/derivaciones.routes.ts
> +                if (isPacienteDestino && organizacion.esCOM && organizacion.configuraciones.emails) {
ready

2021-04-27 16:35 UTC, liquid36 approved these changes

2021-05-03 15:13 UTC, kroce approved these changes

2021-05-03 21:02 UTC, condorpiedra approved these changes

2021-05-03 21:24 UTC, merged