PER: recurso de carnet perinatal
andes/api pull request #1349
Opened 2021-04-20 16:47 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-19
https://proyectos.andes.gob.ar/browse/PER-16

### Funcionalidad desarrollada 
1. Nuevo recurso carnet-perinatal
2. Eventos para carnet-perinatal

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

En el elementoRUP para el conceptId 1191000013107 (consulta de control de embarazo), hay que agregar:

_"dispatch" : [ 
        {
            "event" : "perinatal:control:validacion",
            "method" : "validar-prestacion"
        }, 
        {
            "event" : "perinatal:control:cancelar-validacion",
            "method" : "romper-validacion"
        }
    ]_

2021-04-21 11:29 UTC, liquid36 requested changes

2021-04-21 11:29 UTC, liquid36 commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +EventCore.on('perinatal:control:validacion', async ({ prestacion }) => {
Si proviene de un dispatch de un elementoRUP, viene el registro como argumento. Te ahorras de buscarlo a mano y de tener el conceptId hardcoreado. 

```suggestion
EventCore.on('perinatal:control:validacion', async ({ prestacion, registro }) => {
```

2021-04-21 11:29 UTC, liquid36 commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +                fechaUltimoControl: moment(prestacion.ejecucion.fecha).startOf('day').toDate(),
Acá usas un startOf pero en el caso de arriba (si ya existe el carnet) no. Van a quedar inconsistente.

2021-04-21 11:29 UTC, liquid36 commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +            await CarnetPerinatalCtr.create(carnet, dataLog);
Existe un metodo para extraer el usuario que audito la prestación para no tener que inventar datos. 

```suggestion
    const user = Auth.getUserFromResource(prestacion);
    await CarnetPerinatalCtr.create(carnet, user);
```

2021-04-21 11:29 UTC, liquid36 commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +dataLog.method = null;
ESto así no es necesario.

2021-04-21 14:55 UTC, juuliotero commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +dataLog.method = null;
corregido

2021-04-21 14:55 UTC, juuliotero commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +                fechaUltimoControl: moment(prestacion.ejecucion.fecha).startOf('day').toDate(),
corregido

2021-04-21 14:55 UTC, juuliotero commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +EventCore.on('perinatal:control:validacion', async ({ prestacion }) => {
corregido

2021-04-27 11:19 UTC, liquid36 commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +        const gesta = registro.valor.term;
Usaría el conceptiId y no el term para identificar la gesta.

2021-04-27 22:24 UTC, juuliotero commented on modules/perinatal/controller/carnet-perinatal.events.ts
> +        const gesta = registro.valor.term;
Modificado

2021-05-03 19:15 UTC, MCele requested changes
Se generan 2 documentos en la colección para un mismo paciente y embarazo, por ejemplo para dos controles sobre un mismo paciente en el que el embarazo se lo carga como "primigesta" en uno  y "primigesta añosa" en el otro. Ambos tienen conceptId distintos pero corresponden al primer embarazo.

2021-05-04 14:01 UTC, juuliotero commented
> Se generan 2 documentos en la colección para un mismo paciente y embarazo, por ejemplo para dos controles sobre un mismo paciente en el que el embarazo se lo carga como "primigesta" en uno y "primigesta añosa" en el otro. Ambos tienen conceptId distintos pero corresponden al primer embarazo. Creo que se debería considerar primer embarazo a todo lo que involucra "primeriza": true

corregido

2021-05-05 12:29 UTC, MCele approved these changes

2021-05-05 18:18 UTC, condorpiedra approved these changes

2021-05-05 18:48 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [3962](http://condorpiedra.andes.gob.ar:85/3962/mochawesome.html)
CYPRESS RUN: [3009](https://dashboard.cypress.io/projects/xr7gft/runs/3009/specs)
TEST START: 2021-05-05T18:48:05.381Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-05 18:51 UTC, merged