Core 82
andes/api pull request #1356
Opened 2021-04-21 17:55 UTC by liquid36

### Requerimiento

Implementa AndesServices. 

### Funcionalidad desarrollada 
1. 
2. 
3. 

### UserStories llegó a completarse
- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [ ] No

2021-04-21 23:53 UTC, sychus requested changes

2021-04-21 23:53 UTC, sychus commented on core/tm/routes/profesional.ts
> +    const resRenaper = await services.get('renaper').exec({ documento, sexo });
exec sigue vigente??

2021-04-21 23:53 UTC, sychus commented on initialize.ts
> +import { setupServicies } from './services';
spelling: setupServices

2021-04-21 23:53 UTC, sychus commented on initialize.ts
> +    setupServicies(app);
spelling: setupServices

2021-04-21 23:53 UTC, sychus commented on services.ts
> +export function setupServicies(app: express.Express) {
spelling: setupServices

2021-04-23 16:26 UTC, liquid36 commented
El exec de Mongo esta deprecado, esto es otra cosa.

2021-04-23 16:38 UTC, sychus commented
> El exec de Mongo esta deprecado, esto es otra cosa.

Sip....me di cuenta cuando miré el codigo del paquete... por eso saque el comentario. :-)

2021-04-23 16:41 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3850](http://condorpiedra.andes.gob.ar:85/3850/mochawesome.html)
CYPRESS RUN: [2913](https://dashboard.cypress.io/projects/xr7gft/runs/2913/specs)
TEST START: 2021-04-23T16:41:37.760Z
TOTAL: 375
SUCCESS: 367
FAIL: 8
SKIPPED: 0

2021-04-23 17:00 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3851](http://condorpiedra.andes.gob.ar:85/3851/mochawesome.html)
CYPRESS RUN: [2914](https://dashboard.cypress.io/projects/xr7gft/runs/2914/specs)
TEST START: 2021-04-23T16:51:19.022Z
TOTAL: 375
SUCCESS: 367
FAIL: 8
SKIPPED: 0

2021-04-23 19:08 UTC, sychus approved these changes

2021-04-27 11:34 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3860](http://condorpiedra.andes.gob.ar:85/3860/mochawesome.html)
CYPRESS RUN: [2922](https://dashboard.cypress.io/projects/xr7gft/runs/2922/specs)
TEST START: 2021-04-27T11:34:12.562Z
TOTAL: 370
SUCCESS: 368
FAIL: 2
SKIPPED: 0

2021-04-27 12:02 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3863](http://condorpiedra.andes.gob.ar:85/3863/mochawesome.html)
CYPRESS RUN: [2924](https://dashboard.cypress.io/projects/xr7gft/runs/2924/specs)
TEST START: 2021-04-27T12:02:39.585Z
TOTAL: 370
SUCCESS: 369
FAIL: 1
SKIPPED: 0

2021-05-04 18:40 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3926](http://condorpiedra.andes.gob.ar:85/3926/mochawesome.html)
CYPRESS RUN: [2979](https://dashboard.cypress.io/projects/xr7gft/runs/2979/specs)
TEST START: 2021-05-04T18:40:25.901Z
TOTAL: 370
SUCCESS: 338
FAIL: 32
SKIPPED: 0

2021-05-05 11:52 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [3936](http://condorpiedra.andes.gob.ar:85/3936/mochawesome.html)
CYPRESS RUN: [2985](https://dashboard.cypress.io/projects/xr7gft/runs/2985/specs)
TEST START: 2021-05-05T11:52:02.083Z
TOTAL: 370
SUCCESS: 370
FAIL: 0
SKIPPED: 0

2021-05-13 16:33 UTC, merged