COM: unidad destino derivación
andes/api pull request #1357
Opened 2021-04-22 12:26 UTC by plammel

### Requerimiento

https://github.com/andes/api/compare/COM-70
### Funcionalidad desarrollada 

1. Incluye unidad destino en derivación
2. 
3. 

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si: Modificar registro de organización de organización de CENTRO OPERATIVO MEDICO. Modificar flag `aceptaDerivacion: true`
- [ ] No

2021-04-22 12:42 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3830](http://condorpiedra.andes.gob.ar:85/3830/mochawesome.html)
CYPRESS RUN: [2893](https://dashboard.cypress.io/projects/xr7gft/runs/2893/specs)
TEST START: 2021-04-22T12:39:08.664Z
TOTAL: 366
SUCCESS: 366
FAIL: 0
SKIPPED: 0

2021-04-26 20:16 UTC, sychus approved these changes
💯

2021-04-27 11:10 UTC, liquid36 requested changes

2021-04-27 11:10 UTC, liquid36 commented on modules/centroOperativoMedico/schemas/derivaciones.schema.ts
> +    unidadDestino: {
Las unidades organizativas son conceptos de Snomed, en toda la aplicación se usan como tal. 
Sugiero que se registre de la misma manera.

2021-04-27 18:14 UTC, plammel commented on modules/centroOperativoMedico/schemas/derivaciones.schema.ts
> +    unidadDestino: {
Modificado

2021-04-27 18:28 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [3877](http://condorpiedra.andes.gob.ar:85/3877/mochawesome.html)
CYPRESS RUN: [2936](https://dashboard.cypress.io/projects/xr7gft/runs/2936/specs)
TEST START: 2021-04-27T18:28:03.196Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-04-27 19:22 UTC, sychus reviewed
@plammel no veo más en las descripciones ni en ningún lado la info del sector.

2021-04-28 12:24 UTC, sychus approved these changes
ahora quedo ok!

2021-04-28 14:11 UTC, martinebucarey approved these changes

2021-04-28 14:26 UTC, merged