MPI - Detecta vinculación de pacientes y emite un evento
andes/api pull request #1368
Opened 2021-04-30 19:01 UTC by negro89

### Requerimiento
Detectar vinculación de pacientes para actualizar datos mediante un evento

### Funcionalidad desarrollada 

1. Nueva funcion en controller para determinar si una operación de modificación es una vinculación

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-04-30 20:13 UTC, sychus requested changes

2021-04-30 20:13 UTC, sychus commented on core-v2/mpi/paciente/paciente.controller.ts
> +    }
En el caso de los temporales, no me sirve para hacer el rollback. Es decir, el patch va a devolver activo true y el paciente temporal. Pero vos solo controlas que tengas un array de identificadores. Y los temporales no tienen identificadores.

2021-04-30 20:13 UTC, sychus commented on core-v2/mpi/paciente/paciente.routes.ts
> +        }
Sigo pensando que es un problema disparar el event acá... para mi tendríamos que tener una ruta específica. En el PR que hice, tuve q hacer algo similar a esto... pero aún no me satisface jajaja

2021-05-03 15:29 UTC, negro89 commented on core-v2/mpi/paciente/paciente.controller.ts
> +    }
@sychus cualquier paciente que posea vinculaciones tiene un array de identificadores. Lo mas probable es que uno de los dos no lo tenga (Paciente que queda inactivo) a menos que también tenga una vinculación. Lo que se controla no es en si que tenga este array, sino que se compara el paciente modificado contra el de la DB para saber si se agregó o quitó un paciente vinculado.

2021-05-03 15:29 UTC, negro89 commented on core-v2/mpi/paciente/paciente.routes.ts
> +        }
jejeje volvamos al análisis entonces.

2021-05-03 21:30 UTC, sychus commented on core-v2/mpi/paciente/paciente.controller.ts
> +    }
Claro, pero sigue pasando lo mismo q en mi solución. Es decir, como se ejecuta en un patch no importa si hubo una acción de vinculación o no siempre se va a disparar el evento salvo que ninguno de los 2 tenga un array de vinculación (es el único caso que podemos afirmar q no se realizó la acción) como vos bien pones return false. Pero es por eso mismo que no me cierra. La propuesta sería entonces tener un endpoint que sólo se dispare cuando la acción de vincular o desvincular se lleve a cabo. De esa forma, podría reusar el código que hice y realizar la acción de actualización de las prestaciones sólo en los casos de vinculación o desvinculación.

2021-05-05 16:21 UTC, sychus commented
@negro89 hice unas modificaciones tomando como base esto que armaste. Pero cierro este PR por otro nuevo y lo charlamos dale?

2021-05-05 16:21 UTC, closed without merging