feat(mpi): Eventos de linkeo y deslinkeo y actualización de la información de pacientes en las prestaciones médicas
andes/api pull request #1376
Opened 2021-05-05 16:37 UTC by sychus

### Requerimiento
Poder realizar la actualización de la información del objeto pacientes para los eventos de vinculación y desvinculación de pacientes.

### Funcionalidad desarrollada 

1. Se crearon eventos para actualizar el objeto paciente dentro de las prestaciones.
2. Se Agregaron controles deontro del patch de paciente existente para poder identificar correctamente cada una de las acciones.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-05-05 16:53 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3956](http://condorpiedra.andes.gob.ar:85/3956/mochawesome.html)
CYPRESS RUN: [3003](https://dashboard.cypress.io/projects/xr7gft/runs/3003/specs)
TEST START: 2021-05-05T16:53:32.372Z
TOTAL: 367
SUCCESS: 353
FAIL: 14
SKIPPED: 0

2021-05-05 17:40 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3957](http://condorpiedra.andes.gob.ar:85/3957/mochawesome.html)
CYPRESS RUN: [3004](https://dashboard.cypress.io/projects/xr7gft/runs/3004/specs)
TEST START: 2021-05-05T17:40:27.334Z
TOTAL: 367
SUCCESS: 353
FAIL: 14
SKIPPED: 0

2021-05-05 19:17 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3964](http://condorpiedra.andes.gob.ar:85/3964/mochawesome.html)
CYPRESS RUN: [3011](https://dashboard.cypress.io/projects/xr7gft/runs/3011/specs)
TEST START: 2021-05-05T19:16:44.540Z
TOTAL: 295
SUCCESS: 276
FAIL: 19
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-05-05 19:35 UTC, negro89 commented on core-v2/mpi/paciente/paciente.controller.ts
> +    return false;
```suggestion
    return !paciente.activo && data.activo;
```

2021-05-05 19:35 UTC, negro89 commented on core-v2/mpi/paciente/paciente.events.ts
> +        return error;
Quizás este error no debería retornarse ya que se trata de un evento que ocurre 'por atrás' y que debe ser invisible para el usuario.

2021-05-05 20:02 UTC, sychus commented on core-v2/mpi/paciente/paciente.controller.ts
> +    return false;
Correcto!!!

2021-05-05 20:02 UTC, sychus commented on core-v2/mpi/paciente/paciente.events.ts
> +        return error;
Si totalmente

2021-05-05 20:14 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3965](http://condorpiedra.andes.gob.ar:85/3965/mochawesome.html)
CYPRESS RUN: [3012](https://dashboard.cypress.io/projects/xr7gft/runs/3012/specs)
TEST START: 2021-05-05T20:14:25.852Z
TOTAL: 367
SUCCESS: 353
FAIL: 14
SKIPPED: 0

2021-05-06 13:47 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3978](http://condorpiedra.andes.gob.ar:85/3978/mochawesome.html)
CYPRESS RUN: [3025](https://dashboard.cypress.io/projects/xr7gft/runs/3025/specs)
TEST START: 2021-05-06T13:46:56.192Z
TOTAL: 367
SUCCESS: 351
FAIL: 16
SKIPPED: 0

2021-05-06 14:44 UTC, negro89 approved these changes

2021-05-06 15:08 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [3985](http://condorpiedra.andes.gob.ar:85/3985/mochawesome.html)
CYPRESS RUN: [3032](https://dashboard.cypress.io/projects/xr7gft/runs/3032/specs)
TEST START: 2021-05-06T15:08:16.378Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

2021-05-07 11:33 UTC, condorpiedra requested changes

2021-05-07 11:33 UTC, condorpiedra commented on core-v2/mpi/paciente/paciente.routes.ts
> +            EventCore.emitAsync('mpi:pacientes:link', updated);
La emisión de los eventos debería estar en la función linkOperation para dejar más limpia la ruta

2021-05-07 11:33 UTC, condorpiedra commented on core-v2/mpi/paciente/paciente.routes.ts
> +            EventCore.emitAsync('mpi:pacientes:unlink', updated);
igual al anterior

2021-05-07 12:20 UTC, MCele requested changes

2021-05-07 12:20 UTC, MCele commented on core-v2/mpi/paciente/paciente.controller.ts
> +    return !paciente.activo && data.activo;
No creo que alcance con controlar un cambio de estado en el paciente (de inactivo a activo), ya que eso también se puede realizar de forma manual desde auditoría y en ese caso se ejecuta el mismo patch. Por lo que luego se termina ejecutando el evento 'mpi:pacientes:unlink'

2021-05-07 12:32 UTC, MCele commented
Según entiendo el objetivo es actualizar las prestacines del paciente vinculado (el que se inactiva). Según lo que probé al vincular se actualizan las prestaciones del paciente principal (activo) desde el evento mpi:pacientes:link y no para el paciente vinculado.
Tener en cuenta que al momento de vincular se ejecutan 2 Patch, uno por cada paciente (se agrega el vinculado al principal y se edita el estado del vinculado).

2021-05-07 12:42 UTC, MCele commented
Otra inquietud que me surgió es si por ahora no se va a considerar la vinculación que realiza la api internamente al crear un paciente desde MPI en el evento "mpi:patient:create"?

2021-05-07 12:52 UTC, sychus commented
> Otra inquietud que me surgió es si por ahora no se va a considerar la vinculación que realiza la api internamente al crear un paciente desde MPI en el evento "mpi:patient:create"?

Es que es lo que le decia a Naty, para mi todo este control debe estar en la API y no en la app. ES innecesario hacer 2 patch, por eso el primer planteo era tenerlo separado en otra ruta. Lo que hice fue adaptarme a como lo tienen hoy ¿Uds ven otra forma de hacerlo así como está hoy?

2021-05-27 15:37 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4191](http://condorpiedra.andes.gob.ar:85/4191/mochawesome.html)
CYPRESS RUN: [3222](https://dashboard.cypress.io/projects/xr7gft/runs/3222/specs)
TEST START: 2021-05-27T15:36:53.022Z
TOTAL: 393
SUCCESS: 393
FAIL: 0
SKIPPED: 0

2021-05-28 10:36 UTC, condorpiedra requested changes

2021-05-28 10:36 UTC, condorpiedra commented on modules/rup/controllers/prestacion.ts
> +                        obraSocial: sourcePatient.financiador[0] ? sourcePatient.financiador[0] : p.paciente.financiador[0],
p.paciente no contiene la propiedad tiene financiador

2021-05-28 14:34 UTC, sychus commented on modules/rup/controllers/prestacion.ts
> +                        obraSocial: sourcePatient.financiador[0] ? sourcePatient.financiador[0] : p.paciente.financiador[0],
@condorpiedra esto ya lo modificaste, cierro esta observación entonces.

2021-05-28 14:53 UTC, condorpiedra commented
> me parece que estamos creando aún más dependencia con la APP enviando esta información extra. Si el día de mañana queremos hacer esta operación hay que replicar esto en todas las apps satelites que lo hagan (acordarse de enviar esa info extra). Conceptualmente es una responsabilidad de la api resolver todo esto, por eso yo usaba el paciente inmutable para evitar enviar información extra desde la app.

No es responsabilidad del recurso paciente resolver esto. Los ideal es mantener este recurso lo mas restful posible

2021-06-01 17:15 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4231](http://condorpiedra.andes.gob.ar:85/4231/mochawesome.html)
CYPRESS RUN: [3257](https://dashboard.cypress.io/projects/xr7gft/runs/3257/specs)
TEST START: 2021-06-01T17:15:31.461Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-01 18:08 UTC, condorpiedra approved these changes

2021-06-01 18:16 UTC, merged