AM: registro de familiares desde la app
andes/api pull request #1386
Opened 2021-05-13 18:46 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-153

### Funcionalidad desarrollada 
1. Nueva ruta para registrar un hijo menos a 11 años a un paciente

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-05-13 19:02 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [4060](http://condorpiedra.andes.gob.ar:85/4060/mochawesome.html)
CYPRESS RUN: [3096](https://dashboard.cypress.io/projects/xr7gft/runs/3096/specs)
TEST START: 2021-05-13T19:02:36.725Z
TOTAL: 388
SUCCESS: 388
FAIL: 0
SKIPPED: 0

2021-05-17 11:52 UTC, JSantarelli approved these changes

2021-05-18 13:36 UTC, kroce requested changes
@juuliotero sería bueno mover la lógica al controller para que la ruta sea mas legible, por otro lado una observación de @condorpiedra, no se está seteando el sexo en el familiar.

2021-05-18 15:49 UTC, andrrrl approved these changes
:medal_sports:

2021-05-18 16:30 UTC, juuliotero commented
> @juuliotero sería bueno mover la lógica al controller para que la ruta sea mas legible, por otro lado una observación de @condorpiedra, no se está seteando el sexo en el familiar.
> Perdón...lo del sexo ya estaba asi, dejemoslo entonces.

corregido

2021-05-18 16:39 UTC, andrrrl requested changes

2021-05-18 16:39 UTC, andrrrl commented on modules/mobileApp/routes/paciente.ts
> +                if (edadFamiliar > 11) {
Debería ser
```suggestion
                if (edadFamiliar > 10) {
```

2021-05-18 17:12 UTC, juuliotero commented on modules/mobileApp/routes/paciente.ts
> +                if (edadFamiliar > 11) {
listo

2021-05-19 11:44 UTC, andrrrl approved these changes

2021-05-26 16:43 UTC, plammel reviewed
Me surgen algunas preguntas viendo este requerimiento... @kroce 
¿Existe algún tipo de control que evite que, como usuario, vincule desde la app como hijo propio a un niño cualquiera?
Teniendo en cuenta que muchos niños no se crían bajo la tutela de sus padres, ¿No sería apropiado orientar esta funcionalidad a usuario "adulto responsable" (abuelxs, tixs, etc) o algo por el estilo?
Código OK.

2021-05-27 11:18 UTC, kroce commented
> Me surgen algunas preguntas viendo este requerimiento... @kroce
> ¿Existe algún tipo de control que evite que, como usuario, vincule desde la app como hijo propio a un niño cualquiera? (entiendo que el nro de tramite de DNI sería una forma de control)
> Teniendo en cuenta que muchos niños no se crían bajo la tutela de sus padres, ¿No sería apropiado orientar esta funcionalidad a usuario "adulto responsable" (abuelxs, tixs, etc) o algo por el estilo?
> Código OK.

@plammel como mencionás el control sería a través del número de trámite. Respecto a lo otro, por ahora el cambio es para poder vincular lo que actualmente puede accederrse desde "Mis familiares" a través de la app mobile, que son solo los hijos menores de 11 años.

2021-05-27 11:26 UTC, kroce approved these changes

2021-05-27 11:34 UTC, plammel approved these changes

2021-05-27 11:42 UTC, merged