feat(fichaEpidemiologica): Apertura de casos por nexo y antigeno desde la ficha epidemiológica
andes/api pull request #1390
Opened 2021-05-14 17:22 UTC by sychus

- Nuevo job para abrir casos por nexo y antígeno desde la ficha de epidemiología.
- Está completamente separado del proceso de prestaciones existente debido a que van a tener que convivir un tiempo hasta que finalmente el otro JOB se desactive.

### Requerimiento

https://proyectos.andes.gob.ar/browse/EP-68

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-05-17 11:29 UTC, liquid36 commented on jobs/exportNexosFichaSisa.ts
> +export async function exportSisaFicha(done, horas) {
Después de lo aprendido con el otro Job y las idas y vuelta que tuve, le podnría a esta función  un Desde/Hasta. Y que sea el Job que calcule las horas, es decir, que haga la cuentita de la hora actual menos 4. 
De esta forma, ha futuro si se quiere llamar desde una API no hay que tocar más nada.

2021-05-17 11:30 UTC, liquid36 commented on jobs/exportNexosFichaSisa.ts
> +                    $toObjectId: '$createdBy.organizacion.id'
Me llama la atención! La ficha no tienen un campo Organización?

A la larga confiar de la organización del Token no es una buena idea. Puede que queramos crear una ficha de una organización desde otra o desde algún job.

2021-05-18 13:21 UTC, sychus commented on jobs/exportNexosFichaSisa.ts
> +export async function exportSisaFicha(done, horas) {
buena observación, lo que hice también fue la posibilidad de llamarlo con desde y hasta (entre fechas) para que calcule las horas o el bien que envie la cantiudad de horas que quiera y por default 4. Creo que con eso se cubren todos los aspectos.

2021-05-18 13:37 UTC, sychus commented on jobs/exportNexosFichaSisa.ts
> +                    $toObjectId: '$createdBy.organizacion.id'
Si tiene, la cuestión es que se puede ir pisando la información y cada instancia pisoteada se guarda como un snapshot en el historial de modificaciones de esa ficha (otra colección). Pero el registro que nunca cambia es el createdAt y por eso lo saque de ahí. La información que va a sisa siempre tiene que sea de la organzación que crea la ficha (más allá que luego la modifiquen desde otra). En caso que la ficha se cree con un job, supongo que también se tendría que enviar información tanto del user robot como de la organzación q genera ese robot.

2021-05-26 16:01 UTC, plammel requested changes

2021-06-01 15:52 UTC, plammel approved these changes

2021-06-01 16:18 UTC, martinebucarey approved these changes

2021-06-02 16:17 UTC, merged