VAC: poder desvincular paciente en el patch de inscripciones
andes/api pull request #1391
Opened 2021-05-17 16:17 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-69

### Funcionalidad desarrollada 
1. Permitir eliminar paciente de inscripción

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-05-17 19:06 UTC, palita1991 approved these changes

2021-05-19 14:08 UTC, plammel approved these changes

2021-05-19 16:41 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [4098](http://condorpiedra.andes.gob.ar:85/4098/mochawesome.html)
CYPRESS RUN: [3134](https://dashboard.cypress.io/projects/xr7gft/runs/3134/specs)
TEST START: 2021-05-19T16:40:40.916Z
TOTAL: 374
SUCCESS: 373
FAIL: 1
SKIPPED: 0

2021-05-21 10:44 UTC, condorpiedra requested changes

2021-05-21 10:44 UTC, condorpiedra commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +            if (req.body.desasociarPaciente) {
Si hay problemas con la propiedad que se elimina, en vez de enviar esta propiedad en el body se puede cambiar la forma en que se guarda.  Cambiando el update final por el save().  Se puede hacer previamente un set con inscripto

2021-06-08 18:15 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4293](http://condorpiedra.andes.gob.ar:85/4293/mochawesome.html)
CYPRESS RUN: [3319](https://dashboard.cypress.io/projects/xr7gft/runs/3319/specs)
TEST START: 2021-06-08T18:14:37.124Z
TOTAL: 266
SUCCESS: 242
FAIL: 24
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-06-09 11:08 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4310](http://condorpiedra.andes.gob.ar:85/4310/mochawesome.html)
CYPRESS RUN: [3336](https://dashboard.cypress.io/projects/xr7gft/runs/3336/specs)
TEST START: 2021-06-09T11:07:45.232Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-09 11:24 UTC, condorpiedra approved these changes

2021-06-09 11:25 UTC, merged