MPI: se suma lugarNacimiento a schema de paciente
andes/api pull request #1394
Opened 2021-05-19 15:45 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-349

### Funcionalidad desarrollada 
1. Se suma lugarNacimiento a Schema de paciente

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-05-19 17:15 UTC, liquid36 approved these changes

2021-05-20 16:46 UTC, plammel approved these changes

2021-06-03 19:41 UTC, negro89 approved these changes

2021-06-16 14:06 UTC, condorpiedra requested changes

2021-06-16 14:06 UTC, condorpiedra commented on shared/schemas/ubicacion.ts
> +    lugar: { type: String }
No cambiaría el esquema de ubicación sino realizaría la modificación en lugarNacimiento

2021-06-16 14:36 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4359](http://condorpiedra.andes.gob.ar:85/4359/mochawesome.html)
CYPRESS RUN: [3382](https://dashboard.cypress.io/projects/xr7gft/runs/3382/specs)
TEST START: 2021-06-16T14:27:08.476Z
TOTAL: 345
SUCCESS: 331
FAIL: 13
SKIPPED: 1

2021-06-22 19:30 UTC, MCele commented on shared/schemas/ubicacion.ts
> +    lugar: { type: String }
corregido!

2021-06-22 19:42 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4396](http://condorpiedra.andes.gob.ar:85/4396/mochawesome.html)
CYPRESS RUN: [3415](https://dashboard.cypress.io/projects/xr7gft/runs/3415/specs)
TEST START: 2021-06-22T19:42:29.322Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

2021-06-23 14:41 UTC, condorpiedra approved these changes

2021-06-23 14:44 UTC, merged