IN - Anular internación con varios movimientos
andes/api pull request #1409
Opened 2021-05-31 11:54 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-259

### Funcionalidad desarrollada 

1. Agrega identificador de movimiento al esquema de 'cama-estados'.
2. Rastrea los cambios de estado de camas como consecuencia de los movimientos del paciente y realiza un borrado lógico.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-05-31 12:12 UTC, liquid36 requested changes

2021-05-31 12:12 UTC, liquid36 commented on modules/rup/internacion/internacion.controller.ts
> +        const internacion: any = await Prestacion.findById(cama.idInternacion);
La prestación existe si es la capa de estadistica, sino esta el resumen de internación.

2021-05-31 12:12 UTC, liquid36 commented on modules/rup/internacion/internacion.controller.ts
> +        let movimientos = await CamasEstadosController.searchEstados({ desde: internacion.solicitud.fecha, hasta: cama.fecha, organizacion, capa, ambito }, { internacion: internacion.id, esMovimiento
La fecha de inicio y final de la internación no se da por la `solicitud.desde`. Dentro de los registros esta la fecha de inicio de la prestación y de fin (si existe).

2021-05-31 12:12 UTC, liquid36 commented on modules/rup/internacion/internacion.controller.ts
> +        });
En estos casos usar un map:
```suggestion
        const movimientosConsecuentes =  movimientos.map(mov => {
            if (mov.idMovimiento) {
                // Obtenemos las camas que pasan a estado 'disponible' como consecuencia de mover al paciente
                return CamasEstadosController.searchEstados({ 
                      desde: internacion.solicitud.fecha, 
                      hasta: cama.fecha, 
                      organizacion, 
                      capa, 
                      ambito 
                   }, 
                   { movimiento: mov.idMovimiento, estado: 'disponible' }
                    );
            }
        });
```

2021-05-31 12:12 UTC, liquid36 commented on modules/rup/internacion/internacion.controller.ts
> +                movimientosConsecuentes.push(CamasEstadosController.searchEstados({ desde: internacion.solicitud.fecha, hasta: cama.fecha, organizacion, capa, ambito }, { movimiento: mov.idMovimiento
Acá hay que buscar la fecha exacta del movimiento, NO hace falta buscar todo el trascurso de la internación.

2021-05-31 12:12 UTC, liquid36 commented on modules/rup/internacion/internacion.controller.ts
> +        movimientos.forEach(mov => {
Idem lo de aplicar `.map()`

2021-05-31 12:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4212](http://condorpiedra.andes.gob.ar:85/4212/mochawesome.html)
CYPRESS RUN: [3239](https://dashboard.cypress.io/projects/xr7gft/runs/3239/specs)
TEST START: 2021-05-31T12:12:19.054Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-05-31 12:14 UTC, liquid36 commented on modules/rup/internacion/cama-estados.controller.ts
> +    if (filtros.movimiento) {
Este IF, agregarlo en el primer match y vamos a ver de crear un indice. Sino se va a poner muy pesada la consultas.

2021-05-31 17:08 UTC, negro89 commented
@liquid36 todas las correcciones realizadas excepto la primera sugerencia del map ya que agregaba bastante complejidad al código para lograr el array buscado.

2021-06-01 13:05 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4225](http://condorpiedra.andes.gob.ar:85/4225/mochawesome.html)
CYPRESS RUN: [3251](https://dashboard.cypress.io/projects/xr7gft/runs/3251/specs)
TEST START: 2021-06-01T13:04:54.413Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-24 13:52 UTC, liquid36 approved these changes

2021-06-24 16:01 UTC, merged