IN - Agrega fecha de ingreso en censo diario
andes/api pull request #1415
Opened 2021-06-01 16:46 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-297

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-06-01 17:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4230](http://condorpiedra.andes.gob.ar:85/4230/mochawesome.html)
CYPRESS RUN: [3256](https://dashboard.cypress.io/projects/xr7gft/runs/3256/specs)
TEST START: 2021-06-01T17:02:32.564Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-01 17:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4233](http://condorpiedra.andes.gob.ar:85/4233/mochawesome.html)
CYPRESS RUN: [3259](https://dashboard.cypress.io/projects/xr7gft/runs/3259/specs)
TEST START: 2021-06-01T17:36:59.116Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-01 18:02 UTC, liquid36 reviewed
Faltaría tener en cuenta la impresión del censo diario.

2021-06-01 19:07 UTC, negro89 commented
> Faltaría tener en cuenta la impresión del censo diario.

Hecho.

2021-06-02 10:35 UTC, liquid36 requested changes

2021-06-02 10:35 UTC, liquid36 commented on modules/descargas/informe-censo/censo-body.ts
> +                                <th>Fecha de ingreso</th>
revisar el orden de las columnas

2021-06-02 16:57 UTC, liquid36 approved these changes

2021-06-02 16:58 UTC, merged