DESCARGAS - Recupero de costo (anexo 2)
andes/api pull request #1417
Opened 2021-06-02 12:10 UTC by rodrigokokot

### Requerimiento

Problemas en la visualización de la información y diseño del pdf a descargar

### UserStories llegó a completarse

- [ ] Si
- [X] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-06-02 18:12 UTC, plammel requested changes

2021-06-02 18:12 UTC, plammel commented on modules/descargas/recupero-costo/recupero-costo-body.ts
> +            edad: `${moment().diff(_data.turno.paciente.fechaNacimiento, 'years')} años`,
calcular la edad utilizando la función `calcularEdad` en el schema de paciente
https://github.com/andes/api/blob/613ea8624df802bd42e6f082c9946276a196be4b/core-v2/mpi/paciente/paciente.schema.ts#L171

2021-06-03 14:15 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4246](http://condorpiedra.andes.gob.ar:85/4246/mochawesome.html)
CYPRESS RUN: [3272](https://dashboard.cypress.io/projects/xr7gft/runs/3272/specs)
TEST START: 2021-06-03T14:15:36.426Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-03 19:34 UTC, condorpiedra requested changes

2021-06-03 19:34 UTC, condorpiedra commented on modules/descargas/recupero-costo/recupero-costo-body.ts
> +            nombre: _data.turno.paciente.nombre,
Faltaría el apellido del paciente
nombre: `${ _data.turno.paciente.apellido }, ${ _data.turno.paciente.nombre }`,

2021-06-03 19:35 UTC, condorpiedra commented
Otro detalle lo probé y queda en dos hojas por ahí se podría sacar el hr y acomodar un poco para que no quede separado.

2021-06-04 17:48 UTC, condorpiedra approved these changes

2021-06-04 17:48 UTC, merged