PDP - Registro de cuentas
andes/api pull request #1424
Opened 2021-06-08 15:57 UTC by palita1991

### Requerimiento

https://proyectos.andes.gob.ar/browse/PDP-43

### Funcionalidad desarrollada 

1. Se cambia el retorno de los mensajes de la api ya que no se podian mostrar correctamente en la app
2. 
3. 

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-06-09 14:46 UTC, plammel approved these changes

2021-06-10 19:19 UTC, negro89 approved these changes

2021-06-24 15:11 UTC, andrrrl approved these changes

2021-06-29 16:28 UTC, kroce requested changes
@palita1991 con estos cambios en la api no se muestran correctamente las notificaciones en la app mobile. Sugiero realizar los cambios en la app del portal para que tome los mensajes.

2021-07-01 16:34 UTC, palita1991 commented
Se cierra ya que al poner return como antes no hay cambios nuevos para subir

2021-07-01 16:45 UTC, palita1991 commented
Se cierra ya que se dejo los return como estan en master

2021-07-01 16:45 UTC, closed without merging