Mapa-camas - Días de estada en el listado
andes/api pull request #1425
Opened 2021-06-09 18:45 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-287

### Funcionalidad desarrollada 

1. Agrega fecha de ingreso al esquema de cama-estado
2. Elimina fecha de ingreso del paciente en cama que se desocupa por movimiento

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-06-09 19:01 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4315](http://condorpiedra.andes.gob.ar:85/4315/mochawesome.html)
CYPRESS RUN: [3341](https://dashboard.cypress.io/projects/xr7gft/runs/3341/specs)
TEST START: 2021-06-09T19:01:22.805Z
TOTAL: 395
SUCCESS: 394
FAIL: 1
SKIPPED: 0

2021-06-10 12:57 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4318](http://condorpiedra.andes.gob.ar:85/4318/mochawesome.html)
CYPRESS RUN: [3344](https://dashboard.cypress.io/projects/xr7gft/runs/3344/specs)
TEST START: 2021-06-10T12:57:10.175Z
TOTAL: 395
SUCCESS: 395
FAIL: 0
SKIPPED: 0

2021-06-11 11:22 UTC, liquid36 commented on modules/rup/internacion/camas.controller.ts
> +    let estadoCama = await findById({ organizacion: data.organizacion, capa: data.capa, ambito: data.ambito }, data.id, data.fecha);
¿Pinto cambiarlo a let?

2021-06-11 11:43 UTC, negro89 commented on modules/rup/internacion/camas.controller.ts
> +    let estadoCama = await findById({ organizacion: data.organizacion, capa: data.capa, ambito: data.ambito }, data.id, data.fecha);
no no jajaj ..hice un cambio pero no perduró. Vuelve a const.

2021-06-14 15:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4339](http://condorpiedra.andes.gob.ar:85/4339/mochawesome.html)
CYPRESS RUN: [3362](https://dashboard.cypress.io/projects/xr7gft/runs/3362/specs)
TEST START: 2021-06-14T15:12:01.782Z
TOTAL: 396
SUCCESS: 395
FAIL: 0
SKIPPED: 1

2021-06-14 17:32 UTC, liquid36 requested changes
Negativo, el uso de `op` en un patch esta deprecado. Todo el update se tiene que hacer en la ruta changeTime.
Podes actualizar todos los estados con un solo update, haciendo el arrayFilter según el idInternación. Ese es el dato que agrupa todos los movimientos a actualizar

2021-06-29 10:37 UTC, liquid36 approved these changes

2021-07-02 13:14 UTC, merged