rup: concepts requeridos dinamicos
andes/api pull request #1427
Opened 2021-06-11 16:57 UTC by liquid36

### Requerimiento

https://proyectos.andes.gob.ar/browse/RUP-255

### Funcionalidad desarrollada  
1. 
2. 
3. 

### UserStories llegó a completarse 
- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos 
- [ ] Si
- [ ] No

2021-06-14 11:30 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4338](http://condorpiedra.andes.gob.ar:85/4338/mochawesome.html)
CYPRESS RUN: [3361](https://dashboard.cypress.io/projects/xr7gft/runs/3361/specs)
TEST START: 2021-06-14T11:29:50.899Z
TOTAL: 396
SUCCESS: 395
FAIL: 0
SKIPPED: 1

2021-06-14 16:41 UTC, condorpiedra requested changes

2021-06-14 16:41 UTC, condorpiedra commented on modules/rup/elementos-rup.controller.ts
> +            key => engine.addFact(key, contexto[key])
Para el caso en que contexto[key] quede undefined, habría que realizar un control o bien realizar un removeFact.  Ejemplo: caso en que el paciente no registra prestaciones con la expresión configurada.

2021-06-14 17:11 UTC, liquid36 commented on modules/rup/elementos-rup.controller.ts
> +            key => engine.addFact(key, contexto[key])
Proba ahora, justo estaba con los test y modifique algunas cosas.

2021-06-14 17:20 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4341](http://condorpiedra.andes.gob.ar:85/4341/mochawesome.html)
CYPRESS RUN: [3364](https://dashboard.cypress.io/projects/xr7gft/runs/3364/specs)
TEST START: 2021-06-14T17:20:29.242Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

2021-06-15 12:41 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4347](http://condorpiedra.andes.gob.ar:85/4347/mochawesome.html)
CYPRESS RUN: [3370](https://dashboard.cypress.io/projects/xr7gft/runs/3370/specs)
TEST START: 2021-06-15T12:41:23.147Z
TOTAL: 399
SUCCESS: 391
FAIL: 7
SKIPPED: 1

2021-06-15 12:51 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4348](http://condorpiedra.andes.gob.ar:85/4348/mochawesome.html)
CYPRESS RUN: [3371](https://dashboard.cypress.io/projects/xr7gft/runs/3371/specs)
TEST START: 2021-06-15T12:50:59.357Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

2021-06-17 15:50 UTC, condorpiedra approved these changes

2021-06-17 20:13 UTC, MCele approved these changes

2021-06-18 12:08 UTC, merged