Mapa-camas: Actualiza unidad organizativa original al editar una cama
andes/api pull request #1430
Opened 2021-06-15 13:23 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-300

### Funcionalidad desarrollada 

1. Actualiza unidad organizativa original de la CAMA al editarla (Anteriormente solo editaba el estado de la cama).

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-06-15 13:38 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4350](http://condorpiedra.andes.gob.ar:85/4350/mochawesome.html)
CYPRESS RUN: [3373](https://dashboard.cypress.io/projects/xr7gft/runs/3373/specs)
TEST START: 2021-06-15T13:37:52.024Z
TOTAL: 388
SUCCESS: 386
FAIL: 1
SKIPPED: 1

2021-06-15 13:48 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4351](http://condorpiedra.andes.gob.ar:85/4351/mochawesome.html)
CYPRESS RUN: [3374](https://dashboard.cypress.io/projects/xr7gft/runs/3374/specs)
TEST START: 2021-06-15T13:47:43.710Z
TOTAL: 378
SUCCESS: 376
FAIL: 1
SKIPPED: 1

2021-06-15 19:04 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4354](http://condorpiedra.andes.gob.ar:85/4354/mochawesome.html)
CYPRESS RUN: [3377](https://dashboard.cypress.io/projects/xr7gft/runs/3377/specs)
TEST START: 2021-06-15T19:04:35.816Z
TOTAL: 396
SUCCESS: 395
FAIL: 0
SKIPPED: 1

2021-06-16 10:49 UTC, liquid36 requested changes
No anda como correspónde, si uso la funcionalidad de prestar cama también se editar la unidad organizativa original. 

Lo que tenes que hacer es desde la app en la pantall de editar cama asignar vos la variable `unidadOrganizativaOriginal`. Luego cuando viene a la API la línea `camaEncontrada.set(data);` hace automáticamente su trabajo. 

A primera vista no debería haber cambios de API, solo APP.

2021-06-16 12:56 UTC, negro89 commented
Se resuelve en app https://github.com/andes/app/pull/2327

2021-06-16 12:56 UTC, closed without merging