Vacunación -  Registrar fecha de próximo llamado
andes/api pull request #1448
Opened 2021-06-24 19:54 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-86

### Funcionalidad desarrollada 

1. Nuevo parámtro de búsqueda 'fechaProximoLlamado'
2. Al asignar una fecha se elimina el atributo 'asignado' para que la inscripción pueda ser cargada mas adelante
3. Agrega filtro para que las inscripciones con fecha de próximo llamado solo puedan volver a cargarse a partir de dicha fecha

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-06-24 20:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4418](http://condorpiedra.andes.gob.ar:85/4418/mochawesome.html)
CYPRESS RUN: [3435](https://dashboard.cypress.io/projects/xr7gft/runs/3435/specs)
TEST START: 2021-06-24T20:07:56.877Z
TOTAL: 346
SUCCESS: 331
FAIL: 14
SKIPPED: 1

2021-06-25 00:07 UTC, sychus requested changes
Algunos detalles

2021-06-25 00:07 UTC, sychus commented on modules/vacunas/inscripcion-vacunas.routes.ts
>              if (inscripto.paciente === null) {
```suggestion
            if (!inscripto.paciente) {
```

2021-06-25 00:07 UTC, sychus commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +            if (inscripto.fechaProximoLlamado !== null) {
```suggestion
            if (inscripto.fechaProximoLlamado) {
```

2021-06-25 00:07 UTC, sychus commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +import moment = require('moment');
¿donde usas moment?

2021-06-25 11:55 UTC, negro89 commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +            // Retorna true si no existe la propiedad o la fecha ingresada (value) es mayor
Si, es un poco confuso pero la fecha ingresada (llamando a la función) por lo general debería ser la del día. Esta fecha debería ser mayor la del próximo llamado del inscripto. Es un poco mas sencillo explicarlo asi pero es cierto que la búsqueda está expresada en sentido contrario.

2021-06-25 15:42 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4423](http://condorpiedra.andes.gob.ar:85/4423/mochawesome.html)
CYPRESS RUN: [3440](https://dashboard.cypress.io/projects/xr7gft/runs/3440/specs)
TEST START: 2021-06-25T15:42:13.569Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-06-25 15:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4424](http://condorpiedra.andes.gob.ar:85/4424/mochawesome.html)
CYPRESS RUN: [3441](https://dashboard.cypress.io/projects/xr7gft/runs/3441/specs)
TEST START: 2021-06-25T15:53:06.729Z
TOTAL: 398
SUCCESS: 395
FAIL: 2
SKIPPED: 1

2021-06-25 16:27 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4426](http://condorpiedra.andes.gob.ar:85/4426/mochawesome.html)
CYPRESS RUN: [3443](https://dashboard.cypress.io/projects/xr7gft/runs/3443/specs)
TEST START: 2021-06-25T16:27:08.688Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-06-25 17:12 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4428](http://condorpiedra.andes.gob.ar:85/4428/mochawesome.html)
CYPRESS RUN: [3445](https://dashboard.cypress.io/projects/xr7gft/runs/3445/specs)
TEST START: 2021-06-25T17:12:04.575Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-06-25 18:05 UTC, plammel commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                inscripcion.asignado = undefined;
No se que onda limpiar atributos usando undefined... tal vez sea más apropiado blanquear usando null o delete del atributo. Probablemente sea solo una cuestión de preferencias personales, pero no está de más indagar al respecto.

2021-06-25 18:18 UTC, liquid36 commented
¿ que es fechaProximoLlamado?

2021-06-25 18:20 UTC, liquid36 commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                inscripcion.asignado = undefined;
Depdene, con undefined no va a quedar en la base datos y te lo toma el { $exists : false }. 
Con null queda en la base de datos como nulo, así que el { $exists : false } no valida. 

El `delete` puede ser un poco más vistoso

2021-06-28 11:57 UTC, negro89 commented on modules/vacunas/inscripcion-vacunas.routes.ts
> +                inscripcion.asignado = undefined;
Agrego que en este caso el delete no ayuda, ya que el recurso asume que es un atributo que no se modifica

2021-06-28 12:03 UTC, negro89 commented on modules/vacunas/schemas/inscripcion-vacunas.schema.ts
> +    fechaProximoLlamado: Date,
Me salvaste las papas, no se si fue error de distracción o tipeo pero había quedado mal.

2021-06-28 12:25 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4438](http://condorpiedra.andes.gob.ar:85/4438/mochawesome.html)
CYPRESS RUN: [3455](https://dashboard.cypress.io/projects/xr7gft/runs/3455/specs)
TEST START: 2021-06-28T12:24:47.653Z
TOTAL: 398
SUCCESS: 395
FAIL: 2
SKIPPED: 1

2021-06-28 13:08 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4439](http://condorpiedra.andes.gob.ar:85/4439/mochawesome.html)
CYPRESS RUN: [3456](https://dashboard.cypress.io/projects/xr7gft/runs/3456/specs)
TEST START: 2021-06-28T13:08:26.406Z
TOTAL: 398
SUCCESS: 397
FAIL: 0
SKIPPED: 1

2021-07-26 17:43 UTC, kroce approved these changes

2021-07-26 18:26 UTC, palita1991 approved these changes

2021-07-26 18:28 UTC, merged