Vac 80: Job para actualizar la collection cache para los indicadores de vacunación covid19
andes/api pull request #1452
Opened 2021-06-28 18:43 UTC by sychus

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-06-30 16:01 UTC, martinebucarey approved these changes

2021-06-30 17:21 UTC, liquid36 requested changes

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +        const resultados = await toArray(resultado);
toArray no sirve más, en este caso usaría el cursor.

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +            { $sort: { zona: 1 } }
es necesario un sor?

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +                $project: {
mucha sanguchito de fields, uno por linea ayuda a leer

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +                            { $cond: [{ $and: [{ $gte: ['$edad', 0] }, { $lte: ['$edad', 4] }] }, '0 a 4 Años', ''] },
confio ciegamente en lo que se hace acá jaja

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +                $addFields: {
acá a un $unwind, mongo lo optimiza. 
https://docs.mongodb.com/manual/core/aggregation-pipeline-optimization/#-lookup----unwind-coalescence

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +                $addFields: {
Acá va un $unwind, mongo lo optimiza

https://docs.mongodb.com/manual/core/aggregation-pipeline-optimization/#-lookup----unwind-coalescence

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +        for (const res of resultados) {
Si tuviesemo mongo 4.2 o 4.4 podríamos usar le operador $merge

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +                                $subtract: [new Date(),
Todos los días la gente va a cumplir años, deberías comparar contra la fecha de ejecución de la prestación. Sino es probable que los numneros cambien cada cumpleaños

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +                $match: { 'ejecucion.registros.valor.vacuna.dosis.nombre': { $regex: /1ra/ } }  // Pidieron que por ahora sea primera dosis
No hay una forma mas elegante de saber si es primera dosis?

2021-06-30 17:21 UTC, liquid36 commented on scripts/vacunacionRangoEtario.ts
> +        return err;
Ojo que si hay un error, nunca se ejecuta el done y el  job nunca va a terminar

2021-06-30 17:23 UTC, sychus commented on scripts/vacunacionRangoEtario.ts
> +                $match: { 'ejecucion.registros.valor.vacuna.dosis.nombre': { $regex: /1ra/ } }  // Pidieron que por ahora sea primera dosis
lamentablemente no

2021-06-30 18:26 UTC, sychus commented on scripts/vacunacionRangoEtario.ts
> +                                $subtract: [new Date(),
si posta...

2021-06-30 19:32 UTC, sychus commented on scripts/vacunacionRangoEtario.ts
> +                                $subtract: [new Date(),
solved

2021-06-30 19:32 UTC, sychus commented on scripts/vacunacionRangoEtario.ts
> +            { $sort: { zona: 1 } }
para nada

2021-06-30 19:33 UTC, sychus commented on scripts/vacunacionRangoEtario.ts
> +        for (const res of resultados) {
entre otras cosas...  :-(

2021-06-30 19:33 UTC, sychus commented on scripts/vacunacionRangoEtario.ts
> +        const resultados = await toArray(resultado);
solved

2021-07-01 15:00 UTC, plammel approved these changes

2021-07-02 14:48 UTC, liquid36 commented
USUARIO: hfernandez  
BUILD NUMBER: [4479](http://condorpiedra.andes.gob.ar:85/4479/mochawesome.html)
CYPRESS RUN: [3498](https://dashboard.cypress.io/projects/xr7gft/runs/3498/specs)
TEST START: 2021-07-02T14:48:31.942Z
TOTAL: 398
SUCCESS: 396
FAIL: 1
SKIPPED: 1

2021-07-26 18:41 UTC, plammel commented
👀 @martinebucarey este PR se está quedando huérfano y viejo. Habría que remontarlo.

2021-07-26 18:43 UTC, martinebucarey commented
> eyes @martinebucarey este PR se está quedando huérfano y viejo. Habría que remontarlo.

Si, el viernes estuvimos hablando con naty y chichi por este tema, va a haber un cambio grande con como se guardan las vacunas, creo que ya esta por salir o salio que hicieron Marian y Naty. Naty iba a chusmear el script para ver como usar esto nuevo que se hizo.

2021-07-26 19:17 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4714](http://condorpiedra.andes.gob.ar:85/4714/mochawesome.html)
CYPRESS RUN: [3713](https://dashboard.cypress.io/projects/xr7gft/runs/3713/specs)
TEST START: 2021-07-26T19:17:05.040Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-29 18:06 UTC, condorpiedra commented
Para las consultas de vacunas se comienza a utilizar pacientes-vacunas

2021-07-29 18:06 UTC, closed without merging