Profesional - Nuevo subesquema con datos basicos
andes/api pull request #1467
Opened 2021-07-12 15:12 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/CORE-84

### Funcionalidad desarrollada 

1. Crea subschema con datos básicos, sin índices

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-07-12 15:26 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4546](http://condorpiedra.andes.gob.ar:85/4546/mochawesome.html)
CYPRESS RUN: [3564](https://dashboard.cypress.io/projects/xr7gft/runs/3564/specs)
TEST START: 2021-07-12T15:26:15.680Z
TOTAL: 403
SUCCESS: 402
FAIL: 0
SKIPPED: 1

2021-07-13 16:44 UTC, liquid36 requested changes
Esta bien aplicado pero quedan unos detalles.

2021-07-13 16:44 UTC, liquid36 commented on core/tm/schemas/profesional.ts
> +    foto: { type: String, required: false },
Sacaría estos campos del básico.

2021-07-13 16:44 UTC, liquid36 commented on core/tm/schemas/profesional.ts
> +    apellido: { type: String, required: false },
Estos campos deberían ser requeridos.

2021-07-13 16:45 UTC, liquid36 commented on core/tm/schemas/profesional.ts
> +    apellido: { type: String, required: false },
El sexo en principio no, porque no lo tenemos en el Auth como datos básico del profesional.

2021-07-13 17:34 UTC, negro89 commented on core/tm/schemas/profesional.ts
> +    apellido: { type: String, required: false },
Corregido.

2021-07-19 14:59 UTC, liquid36 approved these changes

2021-07-19 17:42 UTC, merged