(MONIT-41): buscar usuario por email
andes/api pull request #1476
Opened 2021-07-19 14:47 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MONIT-41

### Funcionalidad desarrollada 
1. Se modifico que la busqueda no sea solamente por documento sino tambien por email. 

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-07-19 19:12 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4605](http://condorpiedra.andes.gob.ar:85/4605/mochawesome.html)
CYPRESS RUN: [3615](https://dashboard.cypress.io/projects/xr7gft/runs/3615/specs)
TEST START: 2021-07-19T19:12:43.164Z
TOTAL: 399
SUCCESS: 396
FAIL: 2
SKIPPED: 1

2021-07-20 11:11 UTC, liquid36 approved these changes

2021-07-20 11:26 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4608](http://condorpiedra.andes.gob.ar:85/4608/mochawesome.html)
CYPRESS RUN: [3618](https://dashboard.cypress.io/projects/xr7gft/runs/3618/specs)
TEST START: 2021-07-20T11:19:24.197Z
TOTAL: 334
SUCCESS: 318
FAIL: 15
SKIPPED: 1

2021-07-20 11:37 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [4609](http://condorpiedra.andes.gob.ar:85/4609/mochawesome.html)
CYPRESS RUN: [3619](https://dashboard.cypress.io/projects/xr7gft/runs/3619/specs)
TEST START: 2021-07-20T11:36:48.076Z
TOTAL: 399
SUCCESS: 398
FAIL: 0
SKIPPED: 1

2021-07-22 11:29 UTC, liquid36 requested changes
Estoy viendo el PR de Monitoreo. Acá estas agregando un parámetro de búsqueda al search. 
El search es un campo que internamente hace un OR, en este caso busca por documento o por email. 

Pero en monitorio en vez de usar el campo `search` estas pasando documento o email según corresponda. 

Lo ideal sería desde monitoreo usar el campo **search** y de yapa te ahorras esos if desde monitoreo.

2021-07-22 15:16 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4664](http://condorpiedra.andes.gob.ar:85/4664/mochawesome.html)
CYPRESS RUN: [3667](https://dashboard.cypress.io/projects/xr7gft/runs/3667/specs)
TEST START: 2021-07-22T15:16:22.355Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-07-22 15:29 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4665](http://condorpiedra.andes.gob.ar:85/4665/mochawesome.html)
CYPRESS RUN: [3668](https://dashboard.cypress.io/projects/xr7gft/runs/3668/specs)
TEST START: 2021-07-22T15:29:45.395Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-22 17:20 UTC, liquid36 requested changes

2021-07-22 17:20 UTC, liquid36 commented on modules/mobileApp/schemas/pacienteApp.ts
> +    documento: 1
Esta bien agregar el indice por documento pero no tiene que ser compuesto.
```suggestion

 PacienteAppSchema.index({
     email: 1
 });
 
 PacienteAppSchema.index({
     documento: 1
 });
```

Son dos indices distintos.

2021-07-22 17:22 UTC, liquid36 commented on modules/mobileApp/schemas/pacienteApp.ts
> +    documento: 1
Un indice copmpuesto tiene setido si la operación es un ADN 
```
PacienteApp.find({ documento, email });
```

En este caso se busca con un `$or`, mongo en este caso puede utilizar dos indices distintos y después une el resultado.

2021-07-22 18:23 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4674](http://condorpiedra.andes.gob.ar:85/4674/mochawesome.html)
CYPRESS RUN: [3677](https://dashboard.cypress.io/projects/xr7gft/runs/3677/specs)
TEST START: 2021-07-22T18:16:23.031Z
TOTAL: 356
SUCCESS: 339
FAIL: 16
SKIPPED: 1

2021-07-22 18:58 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4677](http://condorpiedra.andes.gob.ar:85/4677/mochawesome.html)
CYPRESS RUN: [3680](https://dashboard.cypress.io/projects/xr7gft/runs/3680/specs)
TEST START: 2021-07-22T18:58:20.105Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-23 11:27 UTC, liquid36 approved these changes

2021-07-23 18:43 UTC, condorpiedra approved these changes

2021-07-23 18:43 UTC, merged