VAC - Script para migración de vacunas
andes/api pull request #1483
Opened 2021-07-22 15:27 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-94

### Funcionalidad desarrollada 

1. Script para migrar prestaciones de campaña de vacunación de covid-19 a colección paciente-vacunas

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-07-22 15:50 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4666](http://condorpiedra.andes.gob.ar:85/4666/mochawesome.html)
CYPRESS RUN: [3669](https://dashboard.cypress.io/projects/xr7gft/runs/3669/specs)
TEST START: 2021-07-22T15:50:24.801Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-22 17:11 UTC, condorpiedra requested changes

2021-07-22 17:11 UTC, condorpiedra commented on scripts/VAC-94.ts
> +                await Prestacion.findOneAndRemove({ 'paciente.id': idPaciente });
No hay que eliminar la prestación

2021-07-27 12:43 UTC, negro89 commented on scripts/VAC-94.ts
> +                await Prestacion.findOneAndRemove({ 'paciente.id': idPaciente });
Corregido.

2021-07-28 15:08 UTC, condorpiedra approved these changes

2021-07-28 15:28 UTC, plammel approved these changes

2021-07-28 15:46 UTC, merged