feat(vacunas): ajuste de proceso covid
andes/api pull request #1487
Opened 2021-07-23 12:01 UTC by liquid36

### Requerimiento
Controla argumentos en función exportCovid19 y vuelve a enlazar 
 
### UserStories llegó a completarse 
- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos 
- [ ] Si
- [ ] No

2021-07-23 15:50 UTC, condorpiedra approved these changes

2021-07-26 12:36 UTC, kroce approved these changes

2021-07-27 11:11 UTC, condorpiedra requested changes

2021-07-27 11:11 UTC, condorpiedra commented on jobs/jobExportVacunaCovid19.ts
>  function run(done) {
el argumento done no se usa? Se podría eliminar entonces

2021-07-27 11:27 UTC, liquid36 commented on jobs/jobExportVacunaCovid19.ts
>  function run(done) {
Ahora si se usa, gracias!

2021-07-27 14:35 UTC, condorpiedra approved these changes

2021-07-27 15:45 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4729](http://condorpiedra.andes.gob.ar:85/4729/mochawesome.html)
CYPRESS RUN: [3726](https://dashboard.cypress.io/projects/xr7gft/runs/3726/specs)
TEST START: 2021-07-27T15:45:08.204Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-27 16:15 UTC, merged