Vac - Refactor de datos para colección nomivac
andes/api pull request #1497
Opened 2021-07-30 16:30 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-90

### Funcionalidad desarrollada 

1. Agrega propiedades al esquema 'vacunas' y elimina duplicado 'vacunasApi'

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-08-02 18:10 UTC, liquid36 reviewed
Sugiero dejar el esquema dentro del modulo Vacunas y borrarlo de mobile. 
La descripción de JIRA no tiene relación con lo que se hace en el PR.

2021-08-03 11:56 UTC, negro89 commented
> Sugiero dejar el esquema dentro del modulo Vacunas y borrarlo de mobile.
> La descripción de JIRA no tiene relación con lo que se hace en el PR.

@liquid36 Movido el esquema de vacunas como sugeriste.
Lo que describe jira ya está hecho y esta bien, el problema es que faltaba esta modificación en el esquema para que funcione.

2021-08-03 13:02 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4777](http://condorpiedra.andes.gob.ar:85/4777/mochawesome.html)
CYPRESS RUN: [3773](https://dashboard.cypress.io/projects/xr7gft/runs/3773/specs)
TEST START: 2021-08-03T13:02:16.704Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-08-06 14:33 UTC, liquid36 requested changes

2021-08-06 14:33 UTC, liquid36 commented on modules/vacunas/schemas/vacunas.ts
> +    efector: {
¿El efector porque cambia de tipo? En la base de datos es un string.

2021-08-11 17:09 UTC, condorpiedra commented on modules/vacunas/schemas/vacunas.ts
> +    efector: {
Se vuelve a String

2021-08-11 17:15 UTC, condorpiedra approved these changes

2021-08-11 17:18 UTC, liquid36 approved these changes

2021-08-11 17:26 UTC, liquid36 commented
USUARIO: nhuenchuman  
BUILD NUMBER: [4855](http://condorpiedra.andes.gob.ar:85/4855/mochawesome.html)
CYPRESS RUN: [3848](https://dashboard.cypress.io/projects/xr7gft/runs/3848/specs)
TEST START: 2021-08-11T17:25:42.795Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-11 18:17 UTC, merged