MAT - Filtro por profesión
andes/api pull request #1503
Opened 2021-08-04 11:18 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-60

### Funcionalidad desarrollada 

1. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-08-04 11:24 UTC, liquid36 reviewed
No debería ser un select y filtrar por ID o código de profesión?

2021-08-04 11:35 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4795](http://condorpiedra.andes.gob.ar:85/4795/mochawesome.html)
CYPRESS RUN: [3790](https://dashboard.cypress.io/projects/xr7gft/runs/3790/specs)
TEST START: 2021-08-04T11:34:46.610Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-19 17:59 UTC, MCele approved these changes

2021-08-24 16:44 UTC, palita1991 approved these changes

2021-09-01 14:03 UTC, liquid36 approved these changes

2021-09-01 17:23 UTC, condorpiedra requested changes

2021-09-01 17:23 UTC, condorpiedra commented on core/tm/routes/profesional.ts
> +                { 'formacionPosrado.profesion.codigo': profesionSearch }
'formacionPosgrado.profesion.codigo' sería

2021-09-01 17:26 UTC, condorpiedra commented on core/tm/routes/profesional.ts
> +                { 'formacionPosrado.profesion.codigo': profesionSearch }
También sería bueno agregar un índice por estos campos

2021-09-08 16:09 UTC, condorpiedra approved these changes

2021-09-08 17:09 UTC, merged