SCRIPT: Actualizar turnos con Sumar
andes/api pull request #1507
Opened 2021-08-06 13:13 UTC by martinebucarey

### Requerimiento
En la ultima actualización de SUMAR hubo un problema con el script y no se renombro la colección, quedo con el nombre sumarOld. Entre el rango de fechas (15/07 -  04/8) los pacientes que están en SUMAR aparecían sin obra social por lo que no se podían enviar a faccionario.

### Funcionalidad desarrollada 

1. Se agrega Script que actualiza los registros en la coleccion agenda agregandole a los pacientes SUMAR la obra social.

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2021-08-06 13:47 UTC, liquid36 commented on scripts/add-sumar-turnos.ts
> +            for await (const turno of bloque.turnos) {
```suggestion
        for (const bloque of agenda.bloques) {
            for (const turno of bloque.turnos) {
```

Estan de más esos `await`, copy/paste detected!

2021-08-06 13:50 UTC, liquid36 commented on scripts/add-sumar-turnos.ts
> +                            $and: [
el ``$and esta de más

2021-08-06 13:54 UTC, martinebucarey commented on scripts/add-sumar-turnos.ts
> +            for await (const turno of bloque.turnos) {
Me declaro culpable. Eliminados

2021-08-06 13:54 UTC, martinebucarey commented on scripts/add-sumar-turnos.ts
> +                            $and: [
Yes, eliminado.

2021-08-06 13:56 UTC, liquid36 commented on scripts/add-sumar-turnos.ts
> +                        const pacienteSumar = await sumar.find({ activo: 'S ' }, { afidni: turno.paciente.documento });
```suggestion
                        const pacienteSumar = await sumar.find({ activo: 'S ', afidni: turno.paciente.documento });
```

2021-08-06 14:17 UTC, martinebucarey commented on scripts/add-sumar-turnos.ts
> +                        const pacienteSumar = await sumar.find({ activo: 'S ' }, { afidni: turno.paciente.documento });
> 

Actualizado

2021-08-09 12:08 UTC, liquid36 commented on scripts/add-sumar-turnos.ts
> +        ]
Un detalle menor, pero es $and es equivalente a: 
```suggestion 
           horaInicio: { 
               $gte: new Date('2021-07-15T00:00:00.000-03:00'), 
               $lte: new Date('2021-08-04T00:00:00.000-03:00')  
          }
```

2021-08-11 11:55 UTC, liquid36 requested changes
Me acorde de algo más, los sobreturnos!

2021-08-11 11:56 UTC, martinebucarey commented
> Me acorde de algo más, los sobreturnos!

uff pequeño detalle, manos a la obra.

2021-08-11 12:02 UTC, liquid36 commented
> > Me acorde de algo más, los sobreturnos!
> 
> uff pequeño detalle, manos a la obra.

Dale Picasso!

2021-08-11 12:33 UTC, martinebucarey commented
> > > Me acorde de algo más, los sobreturnos!
> > 
> > 
> > uff pequeño detalle, manos a la obra.
> 
> Dale Picasso!

Agregado

2021-08-11 12:42 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [4851](http://condorpiedra.andes.gob.ar:85/4851/mochawesome.html)
CYPRESS RUN: [3844](https://dashboard.cypress.io/projects/xr7gft/runs/3844/specs)
TEST START: 2021-08-11T12:42:27.323Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-19 17:32 UTC, plammel approved these changes

2021-08-20 17:32 UTC, liquid36 approved these changes

2021-08-20 17:33 UTC, merged