EP: Mostrar historial de update automatico
andes/api pull request #1509
Opened 2021-08-06 18:48 UTC by plammel

### Requerimiento

Mostrar usuario "Actualizacion automática", cuando el historial es generado por un proceso automatico
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-08-06 19:07 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4828](http://condorpiedra.andes.gob.ar:85/4828/mochawesome.html)
CYPRESS RUN: [3821](https://dashboard.cypress.io/projects/xr7gft/runs/3821/specs)
TEST START: 2021-08-06T19:07:16.728Z
TOTAL: 382
SUCCESS: 378
FAIL: 3
SKIPPED: 1

2021-08-09 11:13 UTC, liquid36 requested changes
De donde sale el proceso automático? Para mantener estandar los tipeos, ese proceso debería rellenar el campo createdBy con su "nombre". Sino introducimos un aluvión de if y en el futuro hay que ir acordandose

2021-08-09 12:22 UTC, plammel commented
> De donde sale el proceso automático? Para mantener estandar los tipeos, ese proceso debería rellenar el campo createdBy con su "nombre". Sino introducimos un aluvión de if y en el futuro hay que ir acordandose

Los procesos rellenan el createdBy, pero los tokens de aplicación solo contienen nombre, pero no username, y estos nombres suelen ser una referencia al proceso o m.servicio, y son poco poco descriptivos para el usuario. 
Por este motivo, la decisión fue que si el usuario no posee username, se entiende que se trata de un token de aplicación y se muestra la leyenda genérica "proceso automático"

2021-08-31 12:12 UTC, martinebucarey approved these changes

2021-08-31 17:22 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4957](http://condorpiedra.andes.gob.ar:85/4957/mochawesome.html)
CYPRESS RUN: [3929](https://dashboard.cypress.io/projects/xr7gft/runs/3929/specs)
TEST START: 2021-08-31T17:21:49.129Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-07 12:18 UTC, martinebucarey commented
Se cierra porque se va a resolver de otra forma

2021-09-07 12:18 UTC, closed without merging