EP: organización x defecto seguimiento
andes/api pull request #1515
Opened 2021-08-19 14:50 UTC by plammel

### Requerimiento

Reemplazar las coordenadas por defecto, por organización por defecto, de manera que se puedan asignar por defecto al CAM.
https://proyectos.andes.gob.ar/browse/EP-118
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si Agregar a registro de organización de "SUBSECRETARIA DE SALUD" atributo: `asignaSeguimientoPaciente: true`
- [ ] No

2021-08-19 15:13 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4898](http://condorpiedra.andes.gob.ar:85/4898/mochawesome.html)
CYPRESS RUN: [3879](https://dashboard.cypress.io/projects/xr7gft/runs/3879/specs)
TEST START: 2021-08-19T15:13:43.348Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-08-24 17:26 UTC, martinebucarey commented on modules/seguimiento-paciente/seguimiento-pacientes.events.ts
> +            const patientGeoRef = (data.paciente.direccion && data.paciente.direccion[0].geoReferencia?.length) ? data.paciente.direccion[0].geoReferencia.reverse() : null;
`            const patientGeoRef = (data.paciente.direccion[0]?.geoReferencia?.length) ? data.paciente.direccion[0].geoReferencia.reverse() : null;
`

2021-08-24 17:27 UTC, martinebucarey requested changes

2021-08-24 17:27 UTC, martinebucarey commented on modules/seguimiento-paciente/seguimiento-pacientes.events.ts
> +                const organizacionDefecto = (await Organizacion.find({ asignaSeguimientoPaciente: true }))[0];
si no vamos a usar mas el default del config y lo vamos a setear en la base por ahi usar un findOne en vez de tomar el primer elemento de un find??

2021-08-24 17:28 UTC, martinebucarey commented
El funcionamiento va joya, solo esos pequeños comentarios

2021-08-25 11:30 UTC, liquid36 commented on modules/seguimiento-paciente/seguimiento-pacientes.events.ts
> +                const organizacionDefecto = await Organizacion.findOne({ asignaSeguimientoPaciente: true });
Que es ese flag?

2021-08-25 12:33 UTC, plammel commented on modules/seguimiento-paciente/seguimiento-pacientes.events.ts
> +                const organizacionDefecto = await Organizacion.findOne({ asignaSeguimientoPaciente: true });
`coordinates`? No es un flag, es un array con coordenadas que usamos para identificar un área programa. Estás coordenadas deberian ser las del paciente, si no posee entonces las coordenadas del efector que originó la ficha. En caso de no ubicar ningún area asignamos una organización por defecto.

2021-08-25 14:37 UTC, liquid36 commented on modules/seguimiento-paciente/seguimiento-pacientes.events.ts
> +                const organizacionDefecto = await Organizacion.findOne({ asignaSeguimientoPaciente: true });
`asignaSeguimientoPaciente` ese flag

2021-09-13 18:08 UTC, martinebucarey approved these changes

2021-09-14 13:57 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5067](http://condorpiedra.andes.gob.ar:85/5067/mochawesome.html)
CYPRESS RUN: [4031](https://dashboard.cypress.io/projects/xr7gft/runs/4031/specs)
TEST START: 2021-09-14T13:48:18.533Z
TOTAL: 400
SUCCESS: 394
FAIL: 5
SKIPPED: 1

2021-09-16 14:45 UTC, kroce approved these changes

2021-09-16 15:50 UTC, kroce approved these changes

2021-09-16 15:58 UTC, merged