TM organizaciones: Agregar permiso global
andes/api pull request #1522
Opened 2021-08-27 16:43 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-190

### Funcionalidad desarrollada 

1. Verifica si el usuario tiene permiso global antes de filtrar la query. 
2. Agrega skip y limit.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-08-30 10:39 UTC, liquid36 requested changes

2021-08-30 10:39 UTC, liquid36 commented on core/tm/routes/organizacion.ts
> +        if (!user.permisosGlobales.some(p => p === 'global:organizaciones:write')){
Los permisos globales se concatenan a los permisos de la organización cuando te loggeas. Así que en esta instancia están pre-cargados en el request. Tenes que consultar con la clase `Auth` directamente como si fuese un permisos normal.

2021-08-30 13:01 UTC, liquid36 commented on core/tm/routes/organizacion.ts
> +    const skip = parseInt(req.query.skip, 10) || 0;
Tener en cuenta que esto afecta a toda la aplicación .

2021-09-02 12:59 UTC, negro89 commented on core/tm/routes/organizacion.ts
> +    const skip = parseInt(req.query.skip, 10) || 0;
Corregido!

2021-09-02 15:11 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4969](http://condorpiedra.andes.gob.ar:85/4969/mochawesome.html)
CYPRESS RUN: [3941](https://dashboard.cypress.io/projects/xr7gft/runs/3941/specs)
TEST START: 2021-09-02T15:11:23.050Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-02 19:00 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4972](http://condorpiedra.andes.gob.ar:85/4972/mochawesome.html)
CYPRESS RUN: [3944](https://dashboard.cypress.io/projects/xr7gft/runs/3944/specs)
TEST START: 2021-09-02T19:00:34.847Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-03 12:20 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4974](http://condorpiedra.andes.gob.ar:85/4974/mochawesome.html)
CYPRESS RUN: [3946](https://dashboard.cypress.io/projects/xr7gft/runs/3946/specs)
TEST START: 2021-09-03T12:20:14.993Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-03 14:26 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4977](http://condorpiedra.andes.gob.ar:85/4977/mochawesome.html)
CYPRESS RUN: [3949](https://dashboard.cypress.io/projects/xr7gft/runs/3949/specs)
TEST START: 2021-09-03T14:26:34.385Z
TOTAL: 388
SUCCESS: 385
FAIL: 2
SKIPPED: 1

2021-09-03 15:20 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4978](http://condorpiedra.andes.gob.ar:85/4978/mochawesome.html)
CYPRESS RUN: [3950](https://dashboard.cypress.io/projects/xr7gft/runs/3950/specs)
TEST START: 2021-09-03T15:20:12.029Z
TOTAL: 358
SUCCESS: 343
FAIL: 14
SKIPPED: 1

2021-09-03 15:35 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4979](http://condorpiedra.andes.gob.ar:85/4979/mochawesome.html)
CYPRESS RUN: [3951](https://dashboard.cypress.io/projects/xr7gft/runs/3951/specs)
TEST START: 2021-09-03T15:34:57.700Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-03 16:13 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4980](http://condorpiedra.andes.gob.ar:85/4980/mochawesome.html)
CYPRESS RUN: [3952](https://dashboard.cypress.io/projects/xr7gft/runs/3952/specs)
TEST START: 2021-09-03T16:11:28.118Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-03 17:01 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4981](http://condorpiedra.andes.gob.ar:85/4981/mochawesome.html)
CYPRESS RUN: [3953](https://dashboard.cypress.io/projects/xr7gft/runs/3953/specs)
TEST START: 2021-09-03T17:00:47.444Z
TOTAL: 1
SUCCESS: 1
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-03 17:28 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4982](http://condorpiedra.andes.gob.ar:85/4982/mochawesome.html)
CYPRESS RUN: [3954](https://dashboard.cypress.io/projects/xr7gft/runs/3954/specs)
TEST START: 2021-09-03T17:27:52.320Z
TOTAL: 400
SUCCESS: 391
FAIL: 8
SKIPPED: 1

2021-09-03 18:03 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4984](http://condorpiedra.andes.gob.ar:85/4984/mochawesome.html)
CYPRESS RUN: [3956](https://dashboard.cypress.io/projects/xr7gft/runs/3956/specs)
TEST START: 2021-09-03T18:03:24.048Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-06 11:24 UTC, kroce approved these changes

2021-09-06 11:47 UTC, liquid36 commented on core/tm/routes/organizacion.ts
> +        if (!user.permisosGlobales.some(p => p === 'global:organizaciones:write')){
Existe un middleware `optionalAuth`. No me parece correcto poner ese filtro sin autentificación.

2021-09-06 13:48 UTC, negro89 commented on core/tm/routes/organizacion.ts
> +        if (!user.permisosGlobales.some(p => p === 'global:organizaciones:write')){
corregido!

2021-09-06 14:29 UTC, kroce approved these changes

2021-09-06 14:59 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [4997](http://condorpiedra.andes.gob.ar:85/4997/mochawesome.html)
CYPRESS RUN: [3967](https://dashboard.cypress.io/projects/xr7gft/runs/3967/specs)
TEST START: 2021-09-06T14:59:40.161Z
TOTAL: 400
SUCCESS: 396
FAIL: 3
SKIPPED: 1

2021-09-06 15:34 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [5001](http://condorpiedra.andes.gob.ar:85/5001/mochawesome.html)
CYPRESS RUN: [3971](https://dashboard.cypress.io/projects/xr7gft/runs/3971/specs)
TEST START: 2021-09-06T15:34:13.634Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-06 16:18 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5004](http://condorpiedra.andes.gob.ar:85/5004/mochawesome.html)
CYPRESS RUN: [3974](https://dashboard.cypress.io/projects/xr7gft/runs/3974/specs)
TEST START: 2021-09-06T16:18:37.718Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-06 17:08 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5008](http://condorpiedra.andes.gob.ar:85/5008/mochawesome.html)
CYPRESS RUN: [3978](https://dashboard.cypress.io/projects/xr7gft/runs/3978/specs)
TEST START: 2021-09-06T17:08:08.450Z
TOTAL: 382
SUCCESS: 379
FAIL: 2
SKIPPED: 1

2021-09-06 17:41 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5010](http://condorpiedra.andes.gob.ar:85/5010/mochawesome.html)
CYPRESS RUN: [3980](https://dashboard.cypress.io/projects/xr7gft/runs/3980/specs)
TEST START: 2021-09-06T17:41:03.506Z
TOTAL: 289
SUCCESS: 275
FAIL: 13
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-07 13:16 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5019](http://condorpiedra.andes.gob.ar:85/5019/mochawesome.html)
CYPRESS RUN: [3988](https://dashboard.cypress.io/projects/xr7gft/runs/3988/specs)
TEST START: 2021-09-07T13:15:48.118Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-07 13:38 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5021](http://condorpiedra.andes.gob.ar:85/5021/mochawesome.html)
CYPRESS RUN: [3990](https://dashboard.cypress.io/projects/xr7gft/runs/3990/specs)
TEST START: 2021-09-07T13:37:18.812Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-07 14:54 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5022](http://condorpiedra.andes.gob.ar:85/5022/mochawesome.html)
CYPRESS RUN: [3991](https://dashboard.cypress.io/projects/xr7gft/runs/3991/specs)
TEST START: 2021-09-07T14:53:28.013Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-07 15:25 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5023](http://condorpiedra.andes.gob.ar:85/5023/mochawesome.html)
CYPRESS RUN: [3992](https://dashboard.cypress.io/projects/xr7gft/runs/3992/specs)
TEST START: 2021-09-07T15:24:37.696Z
TOTAL: 1
SUCCESS: 1
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-07 16:03 UTC, martinebucarey approved these changes

2021-09-07 16:07 UTC, merged