EP: asignar seguimiento a profesional
andes/api pull request #1523
Opened 2021-08-27 18:45 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/EP-123
### Funcionalidad desarrollada 

1. Se agrega asiganciones a schema de seguiiemento
2. filtro por profesional asignado a seguimiento
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-09-02 15:37 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4970](http://condorpiedra.andes.gob.ar:85/4970/mochawesome.html)
CYPRESS RUN: [3942](https://dashboard.cypress.io/projects/xr7gft/runs/3942/specs)
TEST START: 2021-09-02T15:33:55.262Z
TOTAL: 400
SUCCESS: 390
FAIL: 9
SKIPPED: 1

2021-09-02 16:41 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [4971](http://condorpiedra.andes.gob.ar:85/4971/mochawesome.html)
CYPRESS RUN: [3943](https://dashboard.cypress.io/projects/xr7gft/runs/3943/specs)
TEST START: 2021-09-02T16:40:48.862Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-08 12:54 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5033](http://condorpiedra.andes.gob.ar:85/5033/mochawesome.html)
CYPRESS RUN: [4002](https://dashboard.cypress.io/projects/xr7gft/runs/4002/specs)
TEST START: 2021-09-08T12:54:03.900Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-08 15:43 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5040](http://condorpiedra.andes.gob.ar:85/5040/mochawesome.html)
CYPRESS RUN: [4009](https://dashboard.cypress.io/projects/xr7gft/runs/4009/specs)
TEST START: 2021-09-08T15:36:07.635Z
TOTAL: 306
SUCCESS: 273
FAIL: 32
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-09 13:27 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5048](http://condorpiedra.andes.gob.ar:85/5048/mochawesome.html)
CYPRESS RUN: [4013](https://dashboard.cypress.io/projects/xr7gft/runs/4013/specs)
TEST START: 2021-09-09T13:27:00.400Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-10 12:56 UTC, martinebucarey approved these changes

2021-09-10 13:41 UTC, palita1991 approved these changes

2021-09-10 13:53 UTC, kroce requested changes

2021-09-10 13:53 UTC, kroce commented on modules/seguimiento-paciente/schemas/seguimiento-paciente.schema.ts
> +                    _id: Types.ObjectId,
Debería ir id en lugar de _id en el esquema

2021-09-10 13:58 UTC, martinebucarey commented on modules/seguimiento-paciente/schemas/seguimiento-paciente.schema.ts
> +                    _id: Types.ObjectId,
Modificado

2021-09-10 14:08 UTC, kroce approved these changes

2021-09-10 15:06 UTC, merged