INT: censo diario se corrige calculo en los días de estada
andes/api pull request #1524
Opened 2021-08-30 17:30 UTC by MCele

### Requerimiento

Se corrige error en el cálculo de los días de estada de el censo diario: se está reiniciando por cada movimiento de cama, sin importar si es el mismo servicio o uno nuevo.
https://proyectos.andes.gob.ar/browse/IN-322

### Funcionalidad desarrollada 

1. Se debe contabilizar la cantidad de días de estada desde el ingreso al servicio, hasta el día que se consulta.
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-08-31 13:55 UTC, liquid36 commented on modules/rup/internacion/censo.controller.ts
> +            filtros['estados.fecha'] = { $gte: fechaIngreso };
esto esta de más

2021-08-31 14:01 UTC, liquid36 requested changes
Pregunta: ¿habían pedido la fecha de ingreso en el censo, no debería ser la fecha de ingreso al servicio con este cambio?

2021-08-31 14:01 UTC, liquid36 commented on modules/rup/internacion/censo.controller.ts
> +            diasEstada = timestampEnd.diff(fechaIngresoUO, 'days');
La variable `diasEstada`  se estaba usando como un acumulador, esta alterando todas las estadísticas.

2021-09-03 17:59 UTC, MCele commented on modules/rup/internacion/censo.controller.ts
> +            diasEstada = timestampEnd.diff(fechaIngresoUO, 'days');
corregido

2021-09-03 18:00 UTC, MCele commented on modules/rup/internacion/censo.controller.ts
> +            filtros['estados.fecha'] = { $gte: fechaIngreso };
es verdad! ya lo saqué

2021-09-03 18:43 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4985](http://condorpiedra.andes.gob.ar:85/4985/mochawesome.html)
CYPRESS RUN: [3957](https://dashboard.cypress.io/projects/xr7gft/runs/3957/specs)
TEST START: 2021-09-03T18:42:28.977Z
TOTAL: 353
SUCCESS: 339
FAIL: 13
SKIPPED: 1

2021-09-03 19:04 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4986](http://condorpiedra.andes.gob.ar:85/4986/mochawesome.html)
CYPRESS RUN: [3958](https://dashboard.cypress.io/projects/xr7gft/runs/3958/specs)
TEST START: 2021-09-03T19:03:30.466Z
TOTAL: 386
SUCCESS: 374
FAIL: 11
SKIPPED: 1

2021-09-03 19:08 UTC, MCele commented
> Pregunta: ¿habían pedido la fecha de ingreso en el censo, no debería ser la fecha de ingreso al servicio con este cambio?

no entiendo la pregunta. El pedido es que los dias de estada se calcule por servicio. Cambio de servicio, entonces se reinicia el calculo.

2021-09-06 15:09 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [4998](http://condorpiedra.andes.gob.ar:85/4998/mochawesome.html)
CYPRESS RUN: [3968](https://dashboard.cypress.io/projects/xr7gft/runs/3968/specs)
TEST START: 2021-09-06T15:09:12.661Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-09-06 15:44 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5002](http://condorpiedra.andes.gob.ar:85/5002/mochawesome.html)
CYPRESS RUN: [3972](https://dashboard.cypress.io/projects/xr7gft/runs/3972/specs)
TEST START: 2021-09-06T15:44:14.166Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-06 16:55 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5007](http://condorpiedra.andes.gob.ar:85/5007/mochawesome.html)
CYPRESS RUN: [3977](https://dashboard.cypress.io/projects/xr7gft/runs/3977/specs)
TEST START: 2021-09-06T16:55:00.665Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-17 18:38 UTC, condorpiedra commented
Está pendiente de definición

2021-09-20 11:50 UTC, liquid36 commented
> Está pendiente de definición

¿Qué cosa?

2021-10-04 11:10 UTC, condorpiedra approved these changes

2021-10-04 11:26 UTC, merged