CORE: filtro solicitudes dashboard
andes/api pull request #1527
Opened 2021-09-01 12:10 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/CORE-71
### Funcionalidad desarrollada 

1.  Cambia busqueda de fecha de solicitud por creación de la prestación
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-09-01 12:40 UTC, liquid36 requested changes
hay que poner en el $match `inicio: 'top'` sino el indice no se tiene en cuenta. A demás ahora no es necesario filtrar por el primer estado ya que el flag `inicio` nos indica que es solicitud de TOP.

2021-09-10 12:30 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [5055](http://condorpiedra.andes.gob.ar:85/5055/mochawesome.html)
CYPRESS RUN: [4020](https://dashboard.cypress.io/projects/xr7gft/runs/4020/specs)
TEST START: 2021-09-10T12:30:16.790Z
TOTAL: 369
SUCCESS: 357
FAIL: 12
SKIPPED: 0

2021-09-10 12:41 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [5056](http://condorpiedra.andes.gob.ar:85/5056/mochawesome.html)
CYPRESS RUN: [4021](https://dashboard.cypress.io/projects/xr7gft/runs/4021/specs)
TEST START: 2021-09-10T12:41:44.553Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-10 12:42 UTC, kroce approved these changes

2021-09-10 12:55 UTC, palita1991 approved these changes

2021-09-10 12:56 UTC, merged