Epidemiología - Registrar alta y fallecimiento en seguimiento epidemiologico
andes/api pull request #1534
Opened 2021-09-06 18:56 UTC by martinebucarey

### Requerimiento
Registrar alta y fallecimiento en seguimiento epidemiologico

### Funcionalidad desarrollada 

1. Se agrega un nuevo evento rup:paciente:fallecido para poder registrar el fallecimiento de un paciente en el modulo de seguimiento epidemiologico. Cuando se registre algunos de los conceptos agregados en el nuevo elementoRUP (ver actualizaciones de base de datos), se dispara dicho evento.
2. Se agrego un elementoRup con el concepto "muerto" y sus descendientes.
3. Se agrega el evento que registra los seguimientos, la opción para registrar el alta de un paciente.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si Agregar en la coleccion elementoRUP el siguiente documento:
[elementoRupFallecido.txt](https://github.com/andes/api/files/7117544/elementoRupFallecido.txt)
- [ ] No

2021-09-06 19:05 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5014](http://condorpiedra.andes.gob.ar:85/5014/mochawesome.html)
CYPRESS RUN: [3984](https://dashboard.cypress.io/projects/xr7gft/runs/3984/specs)
TEST START: 2021-09-06T19:05:00.940Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-13 17:28 UTC, plammel approved these changes

2021-09-20 13:49 UTC, liquid36 requested changes

2021-09-20 13:49 UTC, liquid36 commented on modules/rup/controllers/elementos-rup.controller.ts
> +EventCore.on('rup:paciente:fallecido', async (data) => {
Esto es código de la ficha, debería ir en el modulo de la ficha y seguimiento.

2021-09-20 13:49 UTC, liquid36 commented on modules/rup/controllers/elementos-rup.controller.ts
> +        const lastSeguimiento = await SeguimientoPaciente.findOne({ 'paciente.id': data.prestacion.paciente.id }).sort({ createdAt: -1 });
Para analizar a futuro, podría tener dos fichas de distintos tipos abiertas al mismo tiempo?

2021-09-20 17:44 UTC, martinebucarey commented on modules/rup/controllers/elementos-rup.controller.ts
> +EventCore.on('rup:paciente:fallecido', async (data) => {
Modificado

2021-09-20 17:46 UTC, martinebucarey commented on modules/rup/controllers/elementos-rup.controller.ts
> +        const lastSeguimiento = await SeguimientoPaciente.findOne({ 'paciente.id': data.prestacion.paciente.id }).sort({ createdAt: -1 });
mmm seria un caso bastante raro pero si se llegara a dar, creo que estaría bien que el seguimiento sea uno solo y no sea un seguimiento por cada ficha. Se puede analizar en la próxima pandemia ja!.

2021-09-29 12:16 UTC, liquid36 approved these changes

2021-09-29 12:23 UTC, liquid36 commented
cambie el tipo de componente de **ObservacionesComponenet** a **EvolucionProblemaDefaultComponent** para dejar el que se usa ahora ya que solo se crea el componente para agregar el evento.

2021-09-29 14:07 UTC, merged