feat(IN):se agrega permiso para ver registros
andes/api pull request #1535
Opened 2021-09-07 16:26 UTC by waltergarrido

### Requerimiento

https://proyectos.andes.gob.ar/browse/IN-323
### Funcionalidad desarrollada 

1. Se agrega permiso "regitros"  
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-09-07 16:46 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5026](http://condorpiedra.andes.gob.ar:85/5026/mochawesome.html)
CYPRESS RUN: [3995](https://dashboard.cypress.io/projects/xr7gft/runs/3995/specs)
TEST START: 2021-09-07T16:46:16.458Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-07 17:16 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5027](http://condorpiedra.andes.gob.ar:85/5027/mochawesome.html)
CYPRESS RUN: [3996](https://dashboard.cypress.io/projects/xr7gft/runs/3996/specs)
TEST START: 2021-09-07T17:11:40.459Z
TOTAL: 313
SUCCESS: 297
FAIL: 15
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-08 17:09 UTC, liquid36 requested changes

2021-09-08 17:09 UTC, liquid36 commented on scripts/IN-323.ts
> +                'organizaciones.permisos': match
Este filtro tiene que ir arriba en el aggregate, sino te traes todos los usuarios innecesariamente.

2021-09-09 15:44 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5050](http://condorpiedra.andes.gob.ar:85/5050/mochawesome.html)
CYPRESS RUN: [4015](https://dashboard.cypress.io/projects/xr7gft/runs/4015/specs)
TEST START: 2021-09-09T15:44:05.277Z
TOTAL: 398
SUCCESS: 384
FAIL: 13
SKIPPED: 1

2021-09-09 17:37 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5053](http://condorpiedra.andes.gob.ar:85/5053/mochawesome.html)
CYPRESS RUN: [4018](https://dashboard.cypress.io/projects/xr7gft/runs/4018/specs)
TEST START: 2021-09-09T17:36:49.563Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-09-14 13:21 UTC, plammel approved these changes

2021-09-20 13:05 UTC, liquid36 commented on scripts/IN-323.ts
> +                'organizaciones._id': user.organizaciones._id,
Si buscas por el `id` del usuario que es único, no es necesario otro filtro.

2021-09-20 13:05 UTC, liquid36 commented on scripts/IN-323.ts
> +                multi: true
El update es uno solo por usuario, no es necesario un `multi`

2021-09-20 13:06 UTC, liquid36 commented on scripts/IN-323.ts
> +                id: '$_id'
projectas el campo ID pero después no se usa en ningún lado.

2021-09-20 13:07 UTC, liquid36 approved these changes
Dejo detalles que no afectan a la funcionalidad, pero si son detalles que hacen a la prolijidad del código.

2021-09-20 13:11 UTC, liquid36 commented
Hay que revisar los test porque fallan por estos cambios!!!!

2021-09-20 13:22 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5113](http://condorpiedra.andes.gob.ar:85/5113/mochawesome.html)
CYPRESS RUN: [4071](https://dashboard.cypress.io/projects/xr7gft/runs/4071/specs)
TEST START: 2021-09-20T13:22:21.447Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-09-21 12:13 UTC, liquid36 commented
USUARIO: wgarrido  
BUILD NUMBER: [5116](http://condorpiedra.andes.gob.ar:85/5116/mochawesome.html)
CYPRESS RUN: [4074](https://dashboard.cypress.io/projects/xr7gft/runs/4074/specs)
TEST START: 2021-09-21T12:13:04.521Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-23 15:06 UTC, merged