PDP - Guardar reporte de error
andes/api pull request #1538
Opened 2021-09-09 15:11 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/PDP-73

### Funcionalidad desarrollada 

1. Extiende esquema de logPaciente para guardar reporte de error de PDP

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-09-09 15:30 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5049](http://condorpiedra.andes.gob.ar:85/5049/mochawesome.html)
CYPRESS RUN: [4014](https://dashboard.cypress.io/projects/xr7gft/runs/4014/specs)
TEST START: 2021-09-09T15:29:46.495Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-13 13:48 UTC, condorpiedra requested changes

2021-09-13 13:48 UTC, condorpiedra commented on core/log/schemas/logPaciente.ts
> +            'portal:error:registrosSalud',
No utilizar la palabra "portal" en las operaciones ya que se podrían utilizar desde distintas apps (ej: error:registrosSalud podría ser una forma)

2021-09-14 11:35 UTC, negro89 commented on core/log/schemas/logPaciente.ts
> +            'portal:error:registrosSalud',
corregidoo

2021-09-14 13:16 UTC, plammel approved these changes

2021-09-16 17:04 UTC, condorpiedra approved these changes

2021-09-16 17:04 UTC, merged