VAC: nuevo campo enDomicilio para vacunas-paciente
andes/api pull request #1542
Opened 2021-09-14 18:02 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-104

### Funcionalidad desarrollada 

1. Nuevo campo enDomicilio para paciente-vacunas
2. Script para actualizar la coleccion a partir de las prestaciones de campañas de vacunación covid

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-09-14 19:01 UTC, kroce requested changes
@juuliotero : Falta la parte que al cargar una vacuna en rup con el check de "vacunación domiciliaria" seleccionado, esto impacte en el nuevo campo de pacientes-vacunas.

2021-09-15 12:32 UTC, juuliotero commented
> @juuliotero : Falta la parte que al cargar una vacuna en rup con el check de "vacunación domiciliaria" seleccionado, esto impacte en el nuevo campo de pacientes-vacunas.

Se suma el cambio

2021-09-16 11:18 UTC, liquid36 commented
USUARIO: cceleste  
BUILD NUMBER: [5080](http://condorpiedra.andes.gob.ar:85/5080/mochawesome.html)
CYPRESS RUN: [4043](https://dashboard.cypress.io/projects/xr7gft/runs/4043/specs)
TEST START: 2021-09-16T11:18:20.464Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-16 13:30 UTC, kroce approved these changes

2021-09-16 13:43 UTC, condorpiedra approved these changes

2021-09-16 13:47 UTC, merged