fix(CIT-118): Error al mostrar datos de pacientes unificados
andes/api pull request #1543
Opened 2021-09-15 13:24 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-118

### Funcionalidad desarrollada 
1. Se agregó un nuevo parámetro para poder traerme todo el historial fuera de agendas. También se agrego un condicional por si el paciente no esta vinculado con nadie y no devuelva un arreglo vacío innecesario. 

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-09-15 13:38 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5074](http://condorpiedra.andes.gob.ar:85/5074/mochawesome.html)
CYPRESS RUN: [4038](https://dashboard.cypress.io/projects/xr7gft/runs/4038/specs)
TEST START: 2021-09-15T13:38:22.496Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-16 17:26 UTC, condorpiedra requested changes
No es necesario realizar dos consultas para esto se resuelve realizando un get y consultar por await PacienteCtr.findById(pacienteID); 

const query = {
..
        'paciente.id': { $in: paciente.vinculos },
.
.

    };

2021-09-17 17:39 UTC, condorpiedra approved these changes

2021-09-21 11:56 UTC, MCele approved these changes

2021-09-29 14:53 UTC, merged