BI: filtro de zona para reportes
andes/api pull request #1545
Opened 2021-09-15 15:18 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/BI-87
### Funcionalidad desarrollada 

1. Al recibir param de zonaSanitaria, recupera los ids de organizaciones pertenecientes a la zona y filtra por esas organizaciones
2. 
3. 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/BI-87
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-09-15 15:38 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5076](http://condorpiedra.andes.gob.ar:85/5076/mochawesome.html)
CYPRESS RUN: [4040](https://dashboard.cypress.io/projects/xr7gft/runs/4040/specs)
TEST START: 2021-09-15T15:37:33.327Z
TOTAL: 358
SUCCESS: 335
FAIL: 22
SKIPPED: 1

2021-09-17 18:08 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5104](http://condorpiedra.andes.gob.ar:85/5104/mochawesome.html)
CYPRESS RUN: [4062](https://dashboard.cypress.io/projects/xr7gft/runs/4062/specs)
TEST START: 2021-09-17T18:08:40.959Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-20 13:20 UTC, liquid36 requested changes

2021-09-20 13:20 UTC, liquid36 commented on core/tm/controller/organizacion.ts
> +    return await Organizacion.find(params);
El await esta de más acá y por ande el async de la función. El `find` ya devuelve una promesa y el await externo se encarga de esperarlo.

2021-09-20 13:20 UTC, liquid36 commented on core/tm/controller/organizacion.ts
> +    return await Organizacion.find(params);
Lo ideal hubiese sido avanzar en un ResourceBase de Organizaciónes por lo menos para tener el controlador y las búsquedas por código. En otra oportunidad se avanzará en migrar las rutas.

2021-09-20 13:20 UTC, liquid36 commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +            organizaciones = (await findOrganizaciones({ 'zonaSanitaria._id': params.zonaSanitaria })).map(o => mongoose.Types.ObjectId(o.id));
Acomodar este spagueti de código en varias lineas.

2021-09-21 16:17 UTC, plammel commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +            organizaciones = (await findOrganizaciones({ 'zonaSanitaria._id': params.zonaSanitaria })).map(o => mongoose.Types.ObjectId(o.id));
> Acomodar este spagueti de código en varias lineas.

updateado

2021-09-21 18:33 UTC, negro89 approved these changes

2021-09-21 18:36 UTC, martinebucarey approved these changes

2021-09-23 13:00 UTC, merged