VAC: arreglo de script para actualizar enDomicilio
andes/api pull request #1549
Opened 2021-09-17 15:05 UTC by juuliotero

### Requerimiento
Verificar porque el script VAC-104 no actualiza el campo enDomicilio en pacientes-vacunas cuando hay más de una aplicación

### Funcionalidad desarrollada 
1. Se arregla el script VAC-104 para que actualice todas las aplicaciones

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-09-17 17:42 UTC, condorpiedra requested changes

2021-09-17 17:42 UTC, condorpiedra commented on scripts/VAC-104.ts
> +            if (index >= 0 && !aplicaciones[index].enDomicilio) {
La condición no debería ser aplicaciones[index].enDomicilio ?

2021-09-20 13:07 UTC, juuliotero commented on scripts/VAC-104.ts
> +            if (index >= 0 && !aplicaciones[index].enDomicilio) {
Solo actualiza si no tiene marcado el campo, si existe asumo que ya se registro que la aplicación fue en el domicilio del paciente.

2021-09-20 14:53 UTC, kroce approved these changes

2021-09-20 15:05 UTC, condorpiedra approved these changes

2021-09-20 15:22 UTC, merged