VAC: modificación de proceso para exportar vacunas
andes/api pull request #1554
Opened 2021-09-20 22:10 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/VAC-78

### Funcionalidad desarrollada 
1. Se busca el paciente por id, y si no está activo y tiene paciente asociado se traen los datos del paciente principal

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-09-21 11:35 UTC, liquid36 requested changes

2021-09-21 11:35 UTC, liquid36 commented on modules/vacunas/controller/vacunas.controller.ts
> +                    fechaNacimiento: paciente.fechaNacimiento,
Falta formatear la fecha: `%d-%m-%Y`

2021-09-22 12:29 UTC, juuliotero commented on modules/vacunas/controller/vacunas.controller.ts
> +                    fechaNacimiento: paciente.fechaNacimiento,
corregido

2021-09-22 12:41 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [5130](http://condorpiedra.andes.gob.ar:85/5130/mochawesome.html)
CYPRESS RUN: [4088](https://dashboard.cypress.io/projects/xr7gft/runs/4088/specs)
TEST START: 2021-09-22T12:40:48.473Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-22 18:16 UTC, plammel requested changes

2021-09-22 18:16 UTC, plammel commented on modules/vacunas/controller/vacunas.controller.ts
> +                    calle: paciente.direccion[0] ? paciente.direccion[0].valor : '',
Cuidado acá que `paciente.direccion` podría venir en null o undefined. Ya nos pasó en seguimiento y tuvimos que validar que existiera el array de direccion antes de consultar por la primera posición.
https://github.com/andes/api/blob/e014d3033d2bc5fa3a21c43da7c5ce5f9f5e4acc/modules/seguimiento-paciente/seguimiento-pacientes.events.ts#L25

2021-09-27 17:26 UTC, plammel approved these changes

2021-10-04 12:05 UTC, liquid36 approved these changes

2021-10-04 16:31 UTC, merged