refactor(MAT-71): verificación de vencimiento de formación de grado
andes/api pull request #1555
Opened 2021-09-21 18:31 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-71

### Funcionalidad desarrollada 
1. Se modifico el job vencimientoMatriculaGrado optimizando la consulta que se realiza en el find. 

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-09-21 18:42 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5125](http://condorpiedra.andes.gob.ar:85/5125/mochawesome.html)
CYPRESS RUN: [4083](https://dashboard.cypress.io/projects/xr7gft/runs/4083/specs)
TEST START: 2021-09-21T18:42:15.732Z
TOTAL: 370
SUCCESS: 366
FAIL: 3
SKIPPED: 1

2021-09-21 18:56 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5126](http://condorpiedra.andes.gob.ar:85/5126/mochawesome.html)
CYPRESS RUN: [4084](https://dashboard.cypress.io/projects/xr7gft/runs/4084/specs)
TEST START: 2021-09-21T18:55:47.571Z
TOTAL: 398
SUCCESS: 386
FAIL: 11
SKIPPED: 1

2021-09-22 11:47 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5128](http://condorpiedra.andes.gob.ar:85/5128/mochawesome.html)
CYPRESS RUN: [4086](https://dashboard.cypress.io/projects/xr7gft/runs/4086/specs)
TEST START: 2021-09-22T11:47:21.987Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-22 17:51 UTC, plammel requested changes

2021-09-22 17:51 UTC, plammel commented on core/tm/controller/profesional.ts
> +                if (profesional.formacionGrado.matriculado && profesional.formacionGrado.matriculacion[profesional.formacionGrado.matriculacion.length - 1].fin <= new Date()) {
Estos filtros están de más, ya los estás aplicando en los match del aggregate. Solo faltaría profesional.habilitado
```suggestion
        if (profesional.habilitado) {
            if (profesional.formacionGrado.matriculacion) {
                if (profesional.formacionGrado.matriculado && profesional.formacionGrado.matriculacion[profesional.formacionGrado.matriculacion.length - 1].fin <= new Date()) {
```

2021-09-23 12:46 UTC, MarianoCampetella commented on core/tm/controller/profesional.ts
> +                if (profesional.formacionGrado.matriculado && profesional.formacionGrado.matriculacion[profesional.formacionGrado.matriculacion.length - 1].fin <= new Date()) {
Corregido!!

2021-09-24 12:29 UTC, plammel requested changes

2021-09-24 12:29 UTC, plammel commented on core/tm/controller/profesional.ts
> +        { $unwind: '$formacionGrado'},
Últimos TOCs... 
```suggestion
        { $match: { 'formacionGrado.matriculado': true, profesionalMatriculado: true, habilitado: true }},
        { $unwind: '$formacionGrado' },
```

2021-09-24 13:58 UTC, MarianoCampetella commented on core/tm/controller/profesional.ts
> +        { $unwind: '$formacionGrado'},
Corregido!!

2021-09-24 14:01 UTC, plammel approved these changes

2021-12-27 13:01 UTC, martinebucarey requested changes
se ve bien el aggregate, lo unico que le faltaria es el cursor que pide la tarea, podes revisar como lo usaste aca https://github.com/andes/api/pull/1634 y hacer lo mismo.

2021-12-27 17:19 UTC, martinebucarey requested changes

2021-12-27 17:19 UTC, martinebucarey commented on core/tm/controller/profesional.ts
> +    for (const profesional of profesionales) {
```suggestion
    for await (const profesional of profesionales) {
```

2021-12-28 12:47 UTC, MarianoCampetella commented on core/tm/controller/profesional.ts
> +    for (const profesional of profesionales) {
Corregido!

2022-01-03 15:10 UTC, MCele approved these changes

2022-01-04 15:03 UTC, liquid36 approved these changes

2022-01-04 15:03 UTC, merged