PER - 49: filtros por fechas de control
andes/api pull request #1558
Opened 2021-09-22 17:23 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-49

### Funcionalidad desarrollada 
1. Dentro de la api se agrego el atributo fechaControl para poder machear desde la parte de matriculaciones y hacer el filtro por fechas de controles. 

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-09-22 17:41 UTC, martinebucarey submitted a review, later dismissed

2021-09-22 17:41 UTC, martinebucarey commented on core/tm/controller/profesional.ts
> +                    );
Esto es de otro PR me parece que no tiene que ver con la tarea https://github.com/andes/api/pull/1555/files

2021-09-22 17:49 UTC, plammel requested changes

2021-09-22 17:49 UTC, plammel commented on core/tm/controller/profesional.ts
> +                if (profesional.formacionGrado.matriculado && profesional.formacionGrado.matriculacion[profesional.formacionGrado.matriculacion.length - 1].fin <= new Date()) {
Estos filtros están de más, ya los estás aplicando en los match del aggregate. Solo faltaría `profesional.habilitado`

2021-09-22 18:11 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5154](http://condorpiedra.andes.gob.ar:85/5154/mochawesome.html)
CYPRESS RUN: [4106](https://dashboard.cypress.io/projects/xr7gft/runs/4106/specs)
TEST START: 2021-09-22T18:02:22.459Z
TOTAL: 295
SUCCESS: 281
FAIL: 13
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-09-23 12:51 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5158](http://condorpiedra.andes.gob.ar:85/5158/mochawesome.html)
CYPRESS RUN: [4110](https://dashboard.cypress.io/projects/xr7gft/runs/4110/specs)
TEST START: 2021-09-23T12:50:57.156Z
TOTAL: 400
SUCCESS: 398
FAIL: 1
SKIPPED: 1

2021-09-23 13:08 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5159](http://condorpiedra.andes.gob.ar:85/5159/mochawesome.html)
CYPRESS RUN: [4111](https://dashboard.cypress.io/projects/xr7gft/runs/4111/specs)
TEST START: 2021-09-23T13:07:18.405Z
TOTAL: 395
SUCCESS: 382
FAIL: 12
SKIPPED: 1

2021-09-23 14:01 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5162](http://condorpiedra.andes.gob.ar:85/5162/mochawesome.html)
CYPRESS RUN: [4114](https://dashboard.cypress.io/projects/xr7gft/runs/4114/specs)
TEST START: 2021-09-23T14:00:50.726Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-09-23 14:57 UTC, liquid36 approved these changes

2021-09-23 15:08 UTC, plammel approved these changes

2021-09-24 12:54 UTC, merged