MAT: filtrar matricula por fechas aisladas
andes/api pull request #1560
Opened 2021-09-24 11:53 UTC by juuliotero

### Requerimiento
En reportes, permitir filtrar por fechaDesde y fechaHasta aisladas, no solo por rango completo.

### Funcionalidad desarrollada 
1. Se modifica la ruta /profesionales/matricula para buscar por fechaHasta y fechaDesde

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-09-28 15:57 UTC, plammel approved these changes

2021-09-30 18:38 UTC, palita1991 requested changes
@juuliotero cuando queres filtrar con ambas, te trae todos los profesionales y no filtra por la fecha de matriculación, no así cuando las pones aisladas
![image](https://user-images.githubusercontent.com/30004190/135511964-49f902a9-3311-4b42-9e82-bcdbbbe9660b.png)

2021-10-01 16:25 UTC, juuliotero commented
> @juuliotero cuando queres filtrar con ambas, te trae todos los profesionales y no filtra por la fecha de matriculación, no así cuando las pones aisladas ![image](https://user-images.githubusercontent.com/30004190/135511964-49f902a9-3311-4b42-9e82-bcdbbbe9660b.png)

Corregido palita

2021-10-01 16:37 UTC, liquid36 commented
USUARIO: jotero  
BUILD NUMBER: [5224](http://condorpiedra.andes.gob.ar:85/5224/mochawesome.html)
CYPRESS RUN: [4170](https://dashboard.cypress.io/projects/xr7gft/runs/4170/specs)
TEST START: 2021-10-01T16:36:54.804Z
TOTAL: 397
SUCCESS: 393
FAIL: 3
SKIPPED: 1

2021-10-04 11:38 UTC, liquid36 commented
USUARIO: mpalavecino  
BUILD NUMBER: [5230](http://condorpiedra.andes.gob.ar:85/5230/mochawesome.html)
CYPRESS RUN: [4176](https://dashboard.cypress.io/projects/xr7gft/runs/4176/specs)
TEST START: 2021-10-04T11:38:22.082Z
TOTAL: 401
SUCCESS: 400
FAIL: 0
SKIPPED: 1

2021-10-04 15:09 UTC, palita1991 approved these changes

2021-10-04 15:35 UTC, merged