Adjuntar y eliminar archivos relacionados con el profesional
andes/api pull request #1580
Opened 2021-10-14 14:31 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-31

### Funcionalidad desarrollada 
1. Se agregaron nuevas funcionalidades para guardar y eliminar los archivos necesarios de cada profesional dentro de matriculaciones.

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-10-14 16:59 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5304](http://condorpiedra.andes.gob.ar:85/5304/mochawesome.html)
CYPRESS RUN: [4249](https://dashboard.cypress.io/projects/xr7gft/runs/4249/specs)
TEST START: 2021-10-14T16:58:44.227Z
TOTAL: 357
SUCCESS: 344
FAIL: 12
SKIPPED: 1

2021-10-18 17:22 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5324](http://condorpiedra.andes.gob.ar:85/5324/mochawesome.html)
CYPRESS RUN: [4269](https://dashboard.cypress.io/projects/xr7gft/runs/4269/specs)
TEST START: 2021-10-18T17:13:34.288Z
TOTAL: 392
SUCCESS: 384
FAIL: 7
SKIPPED: 1

2021-10-19 11:33 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5329](http://condorpiedra.andes.gob.ar:85/5329/mochawesome.html)
CYPRESS RUN: [4274](https://dashboard.cypress.io/projects/xr7gft/runs/4274/specs)
TEST START: 2021-10-19T11:17:20.461Z
TOTAL: 325
SUCCESS: 284
FAIL: 40
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-10-19 11:57 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5330](http://condorpiedra.andes.gob.ar:85/5330/mochawesome.html)
CYPRESS RUN: [4275](https://dashboard.cypress.io/projects/xr7gft/runs/4275/specs)
TEST START: 2021-10-19T11:57:15.095Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2021-11-18 15:18 UTC, plammel requested changes
Lintear

2021-11-18 15:18 UTC, plammel commented on core/tm/routes/profesional.ts
> +});
Consumir directamente el endpoint de andesDrive (`/api/drive/:id`),
https://github.com/andes/api/pull/1580#discussion_r729760872
```suggestion
```

2021-11-18 16:18 UTC, plammel approved these changes

2021-11-18 16:27 UTC, MCele approved these changes

2021-11-18 16:46 UTC, juuliotero approved these changes

2021-11-18 17:01 UTC, liquid36 approved these changes

2021-11-18 17:44 UTC, merged