MAT - Filtros para renovación de matrículas
andes/api pull request #1588
Opened 2021-10-21 14:14 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-81

### Funcionalidad desarrollada 

1. Se agrega endpoint para búsqueda de profesionales en proceso de renovacion de matrícula.
2. Modifica esquema de turno agregando atribudo con datos del usuario y organización que edita.
3. Agrega filtros por estado en generación de reporte.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-11-15 16:59 UTC, juuliotero submitted a review, later dismissed

2021-11-15 16:59 UTC, juuliotero commented on modules/matriculaciones/schemas/turno.ts
> +    updatedBy: {
¿no conviene usar el AuditPlugin?

2021-11-30 18:22 UTC, plammel requested changes

2021-11-30 18:22 UTC, plammel commented on modules/matriculaciones/routes/turno.ts
> +router.patch('/turnos/save/:turnoId', Auth.authenticate(), async (request, response, next) => {
Ya que modificás las ruta, sacaría el `save` del path, q no es muy restful q digamos... el save ya está implicito el método patch
```suggestion
router.patch('/turnos/:turnoId', Auth.authenticate(), async (request, response, next) => {
```

2021-12-27 12:03 UTC, martinebucarey commented
@negro89 revisar comentarios  y conflictos

2021-12-28 14:59 UTC, negro89 commented on core/tm/routes/profesional.ts
> +    if (req.query.fechaDesde) {
gracias, corregido!

2021-12-28 15:04 UTC, negro89 commented on modules/matriculaciones/routes/turno.ts
> +router.patch('/turnos/save/:turnoId', Auth.authenticate(), async (request, response, next) => {
Concuerdo, pero dejemoslo para otra ocación. Ya es bastante larga la instancia de testing para esta tarea.

2021-12-28 15:35 UTC, plammel approved these changes

2022-01-03 16:48 UTC, MCele approved these changes

2022-01-03 17:25 UTC, merged