TOP - Suspensión de turno dado a solicitud
andes/api pull request #1593
Opened 2021-10-26 19:05 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-26

### Funcionalidad desarrollada 

1. Desvincula la solicitud del turno suspendido y agrega el registro en el historial

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-11-01 12:00 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5419](http://condorpiedra.andes.gob.ar:85/5419/mochawesome.html)
CYPRESS RUN: [4357](https://dashboard.cypress.io/projects/xr7gft/runs/4357/specs)
TEST START: 2021-11-01T12:00:01.235Z
TOTAL: 378
SUCCESS: 375
FAIL: 2
SKIPPED: 1

2021-11-01 12:32 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5420](http://condorpiedra.andes.gob.ar:85/5420/mochawesome.html)
CYPRESS RUN: [4358](https://dashboard.cypress.io/projects/xr7gft/runs/4358/specs)
TEST START: 2021-11-01T12:32:09.396Z
TOTAL: 348
SUCCESS: 335
FAIL: 12
SKIPPED: 1

2021-11-01 12:53 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5421](http://condorpiedra.andes.gob.ar:85/5421/mochawesome.html)
CYPRESS RUN: [4359](https://dashboard.cypress.io/projects/xr7gft/runs/4359/specs)
TEST START: 2021-11-01T12:53:24.663Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

2021-11-01 20:31 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5424](http://condorpiedra.andes.gob.ar:85/5424/mochawesome.html)
CYPRESS RUN: [4362](https://dashboard.cypress.io/projects/xr7gft/runs/4362/specs)
TEST START: 2021-11-01T20:30:49.781Z
TOTAL: 262
SUCCESS: 237
FAIL: 25
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-02 12:24 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5426](http://condorpiedra.andes.gob.ar:85/5426/mochawesome.html)
CYPRESS RUN: [4364](https://dashboard.cypress.io/projects/xr7gft/runs/4364/specs)
TEST START: 2021-11-02T12:23:58.534Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2021-11-02 16:31 UTC, palita1991 approved these changes

2021-12-02 12:22 UTC, liquid36 requested changes

2021-12-02 12:22 UTC, liquid36 commented on modules/turnos/routes/agenda.ts
> +                        bloque.turnos.forEach(async t => {
El `forEach` no es asincrónico. Hay que reemplazar todo por un `map` y un `Promise.all()`

2021-12-02 12:22 UTC, liquid36 commented on modules/rup/controllers/prestacion.ts
> +        const idTurno = typeof turno.id === 'string' ? Types.ObjectId(turno.id) : turno.id;
¿Que problema tuviste acá? 
`new Types.ObjectId(turno.id)` funciona tanto para string como para ObjectId.

2021-12-10 15:03 UTC, negro89 commented on modules/rup/controllers/prestacion.ts
> +        const idTurno = typeof turno.id === 'string' ? Types.ObjectId(turno.id) : turno.id;
No sabia. En alguna prueba que hice no me encontró el turno y supuse que venía por ahi. Ahi lo dejé como estaba. Gracias por la aclaracion!

2021-12-16 17:36 UTC, merged