MPI: nueva colección para cargar pacientes empadronados
andes/api pull request #1595
Opened 2021-10-27 15:56 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-363

### Funcionalidad desarrollada 
1. Nuevo schema pacientes-empadronados 
2. Script para llenar colección pacientes-empadronados por rango de fechas

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-11-04 14:51 UTC, negro89 requested changes

2021-11-04 14:51 UTC, negro89 commented on scripts/cargarEmpadronados.ts
> +        datos.pais = 'Argentina';
problemilla: 'pais' no está en el esquema de empadronamiento. 'efectorEmpadronamiento' está pero no se setea en ninguno de los dos casos.

2021-11-04 14:51 UTC, negro89 commented on scripts/cargarEmpadronados.ts
> +    const pacientesSumar = await pacientesPorPeriodoSumar(fechaDesde, fechaHasta);
Desconozco la cantidad de registros que puede traer esta consulta pero si son muchos quizás tener en cuenta la posibilidad su usar un cursor para traer de a tandas.

2021-12-07 13:30 UTC, juuliotero commented on scripts/cargarEmpadronados.ts
> +    const pacientesSumar = await pacientesPorPeriodoSumar(fechaDesde, fechaHasta);
Al usar un filtro por fechas los pacientes a recorrer no van a ser tantos, pero no se si conviene igual usar uno.

2021-12-21 12:49 UTC, liquid36 approved these changes

2021-12-21 12:51 UTC, merged