EP: eliminar ficha
andes/api pull request #1604
Opened 2021-11-04 18:47 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/EP-167
### Funcionalidad desarrollada 

1. eliminar ficha con permiso restrictivo
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-11-04 18:56 UTC, martinebucarey requested changes

2021-11-04 18:56 UTC, martinebucarey commented on modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
> +    active: Boolean
```suggestion
   active: {
        type: Boolean,
        required: true,
        default: true
    }
```

2021-11-05 15:54 UTC, martinebucarey commented
Hay que agregar el package con el andes/core actualizado asi toma el cambio de default params

2021-11-05 17:43 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5441](http://condorpiedra.andes.gob.ar:85/5441/mochawesome.html)
CYPRESS RUN: [4379](https://dashboard.cypress.io/projects/xr7gft/runs/4379/specs)
TEST START: 2021-11-05T17:43:25.578Z
TOTAL: 386
SUCCESS: 383
FAIL: 2
SKIPPED: 1

2021-11-05 17:57 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5442](http://condorpiedra.andes.gob.ar:85/5442/mochawesome.html)
CYPRESS RUN: [4380](https://dashboard.cypress.io/projects/xr7gft/runs/4380/specs)
TEST START: 2021-11-05T17:57:12.495Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

2021-11-05 18:22 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5444](http://condorpiedra.andes.gob.ar:85/5444/mochawesome.html)
CYPRESS RUN: [4381](https://dashboard.cypress.io/projects/xr7gft/runs/4381/specs)
TEST START: 2021-11-05T18:21:22.915Z
TOTAL: 292
SUCCESS: 268
FAIL: 24
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-05 18:40 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5445](http://condorpiedra.andes.gob.ar:85/5445/mochawesome.html)
CYPRESS RUN: [4382](https://dashboard.cypress.io/projects/xr7gft/runs/4382/specs)
TEST START: 2021-11-05T18:39:57.542Z
TOTAL: 303
SUCCESS: 279
FAIL: 24
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-08 14:19 UTC, martinebucarey commented on scripts/EP-167.ts
> +        const $set = { active: true };
Antes del set agregaría un control de que el campo no exista, seguramente después de que subamos este cambio vamos a tener que correr varias veces el script porque las fichas que se creen apenas actualizamos no van a salir con el campo active.

2021-11-09 13:29 UTC, martinebucarey commented on scripts/EP-167.ts
> +    const fichas = FormsEpidemiologia.find({}).cursor();
```suggestion
    const fichas = FormsEpidemiologia.find({ active: { $exists: false } }).cursor();

```

2021-11-15 17:51 UTC, martinebucarey approved these changes

2021-11-16 17:00 UTC, liquid36 approved these changes

2021-11-17 13:15 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5493](http://condorpiedra.andes.gob.ar:85/5493/mochawesome.html)
CYPRESS RUN: [4430](https://dashboard.cypress.io/projects/xr7gft/runs/4430/specs)
TEST START: 2021-11-17T13:15:00.237Z
TOTAL: 323
SUCCESS: 309
FAIL: 13
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-17 13:22 UTC, merged