fix(RUP): espacio entre conceptos
andes/api pull request #1605
Opened 2021-11-08 14:21 UTC by waltergarrido

### Requerimiento

https://proyectos.andes.gob.ar/browse/RUP-296
### Funcionalidad desarrollada 

1. se modifica scss el espacio .
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-11-08 16:12 UTC, negro89 requested changes
Se ve bien! pero al cambiar el tamaño de la tabulación de 4 a 2 espacios es dificil seguir los cambios. Creo que mantenerlo en 4 espacios es lo ideal.
Además hay mucho código comentado que, aunque no se incorpora en este PR, es una buena oportunidad para sacarlo ;)

2021-11-08 16:46 UTC, liquid36 commented
> Se ve bien! pero al cambiar el tamaño de la tabulación de 4 a 2 espacios es dificil seguir los cambios. Creo que mantenerlo en 4 espacios es lo ideal. Además hay mucho código comentado que, aunque no se incorpora en este PR, es una buena oportunidad para sacarlo ;)

El estandar es 4 en todo el código!

2021-11-09 15:09 UTC, waltergarrido commented
> > Se ve bien! pero al cambiar el tamaño de la tabulación de 4 a 2 espacios es dificil seguir los cambios. Creo que mantenerlo en 4 espacios es lo ideal. Además hay mucho código comentado que, aunque no se incorpora en este PR, es una buena oportunidad para sacarlo ;)
> 
> El estandar es 4 en todo el código!

Disculpen se modifico la tabulacion ahora modifico y subo .

2021-11-09 15:34 UTC, closed without merging

2021-11-09 15:35 UTC, waltergarrido commented
cerrado.