CIT: permiso asignación masiva
andes/api pull request #1609
Opened 2021-11-11 15:24 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-133
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2021-11-15 17:48 UTC, martinebucarey approved these changes

2021-11-19 12:19 UTC, martinebucarey requested changes

2021-11-19 12:19 UTC, martinebucarey commented on auth/permisos.ts
> +            },
Esto iria dentro de los permisos de agendas

2021-11-30 13:47 UTC, martinebucarey approved these changes

2021-11-30 14:24 UTC, liquid36 approved these changes

2021-12-22 13:21 UTC, liquid36 commented
LLevaría este cambio al pr de https://github.com/andes/api/pull/1626/files sino se complica el testing.

2021-12-22 17:54 UTC, closed without merging

2021-12-22 17:55 UTC, plammel commented
se migra funcionalidad a #1626