MPI: registro de los pacientes con los que interactúa un usuario
andes/api pull request #1614
Opened 2021-11-15 15:41 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MPI-348

### Funcionalidad desarrollada 
1. Nuevo schema mpiPacientesFrecuentes
2. Nuevo evento 'mpi:pacientes:frecuentes'

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-11-26 15:19 UTC, liquid36 requested changes
Faltaría la parte de la app (?)

2021-11-26 15:19 UTC, liquid36 commented on core-v2/mpi/paciente/paciente.events.ts
> +EventCore.on('mpi:pacientes:frecuentes', async (paciente: IPacienteDoc, usuario: IAuthUsers) => {
La lógica es al revez, uno se subscribe a los eventos que ya existen, así se evita modificar modulos que no corresponde. Queda trasparente. 

Como se usa acá es lo mismo que ejecutar directamente una función.

2021-12-03 17:46 UTC, juuliotero commented on core-v2/mpi/paciente/paciente.events.ts
> +EventCore.on('mpi:pacientes:frecuentes', async (paciente: IPacienteDoc, usuario: IAuthUsers) => {
¡Listo!

2021-12-03 17:49 UTC, juuliotero commented
@liquid36 separé la parte de la app en https://proyectos.andes.gob.ar/browse/MPI-366

2021-12-21 13:46 UTC, liquid36 commented
Se cierra este PR, no llego a completarse la tarea.  Quedara para que otro chico la haga de nuevo .

2021-12-21 13:46 UTC, closed without merging