IN - Registro de uso de respirador en colección internacionPacienteResumen
andes/api pull request #1615
Opened 2021-11-15 22:46 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-353
https://proyectos.andes.gob.ar/browse/IN-354

### Funcionalidad desarrollada 

1. Agrega atributo 'registros' para guardar datos del respirador usado
2. Nuevos eventos para actualizar resumen de internación del paciente al validar/romper-validación usando conceptos de respiración asistida

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

Dos nuevos registros en colección ElementosRUP:

{
    "activo" : true,
    "componente" : "RespiracionAsistidaComponent",
    "tipo" : "atomo",
    "esSolicitud" : false,
    "conceptos" : [ 
        {
            "conceptId" : "266700009",
            "term" : "respiración asistida",
            "fsn" : "respiración asistida (procedimiento)",
            "semanticTag" : "procedimiento"
        }
    ],
    "requeridos" : [],
    "frecuentes" : [],
    "dispatch" : [ 
        {
            "event" : "internacion:respirador:registro",
            "method" : "registro-respirador"
        }
    ]
}

2021-11-16 11:51 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5487](http://condorpiedra.andes.gob.ar:85/5487/mochawesome.html)
CYPRESS RUN: [4424](https://dashboard.cypress.io/projects/xr7gft/runs/4424/specs)
TEST START: 2021-11-16T11:51:30.179Z
TOTAL: 358
SUCCESS: 355
FAIL: 2
SKIPPED: 1

2021-11-16 12:46 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5488](http://condorpiedra.andes.gob.ar:85/5488/mochawesome.html)
CYPRESS RUN: [4425](https://dashboard.cypress.io/projects/xr7gft/runs/4425/specs)
TEST START: 2021-11-16T12:46:04.644Z
TOTAL: 416
SUCCESS: 415
FAIL: 0
SKIPPED: 1

2021-12-10 11:57 UTC, martinebucarey requested changes

2021-12-10 11:57 UTC, martinebucarey commented on modules/rup/routes/prestacion.ts
> +                elemento.dispatch.forEach(async hook => {
el async no va

2021-12-16 13:44 UTC, negro89 commented
cambios hechos y branch actualizada

2021-12-17 13:16 UTC, martinebucarey reviewed
En las pruebas que hice no me registra nada en la coleccion internacionPacienteResumen porque no encuentra en la prestacion el trackId, eso es probable que sea por mi base de datos?? (hice pruebas locales)

2021-12-17 13:16 UTC, martinebucarey commented on modules/rup/routes/prestacion.ts
> +                    }
Me parece que agregar estos if pierde un poco el dinamismo del dispatch.
En este caso yo pondría los dispatch de la siguiente manera:
{
    "event" : "internacion:respirador:registro",
    "method" : "validar-prestacion"
}
{
    "event" : "internacion:respirador:destete",
    "method" : "validar-prestacion"
}
Y seguimos usando solo romper y validar que se pueden usar para cualquier elemento rup

2021-12-28 17:10 UTC, negro89 commented on modules/rup/routes/prestacion.ts
> +                    }
me parece una propuesta maravillosa, no se por qué no lo hice asi. Corregido

2022-01-10 12:51 UTC, liquid36 approved these changes

2022-01-10 14:10 UTC, martinebucarey approved these changes

2022-01-10 15:51 UTC, merged