RUP (Fix) - Descarga de Ecografías tira error 500
andes/api pull request #1628
Opened 2021-12-14 13:22 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-300

### Funcionalidad desarrollada 

1. Se asocia un elementoRUP por default durante la impresión a los registros que no lo posean

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2021-12-14 14:13 UTC, liquid36 requested changes

2021-12-14 14:13 UTC, liquid36 commented on modules/rup/controllers/elementos-rup.controller.ts
> +                registro.elementoRUPObject = await ElementoRUP.findOne({ defaultFor: { $in: [registro.semanticTag] }, esSolicitud: registro.esSolicitud });
Si no se encuentra por ID deberías usar `elementosRUPSet.getByConcept()` así mantenemos la misma lógica de busqueda de conceptos. 

```javascript
if (registro.elementoRUP) {
    registro.elementoRUPObject = elementosRUPSet.getByID(registro.elementoRUP);
} else {
    registro.elementoRUPObject = elementosRUPSet.getByConcept(registro.concepto, registro.esSolicitud);
}
```

2021-12-14 14:13 UTC, liquid36 commented on modules/descargas/informe-rup/utils/registro-to-html.ts
> +    if (!elementoRUP) {
Acá no debería ser necesario.

2021-12-16 16:48 UTC, negro89 commented on modules/descargas/informe-rup/utils/registro-to-html.ts
> +    if (!elementoRUP) {
listorti @liquid36

2021-12-16 16:55 UTC, liquid36 approved these changes

2021-12-16 16:58 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5651](http://condorpiedra.andes.gob.ar:85/5651/mochawesome.html)
CYPRESS RUN: [4584](https://dashboard.cypress.io/projects/xr7gft/runs/4584/specs)
TEST START: 2021-12-16T16:57:53.189Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-16 17:20 UTC, merged