RUP (Fix) - Poder editar valor de edad gestacional
andes/api pull request #1630
Opened 2021-12-15 15:39 UTC by negro89

ademas edita informe para registros de formulaBase sin valor

### Requerimiento
https://proyectos.andes.gob.ar/browse/PER-65

### Funcionalidad desarrollada 

1. Agrega param 'valorEditable' en elementoRUP de formulaBase (edad gestacional) que permite editar manualmente el valor de edad gestacional.
2. Agrega bool en componente formulaBase para los registros que permitan ingresar el valor manualmente (valorEditable = true). Cuando el bool esta activo, desaparecen visualmente los registros requeridos y permite que el uss pueda ingresar a mano el valor final.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

Registro de coleccion ElementosRUP con id **ObjectId("6081bc9484ff50fdf474f062")** (FormulaBaseComponent con concepto 'edad gestacional') agregar param 'valorEditable' en true.

2021-12-16 14:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5648](http://condorpiedra.andes.gob.ar:85/5648/mochawesome.html)
CYPRESS RUN: [4581](https://dashboard.cypress.io/projects/xr7gft/runs/4581/specs)
TEST START: 2021-12-16T14:19:10.021Z
TOTAL: 402
SUCCESS: 400
FAIL: 1
SKIPPED: 1

2021-12-16 17:23 UTC, liquid36 requested changes

2021-12-16 17:23 UTC, liquid36 commented on modules/rup/schemas/prestacion.registro.ts
> +    valorManual: Boolean,
introducir un nuevo campo de valor es inviable, montones de consulta habría que tener en cuenta. 

El tema de ingresar un valor a mano debería ser solo perceptible en la UI, pero el campo valor se tiene que seguir rellenando para el funcionamiento normal del sistema.

2021-12-16 17:34 UTC, negro89 commented on modules/rup/schemas/prestacion.registro.ts
> +    valorManual: Boolean,
Si si, el campo valor seguiría llenandose normalmente en cualquier caso. La propiedad valorManual en true solo indica al componente que debe leer el valor del registro y no calcular mediante la formula con los subregistros. 
Quizas valorManual debería llamarse 'introduceValorManual' o similar ya que no almacena un valor en si.

La propiedad 'valorEditable' de la molecula (Solo para edad gestacional, por ahora) serviría para dar la opción al uss si usar la formula o ingresar en valor manualmente.

2021-12-20 17:35 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5684](http://condorpiedra.andes.gob.ar:85/5684/mochawesome.html)
CYPRESS RUN: [4612](https://dashboard.cypress.io/projects/xr7gft/runs/4612/specs)
TEST START: 2021-12-20T17:35:23.938Z
TOTAL: 352
SUCCESS: 349
FAIL: 2
SKIPPED: 1

2021-12-28 19:20 UTC, MCele approved these changes

2022-01-07 15:37 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5787](http://condorpiedra.andes.gob.ar:85/5787/mochawesome.html)
CYPRESS RUN: [4710](https://dashboard.cypress.io/projects/xr7gft/runs/4710/specs)
TEST START: 2022-01-07T15:37:24.861Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-07 16:15 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5789](http://condorpiedra.andes.gob.ar:85/5789/mochawesome.html)
CYPRESS RUN: [4712](https://dashboard.cypress.io/projects/xr7gft/runs/4712/specs)
TEST START: 2022-01-07T16:15:34.645Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-12 17:05 UTC, liquid36 approved these changes

2022-01-12 17:10 UTC, merged