BI - Agregar id del profesional a la colección codificación
andes/api pull request #1634
Opened 2021-12-22 17:33 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/BI-112

### Funcionalidad desarrollada 
1. Se creo un script para actualizar la coleccion "codificacion" agregando dentro de la misma el id del profesional correspondiente

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2021-12-22 17:48 UTC, martinebucarey requested changes

2021-12-22 17:48 UTC, martinebucarey commented on scripts/update-codificacion.ts
> +    const fechaHasta = new Date();
No hardcodear las fechas, la idea es que se pueda mandar dos fechas por parámetro para poder correrlo de a partes en caso de ser necesario (chequera como funciona process.argv para esto)

2021-12-22 17:53 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5708](http://condorpiedra.andes.gob.ar:85/5708/mochawesome.html)
CYPRESS RUN: [4632](https://dashboard.cypress.io/projects/xr7gft/runs/4632/specs)
TEST START: 2021-12-22T17:43:43.256Z
TOTAL: 404
SUCCESS: 387
FAIL: 16
SKIPPED: 1

2021-12-22 18:54 UTC, MarianoCampetella commented on scripts/update-codificacion.ts
> +    const fechaHasta = new Date();
Corregido, ahora se pueden ingresar los datos por parametros!

2021-12-22 19:04 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5710](http://condorpiedra.andes.gob.ar:85/5710/mochawesome.html)
CYPRESS RUN: [4634](https://dashboard.cypress.io/projects/xr7gft/runs/4634/specs)
TEST START: 2021-12-22T19:03:56.984Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2021-12-23 11:13 UTC, martinebucarey requested changes

2021-12-23 11:13 UTC, martinebucarey commented on scripts/update-codificacion.ts
> +    }).cursor({ batchSize: 100 });
```suggestion
// si vienen fecha se setea sino busca todas
if(process.argv.length === 5){
     const fechaDesde = new Date(process.argv[3]);
    const fechaHasta = new Date(process.argv[4]);
    const codificaciones: any = await Codificacion.find({
        createdAt:{$gte:fechaDesde, $lte:fechaHasta}
    }).cursor({ batchSize: 100 });
} else {
 const codificaciones: any = await Codificacion.find({ }).cursor({ batchSize: 100 });
}
   
```

2021-12-23 11:17 UTC, liquid36 commented on scripts/update-codificacion.ts
> +    }).cursor({ batchSize: 100 });
El find va sin el _await_ para que sea cursor

2021-12-23 11:19 UTC, martinebucarey commented on scripts/update-codificacion.ts
> +    }).cursor({ batchSize: 100 });
eso

2021-12-27 14:36 UTC, martinebucarey requested changes
Lo que hacemos cuando modificamos la query es subirla con formato txt o alguno de esos modificada para poder setearla en la base que haya que probarla. En el caso que se modifique mucho de la query no es facil mirar la captura para probar.
No queda muy claro poniendo esa imagen en el PR que es lo que hay que modificar porque dice la colección query y no cual seria el documento de esa colección a modificar.
Cuando creas el Pr podes arrastrar el txt o tmb tenes la opción de adjuntar archivos.

2022-01-03 13:40 UTC, liquid36 approved these changes

2022-01-03 14:02 UTC, martinebucarey approved these changes

2022-01-04 15:06 UTC, merged