BI: incluir profesional en turno de agenda
andes/api pull request #1640
Opened 2022-01-04 15:17 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/BI-114
https://proyectos.andes.gob.ar/browse/BI-115
### Funcionalidad desarrollada 

1. Profesional en scheame de turno
2. Script para incluir profesional en turno de agenda
3. Query de agendas-consolidado incluye date de id de profesional de turno

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [x] Si: actualizar registro de query de agenda-consolidados
[query_agenda-consolidado.txt](https://github.com/andes/api/files/7808528/query_agenda-consolidado.txt)

- [ ] No

2022-01-04 15:34 UTC, liquid36 commented on scripts/BI-115.ts
> +    while (prestacion = await prestaciones.next()) {
```suggestion
    for await (const prestacion of prestaciones) {
```

2022-01-04 15:39 UTC, plammel commented on scripts/BI-115.ts
> +    while (prestacion = await prestaciones.next()) {
👌

2022-01-10 17:48 UTC, martinebucarey commented on scripts/BI-115.ts
> +    if (process.argv.length >= 3) {
```suggestion
    if (process.argv.length > 3) {
```
Si es mayor o igual, si no le mandas ningun argumento entra al if porque el length es 3

2022-01-10 17:49 UTC, martinebucarey requested changes

2022-01-10 17:49 UTC, martinebucarey commented on scripts/BI-115.ts
> +import { IPrestacion } from '../modules/rup/prestaciones.interface';
```suggestion

```
no se usa

2022-01-11 19:09 UTC, plammel commented on scripts/BI-115.ts
> +import { IPrestacion } from '../modules/rup/prestaciones.interface';
updeteado!

2022-01-19 17:05 UTC, martinebucarey commented on scripts/BI-115.ts
> +import { getTurno } from 'modules/turnos/controller/agenda';
```suggestion
import { getTurno } from '../modules/turnos/controller/agenda';
```
Me dice que no lo encuentra con la ruta absoluta

2022-01-19 17:25 UTC, martinebucarey requested changes

2022-01-19 17:25 UTC, martinebucarey commented on scripts/BI-115.ts
> +                { 'sobbreturnos._id': turnoId }
Me estaba volviendo loco porque no me actualizaba los sobreturnos y mira lo que era, no se si te lo voy perdonar facilmente esto jajaja
```suggestion
                { 'sobreturnos._id': turnoId }
```

2022-01-25 17:33 UTC, martinebucarey approved these changes

2022-01-28 10:41 UTC, merged