BI: profesional validador turno
andes/api pull request #1641
Opened 2022-01-05 17:06 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/BI-117
### Funcionalidad desarrollada 

1. Al validar una prestación,  en el turno de la misma (si tiene) se guarda el id del profesional validador
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2022-01-06 13:25 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5773](http://condorpiedra.andes.gob.ar:85/5773/mochawesome.html)
CYPRESS RUN: [4696](https://dashboard.cypress.io/projects/xr7gft/runs/4696/specs)
TEST START: 2022-01-06T13:06:36.374Z
TOTAL: 404
SUCCESS: 376
FAIL: 27
SKIPPED: 1

2022-01-06 17:40 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5784](http://condorpiedra.andes.gob.ar:85/5784/mochawesome.html)
CYPRESS RUN: [4707](https://dashboard.cypress.io/projects/xr7gft/runs/4707/specs)
TEST START: 2022-01-06T17:40:46.473Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-18 03:37 UTC, silviroa requested changes
- debería agregarse el mismo dato en los sobreturnos

2022-01-19 16:50 UTC, martinebucarey approved these changes

2022-01-19 16:51 UTC, martinebucarey commented
> * debería agregarse el mismo dato en los sobreturnos

Si no me equivoco el fin  `findByTurnoId` busca turnos y sobreturnos (@plammel ), de todas formas hice la prueba con un sobreturno y me lo guardo bien.

2022-01-20 11:43 UTC, silviroa approved these changes

2022-01-20 11:44 UTC, silviroa commented
> > * debería agregarse el mismo dato en los sobreturnos
> 
> Si no me equivoco el fin `findByTurnoId` busca turnos y sobreturnos (@plammel ), de todas formas hice la prueba con un sobreturno y me lo guardo bien.

- Tenés razon

2022-01-20 11:47 UTC, liquid36 approved these changes

2022-01-20 17:39 UTC, merged