CIT - verificar solapamiento al clonar agendas
andes/api pull request #1646
Opened 2022-01-07 17:47 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-158

### Funcionalidad desarrollada 
1. Verificamos si al momento de clonar una agenda ya existe una con el mismo profesional o espacio físico para que, en caso afirmativo, se imprima un mensaje de error. En caso contrario se clona la agenda con éxito. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-01-07 18:18 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5791](http://condorpiedra.andes.gob.ar:85/5791/mochawesome.html)
CYPRESS RUN: [4714](https://dashboard.cypress.io/projects/xr7gft/runs/4714/specs)
TEST START: 2022-01-07T18:08:38.598Z
TOTAL: 336
SUCCESS: 328
FAIL: 7
SKIPPED: 1

2022-01-07 18:41 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5793](http://condorpiedra.andes.gob.ar:85/5793/mochawesome.html)
CYPRESS RUN: [4716](https://dashboard.cypress.io/projects/xr7gft/runs/4716/specs)
TEST START: 2022-01-07T18:40:59.257Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-11 13:18 UTC, martinebucarey commented on modules/turnos/routes/agenda.ts
> -    }
Esto por que se elimino?? me parece que no tiene que ver con este PR

2022-01-11 14:09 UTC, martinebucarey commented on modules/turnos/routes/agenda.ts
> +                    break;
este break; ?? porque se agrego??

2022-01-11 14:18 UTC, MarianoCampetella commented on modules/turnos/routes/agenda.ts
> +                    break;
El break se agrego por el hecho de que si existe al menos una agenda solapada no siga buscando dentro del bucle con el resto de las agendas.

2022-01-14 12:29 UTC, liquid36 commented on modules/turnos/routes/agenda.ts
> -    }
Esto es algo de San Juan que nunca arreglaron y se le estaba rompiendo el server por una query destructiva. Así que pusimos un return adelante para que no les estallé la cabeza. No habría que borrarlo.

2022-01-19 15:47 UTC, plammel requested changes

2022-01-19 15:47 UTC, plammel commented on modules/turnos/controller/agenda.ts
> +import * as agendaCtrl from '../controller/agenda';
Atención acá: Primeramente, como buena práctica, importamos solo las funciones que vamos a usar del controlador, en lugar de traernos todo innecesariamente.
Segunda, fijate que el controllador se está auto importando, el import está demás
```suggestion
```

2022-01-19 15:47 UTC, plammel commented on modules/turnos/routes/agenda.ts
> +router.post('/agenda/:idAgenda/clonar', async (req, res, next) => {
Cuidado con este cambio de ruta: este PR tendría que estar asociado a otro PR de la app donde se cambie el path del request que está consumiendo este endpoint.

2022-01-21 16:17 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5837](http://condorpiedra.andes.gob.ar:85/5837/mochawesome.html)
CYPRESS RUN: [4756](https://dashboard.cypress.io/projects/xr7gft/runs/4756/specs)
TEST START: 2022-01-21T16:03:36.026Z
TOTAL: 404
SUCCESS: 378
FAIL: 25
SKIPPED: 1

2022-01-21 17:26 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5838](http://condorpiedra.andes.gob.ar:85/5838/mochawesome.html)
CYPRESS RUN: [4757](https://dashboard.cypress.io/projects/xr7gft/runs/4757/specs)
TEST START: 2022-01-21T17:25:52.107Z
TOTAL: 386
SUCCESS: 382
FAIL: 3
SKIPPED: 1

2022-01-21 17:49 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5839](http://condorpiedra.andes.gob.ar:85/5839/mochawesome.html)
CYPRESS RUN: [4758](https://dashboard.cypress.io/projects/xr7gft/runs/4758/specs)
TEST START: 2022-01-21T17:49:12.205Z
TOTAL: 336
SUCCESS: 331
FAIL: 4
SKIPPED: 1

2022-01-24 14:02 UTC, MarianoCampetella commented on modules/turnos/controller/agenda.ts
> +import * as agendaCtrl from '../controller/agenda';
Con la nueva refactorización que hizo Mariam, eso ya fue eliminado.

2022-01-25 15:45 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5846](http://condorpiedra.andes.gob.ar:85/5846/mochawesome.html)
CYPRESS RUN: [4765](https://dashboard.cypress.io/projects/xr7gft/runs/4765/specs)
TEST START: 2022-01-25T15:45:15.043Z
TOTAL: 404
SUCCESS: 401
FAIL: 2
SKIPPED: 1

2022-01-25 16:31 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [5847](http://condorpiedra.andes.gob.ar:85/5847/mochawesome.html)
CYPRESS RUN: [4766](https://dashboard.cypress.io/projects/xr7gft/runs/4766/specs)
TEST START: 2022-01-25T16:31:05.224Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-02-01 14:28 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5881](http://condorpiedra.andes.gob.ar:85/5881/mochawesome.html)
CYPRESS RUN: [4799](https://dashboard.cypress.io/projects/xr7gft/runs/4799/specs)
TEST START: 2022-02-01T14:28:01.935Z
TOTAL: 325
SUCCESS: 299
FAIL: 25
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-02-01 14:49 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5882](http://condorpiedra.andes.gob.ar:85/5882/mochawesome.html)
CYPRESS RUN: [4800](https://dashboard.cypress.io/projects/xr7gft/runs/4800/specs)
TEST START: 2022-02-01T14:48:46.634Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-02-01 15:09 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5883](http://condorpiedra.andes.gob.ar:85/5883/mochawesome.html)
CYPRESS RUN: [4801](https://dashboard.cypress.io/projects/xr7gft/runs/4801/specs)
TEST START: 2022-02-01T15:09:05.289Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-02-01 17:18 UTC, martinebucarey approved these changes

2022-02-01 17:18 UTC, merged