EP: ignore ultimo estado fallecido
andes/api pull request #1647
Opened 2022-01-11 18:35 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/EP-175
### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2022-01-11 19:02 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5810](http://condorpiedra.andes.gob.ar:85/5810/mochawesome.html)
CYPRESS RUN: [4733](https://dashboard.cypress.io/projects/xr7gft/runs/4733/specs)
TEST START: 2022-01-11T19:01:47.777Z
TOTAL: 337
SUCCESS: 323
FAIL: 13
SKIPPED: 1

2022-01-18 13:05 UTC, martinebucarey requested changes
Hice varias pruebas y pareciera funcionar joya, queda arreglar el tema del circle.

2022-01-20 16:59 UTC, liquid36 commented
USUARIO: plammel  
BUILD NUMBER: [5835](http://condorpiedra.andes.gob.ar:85/5835/mochawesome.html)
CYPRESS RUN: [4754](https://dashboard.cypress.io/projects/xr7gft/runs/4754/specs)
TEST START: 2022-01-20T16:59:37.832Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-25 18:15 UTC, martinebucarey approved these changes

2022-01-25 18:18 UTC, merged