CIT - Descarga del csv del listado de pacientes en turnos y prestaciones
andes/api pull request #1651
Opened 2022-01-26 11:35 UTC by MarianoCampetella

…prestaciones

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-147

### Funcionalidad desarrollada 
1. Se genera una nueva ruta donde se arma el csv previo a ser descargado. Se implementa una nueva función "obtenerProfesionales" para obtener todos los profesionales de forma ordenada en un string.

### UserStories llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

2022-01-26 12:28 UTC, liquid36 requested changes
Dos cosas macros a tener en cuenta: 

1. Si dos usuarios al mismo tiempo descarcan un CSV, uno esta pisando al otro. Porque le nombre del archivo temporal es el mismo. Esto se soluciona facilmente evitando escribir en disco (operación lenta) y usando los stream de Node.Js en memoría. Te paso un ejemplo de como se usa en BiQuery : https://github.com/andes/andesMicroservices/blob/17d3a6a50fe9c88b50cd29ae148f0d3f17ef107a/bi-queries/index.ts#L111

2. Esta mal que el resultado venga en el body, debería ejecutarse toda la consulta que se realiza en el buscador de turnos y prestación sin la paginación. La misma API debe calcular todo el listado de nuevo pero en vez de pasarlo en formato JSON lo envía en CSV.

2022-01-26 18:12 UTC, MarianoCampetella commented
> Dos cosas macros a tener en cuenta:
> 
> 1. Si dos usuarios al mismo tiempo descarcan un CSV, uno esta pisando al otro. Porque le nombre del archivo temporal es el mismo. Esto se soluciona facilmente evitando escribir en disco (operación lenta) y usando los stream de Node.Js en memoría. Te paso un ejemplo de como se usa en BiQuery : https://github.com/andes/andesMicroservices/blob/17d3a6a50fe9c88b50cd29ae148f0d3f17ef107a/bi-queries/index.ts#L111
> 2. Esta mal que el resultado venga en el body, debería ejecutarse toda la consulta que se realiza en el buscador de turnos y prestación sin la paginación. La misma API debe calcular todo el listado de nuevo pero en vez de pasarlo en formato JSON lo envía en CSV.

Se corrigieron ambos puntos!

2022-01-26 18:32 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5852](http://condorpiedra.andes.gob.ar:85/5852/mochawesome.html)
CYPRESS RUN: [4770](https://dashboard.cypress.io/projects/xr7gft/runs/4770/specs)
TEST START: 2022-01-26T18:32:33.271Z
TOTAL: 404
SUCCESS: 392
FAIL: 11
SKIPPED: 1

2022-01-26 18:43 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5853](http://condorpiedra.andes.gob.ar:85/5853/mochawesome.html)
CYPRESS RUN: [4771](https://dashboard.cypress.io/projects/xr7gft/runs/4771/specs)
TEST START: 2022-01-26T18:43:43.946Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-27 14:33 UTC, liquid36 commented on modules/estadistica/routes/turnos_prestaciones.ts
> +                        Fecha: (row.fecha) ? moment(row.fecha).format('DD-MM-YYYY') : '',
Es un detalle, pero de esta forma se puede ordenar la columna.
```suggestion
                        Fecha: (row.fecha) ? moment(row.fecha).format('YYYY-MM-DD') : '',
```

2022-01-27 15:41 UTC, MarianoCampetella commented on modules/estadistica/routes/turnos_prestaciones.ts
> +                        Financiador: (row.paciente.obraSocial) ? row.paciente.obraSocial.nombre : 'No posee'
Se agrego la columna de ámbito!!

2022-02-01 12:42 UTC, martinebucarey approved these changes

2022-02-01 17:30 UTC, merged