Epidemiologia - Pantalla de consulta para certificados de aislamiento #2574
andes/api pull request #1652
Opened 2022-01-26 14:13 UTC by martinebucarey

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-183

### Funcionalidad desarrollada 

1. Se agrega ruta que consulta si existe un certificado de aislamiento para un paciente. 

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2022-01-26 14:26 UTC, liquid36 commented
USUARIO: martinebucarey  
BUILD NUMBER: [5851](http://condorpiedra.andes.gob.ar:85/5851/mochawesome.html)
CYPRESS RUN: [4769](https://dashboard.cypress.io/projects/xr7gft/runs/4769/specs)
TEST START: 2022-01-26T14:26:28.249Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-01-27 11:54 UTC, liquid36 requested changes

2022-01-27 11:54 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +    };
Este find no va a caminar. Primero habría que buscar el paciente y luego ir por pacienteID a buscar las prestaciones. De paso se valida la identidad del paciente.

2022-01-27 14:08 UTC, martinebucarey commented on modules/validar-certificado/routes/validar-certificado.ts
> +    };
Si, tenes razon , actualizado

2022-02-01 18:33 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +        'paciente.sexo': sexo
no es necesario

2022-02-01 18:33 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +        return res.send(false);
```suggestion
        return next('paciente_invalido');
```

2022-02-01 18:33 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +        'estadoActual.createdAt': fechaCondicion,
faltaría revisar que el estadoActual sea validado.

2022-02-01 18:33 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +        return res.send(false);
```suggestion
        return next('certificado_invalido');
```

2022-02-01 18:33 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +        return res.send(registroCertificado);
```suggestion
        return res.json(true);
```

o

```suggestion
        return res.json({ status: true });
```
(chamuyo)

2022-02-02 12:32 UTC, martinebucarey commented on modules/validar-certificado/routes/validar-certificado.ts
> +        return res.send(registroCertificado);
En este caso el registroCertificado es el booleano que me dice si en la prestacion esta el registro. Por lo que debería mandar true o false en caso de encontrarlo o no, no siempre es true

2022-02-02 13:33 UTC, liquid36 commented on modules/validar-certificado/routes/validar-certificado.ts
> +        return res.send(registroCertificado);
Si, esta bien. Yo seguiria el estandar HTML. Status code 400 en caso de que no sea valido y status code 200 para cuando sea valido. Siempre devolviendo un json como respuesta.

2022-02-02 14:06 UTC, martinebucarey commented on modules/validar-certificado/routes/validar-certificado.ts
> +        'estadoActual.createdAt': fechaCondicion,
Pequeño detalle me había olvidado. hecho

2022-02-02 14:06 UTC, martinebucarey commented on modules/validar-certificado/routes/validar-certificado.ts
> +        return res.send(registroCertificado);
Ahora si nos entendemos, actualizado,

2022-02-03 13:27 UTC, liquid36 approved these changes

2022-02-03 15:56 UTC, merged