fix(GDU): se redefine post para evitar crear duplicados
andes/api pull request #1654
Opened 2022-01-31 11:20 UTC by MCele

### Requerimiento

Se redefine post en Gestor de Usuarios para evitar crear duplicados

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-01-31 15:10 UTC, liquid36 requested changes
No es necesario redefinir todo el POST, hay que agregar la restricón de que si el documento ya existe no se puede volver a crear.

1. Convertir todos los documentos de int a string. No solo  el del GLPI
2. Revisar porque se crearon usuarios con documentos como int. 
3. Agregar una restricción de que el documento no pueda duplicarse. Todo lo demás sigue como están.

Query para actualizar documentos: 

```
db.getCollection('authUsers').updateMany(
{   documento:{$type:'number'} },
[{ $set: { documento: { $toString:"$documento" }} } ]  
)
```

Quedo corregido en demo.

2022-02-08 18:41 UTC, MCele commented on modules/gestor-usuarios/usuarios.routes.ts
> +        post: async (req, res, next) => {
1. es verdad, se me chispotió el filtro por usuario, ya lo corregí.

2022-02-16 11:26 UTC, martinebucarey approved these changes

2022-02-16 11:26 UTC, martinebucarey commented on modules/gestor-usuarios/usuarios.routes.ts
> +
De mañas no mas, podríamos eliminar estos espacios??

2022-02-16 11:31 UTC, liquid36 commented on modules/gestor-usuarios/usuarios.routes.ts
> +
:laughing:

2022-02-18 13:42 UTC, liquid36 approved these changes

2022-02-21 14:02 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5962](http://condorpiedra.andes.gob.ar:85/5962/mochawesome.html)
CYPRESS RUN: [4879](https://dashboard.cypress.io/projects/xr7gft/runs/4879/specs)
TEST START: 2022-02-21T14:01:48.303Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-02-21 15:22 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5965](http://condorpiedra.andes.gob.ar:85/5965/mochawesome.html)
CYPRESS RUN: [4882](https://dashboard.cypress.io/projects/xr7gft/runs/4882/specs)
TEST START: 2022-02-21T15:18:32.151Z
TOTAL: 320
SUCCESS: 303
FAIL: 16
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-02-21 16:46 UTC, liquid36 commented
USUARIO: cramos  
BUILD NUMBER: [5966](http://condorpiedra.andes.gob.ar:85/5966/mochawesome.html)
CYPRESS RUN: [4883](https://dashboard.cypress.io/projects/xr7gft/runs/4883/specs)
TEST START: 2022-02-21T16:46:28.751Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-02-24 12:41 UTC, merged