TOP - Agenda suspendida
andes/api pull request #1655
Opened 2022-02-03 15:50 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/TOP-122

### Funcionalidad desarrollada 
1. Se agrego el id del turno suspendido para obtener la prestacion y reasignarle el turno correspondiente y generar un nuevo historial.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-02-03 16:04 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5889](http://condorpiedra.andes.gob.ar:85/5889/mochawesome.html)
CYPRESS RUN: [4807](https://dashboard.cypress.io/projects/xr7gft/runs/4807/specs)
TEST START: 2022-02-03T16:04:12.520Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-02-04 13:10 UTC, martinebucarey requested changes

2022-02-04 13:10 UTC, martinebucarey commented on modules/rup/controllers/prestacion.ts
> +    if (observaciones) {
Este if se repite arriba

2022-02-04 13:56 UTC, MarianoCampetella commented on modules/rup/controllers/prestacion.ts
> +    if (observaciones) {
Corregido

2022-02-07 18:53 UTC, palita1991 requested changes
@MarianoCampetella te dejo un vídeo en donde se puede visualizar el caso en que puede ser el encarcado/a del modulo de top tenga abierto el listado esta viendo la solicitud en estado pendiente mientras que en el modulo de citas se suspendió la agenda y se reasigno el turno a otra agenda. Si el encargo/a del módulo de top no recarga la pagina, le puede dar turno sin problemas y sucede el mis bug. Se debería chequear desde top si el paciente ya tiene un turno y que no te deje sacar otro. 

https://www.loom.com/share/35c34cc562dd4e7c90570154036c02c0

2022-02-11 15:51 UTC, palita1991 approved these changes

2022-02-23 14:36 UTC, martinebucarey approved these changes

2022-02-24 13:02 UTC, merged