IN - Descarga de censos en csv
andes/api pull request #1660
Opened 2022-02-11 18:07 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-342

### Funcionalidad desarrollada 

1. Nuevas rutas para daescarga de los censos en csv

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-02-11 18:23 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5911](http://condorpiedra.andes.gob.ar:85/5911/mochawesome.html)
CYPRESS RUN: [4829](https://dashboard.cypress.io/projects/xr7gft/runs/4829/specs)
TEST START: 2022-02-11T18:23:13.221Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2022-02-15 12:19 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5919](http://condorpiedra.andes.gob.ar:85/5919/mochawesome.html)
CYPRESS RUN: [4837](https://dashboard.cypress.io/projects/xr7gft/runs/4837/specs)
TEST START: 2022-02-15T12:18:53.323Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-02-16 14:01 UTC, liquid36 requested changes

2022-02-16 14:01 UTC, liquid36 commented on modules/rup/internacion/censo.routes.ts
> +                Fecha: row.fecha ? moment(row.fecha).format('DD/MM/YYYY hh:mm') : 'TOTALES',
No tiene sentido la hora, la fecha va en formato ingles así se puede ordenar en el csv. 
```suggestion
                Fecha: row.fecha ? moment(row.fecha).format('YYYY-MM-DD') : 'TOTALES',
```

2022-03-29 12:36 UTC, plammel commented on modules/rup/internacion/censo.routes.ts
> +                        if (censoDiario.length > 0 &&
Es bastante confusa esta anidación de ifs... evalúa varias condiciones pero en la mayoría de los casos termina haciendo lo mismo, pusheando al array de censoDiario.
En el caso de este if, una movimiento de "paseA" se considera un dato la útima entrada, y no una entrada en si misma?

2022-04-05 17:06 UTC, martinebucarey commented
Revisar comentarios para subir PR

2022-04-13 14:10 UTC, merged