EP - Permitir descarga de un csv con reporte de seguimientos
andes/api pull request #1666
Opened 2022-02-22 16:39 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-193

### Funcionalidad desarrollada 

1. Nueva ruta en recurso de seguimiento de pacientes para descargar listado por csv

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X ] No

2022-02-22 16:57 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5970](http://condorpiedra.andes.gob.ar:85/5970/mochawesome.html)
CYPRESS RUN: [4887](https://dashboard.cypress.io/projects/xr7gft/runs/4887/specs)
TEST START: 2022-02-22T16:48:31.338Z
TOTAL: 381
SUCCESS: 373
FAIL: 7
SKIPPED: 1

2022-02-22 17:08 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5971](http://condorpiedra.andes.gob.ar:85/5971/mochawesome.html)
CYPRESS RUN: [4888](https://dashboard.cypress.io/projects/xr7gft/runs/4888/specs)
TEST START: 2022-02-22T17:08:09.510Z
TOTAL: 263
SUCCESS: 237
FAIL: 26
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-02-22 17:21 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5972](http://condorpiedra.andes.gob.ar:85/5972/mochawesome.html)
CYPRESS RUN: [4889](https://dashboard.cypress.io/projects/xr7gft/runs/4889/specs)
TEST START: 2022-02-22T17:21:29.754Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-02-23 11:51 UTC, liquid36 commented on modules/seguimiento-paciente/seguimiento-paciente.route.ts
> +const getListadoCsv = async (req, res, next) => {
Si, esto se viene para muchas apis, estaría piola estandarizar algunas cosas.

2022-02-23 13:46 UTC, plammel requested changes

2022-02-23 13:46 UTC, plammel commented on modules/seguimiento-paciente/seguimiento-paciente.route.ts
> +            const ultimoEstado = row.ultimoEstado ? `${row.ultimoEstado?.clave} | ${moment(row.ultimoEstado.valor).format('DD/MM/YYYY hh:mm')}` : '';
mostraría la fecha del estado en otra columna **"Fecha de Estado"** separado del valor de **"Estado"**, así es posible filtrar las filas por estado.
![image](https://user-images.githubusercontent.com/25707055/155331572-f34d3db1-8e64-452e-a4e6-359e87b4159a.png)

2022-03-29 12:45 UTC, plammel commented on modules/seguimiento-paciente/seguimiento-paciente.route.ts
> +            const ultimoEstado = row.ultimoEstado ? `${row.ultimoEstado?.clave} | ${moment(row.ultimoEstado.valor).format('DD/MM/YYYY hh:mm')}` : '';
Adicionalmente, cambiaría el formato de la fecha a `YYYY-MM-DD`

2022-03-31 18:10 UTC, plammel approved these changes

2022-04-12 14:58 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6210](http://condorpiedra.andes.gob.ar:85/6210/mochawesome.html)
CYPRESS RUN: [5105](https://dashboard.cypress.io/projects/xr7gft/runs/5105/specs)
TEST START: 2022-04-12T14:58:27.857Z
TOTAL: 388
SUCCESS: 386
FAIL: 1
SKIPPED: 1

2022-04-13 14:27 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6216](http://condorpiedra.andes.gob.ar:85/6216/mochawesome.html)
CYPRESS RUN: [5111](https://dashboard.cypress.io/projects/xr7gft/runs/5111/specs)
TEST START: 2022-04-13T14:27:04.324Z
TOTAL: 404
SUCCESS: 394
FAIL: 9
SKIPPED: 1

2022-04-13 15:19 UTC, merged