MAT(Fix) - Se crean profesionales duplicados
andes/api pull request #1670
Opened 2022-03-07 20:45 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-93

### Funcionalidad desarrollada 

1. Refactor de las funciones de guardado de profesional
2. Se aplica libreria rxjs

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-03-07 21:02 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6038](http://condorpiedra.andes.gob.ar:85/6038/mochawesome.html)
CYPRESS RUN: [4949](https://dashboard.cypress.io/projects/xr7gft/runs/4949/specs)
TEST START: 2022-03-07T21:01:54.591Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-03-08 11:53 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6040](http://condorpiedra.andes.gob.ar:85/6040/mochawesome.html)
CYPRESS RUN: [4951](https://dashboard.cypress.io/projects/xr7gft/runs/4951/specs)
TEST START: 2022-03-08T11:53:32.209Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-18 13:20 UTC, martinebucarey approved these changes

2022-03-31 18:12 UTC, plammel approved these changes

2022-07-14 16:42 UTC, plammel requested changes

2022-07-14 16:42 UTC, plammel commented on core/tm/routes/profesional.ts
> +        throw 'Error matching requiere documento y sexo';
Ojo acá q se está lanzando una excepción sin handlear y no se está dando respuesta al request
```suggestion
        return next('Error matching requiere documento y sexo');
```

2022-07-15 15:38 UTC, negro89 commented on core/tm/routes/profesional.ts
> +        throw 'Error matching requiere documento y sexo';
Corregidooo

2022-07-22 16:41 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [7088](http://condorpiedra.andes.gob.ar:85/7088/mochawesome.html)
CYPRESS RUN: [5875](https://dashboard.cypress.io/projects/xr7gft/runs/5875/specs)
TEST START: 2022-07-22T16:41:21.968Z
TOTAL: 391
SUCCESS: 389
FAIL: 1
SKIPPED: 1

2022-07-22 16:55 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [7089](http://condorpiedra.andes.gob.ar:85/7089/mochawesome.html)
CYPRESS RUN: [5876](https://dashboard.cypress.io/projects/xr7gft/runs/5876/specs)
TEST START: 2022-07-22T16:55:04.310Z
TOTAL: 409
SUCCESS: 407
FAIL: 1
SKIPPED: 1

2022-07-22 17:39 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [7091](http://condorpiedra.andes.gob.ar:85/7091/mochawesome.html)
CYPRESS RUN: [5878](https://dashboard.cypress.io/projects/xr7gft/runs/5878/specs)
TEST START: 2022-07-22T17:39:03.570Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-07-25 15:51 UTC, MCele commented
al agregar el matching con sexo considerar que los datos de ese campo pueden variar entre mayúsculas y minusculas. Se encontraron en ese campo los siguientes string: "Femenino", "femenino", "masculino", "Masculino"

2022-07-25 16:15 UTC, MCele commented
Al cargar un profesional que ya existe (igual dni y sexo) aparece un modal indicando si se desea reemplazarlo, si se le da cancelar, genera un error en la consola
![image](https://user-images.githubusercontent.com/19591224/180825744-770abbe8-c622-4f98-9966-69edf1724b78.png)

2022-08-12 15:09 UTC, plammel requested changes

2022-08-12 15:09 UTC, plammel commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +import * as moment from 'moment';
```suggestion
```

2022-08-12 15:09 UTC, plammel commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +            return next('error-turno');
Este mensaje se va a mostrar al usuario en la aplicación si falla el request. colocar un mensaje más descriptivo

2022-08-12 15:12 UTC, negro89 commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +import * as moment from 'moment';
cual seria el cambio aca??

2022-08-12 15:31 UTC, negro89 commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +            return next('error-turno');
Este error es un caso particular, ya que solo se produce cuando hay un registro preexistente para el profesional. El problema es que esta respuesta se utiliza como insumo para otro request a la api (Juntos conforman la accion de sacar turno). Por ende, para diferenciar el origen del error se envía este mensaje, handleado desde la app, y uno distinto desde la otra ruta.
En otra tarea se realizará un refactor de esta funcionalidad.

2022-08-12 15:31 UTC, negro89 commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +import * as moment from 'moment';
corregidoo

2022-08-12 15:31 UTC, negro89 commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +    newProfesional.save(async (error) => {
no, quedó pegado de otra implementación que ya no está. Corregido!

2022-08-12 16:08 UTC, plammel approved these changes

2022-08-30 18:33 UTC, merged