MPI: atributos fechaNacimiento y activo en las relaciones de un paciente
andes/api pull request #1674
Opened 2022-03-10 12:44 UTC by MCele

### Requerimiento

https://proyectos.andes.gob.ar/browse/MPI-374

### Funcionalidad desarrollada 

1. Se agregan atributos de fechaNacimiento y activo en las relaciones de un paciente.
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [X] No

### Requiere actualizaciones en la base de datos

- [X] Si, falta script
- [ ] No

2022-03-18 14:58 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [6071](http://condorpiedra.andes.gob.ar:85/6071/mochawesome.html)
CYPRESS RUN: [4981](https://dashboard.cypress.io/projects/xr7gft/runs/4981/specs)
TEST START: 2022-03-18T14:42:05.232Z
TOTAL: 406
SUCCESS: 372
FAIL: 33
SKIPPED: 1

2022-03-18 15:37 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [6074](http://condorpiedra.andes.gob.ar:85/6074/mochawesome.html)
CYPRESS RUN: [4984](https://dashboard.cypress.io/projects/xr7gft/runs/4984/specs)
TEST START: 2022-03-18T15:37:40.577Z
TOTAL: 356
SUCCESS: 353
FAIL: 2
SKIPPED: 1

2022-03-18 17:49 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [6079](http://condorpiedra.andes.gob.ar:85/6079/mochawesome.html)
CYPRESS RUN: [4988](https://dashboard.cypress.io/projects/xr7gft/runs/4988/specs)
TEST START: 2022-03-18T17:49:36.806Z
TOTAL: 388
SUCCESS: 386
FAIL: 1
SKIPPED: 1

2022-03-21 11:59 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [6086](http://condorpiedra.andes.gob.ar:85/6086/mochawesome.html)
CYPRESS RUN: [4994](https://dashboard.cypress.io/projects/xr7gft/runs/4994/specs)
TEST START: 2022-03-21T11:59:10.092Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-31 13:58 UTC, martinebucarey requested changes

2022-03-31 13:58 UTC, martinebucarey commented on core-v2/mpi/jobs/updateRelacionesPacientes.ts
> +                        if (relacionado.relaciones && relacionado.relaciones.length > 0) {
```suggestion
                        if (relacionado.relaciones?.length) {
```

2022-03-31 13:58 UTC, martinebucarey commented on core-v2/mpi/jobs/updateRelacionesPacientes.ts
> +            // }
Comentario

2022-04-05 17:50 UTC, MCele commented on core-v2/mpi/jobs/updateRelacionesPacientes.ts
> +                        if (relacionado.relaciones && relacionado.relaciones.length > 0) {
corregido!

2022-04-05 17:50 UTC, MCele commented on core-v2/mpi/jobs/updateRelacionesPacientes.ts
> +            // }
borrado!

2022-04-07 14:35 UTC, merged