feat(GDU-42): desactivar usuarios no logueados
andes/api pull request #1678
Opened 2022-03-18 14:20 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/GDU-42

### Funcionalidad desarrollada 

1. Se creo un job para desactivar a los usuarios cuya variable lastLogin sea mayor a 3 meses

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-03-18 14:36 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6070](http://condorpiedra.andes.gob.ar:85/6070/mochawesome.html)
CYPRESS RUN: [4980](https://dashboard.cypress.io/projects/xr7gft/runs/4980/specs)
TEST START: 2022-03-18T14:35:47.985Z
TOTAL: 345
SUCCESS: 330
FAIL: 14
SKIPPED: 1

2022-03-21 18:13 UTC, MarianoCampetella commented on core/tm/controller/user.ts
> +    const usuarios: any = await AuthUsers.find({ lastLogin:{ $lte: new Date(date) } }).cursor({ batchSize: 100 });
Corregido

2022-03-22 18:22 UTC, plammel commented on core/tm/controller/user.ts
> +    for await (const user of usuarios) {
para recorrer y manipular arrays, preferentemente usar las funciones de Array https://www.w3schools.com/js/js_array_methods.asp

2022-03-22 18:24 UTC, plammel commented on core/tm/controller/user.ts
> +            { lastLogin:{ $lte: new Date(date) } },
la fecha ya fue creada, está de más el new Date. Para manejar fechas preferir usar moment

2022-03-22 18:27 UTC, plammel requested changes
El nombre correcto del archivo debería ser authUser.ts

2022-03-31 13:42 UTC, martinebucarey requested changes

2022-03-31 13:42 UTC, martinebucarey commented on core/tm/controller/authUser.ts
> +            { lastLogin:{ $lte: new Date(moment().subtract(3, 'months').format('YYYY-MM-DD')) } },
El new Date() esta de mas

2022-03-31 18:23 UTC, plammel approved these changes

2022-03-31 18:23 UTC, plammel commented on core/tm/controller/authUser.ts
> +            await AuthUsers.update(
En este caso en particular, no es necesario el await, porque no hay ninguna funcionalidad posterior que necesite estar sincronizada con el update. Por otro lado, cuando se necesita sincronizar una serie de operaciones (no dependientes entre si), lo aconsejable es pushearlas en un array y sincronizarlas usando un `Promise.all()` (más performante)

2022-04-05 17:33 UTC, martinebucarey commented
Revisar comentarios para subir PR

2022-04-07 13:52 UTC, martinebucarey approved these changes

2022-04-07 13:56 UTC, martinebucarey commented on core/tm/controller/authUser.ts
> +            await AuthUsers.update(
Por que el segundo await no actualiza correctamente?? cuando ya tiene el user no tiene que esperar a que se actualice para seguir iterando el otro

2022-04-07 17:45 UTC, MarianoCampetella commented on core/tm/controller/authUser.ts
> +            await AuthUsers.update(
Eso mismo tenia entendido. Pero cuando se lo saco directamente no me actualiza. Nose a que se deberá.

2022-04-08 14:42 UTC, liquid36 commented on core/tm/controller/authUser.ts
> +            await AuthUsers.update(
Buenas, si le sacas el await sucede que se ejecuta el `done()` antes de los `update()`. Como es un scripts, cuando se ejecuta el done se termina el proceso y ningún update se ejecuto.

Soluciones: 
- agregarle el await a cada item
- refactorizar el código con un `Promise.all()`

Buen finde!

2022-04-08 14:44 UTC, martinebucarey commented on core/tm/controller/authUser.ts
> +            await AuthUsers.update(
jajaja no lo puedo creer, te quiero mucho marian

2022-05-04 13:18 UTC, merged