RUP - Control de permisos de prestacion por conceptId
andes/api pull request #1680
Opened 2022-03-22 16:39 UTC by negro89

script para actualizar los permisos de rup en la db

### Requerimiento
https://proyectos.andes.gob.ar/browse/RUP-306

### Funcionalidad desarrollada 

1. Chequeo de permisos de prestacion por conceptId en lugar de id
2. Script para actualizar los permisos de la bd

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-03-22 17:59 UTC, plammel commented on core/tm/conceptos-turneables.routes.ts
> +        const prestacionesConceptIds = Auth.getPermissions(req, permiso);
la variable podría llamarse directamente conceptIds

2022-03-22 18:06 UTC, plammel requested changes

2022-03-22 18:06 UTC, plammel commented on scripts/permisos-to-conceptIds.ts
> +    const cursor = await AuthUsers.find({ usuario: 34377650 }).cursor({ batchSize: 100 });
Guarda el dni hardcodeado!
```suggestion
    const cursor = await AuthUsers.find({}).cursor({ batchSize: 100 });
```

2022-03-23 16:15 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6097](http://condorpiedra.andes.gob.ar:85/6097/mochawesome.html)
CYPRESS RUN: [5004](https://dashboard.cypress.io/projects/xr7gft/runs/5004/specs)
TEST START: 2022-03-23T15:54:07.430Z
TOTAL: 406
SUCCESS: 337
FAIL: 68
SKIPPED: 1

2022-03-25 17:09 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6110](http://condorpiedra.andes.gob.ar:85/6110/mochawesome.html)
CYPRESS RUN: [5015](https://dashboard.cypress.io/projects/xr7gft/runs/5015/specs)
TEST START: 2022-03-25T16:48:14.864Z
TOTAL: 406
SUCCESS: 338
FAIL: 67
SKIPPED: 1

2022-03-25 19:34 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6113](http://condorpiedra.andes.gob.ar:85/6113/mochawesome.html)
CYPRESS RUN: [5018](https://dashboard.cypress.io/projects/xr7gft/runs/5018/specs)
TEST START: 2022-03-25T19:13:58.471Z
TOTAL: 406
SUCCESS: 338
FAIL: 67
SKIPPED: 1

2022-03-30 13:45 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6148](http://condorpiedra.andes.gob.ar:85/6148/mochawesome.html)
CYPRESS RUN: [5047](https://dashboard.cypress.io/projects/xr7gft/runs/5047/specs)
TEST START: 2022-03-30T13:42:55.198Z
TOTAL: 338
SUCCESS: 309
FAIL: 28
SKIPPED: 1

2022-03-31 18:32 UTC, plammel commented on scripts/permisos-to-conceptIds.ts
> +            usuario.organizaciones.map(org => {
en estos casos que casos que hay que iterar una función sin necesidad de retornar un nuevo array, lo más adecuado sería utilizar un `forEach`

2022-04-04 12:27 UTC, plammel approved these changes

2022-04-06 19:42 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6187](http://condorpiedra.andes.gob.ar:85/6187/mochawesome.html)
CYPRESS RUN: [5083](https://dashboard.cypress.io/projects/xr7gft/runs/5083/specs)
TEST START: 2022-04-06T19:21:28.673Z
TOTAL: 406
SUCCESS: 338
FAIL: 67
SKIPPED: 1

2022-04-08 18:59 UTC, negro89 commented on scripts/permisos-to-conceptIds.ts
> +            usuario.organizaciones.map(org => {
Si, es lo que hablamos. Corregido @plammel. @martinebucarey fijate que estas de reviewer :hand_over_mouth:

2022-04-08 19:25 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6200](http://condorpiedra.andes.gob.ar:85/6200/mochawesome.html)
CYPRESS RUN: [5095](https://dashboard.cypress.io/projects/xr7gft/runs/5095/specs)
TEST START: 2022-04-08T19:16:30.569Z
TOTAL: 307
SUCCESS: 281
FAIL: 25
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-04-22 17:15 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6263](http://condorpiedra.andes.gob.ar:85/6263/mochawesome.html)
CYPRESS RUN: [5158](https://dashboard.cypress.io/projects/xr7gft/runs/5158/specs)
TEST START: 2022-04-22T17:15:18.290Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-07-13 12:08 UTC, negro89 commented
Se resuelve solo en pr de app https://github.com/andes/app/pull/2610

2022-07-13 12:08 UTC, closed without merging