MAT - Actualiza certificado de ética
andes/api pull request #1681
Opened 2022-03-23 15:17 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-92

### Funcionalidad desarrollada 

1. Se traslada la confección del documento a la api. Agregando firmas necesarias.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-03-23 15:48 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6096](http://condorpiedra.andes.gob.ar:85/6096/mochawesome.html)
CYPRESS RUN: [5003](https://dashboard.cypress.io/projects/xr7gft/runs/5003/specs)
TEST START: 2022-03-23T15:47:47.100Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-03-23 16:34 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6098](http://condorpiedra.andes.gob.ar:85/6098/mochawesome.html)
CYPRESS RUN: [5005](https://dashboard.cypress.io/projects/xr7gft/runs/5005/specs)
TEST START: 2022-03-23T16:18:36.974Z
TOTAL: 406
SUCCESS: 381
FAIL: 24
SKIPPED: 1

2022-03-25 16:41 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6109](http://condorpiedra.andes.gob.ar:85/6109/mochawesome.html)
CYPRESS RUN: [5014](https://dashboard.cypress.io/projects/xr7gft/runs/5014/specs)
TEST START: 2022-03-25T16:41:12.580Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-03-31 18:38 UTC, plammel requested changes

2022-03-31 18:38 UTC, plammel commented on modules/descargas/matriculaciones/certificado-etica-body.ts
> +                        La Dirección de Fiscalización Sanitaria de la Subsecretaría de salud de la Provincia de Neuquén, CERTIFICA que {{ profesional.apellido }},
```suggestion
                        La Dirección de Fiscalización Sanitaria de la Subsecretaría de Salud de la Provincia de Neuquén, CERTIFICA que {{ profesional.apellido }},
```

2022-03-31 18:38 UTC, plammel commented on modules/descargas/matriculaciones/certificado-etica-body.ts
> +                        EL PRESENTE CERTIFICADO TIENE VALIDEZ POR EL TERMINO DE 30(TREINTA) DIAS.
```suggestion
                        EL PRESENTE CERTIFICADO TIENE VALIDEZ POR EL TERMINO DE 30(TREINTA) DÍAS.
```

2022-04-05 17:02 UTC, martinebucarey commented
Revisar comentarios para subir PR

2022-04-18 15:46 UTC, negro89 commented on modules/descargas/matriculaciones/certificado-etica-body.ts
> +                        EL PRESENTE CERTIFICADO TIENE VALIDEZ POR EL TERMINO DE 30(TREINTA) DIAS.
En el certificado actual no se usan tildes en las mayusculas, pero ya que estamos ...ahi quedo :+1:

2022-04-22 12:23 UTC, martinebucarey approved these changes

2022-04-22 13:59 UTC, plammel reviewed
![image](https://user-images.githubusercontent.com/25707055/164726426-8b4b9c84-bf41-421b-8d97-bd598182da42.png)
El documento en lineas generales esta ok. Le haría algunas mejoras de fomato:

- Agrandar un poco los margeneres laterales
- Acomodar el header: el logo de la provincia esta un poco deformado, ver si se puede ajustar el ancho de la imagen, o si es que la imagen es asi. Texto "Provincia del Neuquén" lo centraría o entonces lo alinearía a la derecha, junto con la fecha de emisión del documento. Que opinás @AgosLizzi ?

2022-04-22 16:40 UTC, plammel approved these changes

2022-05-05 14:07 UTC, palita1991 approved these changes

2022-05-16 15:38 UTC, merged