IN (Fix) - Actualiza internación al modificar datos básicos del paciente en MPI
andes/api pull request #1683
Opened 2022-03-25 16:18 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-393

### Funcionalidad desarrollada 

1. Agrega funcion en evento update de paciente, para actualizar los datos basicos en los estados de la internacion actual (si la tuviera), resumen de internacion y prestación que contiene el informe de ingreso.

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-03-31 18:05 UTC, plammel approved these changes

2022-04-29 11:10 UTC, martinebucarey submitted a review, later dismissed

2022-04-29 11:28 UTC, martinebucarey requested changes
No me actualiza los datos cuando modifico mpi: https://www.loom.com/share/1e4906bc5e5043de92e39c0e901a58b7
Y ademas tengo que refrescar la pantalla para que el paciente detalle me aparezca modificado, entiendo que eso de todas no es tema de esta tarea

2022-05-11 14:03 UTC, negro89 commented
> No me actualiza los datos cuando modifico mpi: https://www.loom.com/share/1e4906bc5e5043de92e39c0e901a58b7 Y ademas tengo que refrescar la pantalla para que el paciente detalle me aparezca modificado, entiendo que eso de todas no es tema de esta tarea

listo @martinebucarey, se sacó el cacheo del observable de paciente en un nuevo PR de app: https://github.com/andes/app/pull/2653

2022-05-11 14:17 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6410](http://condorpiedra.andes.gob.ar:85/6410/mochawesome.html)
CYPRESS RUN: [5292](https://dashboard.cypress.io/projects/xr7gft/runs/5292/specs)
TEST START: 2022-05-11T14:17:03.607Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-12 11:54 UTC, martinebucarey approved these changes

2022-05-12 12:31 UTC, merged