IN - secciones vacias dentro del pdf de evaluacion inicial
andes/api pull request #1696
Opened 2022-04-20 13:43 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-404

### Funcionalidad desarrollada 
1. Se crea un nuevo arreglo en donde se filtran los registros que no están vacíos.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-04-20 14:13 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6244](http://condorpiedra.andes.gob.ar:85/6244/mochawesome.html)
CYPRESS RUN: [5139](https://dashboard.cypress.io/projects/xr7gft/runs/5139/specs)
TEST START: 2022-04-20T14:13:28.126Z
TOTAL: 341
SUCCESS: 329
FAIL: 11
SKIPPED: 1

2022-04-20 14:30 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6245](http://condorpiedra.andes.gob.ar:85/6245/mochawesome.html)
CYPRESS RUN: [5140](https://dashboard.cypress.io/projects/xr7gft/runs/5140/specs)
TEST START: 2022-04-20T14:30:33.866Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-04-20 17:33 UTC, martinebucarey requested changes

2022-04-20 17:33 UTC, martinebucarey commented on modules/descargas/informe-rup/informe-body.ts
> +                const arrayRegistros = registro.registros.filter(r => r.registros.length > 0);
```suggestion
                const arrayRegistros = registro.registros.filter(r => r.registros.length);
```

2022-04-21 18:17 UTC, plammel approved these changes

2022-04-21 18:33 UTC, merged