MISC - Agregar filtro por conceptos en el reporte c2
andes/api pull request #1701
Opened 2022-04-26 17:48 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-225

### Funcionalidad desarrollada 
1. Se modificaron los aggregate para que se puedan traer las agendas filtradas mediante el código.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-04-28 17:57 UTC, plammel commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +        if (params.zonaSanitaria) {
@MarianoCampetella entiendo que el `else` está ahi porq o se filtra por zona (conjunto de organizaciones) o por organización. No tiene sentido que ambos filtros se apliquen al mismo tiempo. Es correcto? Lo removiste por alguna razón?

2022-04-29 12:40 UTC, MarianoCampetella commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +        if (params.zonaSanitaria) {
Corregido. No tiene sentido que ambos filtros se apliquen al mismo tiempo.

2022-04-29 12:40 UTC, MarianoCampetella commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +            'sobreturnos.diagnostico.codificaciones.codificacionAuditoria.c2': true,
Corregido, se dejo como estaba antes ya que el cambio no fue requerido!

2022-05-03 17:50 UTC, plammel requested changes

2022-05-03 17:50 UTC, plammel commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +            'bloques.turnos.diagnostico.codificaciones.primeraVez': true,
@MarianoCampetella Faltó revertir este cambio puede ser?

2022-05-03 18:30 UTC, MarianoCampetella commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +            'bloques.turnos.diagnostico.codificaciones.primeraVez': true,
Es necesario que tanto matchAgendas como matchSobreTurnos no tengan el ... codificacion.0.... ya que estos mismos se utilizan en los $match de los respectivos pipeline. Al agregar el ... codificacion.0... va a suceder que no se va a traer todos los reportes c2 como corresponde!

2022-05-05 12:33 UTC, martinebucarey commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +                        $match: matchAgedas
Este $match: matchAgedas ( esta mal el nombre, habría que cambiarlo) ya se hace en la linea 131, porque hay que volver a hacerlo?? entiendo que para el unwind ya llegan los datos filtrados por el primer match

2022-05-05 12:33 UTC, martinebucarey commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +                         $match: matchSobreturnos
mismo comentario que para turnos

2022-05-05 17:12 UTC, MarianoCampetella commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +                        $match: matchAgedas
Este matchAgendas es una constante que se la utiliza en multiples lugares para no tener que declarar nuevas variables. Es necesario volver a hacerlo ya que en caso contrario al momento de filtrar por un codigo cie10 el resultado no va a ser el correcto.

2022-05-10 18:16 UTC, plammel requested changes

2022-05-10 18:16 UTC, plammel commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +                        $match: matchAgedas
@martinebucarey el match se vuelve aplicar para poder excluir las entradas que matchean el cie10 una vez que se aplica el unwind por codificaciones. En ese sentido está correcto volver aplicar el match. @MarianoCampetella lo que si habría que controlar hacer el unwind y aplicar nuevamente el match solo en caso de recibir el parametro para filtrar el cie10, caso contrario, es innecesario. Y corregir el nombre `matchAgedas` x `matchAgendas`

2022-05-16 14:30 UTC, plammel submitted a review, later dismissed
@MarianoCampetella fijate que los resultados sin filtro de diagnostico no estan coincidiendo con los que numeros que arroja con el filtro aplicado
https://www.loom.com/share/1889d4e194374da88f18cd6810e816a0

2022-06-09 14:12 UTC, martinebucarey commented
USUARIO: martinebucarey  
BUILD NUMBER: [6575](http://condorpiedra.andes.gob.ar:85/6575/mochawesome.html)
CYPRESS RUN: [5435](https://dashboard.cypress.io/projects/xr7gft/runs/5435/specs)
TEST START: 2022-06-09T14:11:54.403Z
TOTAL: 370
SUCCESS: 336
FAIL: 33
SKIPPED: 1

2022-06-30 12:18 UTC, MarianoCampetella commented on modules/turnos/controller/diagnosticosC2Controller.ts
> +                        $match: matchAgedas
Corregido!

2022-06-30 12:20 UTC, MarianoCampetella commented
> @MarianoCampetella fijate que los resultados sin filtro de diagnostico no estan coincidiendo con los que numeros que arroja con el filtro aplicado https://www.loom.com/share/1889d4e194374da88f18cd6810e816a0

Corregido!

2022-06-30 12:45 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6720](http://condorpiedra.andes.gob.ar:85/6720/mochawesome.html)
CYPRESS RUN: [5573](https://dashboard.cypress.io/projects/xr7gft/runs/5573/specs)
TEST START: 2022-06-30T12:45:24.548Z
TOTAL: 408
SUCCESS: 404
FAIL: 0
SKIPPED: 4

2022-07-01 13:39 UTC, martinebucarey approved these changes

2022-07-01 13:51 UTC, merged