EP: secciones precargadas
andes/api pull request #1708
Opened 2022-05-03 17:11 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/EP-206
### Funcionalidad desarrollada 

1. Secciones pre cargadas para creación de template de formulario
2. 
3. 

### UserStories llegó a completarse

- [ ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2022-05-04 13:47 UTC, martinebucarey requested changes
No estoy llegando desde la app a la ruta, creo que falta agregar el archivo del resource al initialize

![imagen](https://user-images.githubusercontent.com/56874534/166694467-bbaca8f3-8de6-4d99-923a-db237d8b498a.png)

2022-05-04 14:19 UTC, plammel commented
> No estoy llegando desde la app a la ruta, creo que falta agregar el archivo del resource al initialize
> 
> ![imagen](https://user-images.githubusercontent.com/56874534/166694467-bbaca8f3-8de6-4d99-923a-db237d8b498a.png)

updatedeado

2022-05-04 14:31 UTC, martinebucarey commented
> > No estoy llegando desde la app a la ruta, creo que falta agregar el archivo del resource al initialize
> > ![imagen](https://user-images.githubusercontent.com/56874534/166694467-bbaca8f3-8de6-4d99-923a-db237d8b498a.png)
> 
> updatedeado

Genial ahí si va piola, lo único que hay que modificar en el documento es el campo funcionusuario, que no sea de tipo dependencia sino que sea de tipo selectStatic:
```

{
            "_id" : ObjectId("601061b07406db28e08b2139"),
            "key" : "funcionusuario",
            "label" : "función dentro del sistema",
            "type" : "selectStatic",
            "description" : "",
            "required" : true,
            "subfilter" : false,
            "resources" : "",
            "preload" : false,
            "items" : [ 
                {
                    "id" : "tecnico",
                    "nombre" : "Técnico/Auxiliar con función asistencial"
                }, 
                {
                    "id" : "profesional",
                    "nombre" : "Profesional con función asistencial"
                }, 
                {
                    "id" : "noAsistencial",
                    "nombre" : "Profesional con función no asistencial"
                }, 
                {
                    "id" : "admin",
                    "nombre" : "Trabajador de la salud con función administrativa"
                }
            ]
        }
```

2022-05-04 14:32 UTC, martinebucarey approved these changes

2022-05-05 11:26 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6367](http://condorpiedra.andes.gob.ar:85/6367/mochawesome.html)
CYPRESS RUN: [5252](https://dashboard.cypress.io/projects/xr7gft/runs/5252/specs)
TEST START: 2022-05-05T11:25:44.876Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-05 12:09 UTC, merged