GDU - Quitar permisos en punto de incio internacion
andes/api pull request #1709
Opened 2022-05-05 18:18 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/GDU-47

### Funcionalidad desarrollada 

1. Se desarrollo un script para quitar permisos del punto de inicio de internación en todos los usuarios

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-05-05 18:37 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6380](http://condorpiedra.andes.gob.ar:85/6380/mochawesome.html)
CYPRESS RUN: [5265](https://dashboard.cypress.io/projects/xr7gft/runs/5265/specs)
TEST START: 2022-05-05T18:36:47.341Z
TOTAL: 358
SUCCESS: 345
FAIL: 12
SKIPPED: 1

2022-05-05 18:52 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6381](http://condorpiedra.andes.gob.ar:85/6381/mochawesome.html)
CYPRESS RUN: [5266](https://dashboard.cypress.io/projects/xr7gft/runs/5266/specs)
TEST START: 2022-05-05T18:51:58.737Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-09 17:56 UTC, plammel approved these changes

2022-05-10 17:24 UTC, martinebucarey requested changes

2022-05-10 17:24 UTC, martinebucarey commented on scripts/GDU-47.ts
> +        await AuthUsers.update({ _id: usuario._id }, { $set: { organizaciones: usuario.organizaciones } });
Usar promisseAll para estos casos https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2022-05-10 18:45 UTC, MarianoCampetella commented on scripts/GDU-47.ts
> +        await AuthUsers.update({ _id: usuario._id }, { $set: { organizaciones: usuario.organizaciones } });
Corregido!

2022-05-27 12:10 UTC, martinebucarey commented
@MarianoCampetella si bien no era un requerimiento se charlo antes de subirlo y lo mejor es obviar al castro rendon en la quita de permisos, asi que estaria bueno agregar esto al script

2022-05-27 18:58 UTC, MarianoCampetella commented
> @MarianoCampetella si bien no era un requerimiento se charlo antes de subirlo y lo mejor es obviar al castro rendon en la quita de permisos, asi que estaria bueno agregar esto al script

Corregido. Se quitan los permisos de internacion salvo los de la organizacion Castro Rendom

2022-06-07 12:29 UTC, martinebucarey commented
Ya se corrio

2022-06-07 12:29 UTC, closed without merging