MISC - Agregar alias y documento extranjero a datos de paciente
andes/api pull request #1715
Opened 2022-05-31 14:22 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-226

### Funcionalidad desarrollada 

1. Se completa subesquema de paciente preexistente para su reutilización en esquemas que guardan un set de datos reducidos del paciente. De manera que cada recurso nuevo que lo requiera, utilice este subesquema y de ser necesario le agregue atributos en la seccion 'extras'. 
Todo esto a modo de no perder información del alias, genero y numero de identificacion extranjera que por lo general no se tienen en cuenta.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-05-31 14:55 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6528](http://condorpiedra.andes.gob.ar:85/6528/mochawesome.html)
CYPRESS RUN: [5409](https://dashboard.cypress.io/projects/xr7gft/runs/5409/specs)
TEST START: 2022-05-31T14:55:21.969Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-05-31 15:22 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6529](http://condorpiedra.andes.gob.ar:85/6529/mochawesome.html)
CYPRESS RUN: [5410](https://dashboard.cypress.io/projects/xr7gft/runs/5410/specs)
TEST START: 2022-05-31T15:21:58.216Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

2022-06-01 14:22 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6533](http://condorpiedra.andes.gob.ar:85/6533/mochawesome.html)
CYPRESS RUN: [5414](https://dashboard.cypress.io/projects/xr7gft/runs/5414/specs)
TEST START: 2022-06-01T14:21:56.474Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

2022-06-01 15:44 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6538](http://condorpiedra.andes.gob.ar:85/6538/mochawesome.html)
CYPRESS RUN: [5419](https://dashboard.cypress.io/projects/xr7gft/runs/5419/specs)
TEST START: 2022-06-01T15:44:20.433Z
TOTAL: 356
SUCCESS: 346
FAIL: 9
SKIPPED: 1

2022-07-06 17:06 UTC, AgosLizzi requested changes
Sobre el detalle de los paciente fuera de agenda, sigue apareciendo el nombre con el cual se registró
![detalle](https://user-images.githubusercontent.com/72876985/177604516-3d7fab7e-dada-4ef5-bdb3-e295fc4d0ba4.JPG)
![autopercibido](https://user-images.githubusercontent.com/72876985/177604532-5a445890-fb3d-4cf4-85c3-4a7e9e3b44be.JPG)

2022-07-20 18:38 UTC, AgosLizzi approved these changes

2022-07-25 15:32 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7112](http://condorpiedra.andes.gob.ar:85/7112/mochawesome.html)
CYPRESS RUN: [5899](https://dashboard.cypress.io/projects/xr7gft/runs/5899/specs)
TEST START: 2022-07-25T15:32:20.922Z
TOTAL: 409
SUCCESS: 399
FAIL: 9
SKIPPED: 1

2022-08-10 17:39 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7394](http://condorpiedra.andes.gob.ar:85/7394/mochawesome.html)
CYPRESS RUN: [6140](https://dashboard.cypress.io/projects/xr7gft/runs/6140/specs)
TEST START: 2022-08-10T17:39:08.994Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

2022-08-12 16:50 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7414](http://condorpiedra.andes.gob.ar:85/7414/mochawesome.html)
CYPRESS RUN: [6167](https://dashboard.cypress.io/projects/xr7gft/runs/6167/specs)
TEST START: 2022-08-12T16:49:49.323Z
TOTAL: 406
SUCCESS: 399
FAIL: 6
SKIPPED: 1

2022-08-17 12:41 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7429](http://condorpiedra.andes.gob.ar:85/7429/mochawesome.html)
CYPRESS RUN: [6222](https://dashboard.cypress.io/projects/xr7gft/runs/6222/specs)
TEST START: 2022-08-17T12:40:21.359Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

2022-08-17 13:20 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7432](http://condorpiedra.andes.gob.ar:85/7432/mochawesome.html)
CYPRESS RUN: [6227](https://dashboard.cypress.io/projects/xr7gft/runs/6227/specs)
TEST START: 2022-08-17T13:20:02.226Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-08-17 17:35 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7442](http://condorpiedra.andes.gob.ar:85/7442/mochawesome.html)
CYPRESS RUN: [6242](https://dashboard.cypress.io/projects/xr7gft/runs/6242/specs)
TEST START: 2022-08-17T17:35:04.622Z
TOTAL: 398
SUCCESS: 391
FAIL: 6
SKIPPED: 1

2022-08-19 19:45 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7466](http://condorpiedra.andes.gob.ar:85/7466/mochawesome.html)
CYPRESS RUN: [6272](https://dashboard.cypress.io/projects/xr7gft/runs/6272/specs)
TEST START: 2022-08-19T19:45:31.624Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

2022-08-22 20:24 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [7485](http://condorpiedra.andes.gob.ar:85/7485/mochawesome.html)
CYPRESS RUN: [6293](https://dashboard.cypress.io/projects/xr7gft/runs/6293/specs)
TEST START: 2022-08-22T20:03:00.404Z
TOTAL: 375
SUCCESS: 361
FAIL: 13
SKIPPED: 1

2022-09-05 15:03 UTC, plammel commented on modules/descargas/informe-rup/informe-header.ts
> +                alias: paciente.alias || undefined,
el sexo del paciente no debería seguir registrandose a pesar del genero?

2022-09-14 15:47 UTC, negro89 commented on modules/descargas/informe-rup/informe-header.ts
> +                alias: paciente.alias || undefined,
En los informes de rup el paciente debe ver solo su identidad de genero, ya que es un dato personal y ya no influye en procesos de salud.

2022-09-14 15:55 UTC, negro89 commented on core-v2/mpi/paciente/paciente.events.ts
> +    const idInternacionMedica = ultimoEstadoCapaMedica?.estados.find(e => {
Es cierto. En una modificacion posterior se agregó el control de la linea 122
`if (!ultimoEstadoCapaMedica) {
        return;
    }`
Despues de esto no harían falta los '?'.

2022-09-14 17:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7633](http://condorpiedra.andes.gob.ar:85/7633/mochawesome.html)
CYPRESS RUN: [6479](https://dashboard.cypress.io/projects/xr7gft/runs/6479/specs)
TEST START: 2022-09-14T17:14:09.553Z
TOTAL: 374
SUCCESS: 357
FAIL: 16
SKIPPED: 1

2022-09-22 15:26 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7681](http://condorpiedra.andes.gob.ar:85/7681/mochawesome.html)
CYPRESS RUN: [6673](https://dashboard.cypress.io/projects/xr7gft/runs/6673/specs)
TEST START: 2022-09-22T15:14:26.669Z
TOTAL: 406
SUCCESS: 362
FAIL: 43
SKIPPED: 1

2022-10-06 16:29 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7737](http://condorpiedra.andes.gob.ar:85/7737/mochawesome.html)
CYPRESS RUN: [6855](https://dashboard.cypress.io/projects/xr7gft/runs/6855/specs)
TEST START: 2022-10-06T16:29:27.658Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-10-06 17:31 UTC, MarianoCampetella approved these changes

2022-10-14 15:59 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7753](http://condorpiedra.andes.gob.ar:85/7753/mochawesome.html)
CYPRESS RUN: [6891](https://dashboard.cypress.io/projects/xr7gft/runs/6891/specs)
TEST START: 2022-10-14T15:59:13.020Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-10-14 18:56 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7758](http://condorpiedra.andes.gob.ar:85/7758/mochawesome.html)
CYPRESS RUN: [6896](https://dashboard.cypress.io/projects/xr7gft/runs/6896/specs)
TEST START: 2022-10-14T18:54:25.163Z
TOTAL: 378
SUCCESS: 363
FAIL: 14
SKIPPED: 1

2022-10-18 22:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7786](http://condorpiedra.andes.gob.ar:85/7786/mochawesome.html)
CYPRESS RUN: [6924](https://dashboard.cypress.io/projects/xr7gft/runs/6924/specs)
TEST START: 2022-10-18T22:01:06.639Z
TOTAL: 391
SUCCESS: 375
FAIL: 15
SKIPPED: 1

2022-10-24 14:45 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7838](http://condorpiedra.andes.gob.ar:85/7838/mochawesome.html)
CYPRESS RUN: [6973](https://dashboard.cypress.io/projects/xr7gft/runs/6973/specs)
TEST START: 2022-10-24T14:45:14.754Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

2022-11-11 20:12 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [7905](http://condorpiedra.andes.gob.ar:85/7905/mochawesome.html)
CYPRESS RUN: [7100](https://dashboard.cypress.io/projects/xr7gft/runs/7100/specs)
TEST START: 2022-11-11T20:12:16.807Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-11-28 19:02 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [8025](http://condorpiedra.andes.gob.ar:85/8025/mochawesome.html)
CYPRESS RUN: [7218](https://dashboard.cypress.io/projects/xr7gft/runs/7218/specs)
TEST START: 2022-11-28T19:02:01.302Z
TOTAL: 406
SUCCESS: 389
FAIL: 15
SKIPPED: 2

2022-12-02 15:05 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8063](http://condorpiedra.andes.gob.ar:85/8063/mochawesome.html)
CYPRESS RUN: [7255](https://dashboard.cypress.io/projects/xr7gft/runs/7255/specs)
TEST START: 2022-12-02T15:04:43.127Z
TOTAL: 406
SUCCESS: 393
FAIL: 11
SKIPPED: 2

2022-12-02 15:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8064](http://condorpiedra.andes.gob.ar:85/8064/mochawesome.html)
CYPRESS RUN: [7256](https://dashboard.cypress.io/projects/xr7gft/runs/7256/specs)
TEST START: 2022-12-02T15:15:44.006Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2022-12-02 16:39 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8065](http://condorpiedra.andes.gob.ar:85/8065/mochawesome.html)
CYPRESS RUN: [7257](https://dashboard.cypress.io/projects/xr7gft/runs/7257/specs)
TEST START: 2022-12-02T16:39:30.836Z
TOTAL: 406
SUCCESS: 394
FAIL: 10
SKIPPED: 2

2022-12-02 16:58 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8066](http://condorpiedra.andes.gob.ar:85/8066/mochawesome.html)
CYPRESS RUN: [7258](https://dashboard.cypress.io/projects/xr7gft/runs/7258/specs)
TEST START: 2022-12-02T16:58:01.213Z
TOTAL: 406
SUCCESS: 394
FAIL: 10
SKIPPED: 2

2022-12-02 17:11 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8067](http://condorpiedra.andes.gob.ar:85/8067/mochawesome.html)
CYPRESS RUN: [7259](https://dashboard.cypress.io/projects/xr7gft/runs/7259/specs)
TEST START: 2022-12-02T17:10:21.383Z
TOTAL: 382
SUCCESS: 362
FAIL: 18
SKIPPED: 2

2022-12-05 14:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8081](http://condorpiedra.andes.gob.ar:85/8081/mochawesome.html)
CYPRESS RUN: [7273](https://dashboard.cypress.io/projects/xr7gft/runs/7273/specs)
TEST START: 2022-12-05T14:12:45.486Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

2022-12-05 14:38 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8082](http://condorpiedra.andes.gob.ar:85/8082/mochawesome.html)
CYPRESS RUN: [7274](https://dashboard.cypress.io/projects/xr7gft/runs/7274/specs)
TEST START: 2022-12-05T14:38:24.180Z
TOTAL: 406
SUCCESS: 374
FAIL: 30
SKIPPED: 2

2022-12-05 15:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8084](http://condorpiedra.andes.gob.ar:85/8084/mochawesome.html)
CYPRESS RUN: [7276](https://dashboard.cypress.io/projects/xr7gft/runs/7276/specs)
TEST START: 2022-12-05T15:23:39.796Z
TOTAL: 333
SUCCESS: 301
FAIL: 30
SKIPPED: 2

2022-12-05 16:40 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8087](http://condorpiedra.andes.gob.ar:85/8087/mochawesome.html)
CYPRESS RUN: [7279](https://dashboard.cypress.io/projects/xr7gft/runs/7279/specs)
TEST START: 2022-12-05T16:40:30.900Z
TOTAL: 388
SUCCESS: 362
FAIL: 24
SKIPPED: 2

2023-03-21 15:51 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8608](http://condorpiedra.andes.gob.ar:85/8608/mochawesome.html)
CYPRESS RUN: [7786](https://dashboard.cypress.io/projects/xr7gft/runs/7786/specs)
TEST START: 2023-03-21T15:51:39.230Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

2023-04-13 18:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8703](http://condorpiedra.andes.gob.ar:85/8703/mochawesome.html)
CYPRESS RUN: [7878](https://dashboard.cypress.io/projects/xr7gft/runs/7878/specs)
TEST START: 2023-04-13T18:15:22.497Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

2023-04-13 19:38 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8709](http://condorpiedra.andes.gob.ar:85/8709/mochawesome.html)
CYPRESS RUN: [7884](https://dashboard.cypress.io/projects/xr7gft/runs/7884/specs)
TEST START: 2023-04-13T19:38:37.287Z
TOTAL: 372
SUCCESS: 356
FAIL: 14
SKIPPED: 2

2023-04-14 14:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8711](http://condorpiedra.andes.gob.ar:85/8711/mochawesome.html)
CYPRESS RUN: [7886](https://dashboard.cypress.io/projects/xr7gft/runs/7886/specs)
TEST START: 2023-04-14T14:02:54.490Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

2023-04-14 14:40 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8712](http://condorpiedra.andes.gob.ar:85/8712/mochawesome.html)
CYPRESS RUN: [7887](https://dashboard.cypress.io/projects/xr7gft/runs/7887/specs)
TEST START: 2023-04-14T14:18:54.136Z
TOTAL: 232
SUCCESS: 181
FAIL: 50
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-04-14 15:02 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8713](http://condorpiedra.andes.gob.ar:85/8713/mochawesome.html)
CYPRESS RUN: [7888](https://dashboard.cypress.io/projects/xr7gft/runs/7888/specs)
TEST START: 2023-04-14T15:02:24.760Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

2023-04-26 18:28 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8774](http://condorpiedra.andes.gob.ar:85/8774/mochawesome.html)
CYPRESS RUN: [7945](https://dashboard.cypress.io/projects/xr7gft/runs/7945/specs)
TEST START: 2023-04-26T18:27:10.722Z
TOTAL: 312
SUCCESS: 279
FAIL: 31
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-04-26 19:28 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8776](http://condorpiedra.andes.gob.ar:85/8776/mochawesome.html)
CYPRESS RUN: [7947](https://dashboard.cypress.io/projects/xr7gft/runs/7947/specs)
TEST START: 2023-04-26T19:27:42.211Z
TOTAL: 398
SUCCESS: 371
FAIL: 25
SKIPPED: 2

2023-04-27 16:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8788](http://condorpiedra.andes.gob.ar:85/8788/mochawesome.html)
CYPRESS RUN: [7958](https://dashboard.cypress.io/projects/xr7gft/runs/7958/specs)
TEST START: 2023-04-27T16:03:49.285Z
TOTAL: 398
SUCCESS: 367
FAIL: 29
SKIPPED: 2

2023-05-02 13:21 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8807](http://condorpiedra.andes.gob.ar:85/8807/mochawesome.html)
CYPRESS RUN: [7977](https://dashboard.cypress.io/projects/xr7gft/runs/7977/specs)
TEST START: 2023-05-02T12:59:52.285Z
TOTAL: 262
SUCCESS: 232
FAIL: 28
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-05-02 13:33 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8808](http://condorpiedra.andes.gob.ar:85/8808/mochawesome.html)
CYPRESS RUN: [7978](https://dashboard.cypress.io/projects/xr7gft/runs/7978/specs)
TEST START: 2023-05-02T13:32:56.715Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

2023-05-02 14:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8809](http://condorpiedra.andes.gob.ar:85/8809/mochawesome.html)
CYPRESS RUN: [7979](https://dashboard.cypress.io/projects/xr7gft/runs/7979/specs)
TEST START: 2023-05-02T14:14:53.036Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2023-05-02 14:28 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8810](http://condorpiedra.andes.gob.ar:85/8810/mochawesome.html)
CYPRESS RUN: [7980](https://dashboard.cypress.io/projects/xr7gft/runs/7980/specs)
TEST START: 2023-05-02T14:28:09.414Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-04 16:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8834](http://condorpiedra.andes.gob.ar:85/8834/mochawesome.html)
CYPRESS RUN: [8003](https://dashboard.cypress.io/projects/xr7gft/runs/8003/specs)
TEST START: 2023-05-04T16:47:48.625Z
TOTAL: 406
SUCCESS: 337
FAIL: 67
SKIPPED: 2

2023-05-10 16:03 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8865](http://condorpiedra.andes.gob.ar:85/8865/mochawesome.html)
CYPRESS RUN: [8032](https://dashboard.cypress.io/projects/xr7gft/runs/8032/specs)
TEST START: 2023-05-10T16:03:17.663Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

2023-05-10 17:45 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8866](http://condorpiedra.andes.gob.ar:85/8866/mochawesome.html)
CYPRESS RUN: [8033](https://dashboard.cypress.io/projects/xr7gft/runs/8033/specs)
TEST START: 2023-05-10T17:45:36.431Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-15 15:31 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8894](http://condorpiedra.andes.gob.ar:85/8894/mochawesome.html)
CYPRESS RUN: [8059](https://dashboard.cypress.io/projects/xr7gft/runs/8059/specs)
TEST START: 2023-05-15T15:30:13.035Z
TOTAL: 398
SUCCESS: 390
FAIL: 6
SKIPPED: 2

2023-05-15 16:09 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8895](http://condorpiedra.andes.gob.ar:85/8895/mochawesome.html)
CYPRESS RUN: [8060](https://dashboard.cypress.io/projects/xr7gft/runs/8060/specs)
TEST START: 2023-05-15T16:09:13.784Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-05-15 16:30 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8896](http://condorpiedra.andes.gob.ar:85/8896/mochawesome.html)
CYPRESS RUN: [8061](https://dashboard.cypress.io/projects/xr7gft/runs/8061/specs)
TEST START: 2023-05-15T16:30:03.411Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-15 16:43 UTC, merged