IN: motivo suspensión indicación
andes/api pull request #1716
Opened 2022-06-03 17:26 UTC by plammel

### Requerimiento

https://proyectos.andes.gob.ar/browse/IN-358
### Funcionalidad desarrollada 

1. Registrar motivo de suspensión de indicaciones
2. 
3. 

### UserStories llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/IN-358
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2022-06-03 17:41 UTC, martinebucarey commented
USUARIO: plammel  
BUILD NUMBER: [6549](http://condorpiedra.andes.gob.ar:85/6549/mochawesome.html)
CYPRESS RUN: [5429](https://dashboard.cypress.io/projects/xr7gft/runs/5429/specs)
TEST START: 2022-06-03T17:41:07.481Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-06-06 18:59 UTC, negro89 approved these changes

2022-06-07 12:34 UTC, negro89 approved these changes

2022-06-10 15:41 UTC, AgosLizzi commented
Cuando suspendo un medicamento, agrego motivo, el item sigue seleccionado en el listado y me deja nuevamente suspender y agregar otro motivo. Se crea un loop en el que puedo suspender y agregar motivo hasta que no deselecciono el medicamento. Bastante confuso. Aca va video de muestra:
https://www.loom.com/share/436d3ed9824c4de6a35acf31c446f62c

Sugiero que una vez que se realicé la acción de suspender, se limpie la selección.

2022-06-10 15:52 UTC, AgosLizzi requested changes
Cuando suspendo un medicamento, agrego motivo, el item sigue seleccionado en el listado y me deja nuevamente suspender y agregar otro motivo. Se crea un loop en el que puedo suspender y agregar motivo hasta que no deselecciono el medicamento. Bastante confuso. Aca va video de muestra:

https://www.loom.com/share/436d3ed9824c4de6a35acf31c446f62c

Sugiero que una vez que se realicé la acción de suspender, se limpie la selección.

2022-06-13 15:42 UTC, plammel commented
> Cuando suspendo un medicamento, agrego motivo, el item sigue seleccionado en el listado y me deja nuevamente suspender y agregar otro motivo. Se crea un loop en el que puedo suspender y agregar motivo hasta que no deselecciono el medicamento. Bastante confuso. Aca va video de muestra:
> 
> https://www.loom.com/share/436d3ed9824c4de6a35acf31c446f62c
> 
> Sugiero que una vez que se realicé la acción de suspender, se limpie la selección.

Aplicado

2022-06-16 12:31 UTC, martinebucarey approved these changes

2022-06-16 12:38 UTC, merged