MAT - Agregar campo created en BD
andes/api pull request #1742
Opened 2022-08-08 16:04 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-110

### Funcionalidad desarrollada 
1. Se agrego el plugin AuditPlugin y se agrego el .audit(...) para que se pueda crear en la BD el createdAt y el createdBy que va a contener los datos basicos de la persona que lo creo. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-08-08 16:42 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7362](http://condorpiedra.andes.gob.ar:85/7362/mochawesome.html)
CYPRESS RUN: [6109](https://dashboard.cypress.io/projects/xr7gft/runs/6109/specs)
TEST START: 2022-08-08T16:41:04.578Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-08 18:09 UTC, plammel requested changes

2022-08-08 18:09 UTC, plammel commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +    newProfesional.audit(persona);
Esto no se ve correcto. El usuario de creación tiene que ser el user del request. La manera de auditar registros es del tipo `Auth.audit(auditable, req)`.

2022-08-08 18:09 UTC, plammel commented on modules/matriculaciones/routes/turnoSolicitado.ts
>  router.post('/turnoSolicitados', async (req, res, next) => {
Aprovechar que se modifica este código para agregar seguridad a esta ruta que no está protegida.

2022-08-09 14:22 UTC, MarianoCampetella commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +    newProfesional.audit(persona);
Corregido! Con la única manera que me dejo auditar para el Auth.audit() fue con el userScheduler ya que que con el req y el req.body no me dejaba.

2022-08-09 14:24 UTC, MarianoCampetella commented on modules/matriculaciones/routes/turnoSolicitado.ts
>  router.post('/turnoSolicitados', async (req, res, next) => {
No se puede agregar el Auth.authenticate() ya que no se necesita loguearse para sacar un turno para matricularse por primera ves.

2022-08-09 15:57 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7375](http://condorpiedra.andes.gob.ar:85/7375/mochawesome.html)
CYPRESS RUN: [6121](https://dashboard.cypress.io/projects/xr7gft/runs/6121/specs)
TEST START: 2022-08-09T15:57:11.409Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-19 14:11 UTC, negro89 commented
Tiene sentido auditar en una ruta publica solo para guardar los datos del userSchedule?

2022-08-26 17:13 UTC, plammel commented on modules/matriculaciones/routes/turnoSolicitado.ts
> +    newProfesional.audit(persona);
Está bien, como en este caso no hay autenticación, no hay usuario de audit

2022-08-26 17:13 UTC, plammel approved these changes

2023-08-25 13:25 UTC, silviroa approved these changes

2023-09-05 18:43 UTC, Fabio-Ramirez commented on modules/matriculaciones/routes/turnoSolicitado.ts
>          req.body._id = profesional._id;
Simplemente aprovecharia para sugerir en la linea 12, el adicionar el signo ?, para la verificacion de profesional y asi reducir la condicion del if.

2023-09-05 18:44 UTC, Fabio-Ramirez reviewed
comento alguito.

2023-09-06 11:46 UTC, MarianoCampetella commented on modules/matriculaciones/routes/turnoSolicitado.ts
>          req.body._id = profesional._id;
Buena observación Fabi! 
Corregido!

2023-09-06 18:26 UTC, Fabio-Ramirez approved these changes

2023-10-04 15:45 UTC, merged