CIT - Guardar motivo de suspension de agenda
andes/api pull request #1743
Opened 2022-08-09 16:03 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-185

### Funcionalidad desarrollada 
1. En el esquema de Agenda se agrego el campo motivoDeSuspension para que después se pueda editar con el motivo de suspensión que se carga desde la app

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-08-09 16:41 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7376](http://condorpiedra.andes.gob.ar:85/7376/mochawesome.html)
CYPRESS RUN: [6122](https://dashboard.cypress.io/projects/xr7gft/runs/6122/specs)
TEST START: 2022-08-09T16:40:03.589Z
TOTAL: 387
SUCCESS: 375
FAIL: 11
SKIPPED: 1

2022-08-09 17:43 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7377](http://condorpiedra.andes.gob.ar:85/7377/mochawesome.html)
CYPRESS RUN: [6123](https://dashboard.cypress.io/projects/xr7gft/runs/6123/specs)
TEST START: 2022-08-09T17:42:58.471Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-11 13:31 UTC, martinebucarey requested changes

2022-08-11 13:31 UTC, martinebucarey commented on modules/turnos/controller/agenda.ts
> +        data.motivoDeSuspension = req.body.motivo;
acá entiendo que se esta guardando el motivo de suspension en todas las agendas que no son prePausada, por lo tanto en una publicada vas a guardar un motivo de suspension que no existe.

2022-08-11 14:38 UTC, MarianoCampetella commented on modules/turnos/controller/agenda.ts
> +        data.motivoDeSuspension = req.body.motivo;
Corregido!

2022-08-22 18:03 UTC, martinebucarey approved these changes

2022-08-26 17:07 UTC, plammel approved these changes

2022-12-06 15:18 UTC, MCele approved these changes

2022-12-06 15:25 UTC, merged