PER-75 - Actualizar job perinatal
andes/api pull request #1749
Opened 2022-08-30 13:00 UTC by leon-bravo

### Requerimiento

[PER-75](https://proyectos.andes.gob.ar/browse/PER-75) - Actualizar job perinatal

### Funcionalidad desarrollada 

1. Se modifica el jobs para contemplar cuando la cantidad de embarazos son superiores a 10
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-11-24 11:20 UTC, MarianoCampetella approved these changes

2023-02-08 12:57 UTC, MCele commented
No está funcionando correctamente, arroja un error al traer los datos de sip-plus. Se crea una tarea para darle continuidad

2023-03-02 18:03 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8513](http://condorpiedra.andes.gob.ar:85/8513/mochawesome.html)
CYPRESS RUN: [7692](https://dashboard.cypress.io/projects/xr7gft/runs/7692/specs)
TEST START: 2023-03-02T18:02:35.986Z
TOTAL: 383
SUCCESS: 375
FAIL: 6
SKIPPED: 2

2023-03-02 20:19 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8522](http://condorpiedra.andes.gob.ar:85/8522/mochawesome.html)
CYPRESS RUN: [7701](https://dashboard.cypress.io/projects/xr7gft/runs/7701/specs)
TEST START: 2023-03-02T20:19:43.916Z
TOTAL: 398
SUCCESS: 394
FAIL: 2
SKIPPED: 2

2023-03-02 21:22 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8524](http://condorpiedra.andes.gob.ar:85/8524/mochawesome.html)
CYPRESS RUN: [7703](https://dashboard.cypress.io/projects/xr7gft/runs/7703/specs)
TEST START: 2023-03-02T21:00:58.729Z
TOTAL: 338
SUCCESS: 317
FAIL: 19
SKIPPED: 2

2023-03-03 12:29 UTC, silviroa commented
USUARIO: mbenicio  
BUILD NUMBER: [8529](http://condorpiedra.andes.gob.ar:85/8529/mochawesome.html)
CYPRESS RUN: [7708](https://dashboard.cypress.io/projects/xr7gft/runs/7708/specs)
TEST START: 2023-03-03T12:28:46.637Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-03 15:38 UTC, MCele requested changes

2023-03-03 15:38 UTC, MCele commented on jobs/perinatalFechaFinEmbarazo.ts
> +            let numGesta = null;
si el valor de la variable numGesta no se va a volver a modificar, entonces es recomendable definirla como constante

2023-03-03 15:38 UTC, MCele commented on jobs/perinatalFechaFinEmbarazo.ts
> +function getNumGesta(registroPer: any) {
Al definir los tipos de datos siempre, que sea posible, es recomendable utilizar esquemas o tipos de datos primitivos, evitando el uso de variables tipo any. Por ejemplo si se necesitan 2 datos o más, contenidos dentro del parametro registroPer, se puede ampliar la cantidad de parámetros de la función y definirlos a cada uno con tipo.

2023-03-03 15:42 UTC, MCele commented on jobs/perinatalFechaFinEmbarazo.ts
> +function getNumGesta(registroPer: any) {
la funcion parece resolver bien lo pedido en lineas generales, pero hay que tener en cuenta el siguiente caso:
qué pasa si la prestación que se registró tenia el numero de embarazo en el concepto "embarazo" el dato de "tercer embarazo" (127367000) y también cargaron el numero de embarazo (con otro numero distinto a 3), en ese caso debe priorizarse siempre el valor del concepto "embarazo" y sólo considerarse el campo numérico cuando embarazo incluye al concepto que es mayor a 10 ( conceptId : 127374005)

2023-03-07 13:52 UTC, maring0019 commented on jobs/perinatalFechaFinEmbarazo.ts
> +            let numGesta = null;
No se puede, sale error. En realidad si se modifica numGesta.

2023-03-16 16:52 UTC, maring0019 commented on jobs/perinatalFechaFinEmbarazo.ts
> +            let numGesta = null;
Cambios hechos.

2023-08-16 19:38 UTC, MCele approved these changes

2023-08-24 14:04 UTC, merged