IN - Error al visualizar datos de una cama
andes/api pull request #1751
Opened 2022-08-31 17:49 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-484

### Funcionalidad desarrollada 

1. Se modificó la querie que trae los estados de una cama.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-08-31 18:19 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7553](http://condorpiedra.andes.gob.ar:85/7553/mochawesome.html)
CYPRESS RUN: [6362](https://dashboard.cypress.io/projects/xr7gft/runs/6362/specs)
TEST START: 2022-08-31T18:19:00.551Z
TOTAL: 352
SUCCESS: 348
FAIL: 3
SKIPPED: 1

2022-08-31 18:38 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7554](http://condorpiedra.andes.gob.ar:85/7554/mochawesome.html)
CYPRESS RUN: [6363](https://dashboard.cypress.io/projects/xr7gft/runs/6363/specs)
TEST START: 2022-08-31T18:37:56.795Z
TOTAL: 398
SUCCESS: 394
FAIL: 3
SKIPPED: 1

2022-09-01 11:39 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7558](http://condorpiedra.andes.gob.ar:85/7558/mochawesome.html)
CYPRESS RUN: [6367](https://dashboard.cypress.io/projects/xr7gft/runs/6367/specs)
TEST START: 2022-09-01T11:37:48.216Z
TOTAL: 312
SUCCESS: 301
FAIL: 10
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-09-01 12:19 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7561](http://condorpiedra.andes.gob.ar:85/7561/mochawesome.html)
CYPRESS RUN: [6370](https://dashboard.cypress.io/projects/xr7gft/runs/6370/specs)
TEST START: 2022-09-01T12:18:50.586Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-09-01 12:54 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7563](http://condorpiedra.andes.gob.ar:85/7563/mochawesome.html)
CYPRESS RUN: [6372](https://dashboard.cypress.io/projects/xr7gft/runs/6372/specs)
TEST START: 2022-09-01T12:53:46.722Z
TOTAL: 406
SUCCESS: 392
FAIL: 13
SKIPPED: 1

2022-09-01 13:19 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7565](http://condorpiedra.andes.gob.ar:85/7565/mochawesome.html)
CYPRESS RUN: [6374](https://dashboard.cypress.io/projects/xr7gft/runs/6374/specs)
TEST START: 2022-09-01T13:10:07.255Z
TOTAL: 406
SUCCESS: 389
FAIL: 16
SKIPPED: 1

2022-09-15 12:44 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7639](http://condorpiedra.andes.gob.ar:85/7639/mochawesome.html)
CYPRESS RUN: [6540](https://dashboard.cypress.io/projects/xr7gft/runs/6540/specs)
TEST START: 2022-09-15T12:44:16.752Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-09-15 13:08 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7640](http://condorpiedra.andes.gob.ar:85/7640/mochawesome.html)
CYPRESS RUN: [6541](https://dashboard.cypress.io/projects/xr7gft/runs/6541/specs)
TEST START: 2022-09-15T13:08:40.597Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-10-20 13:44 UTC, negro89 requested changes
Este cambio soluciona el requerimiento pero hay que tener en cuenta que esta query se usa para los estados en general y no es buena idea forzar a traer siempre los estados _esMovimiento: true_. Por eso existe el filtro de la linea 294.

Sugiero hacer el cambio desde la app.

2022-10-21 12:13 UTC, MarianoCampetella commented
> Este cambio soluciona el requerimiento pero hay que tener en cuenta que esta query se usa para los estados en general y no es buena idea forzar a traer siempre los estados _esMovimiento: true_. Por eso existe el filtro de la linea 294.
> 
> Sugiero hacer el cambio desde la app.

Como el cambio se realizo en la api se procede a cerrar el PR

2022-12-07 18:24 UTC, closed without merging