IN - controles para pacientes duplicados en camas distintas
andes/api pull request #1773
Opened 2022-11-23 15:24 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-489

### Funcionalidad desarrollada 

1. Se agrego una condición para verificar que al momento de hacer un traslado de cama el paciente no se haya cambiado anteriormente.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2022-11-23 16:33 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7998](http://condorpiedra.andes.gob.ar:85/7998/mochawesome.html)
CYPRESS RUN: [7191](https://dashboard.cypress.io/projects/xr7gft/runs/7191/specs)
TEST START: 2022-11-23T16:32:39.443Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-11-23 17:14 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7999](http://condorpiedra.andes.gob.ar:85/7999/mochawesome.html)
CYPRESS RUN: [7192](https://dashboard.cypress.io/projects/xr7gft/runs/7192/specs)
TEST START: 2022-11-23T17:14:35.783Z
TOTAL: 406
SUCCESS: 396
FAIL: 9
SKIPPED: 1

2022-11-23 17:26 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8000](http://condorpiedra.andes.gob.ar:85/8000/mochawesome.html)
CYPRESS RUN: [7193](https://dashboard.cypress.io/projects/xr7gft/runs/7193/specs)
TEST START: 2022-11-23T17:25:58.805Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

2022-12-01 16:28 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8056](http://condorpiedra.andes.gob.ar:85/8056/mochawesome.html)
CYPRESS RUN: [7248](https://dashboard.cypress.io/projects/xr7gft/runs/7248/specs)
TEST START: 2022-12-01T16:18:24.470Z
TOTAL: 376
SUCCESS: 358
FAIL: 16
SKIPPED: 2

2022-12-01 17:17 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8058](http://condorpiedra.andes.gob.ar:85/8058/mochawesome.html)
CYPRESS RUN: [7250](https://dashboard.cypress.io/projects/xr7gft/runs/7250/specs)
TEST START: 2022-12-01T17:05:03.485Z
TOTAL: 406
SUCCESS: 386
FAIL: 18
SKIPPED: 2

2022-12-01 18:14 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8059](http://condorpiedra.andes.gob.ar:85/8059/mochawesome.html)
CYPRESS RUN: [7251](https://dashboard.cypress.io/projects/xr7gft/runs/7251/specs)
TEST START: 2022-12-01T18:13:50.377Z
TOTAL: 406
SUCCESS: 395
FAIL: 9
SKIPPED: 2

2022-12-01 19:01 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8060](http://condorpiedra.andes.gob.ar:85/8060/mochawesome.html)
CYPRESS RUN: [7252](https://dashboard.cypress.io/projects/xr7gft/runs/7252/specs)
TEST START: 2022-12-01T19:01:11.638Z
TOTAL: 374
SUCCESS: 365
FAIL: 7
SKIPPED: 2

2022-12-05 12:26 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8078](http://condorpiedra.andes.gob.ar:85/8078/mochawesome.html)
CYPRESS RUN: [7270](https://dashboard.cypress.io/projects/xr7gft/runs/7270/specs)
TEST START: 2022-12-05T12:26:40.006Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2022-12-05 13:47 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8080](http://condorpiedra.andes.gob.ar:85/8080/mochawesome.html)
CYPRESS RUN: [7272](https://dashboard.cypress.io/projects/xr7gft/runs/7272/specs)
TEST START: 2022-12-05T13:47:33.616Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2022-12-06 12:49 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8090](http://condorpiedra.andes.gob.ar:85/8090/mochawesome.html)
CYPRESS RUN: [7282](https://dashboard.cypress.io/projects/xr7gft/runs/7282/specs)
TEST START: 2022-12-06T12:49:31.927Z
TOTAL: 406
SUCCESS: 397
FAIL: 7
SKIPPED: 2

2022-12-06 13:31 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8092](http://condorpiedra.andes.gob.ar:85/8092/mochawesome.html)
CYPRESS RUN: [7284](https://dashboard.cypress.io/projects/xr7gft/runs/7284/specs)
TEST START: 2022-12-06T13:30:54.418Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2022-12-06 14:35 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8096](http://condorpiedra.andes.gob.ar:85/8096/mochawesome.html)
CYPRESS RUN: [7288](https://dashboard.cypress.io/projects/xr7gft/runs/7288/specs)
TEST START: 2022-12-06T14:35:35.490Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

2022-12-14 15:51 UTC, negro89 requested changes
En principio está bien pensado 👏🏼 pero la forma de realizar este control es mediante los movimientos de la internación. Es decir, lo correcto sería traer todos los movimientos de la internación y corroborar que el ultimo se corresponda con la cama actual del paciente. Si eso se cumple, entonces moverlo.
Si con esto alcanza, no sería necesario cambios en la app.

2022-12-15 15:28 UTC, MarianoCampetella commented
> En principio está bien pensado 👏🏼 pero la forma de realizar este control es mediante los movimientos de la internación. Es decir, lo correcto sería traer todos los movimientos de la internación y corroborar que el ultimo se corresponda con la cama actual del paciente. Si eso se cumple, entonces moverlo. Si con esto alcanza, no sería necesario cambios en la app.

Es necesario que todo se haga desde la api? Porque en principio al traerme el idCamaAnterior de la app me soluciona un montón de cosas que en la api son mas complejas de resolver y que practicamente se requieren mas controles.

2022-12-19 14:50 UTC, MCele requested changes
dejé comentario del problema. También noté que cuando se quiere hacer el segundo movimiento (el duplicado desde la misma cama origen), se se cambia de fecha, la app lo está controlando, porque se observa un mensaje que indica que la cama en esa fecha ya no está ocupada, pero si nunca se realiza un cambio de fecha, ese control no se hace, y es cuando se puede realizar el movimiento sin problemas
![image](https://user-images.githubusercontent.com/19591224/208458043-3449d6fe-8725-4969-9618-45a11e5d3329.png)

2023-05-18 16:41 UTC, MarianoCampetella commented
Se procede a cerrar este pr ya que el bug solamente se resuelve desde la app.

2023-05-18 16:41 UTC, closed without merging