Agregar rechazo de una renovacion online
andes/api pull request #1788
Opened 2023-02-28 13:38 UTC by Fabio-Ramirez

### Requerimiento

### Funcionalidad desarrollada 

1. Se agrega el objeto rechazarOnline dentro de una formacion de grado de un profesional.

### UserStories llegó a completarse

- [ x ] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ x ] No

2023-02-28 14:50 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8470](http://condorpiedra.andes.gob.ar:85/8470/mochawesome.html)
CYPRESS RUN: [7645](https://dashboard.cypress.io/projects/xr7gft/runs/7645/specs)
TEST START: 2023-02-28T14:48:50.221Z
TOTAL: 402
SUCCESS: 389
FAIL: 11
SKIPPED: 2

2023-02-28 15:45 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8473](http://condorpiedra.andes.gob.ar:85/8473/mochawesome.html)
CYPRESS RUN: [7648](https://dashboard.cypress.io/projects/xr7gft/runs/7648/specs)
TEST START: 2023-02-28T15:35:11.139Z
TOTAL: 406
SUCCESS: 388
FAIL: 16
SKIPPED: 2

2023-02-28 17:41 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8475](http://condorpiedra.andes.gob.ar:85/8475/mochawesome.html)
CYPRESS RUN: [7650](https://dashboard.cypress.io/projects/xr7gft/runs/7650/specs)
TEST START: 2023-02-28T17:41:37.785Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-02 17:42 UTC, negro89 requested changes

2023-03-02 17:42 UTC, negro89 commented on core/tm/schemas/profesional.ts
> +            estado: { type: String, required: false },
Los estados deberían restringirse, como dice la tarea, a ‘pendiente’, ‘aprobado’, ‘rechazado’ en lugar de un string 'libre'.

2023-03-06 16:11 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8537](http://condorpiedra.andes.gob.ar:85/8537/mochawesome.html)
CYPRESS RUN: [7716](https://dashboard.cypress.io/projects/xr7gft/runs/7716/specs)
TEST START: 2023-03-06T16:11:38.051Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-07 11:36 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8540](http://condorpiedra.andes.gob.ar:85/8540/mochawesome.html)
CYPRESS RUN: [7719](https://dashboard.cypress.io/projects/xr7gft/runs/7719/specs)
TEST START: 2023-03-07T11:35:24.656Z
TOTAL: 248
SUCCESS: 222
FAIL: 24
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-03-07 12:13 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8541](http://condorpiedra.andes.gob.ar:85/8541/mochawesome.html)
CYPRESS RUN: [7720](https://dashboard.cypress.io/projects/xr7gft/runs/7720/specs)
TEST START: 2023-03-07T12:13:39.639Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-07 13:32 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8544](http://condorpiedra.andes.gob.ar:85/8544/mochawesome.html)
CYPRESS RUN: [7723](https://dashboard.cypress.io/projects/xr7gft/runs/7723/specs)
TEST START: 2023-03-07T13:31:56.432Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-03-07 13:47 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [8545](http://condorpiedra.andes.gob.ar:85/8545/mochawesome.html)
CYPRESS RUN: [7724](https://dashboard.cypress.io/projects/xr7gft/runs/7724/specs)
TEST START: 2023-03-07T13:46:47.437Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-07 17:18 UTC, negro89 approved these changes

2023-03-07 17:32 UTC, MCele approved these changes

2023-03-10 14:23 UTC, merged