MAT - Script p/actualizar especialidades de Profesionales
andes/api pull request #1790
Opened 2023-03-16 14:29 UTC by JuanIRamirez

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-134

### Funcionalidad desarrollada 

1.  Se creó un script para actualizar la colección de profesionales desde la colección especialidad.
NOTA: Se buscan los profesionales que tengan formacionPosgrado.especialidad y que formacionPosgrado.especialidad._id sea null o 'formacionPosgrado.especialidad.codigo.sisa' sea null o 'formacionPosgrado.especialidad.habilitado' sea null.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2023-03-16 19:04 UTC, silviroa commented
USUARIO: cramos  
BUILD NUMBER: [8586](http://condorpiedra.andes.gob.ar:85/8586/mochawesome.html)
CYPRESS RUN: [7764](https://dashboard.cypress.io/projects/xr7gft/runs/7764/specs)
TEST START: 2023-03-16T19:04:28.450Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-03-21 13:35 UTC, MarianoCampetella requested changes

2023-03-21 13:35 UTC, MarianoCampetella commented on scripts/MAT-134.ts
> +        for (const fpg of formacionPosgrado) {
fpg se podría cambiar por otro nombre que sea mas significativo!

2023-03-21 13:35 UTC, MarianoCampetella commented on scripts/MAT-134.ts
> +                if (esp != null) {
Las condiciones cuando tienen que ser distintas de nulo o de undefined se arman de la siguiente manera:
if (esp) { ... } lo mismo ocurre cuando preguntas si una variable es verdadera.
En caso contrario si se quiere preguntar si no existe una variable es if (!esp)
Ademas tener cuidado con los operadores de comparación ya que no es lo mismo hacer un == que un ===
Acá dejo una documentación para mayor explicación: https://www.freecodecamp.org/espanol/news/triple-igual-vs-doble-igual-en-javascript-comparison-operators-explained-with-examples/

2023-03-21 13:35 UTC, MarianoCampetella commented on scripts/MAT-134.ts
> +                    }
Si arriba la variable unProf ya esta declarada como false no es necesario tener que implementar un else agregandole el valor en false ya que si nunca entra a la condición del if va a seguir con el valor de false.

2023-03-21 13:35 UTC, MarianoCampetella commented on scripts/MAT-134.ts
> +            const profUp = await Profesional.findByIdAndUpdate( profesionalId, { $set: { formacionPosgrado } });
La constante profUp no es utilizada en ningún lado.

2023-03-21 13:35 UTC, MarianoCampetella commented on scripts/MAT-134.ts
> +    let r = texto.replace(/\(/g, '.');
Por buenas practicas se recomienda utilizar nombre de variables significativas.

2023-03-21 13:35 UTC, MarianoCampetella commented on scripts/MAT-134.ts
> +        .cursor({ batchSize: 100 });
habría que solucionar el problema de identación para una mejor organización del código!

2023-03-22 13:14 UTC, JuanIRamirez commented on scripts/MAT-134.ts
> +        for (const fpg of formacionPosgrado) {
Corregido, cambié fpg por formacionposgrado

2023-03-22 13:32 UTC, JuanIRamirez commented on scripts/MAT-134.ts
> +    let r = texto.replace(/\(/g, '.');
se cambió 'r' por 'textoReplace'

2023-03-22 13:33 UTC, JuanIRamirez commented on scripts/MAT-134.ts
> +        .cursor({ batchSize: 100 });
Así me lo identó EsLint.

2023-03-22 13:33 UTC, JuanIRamirez commented on scripts/MAT-134.ts
> +            const profUp = await Profesional.findByIdAndUpdate( profesionalId, { $set: { formacionPosgrado } });
Corregido

2023-03-22 13:33 UTC, JuanIRamirez commented on scripts/MAT-134.ts
> +                if (esp != null) {
Corregido

2023-03-22 13:34 UTC, JuanIRamirez commented on scripts/MAT-134.ts
> +                    }
Corregido

2023-03-22 14:37 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [8619](http://condorpiedra.andes.gob.ar:85/8619/mochawesome.html)
CYPRESS RUN: [7796](https://dashboard.cypress.io/projects/xr7gft/runs/7796/specs)
TEST START: 2023-03-22T14:36:50.844Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

2023-05-05 18:53 UTC, silviroa approved these changes

2023-05-05 18:54 UTC, merged