RUP - Error en Adjuntos RUP
andes/api pull request #1795
Opened 2023-03-31 14:31 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-237

### Funcionalidad desarrollada 

1. Agrega función para aviso de cancelacion de solicitud de adjuntar archivo

### UserStories llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2023-06-09 12:13 UTC, silviroa requested changes

2023-06-09 12:13 UTC, silviroa commented on modules/mobileApp/auth_routes/rup-adjuntos.ts
> +        const adjunto: any = await PrestacionAdjunto.findById(id);
Existe alguna posibilidad que este find no encuentre ya el ID???

2023-06-09 12:13 UTC, silviroa commented on modules/mobileApp/auth_routes/rup-adjuntos.ts
> +        const adjunto: any = await PrestacionAdjunto.findById(id);
Agregar un control para que no falle el remove()

2024-03-07 13:00 UTC, MCele commented on modules/mobileApp/auth_routes/rup-adjuntos.ts
> +        const adjunto: any = await PrestacionAdjunto.findById(id);
Cambios hechos

2024-05-10 11:59 UTC, silviroa approved these changes

2024-05-23 12:23 UTC, merged