IN - Prestamo/devolucion de cama
andes/api pull request #1800
Opened 2023-04-20 12:53 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-534

### Funcionalidad desarrollada 

1. Se modifica endpoint para patchear estados de cama agregando un caso nuevo para prestamo-devolucion de cama. De manera de recibir informacion para agregar un estado _prestamo_ y _devolución_, y ademas modificar estados intermedios preexistentes entre estos.
2. Refactor de funcion _patch_ en el controller de cama-estados para modificar la unidad organizativa de los estados que coincidan con las fechas ingresadas en un array por parametro.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2023-04-20 13:11 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8731](http://condorpiedra.andes.gob.ar:85/8731/mochawesome.html)
CYPRESS RUN: [7906](https://dashboard.cypress.io/projects/xr7gft/runs/7906/specs)
TEST START: 2023-04-20T13:10:39.254Z
TOTAL: 361
SUCCESS: 351
FAIL: 8
SKIPPED: 2

2023-04-20 13:55 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8733](http://condorpiedra.andes.gob.ar:85/8733/mochawesome.html)
CYPRESS RUN: [7908](https://dashboard.cypress.io/projects/xr7gft/runs/7908/specs)
TEST START: 2023-04-20T13:55:40.528Z
TOTAL: 378
SUCCESS: 371
FAIL: 5
SKIPPED: 2

2023-04-21 03:23 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8742](http://condorpiedra.andes.gob.ar:85/8742/mochawesome.html)
CYPRESS RUN: [7917](https://dashboard.cypress.io/projects/xr7gft/runs/7917/specs)
TEST START: 2023-04-21T03:22:37.881Z
TOTAL: 177
SUCCESS: 132
FAIL: 45
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-04-21 13:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [8744](http://condorpiedra.andes.gob.ar:85/8744/mochawesome.html)
CYPRESS RUN: [7919](https://dashboard.cypress.io/projects/xr7gft/runs/7919/specs)
TEST START: 2023-04-21T13:24:47.584Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-05-05 12:35 UTC, MarianoCampetella requested changes

2023-05-05 12:35 UTC, MarianoCampetella commented on modules/rup/internacion/camas.routes.ts
> +            r3 = await CamasController.patchEstados({ ...devolucion, ambito, capa, fecha: hasta, organizacion, id: data.id }, req);
Supongo que los distintos r con sus numeraciones es porque se refieren a las distintas respuestas que se obtienen. Pero utilizaría un nombre mas especifico como rta para que se sepa que de verdad es una respuesta, es decir, un nombre mas especifico

2023-05-11 19:03 UTC, maring0019 requested changes

2023-07-14 14:16 UTC, negro89 commented on modules/rup/internacion/camas.routes.ts
> +    let result;
Se usa 4 veces mas abajo. Lineas 161, 163, 165 y 166.

2023-07-14 15:11 UTC, negro89 commented on modules/rup/internacion/camas.routes.ts
> +            r3 = await CamasController.patchEstados({ ...devolucion, ambito, capa, fecha: hasta, organizacion, id: data.id }, req);
Exactamente es asi. Se reemplazó el nombre 👍🏼

2023-07-17 13:41 UTC, MarianoCampetella approved these changes

2023-09-05 13:34 UTC, maring0019 approved these changes
Faltaría correr el test con los nuevos cambio.

2023-09-05 13:34 UTC, maring0019 commented on modules/rup/internacion/camas.routes.ts
> +    let result;
Recién veo. No sabía de los cambios. No me llegó la notificación.

No había visto el uso de esa variable. Pero ahora ya lo vi.

2026-04-07 13:26 UTC, closed without merging