Feat-Script p/corregir prestaciones no codificadas
andes/api pull request #1804
Opened 2023-05-04 12:37 UTC by JuanIRamirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-219
### Funcionalidad desarrollada 

1.  Recorre prestaciones de las ultimas 24 Hs. 
2.  Si la codificación de agenda.turno o agenda.sobreturno está vacia le agrega la codificación.
3.  Si turno.horaAsistencia está vacia le asigna turno.horaInicio.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2023-05-16 18:07 UTC, MarianoCampetella requested changes

2023-05-16 18:07 UTC, MarianoCampetella commented on scripts/CIT-219.ts
> +                        if (turno.diagnostico.codificaciones.length === 0) {
Esto se puede resumir a if (turno.diagnostico.codificaciones.length) { ... }
Lo mismo para la linea 42

2023-05-16 18:14 UTC, MarianoCampetella commented
Probé con tres agendas sacadas desde demo y cuando ejecuto el script, la sentencia: data = await codificarTurno('', [agenda], turnoId); me devuelve null. Lo cual cuando se hace un data[0] me tira un error. 
Estará bien que la codificación venga en nulo o no te sucedía eso cuando lo probabas?

2023-05-17 15:50 UTC, JuanIRamirez commented
> Probé con tres agendas sacadas desde demo y cuando ejecuto el script, la sentencia: data = await codificarTurno('', [agenda], turnoId); me devuelve null. Lo cual cuando se hace un data[0] me tira un error. Estará bien que la codificación venga en nulo o no te sucedía eso cuando lo probabas?

En local no me dá ningún error. 
Se pincha cuando te da error ?

2023-05-17 15:51 UTC, JuanIRamirez commented on scripts/CIT-219.ts
> +                        if (turno.diagnostico.codificaciones.length === 0) {
Corregido.

2023-05-18 13:36 UTC, MarianoCampetella commented
> * Recorre prestaciones de las ultimas 24 Hs.
> * Si la codificación de agenda.turno o agenda.sobreturno está vacia le agrega la codificación.
> * Si turno.horaAsistencia está vacia le asigna turno.horaInicio.

Mala mía Juan, anda perfecto!!!
De seguro fue algún dato que me habrá faltado en mi local!!

2023-05-18 15:42 UTC, JuanIRamirez commented
Genial !

El jue, 18 may 2023 a las 10:36, MarianoCampetella (<
***@***.***>) escribió:

>
>    - Recorre prestaciones de las ultimas 24 Hs.
>    - Si la codificación de agenda.turno o agenda.sobreturno está vacia le
>    agrega la codificación.
>    - Si turno.horaAsistencia está vacia le asigna turno.horaInicio.
>
> Mala mía Juan, anda perfecto!!!
> De seguro fue algún dato que me habrá faltado en mi local!!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/andes/api/pull/1804#issuecomment-1553068480>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT4SEDZ3U7EUD3K3GAS7HY3XGYQXBANCNFSM6AAAAAAXVXLDCE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-06 19:54 UTC, negro89 approved these changes

2023-06-06 19:55 UTC, negro89 commented
codigo OK 👍🏼

2023-06-09 15:24 UTC, MarianoCampetella approved these changes

2024-08-12 18:22 UTC, merged