MPI - Agrega detalles al esquema de pacientes
andes/api pull request #1807
Opened 2023-05-17 17:28 UTC by ma7payne

### Requerimiento

https://proyectos.andes.gob.ar/browse/MPI-403

Se requieren los cambios realizados en la tarea de CIT-214:
https://proyectos.andes.gob.ar/browse/CIT-214

### Funcionalidad desarrollada 

1. Se agrega la siguiente información al esquema de pacientes: origen (PUCO, ANDES o SUMAR) y fechaDeActualización
2. Cada vez que se guarda un turno, o se consulta desde MPI le información del paciente, se agrega fechaDeActualización a la obra social o al prestador modificado .
3. Cuando se obtienen datos de la obra social o prestador, tanto de padrones PUCO o SUMAR en MPI, como del selector de prestadores en CIT-214, se determina el origen para completar el cambio en el esquema del paciente.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2023-06-02 13:32 UTC, silviroa commented
USUARIO: mchiappe  
BUILD NUMBER: [8986](http://condorpiedra.andes.gob.ar:85/8986/mochawesome.html)
CYPRESS RUN: [8149](https://dashboard.cypress.io/projects/xr7gft/runs/8149/specs)
TEST START: 2023-06-02T13:31:47.529Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-09-05 12:57 UTC, negro89 approved these changes

2023-09-05 15:38 UTC, Fabio-Ramirez commented on core-v2/mpi/paciente/paciente.controller.ts
> +    const ingresoManual = financiador.some(f => f && f.origen === 'ANDES');
Se sugiere el encadenamiento opcional (?), para verificar la existencia de la variable (f en este caso) y  ademas para reducir codigo.

2023-09-05 15:38 UTC, Fabio-Ramirez commented on core-v2/mpi/paciente/paciente.controller.ts
> +        const index = paciente.financiador?.findIndex(f => f && f.origen === 'ANDES');
Idem que lo comentado anteriormente

2023-09-05 15:39 UTC, Fabio-Ramirez commented on core-v2/mpi/paciente/paciente.controller.ts
> +        const seleccionManual = listaFinanciador.filter(f => f && f.origen === 'ANDES');
Idem.

2023-12-21 17:47 UTC, MCele commented
Mati los cambios en general se ven bien, pero observo lo siguiente para mejorar en el pr:

- Cuando se realiza la dación de turno de un paciente que no tiene Obra Social, ni está en el padrón de Sumar, se guarda vacía la información d ela OS en el array de financiadores.

- Cuando se actualiza un paciente desde MPI, si no tiene Obra social asociada se le carga la obra social, y se actualiza pero falta el dato de "origen" :"PUCO"

![image](https://github.com/andes/api/assets/19591224/31a42bd3-19cf-4b91-afb2-5d1e4d2583f0)

2023-12-22 14:32 UTC, ma7payne commented
@MCele  Listo el fix para el caso de financiador vacío.
@Fabio-Ramirez Listas las sugerencias pedidas.

2024-02-21 14:18 UTC, MCele commented
Mati lo volví a revisar y en base al comentario que ya había dejado observo lo siguiente:
En el punto 1, me parece que quedó bien porque ya no se guardan los datos vacíos. Respecto a los puntos 2 y 3 siguen sin resolverse algunos detalles, es decir:
 si el paciente no tenia cargada una OS y no se selecciona una distinta a la que tiene el paciente, no se guarda su "origen" ("PUCO" o "SUMAR") , aunque ahora sí se guarda el dato de "prepaga":false.
 Respecto al punto 3, el sobre-turno no está contemplado, es decir no guarda los datos de la OS en el paciente aunque se permita seleccionarla.

2024-05-20 13:04 UTC, ma7payne commented
> Mati lo volví a revisar y en base al comentario que ya había dejado observo que en el punto 1, me parece que quedó bien porque ya no se guardan los datos vacíos. Respecto a los puntos 2 y 3 siguen sin resolverse algunos detalles, es decir: si el paciente no tenia cargada una OS y no se selecciona una distinta a la que tiene el paciente, no se guarda su "origen" ("PUCO" o "SUMAR") , aunque ahora sí se guarda el dato de "prepaga":false. Respecto al punto 3, el sobre-turno no está contemplado, es decir no guarda los datos de la OS en el paciente aunque se permita seleccionarla.

@MCele los cambios quedaron listos. Se debe revisar en conjunto con  https://github.com/andes/app/pull/2985

2024-05-23 13:39 UTC, MCele requested changes

2024-05-23 13:39 UTC, MCele commented on core-v2/mpi/paciente/paciente.controller.ts
> +    return paciente.financiador.filter((financiador) => financiador?.origen === 'ANDES');
Mati acá parece faltar un control por campo financiador null, me arroja este error
![image](https://github.com/andes/api/assets/19591224/77d503d4-fb78-4493-aeca-5af27c2ee7a1)

2024-05-23 13:39 UTC, MCele commented on modules/turnos/routes/turno.ts
> +        const financiador = updateFinanciador(obraSocialUpdated, pacienteTurno.obraSocial);
revisar comportamiento de este método ya que muestra y guarda las OS duplicadas en el paciente

2024-06-03 14:39 UTC, MCele requested changes
cambios pendientes

2024-07-16 17:10 UTC, MCele commented on modules/turnos/routes/turno.ts
> +        const financiador = updateFinanciador(obraSocialUpdated, pacienteTurno.obraSocial);
no se pudo volver a reprodcir el caso

2024-08-26 12:45 UTC, ma7payne commented
Listo el cambio!

2024-08-27 20:06 UTC, MCele approved these changes

2024-09-11 16:43 UTC, merged