Citas - Modifica /rup/routes/prestacion p/Auditoría/Fuera de Agenda
andes/api pull request #1813
Opened 2023-06-22 14:04 UTC by JuanIRamirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-227

### Funcionalidad desarrollada 

1. Modifica /rup/routes/prestacion.ts 
2. Devuelve: prestacion: '$prestacion.solicitud.tipoPrestacion.term'
3. Para mostrar en Auditoría / Fuera de Agenda.

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2023-06-30 17:56 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9146](http://condorpiedra.andes.gob.ar:85/9146/mochawesome.html)
CYPRESS RUN: [8293](https://dashboard.cypress.io/projects/xr7gft/runs/8293/specs)
TEST START: 2023-06-30T17:53:02.435Z
TOTAL: 403
SUCCESS: 392
FAIL: 9
SKIPPED: 2

2023-06-30 18:33 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9148](http://condorpiedra.andes.gob.ar:85/9148/mochawesome.html)
CYPRESS RUN: [8295](https://dashboard.cypress.io/projects/xr7gft/runs/8295/specs)
TEST START: 2023-06-30T18:33:16.757Z
TOTAL: 403
SUCCESS: 393
FAIL: 8
SKIPPED: 2

2023-07-13 16:05 UTC, MarianoCampetella requested changes

2023-09-14 11:56 UTC, JuanIRamirez commented on modules/rup/routes/codificacion.ts
> +            }
Hecho

2023-09-14 12:00 UTC, JuanIRamirez commented on modules/rup/routes/codificacion.ts
> +            }
Hecho

2023-09-18 12:28 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9636](http://condorpiedra.andes.gob.ar:85/9636/mochawesome.html)
CYPRESS RUN: [8751](https://dashboard.cypress.io/projects/xr7gft/runs/8751/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-09-18 12:36 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9637](http://condorpiedra.andes.gob.ar:85/9637/mochawesome.html)
CYPRESS RUN: [8751](https://dashboard.cypress.io/projects/xr7gft/runs/8751/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-10-30 13:34 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9839](http://condorpiedra.andes.gob.ar:85/9839/mochawesome.html)
CYPRESS RUN: [8947](https://dashboard.cypress.io/projects/xr7gft/runs/8947/specs)
TEST START: 2023-10-30T13:34:00.408Z
TOTAL: 405
SUCCESS: 402
FAIL: 1
SKIPPED: 2

2023-10-30 14:05 UTC, silviroa commented
USUARIO: jramirez  
BUILD NUMBER: [9841](http://condorpiedra.andes.gob.ar:85/9841/mochawesome.html)
CYPRESS RUN: [8949](https://dashboard.cypress.io/projects/xr7gft/runs/8949/specs)
TEST START: 2023-10-30T14:05:30.949Z
TOTAL: 405
SUCCESS: 403
FAIL: 0
SKIPPED: 2

2023-12-21 15:04 UTC, MarianoCampetella approved these changes

2023-12-21 15:29 UTC, negro89 approved these changes

2024-01-17 14:03 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10294](http://condorpiedra.andes.gob.ar:85/10294/mochawesome.html)
CYPRESS RUN: [9401](https://dashboard.cypress.io/projects/xr7gft/runs/9401/specs)
TEST START: 2024-01-17T14:02:38.904Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-25 13:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10330](http://condorpiedra.andes.gob.ar:85/10330/mochawesome.html)
CYPRESS RUN: [9437](https://dashboard.cypress.io/projects/xr7gft/runs/9437/specs)
TEST START: 2024-01-25T13:08:53.584Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-25 13:25 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10331](http://condorpiedra.andes.gob.ar:85/10331/mochawesome.html)
CYPRESS RUN: [9438](https://dashboard.cypress.io/projects/xr7gft/runs/9438/specs)
TEST START: 2024-01-25T13:24:07.420Z
TOTAL: 336
SUCCESS: 327
FAIL: 6
SKIPPED: 3

2024-01-25 14:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10333](http://condorpiedra.andes.gob.ar:85/10333/mochawesome.html)
CYPRESS RUN: [9440](https://dashboard.cypress.io/projects/xr7gft/runs/9440/specs)
TEST START: 2024-01-25T14:04:43.358Z
TOTAL: 365
SUCCESS: 357
FAIL: 5
SKIPPED: 3

2024-01-25 18:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10340](http://condorpiedra.andes.gob.ar:85/10340/mochawesome.html)
CYPRESS RUN: [9447](https://dashboard.cypress.io/projects/xr7gft/runs/9447/specs)
TEST START: 2024-01-25T18:15:43.298Z
TOTAL: 403
SUCCESS: 401
FAIL: -1
SKIPPED: 3

2026-04-07 13:30 UTC, closed without merging