MAT - Filtros en guía profesional
andes/api pull request #1814
Opened 2023-06-23 14:41 UTC by aldoEMatamala

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-140

### Funcionalidad desarrollada 

1. Corregido bug de listado nulo al tener una formación de grado sin matrícula
2. Corregido vencimiento de matrícula, ahora se verifica con "fecha fin"

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2023-06-23 15:24 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9115](http://condorpiedra.andes.gob.ar:85/9115/mochawesome.html)
CYPRESS RUN: [8262](https://dashboard.cypress.io/projects/xr7gft/runs/8262/specs)
TEST START: 2023-06-23T15:23:32.086Z
TOTAL: 95
SUCCESS: 0
FAIL: 95
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-06-23 15:37 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9116](http://condorpiedra.andes.gob.ar:85/9116/mochawesome.html)
CYPRESS RUN: [8263](https://dashboard.cypress.io/projects/xr7gft/runs/8263/specs)
TEST START: 2023-06-23T15:37:31.105Z
TOTAL: 385
SUCCESS: 380
FAIL: 3
SKIPPED: 2

2023-06-28 13:31 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9123](http://condorpiedra.andes.gob.ar:85/9123/mochawesome.html)
CYPRESS RUN: [8270](https://dashboard.cypress.io/projects/xr7gft/runs/8270/specs)
TEST START: 2023-06-28T13:30:16.224Z
TOTAL: 365
SUCCESS: 346
FAIL: 17
SKIPPED: 2

2023-06-28 13:43 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9124](http://condorpiedra.andes.gob.ar:85/9124/mochawesome.html)
CYPRESS RUN: [8271](https://dashboard.cypress.io/projects/xr7gft/runs/8271/specs)
TEST START: 2023-06-28T13:43:01.392Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-06-29 12:57 UTC, MarianoCampetella requested changes

2023-06-29 12:57 UTC, MarianoCampetella commented on core/tm/routes/profesional.ts
> +                const formGradFilter = element.formacionGrado.filter(p => p.matriculacion !== null);
Te voy a pedir mil disculpas Aldito pero habría que remplazar la variable p por otra mas explicita como formGrado. El resto esta perfecto!

2023-08-03 13:57 UTC, MarianoCampetella approved these changes

2023-08-29 15:27 UTC, merged