(FEAT) PACS - Cancelar orden de trabajo
andes/api pull request #1825
Opened 2023-08-07 15:41 UTC by Fabio-Ramirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/PACS-37

### Funcionalidad desarrollada 

1.  Se agrega funcionalidad para anular el pacs al momento de anular la prestacion asociada.
2.  Ademas se contempla el metodo que contabiliza los pacs que se encuntran en el servicio.
3. Se sugiere cargar un paciente fuera de agenda en el modulo de RUP, con las prestaciones configuradas en la coleccion de   PACS-CONFIG (radiografía simple (procedimiento), ecografía diagnóstica (procedimiento), fibrobroncoscopia (procedimiento), etc). 

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2023-08-07 17:12 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9364](http://condorpiedra.andes.gob.ar:85/9364/mochawesome.html)
CYPRESS RUN: [8502](https://dashboard.cypress.io/projects/xr7gft/runs/8502/specs)
TEST START: 2023-08-07T17:12:17.552Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-11 15:26 UTC, MCele requested changes

2023-08-11 15:26 UTC, MCele commented on modules/pacs/pacs.ts
> +            switch (estadoTipo) {
el uso de switch cuando hay una sola condición me parece innecesario, sugiero cambiarlo por la sentencia if

2023-08-11 17:09 UTC, MCele commented on modules/rup/routes/prestacion.ts
> +                // const update = await updateWorkList(prestacion);
evitemos dejar código comentado

2023-08-16 11:43 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9432](http://condorpiedra.andes.gob.ar:85/9432/mochawesome.html)
CYPRESS RUN: [8569](https://dashboard.cypress.io/projects/xr7gft/runs/8569/specs)
TEST START: 2023-08-16T11:43:04.303Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-16 12:08 UTC, Fabio-Ramirez commented on modules/pacs/pacs.ts
> +            switch (estadoTipo) {
Corregido!

2023-08-16 12:08 UTC, Fabio-Ramirez commented on modules/rup/routes/prestacion.ts
> +                // const update = await updateWorkList(prestacion);
Corregido!

2023-08-24 13:18 UTC, silviroa approved these changes

2023-08-29 13:32 UTC, merged