TOP - Solicitudes: Nuevo estado vencido / Job estado vencido
andes/api pull request #1828
Opened 2023-08-29 19:41 UTC by aldoEMatamala

### Requerimiento

https://proyectos.andes.gob.ar/browse/TOP-156
https://proyectos.andes.gob.ar/browse/TOP-157
### Funcionalidad desarrollada 

1.  Agregado al esquema nuevo estado de solicitud 'vencida'
2. Agregado Job 'vencimientoPrestacion' que cumple requisito TOP-157

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2023-08-31 13:40 UTC, MarianoCampetella requested changes

2023-08-31 13:40 UTC, MarianoCampetella commented on modules/rup/controllers/prestacion.ts
> +        const prestaciones: any = await Prestacion.find(query);
Ya que existe la interfaz de prestación, remplazar el any por dicha interfaz!

2023-09-01 13:06 UTC, MarianoCampetella commented
![image](https://github.com/andes/api/assets/65697028/7f1bc6a4-fd1a-440b-991e-9c3ba96c87a3)
Cuando ejecuto el job desde mi BD Local que es una copia de la BD de demo me ocurre el error que muestro en la imagen, incluso solamente me genero una prestación con estado vencida cuando deberían ser varias. Revisaría el comportamiento del job en primer lugar para que al momento de ejecutarlo no me arroje ningún error por consola. Cualquier duda o sugerencia lo vamos viendo a la par!

2023-09-27 18:46 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9683](http://condorpiedra.andes.gob.ar:85/9683/mochawesome.html)
CYPRESS RUN: [8796](https://dashboard.cypress.io/projects/xr7gft/runs/8796/specs)
TEST START: 2023-09-27T18:46:26.086Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-10-18 17:02 UTC, negro89 commented
@aldoEMatamala ultimo llamado a revisión de comentarios 👮🏼👮🏼👮🏼

2023-10-20 17:54 UTC, aldoEMatamala commented
> ![image](https://user-images.githubusercontent.com/65697028/265024849-7f1bc6a4-fd1a-440b-991e-9c3ba96c87a3.png) Cuando ejecuto el job desde mi BD Local que es una copia de la BD de demo me ocurre el error que muestro en la imagen. Revisaría el comportamiento del job en primer lugar para que al momento de ejecutarlo no me arroje ningún error por consola. Cualquier duda o sugerencia lo vamos viendo a la par!

Buenas Campe! lo consulté con chichi, el error es por algunas prestaciones viejas con datos incompletos, la recomendación fue acotar el rango de fechas, por lo que el job fue modificado para que actualize las prestaciones entre  a partir de 1 año desde la fecha actual (como dicta la tarea) hasta 3 años en el pasado.

2023-10-20 17:54 UTC, aldoEMatamala commented
> @aldoEMatamala ultimo llamado a revisión de comentarios 👮🏼👮🏼👮🏼

revisado!

2023-10-31 18:47 UTC, negro89 approved these changes
codigo ok

2023-11-01 12:26 UTC, MarianoCampetella approved these changes

2023-11-16 16:23 UTC, merged