MAT - Agregar nueva ruta patch
andes/api pull request #1844
Opened 2023-10-17 20:32 UTC by Fabio-Ramirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/MAT-87

### Funcionalidad desarrollada 

1. En routes, el componente profesional, se agregó la ruta patch  y a su vez el endpoint post de profesional solamente se dejo para la creación de uno nuevo.
2. En el componente profesional de controllers se corrigió un linteo y condición.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2023-10-17 21:00 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9778](http://condorpiedra.andes.gob.ar:85/9778/mochawesome.html)
CYPRESS RUN: [8888](https://dashboard.cypress.io/projects/xr7gft/runs/8888/specs)
TEST START: 2023-10-17T20:59:49.302Z
TOTAL: 403
SUCCESS: 399
FAIL: 2
SKIPPED: 2

2023-10-18 11:52 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [9780](http://condorpiedra.andes.gob.ar:85/9780/mochawesome.html)
CYPRESS RUN: [8890](https://dashboard.cypress.io/projects/xr7gft/runs/8890/specs)
TEST START: 2023-10-18T11:51:40.963Z
TOTAL: 303
SUCCESS: 286
FAIL: 15
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-12-07 13:15 UTC, MarianoCampetella requested changes

2024-02-08 14:59 UTC, silviroa commented
USUARIO: nzabaleta  
BUILD NUMBER: [10469](http://condorpiedra.andes.gob.ar:85/10469/mochawesome.html)
CYPRESS RUN: [9570](https://dashboard.cypress.io/projects/xr7gft/runs/9570/specs)
TEST START: 2024-02-08T14:58:11.415Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-02-08 15:15 UTC, silviroa commented
USUARIO: nzabaleta  
BUILD NUMBER: [10470](http://condorpiedra.andes.gob.ar:85/10470/mochawesome.html)
CYPRESS RUN: [9571](https://dashboard.cypress.io/projects/xr7gft/runs/9571/specs)
TEST START: 2024-02-08T15:15:31.214Z
TOTAL: 344
SUCCESS: 332
FAIL: 9
SKIPPED: 3

2024-02-08 15:41 UTC, silviroa commented
USUARIO: framirez  
BUILD NUMBER: [10472](http://condorpiedra.andes.gob.ar:85/10472/mochawesome.html)
CYPRESS RUN: [9573](https://dashboard.cypress.io/projects/xr7gft/runs/9573/specs)
TEST START: 2024-02-08T15:40:46.294Z
TOTAL: 396
SUCCESS: 393
FAIL: 0
SKIPPED: 3

2024-02-19 17:15 UTC, Fabio-Ramirez commented on core/tm/routes/profesional.ts
> +            // resultado.documentos.push(documento);
Corregido

2024-03-14 13:51 UTC, negro89 commented
Test ok
![image](https://github.com/andes/mobile-app/assets/37875706/8e3c6771-75b4-4dd7-bf08-d0fccd7f075d)
![image](https://github.com/andes/mobile-app/assets/37875706/5975703d-daa6-429a-9e49-0c202ba1809b)

2024-03-22 11:23 UTC, merged