CIT - Crear agenda con profesional habilitado.
andes/api pull request #1847
Opened 2023-10-30 12:40 UTC by JuanIRamirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/CIT-247

### Funcionalidad desarrollada 

1. En API tm/routes/profesional.ts, get('/profesional') si recibe parámetro 'habilitado' filtra profesional.habilitado = habilitado (true o false).

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2023-10-31 12:07 UTC, MarianoCampetella requested changes

2023-10-31 12:07 UTC, MarianoCampetella commented on core/tm/routes/profesional.ts
> +    if (req.query.habilitado !== undefined) {
El mismo comentario que en la app. Como solamente se va a filtrar por profesionales activos dejaría el if que antes estaba. A demás si la condición tiene un !== undefined, si viene un valor nulo estaría filtrando por null.

2023-10-31 12:07 UTC, MarianoCampetella commented on core/tm/routes/profesional.ts
> +        if (req.query.habilitado !== undefined) {
Idem al comentario anterior.

2023-10-31 12:18 UTC, aldoEMatamala approved these changes

2023-11-10 12:23 UTC, JuanIRamirez commented on core/tm/routes/profesional.ts
> +        if (req.query.habilitado !== undefined) {
Tiene que ser así, si dejo if(req.query.habilitado) en caso se ser 'false' no entraría al if, y la idea es que el parámetro 'habilitado' sea true o false, si es null no filtra.

2023-11-14 12:05 UTC, JuanIRamirez commented on core/tm/routes/profesional.ts
> +    if (req.query.habilitado !== undefined) {
Tiene que ser así, si dejo if(req.query.habilitado) en caso se ser 'false' no entraría al if, y la idea es que el parámetro 'habilitado' sea true o false, si es (undefined) no filtra.

2023-12-22 13:54 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10112](http://condorpiedra.andes.gob.ar:85/10112/mochawesome.html)
CYPRESS RUN: [9220](https://dashboard.cypress.io/projects/xr7gft/runs/9220/specs)
TEST START: 2023-12-22T13:54:34.399Z
TOTAL: 406
SUCCESS: 398
FAIL: 6
SKIPPED: 2

2023-12-22 14:24 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [10114](http://condorpiedra.andes.gob.ar:85/10114/mochawesome.html)
CYPRESS RUN: [9222](https://dashboard.cypress.io/projects/xr7gft/runs/9222/specs)
TEST START: 2023-12-22T14:23:24.480Z
TOTAL: 370
SUCCESS: 358
FAIL: 11
SKIPPED: 1

2024-01-09 15:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10212](http://condorpiedra.andes.gob.ar:85/10212/mochawesome.html)
CYPRESS RUN: [9320](https://dashboard.cypress.io/projects/xr7gft/runs/9320/specs)
TEST START: 2024-01-09T15:48:40.678Z
TOTAL: 388
SUCCESS: 377
FAIL: 9
SKIPPED: 2

2024-01-09 16:18 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10213](http://condorpiedra.andes.gob.ar:85/10213/mochawesome.html)
CYPRESS RUN: [9321](https://dashboard.cypress.io/projects/xr7gft/runs/9321/specs)
TEST START: 2024-01-09T16:17:27.562Z
TOTAL: 327
SUCCESS: 308
FAIL: 17
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-10 13:16 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10221](http://condorpiedra.andes.gob.ar:85/10221/mochawesome.html)
CYPRESS RUN: [9329](https://dashboard.cypress.io/projects/xr7gft/runs/9329/specs)
TEST START: 2024-01-10T13:15:43.975Z
TOTAL: 401
SUCCESS: 391
FAIL: 7
SKIPPED: 3

2024-01-10 14:33 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10225](http://condorpiedra.andes.gob.ar:85/10225/mochawesome.html)
CYPRESS RUN: [9333](https://dashboard.cypress.io/projects/xr7gft/runs/9333/specs)
TEST START: 2024-01-10T14:32:25.493Z
TOTAL: 356
SUCCESS: 343
FAIL: 11
SKIPPED: 2

2024-01-10 16:15 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10229](http://condorpiedra.andes.gob.ar:85/10229/mochawesome.html)
CYPRESS RUN: [9337](https://dashboard.cypress.io/projects/xr7gft/runs/9337/specs)
TEST START: 2024-01-10T16:14:07.968Z
TOTAL: 376
SUCCESS: 365
FAIL: 8
SKIPPED: 3

2024-01-10 18:23 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10234](http://condorpiedra.andes.gob.ar:85/10234/mochawesome.html)
CYPRESS RUN: [9342](https://dashboard.cypress.io/projects/xr7gft/runs/9342/specs)
TEST START: 2024-01-10T18:23:06.417Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-11 15:13 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10240](http://condorpiedra.andes.gob.ar:85/10240/mochawesome.html)
CYPRESS RUN: [9348](https://dashboard.cypress.io/projects/xr7gft/runs/9348/specs)
TEST START: 2024-01-11T15:13:31.647Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-25 13:54 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10332](http://condorpiedra.andes.gob.ar:85/10332/mochawesome.html)
CYPRESS RUN: [9439](https://dashboard.cypress.io/projects/xr7gft/runs/9439/specs)
TEST START: 2024-01-25T13:53:45.735Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-25 18:26 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10341](http://condorpiedra.andes.gob.ar:85/10341/mochawesome.html)
CYPRESS RUN: [9448](https://dashboard.cypress.io/projects/xr7gft/runs/9448/specs)
TEST START: 2024-01-25T18:26:13.433Z
TOTAL: 401
SUCCESS: 394
FAIL: 4
SKIPPED: 3

2024-01-26 13:04 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10345](http://condorpiedra.andes.gob.ar:85/10345/mochawesome.html)
CYPRESS RUN: [9452](https://dashboard.cypress.io/projects/xr7gft/runs/9452/specs)
TEST START: 2024-01-26T13:04:24.753Z
TOTAL: 381
SUCCESS: 368
FAIL: 10
SKIPPED: 3

2024-01-26 13:17 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10346](http://condorpiedra.andes.gob.ar:85/10346/mochawesome.html)
CYPRESS RUN: [9453](https://dashboard.cypress.io/projects/xr7gft/runs/9453/specs)
TEST START: 2024-01-26T13:17:06.907Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-26 13:33 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10347](http://condorpiedra.andes.gob.ar:85/10347/mochawesome.html)
CYPRESS RUN: [9454](https://dashboard.cypress.io/projects/xr7gft/runs/9454/specs)
TEST START: 2024-01-26T13:32:42.954Z
TOTAL: 401
SUCCESS: 393
FAIL: 5
SKIPPED: 3

2024-01-26 13:57 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10349](http://condorpiedra.andes.gob.ar:85/10349/mochawesome.html)
CYPRESS RUN: [9456](https://dashboard.cypress.io/projects/xr7gft/runs/9456/specs)
TEST START: 2024-01-26T13:56:44.967Z
TOTAL: 388
SUCCESS: 380
FAIL: 5
SKIPPED: 3

2024-01-26 14:20 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10351](http://condorpiedra.andes.gob.ar:85/10351/mochawesome.html)
CYPRESS RUN: [9458](https://dashboard.cypress.io/projects/xr7gft/runs/9458/specs)
TEST START: 2024-01-26T14:20:36.112Z
TOTAL: 401
SUCCESS: 392
FAIL: 6
SKIPPED: 3

2024-01-26 14:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10353](http://condorpiedra.andes.gob.ar:85/10353/mochawesome.html)
CYPRESS RUN: [9460](https://dashboard.cypress.io/projects/xr7gft/runs/9460/specs)
TEST START: 2024-01-26T14:48:38.540Z
TOTAL: 367
SUCCESS: 358
FAIL: 6
SKIPPED: 3

2024-01-26 15:36 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10356](http://condorpiedra.andes.gob.ar:85/10356/mochawesome.html)
CYPRESS RUN: [9463](https://dashboard.cypress.io/projects/xr7gft/runs/9463/specs)
TEST START: 2024-01-26T15:35:38.667Z
TOTAL: 401
SUCCESS: 392
FAIL: 6
SKIPPED: 3

2024-01-26 16:55 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10359](http://condorpiedra.andes.gob.ar:85/10359/mochawesome.html)
CYPRESS RUN: [9466](https://dashboard.cypress.io/projects/xr7gft/runs/9466/specs)
TEST START: 2024-01-26T16:54:23.916Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-29 16:14 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10379](http://condorpiedra.andes.gob.ar:85/10379/mochawesome.html)
CYPRESS RUN: [9486](https://dashboard.cypress.io/projects/xr7gft/runs/9486/specs)
TEST START: 2024-01-29T16:12:51.093Z
TOTAL: 347
SUCCESS: 335
FAIL: 9
SKIPPED: 3

2024-01-29 16:34 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10381](http://condorpiedra.andes.gob.ar:85/10381/mochawesome.html)
CYPRESS RUN: [9488](https://dashboard.cypress.io/projects/xr7gft/runs/9488/specs)
TEST START: 2024-01-29T16:34:15.094Z
TOTAL: 401
SUCCESS: 394
FAIL: 4
SKIPPED: 3

2024-01-29 19:06 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10386](http://condorpiedra.andes.gob.ar:85/10386/mochawesome.html)
CYPRESS RUN: [9493](https://dashboard.cypress.io/projects/xr7gft/runs/9493/specs)
TEST START: 2024-01-29T19:05:47.794Z
TOTAL: 343
SUCCESS: 339
FAIL: 1
SKIPPED: 3

2024-01-30 11:54 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10391](http://condorpiedra.andes.gob.ar:85/10391/mochawesome.html)
CYPRESS RUN: [9498](https://dashboard.cypress.io/projects/xr7gft/runs/9498/specs)
TEST START: 2024-01-30T11:53:43.384Z
TOTAL: 91
SUCCESS: 0
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 12:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10394](http://condorpiedra.andes.gob.ar:85/10394/mochawesome.html)
CYPRESS RUN: [9501](https://dashboard.cypress.io/projects/xr7gft/runs/9501/specs)
TEST START: 2024-01-30T12:47:11.334Z
TOTAL: 326
SUCCESS: 308
FAIL: 16
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 13:20 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [10395](http://condorpiedra.andes.gob.ar:85/10395/mochawesome.html)
CYPRESS RUN: [9502](https://dashboard.cypress.io/projects/xr7gft/runs/9502/specs)
TEST START: 2024-01-30T13:20:33.771Z
TOTAL: 401
SUCCESS: 397
FAIL: 1
SKIPPED: 3

2024-01-30 13:59 UTC, silviroa commented
USUARIO: silviroa  
BUILD NUMBER: [10397](http://condorpiedra.andes.gob.ar:85/10397/mochawesome.html)
CYPRESS RUN: [9504](https://dashboard.cypress.io/projects/xr7gft/runs/9504/specs)
TEST START: 2024-01-30T13:58:29.488Z
TOTAL: 295
SUCCESS: 277
FAIL: 15
SKIPPED: 3
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2024-01-30 15:48 UTC, silviroa commented
USUARIO: lmlagos  
BUILD NUMBER: [10399](http://condorpiedra.andes.gob.ar:85/10399/mochawesome.html)
CYPRESS RUN: [9506](https://dashboard.cypress.io/projects/xr7gft/runs/9506/specs)
TEST START: 2024-01-30T15:48:02.820Z
TOTAL: 401
SUCCESS: 399
FAIL: -1
SKIPPED: 3

2024-01-31 14:55 UTC, merged