IN - Reporte indicaciones de medicamentos
andes/api pull request #1883
Opened 2024-04-08 11:29 UTC by aldoEMatamala

### Requerimiento

https://proyectos.andes.gob.ar/browse/IN-574
### Funcionalidad desarrollada 

  1.  reporte de los pedidos de medicamentos de un sector para realizar el control de entrega de medicación 
  2 .extraccion de una planilla con la siguiente información: DNI paciente / sector / unidad org./ cama actual/ los datos del medicamento, filtros por sector, unidad organizativa y por nombre de medicamento para un efector.
  3. Descarga en csv

### UserStories llegó a completarse

- [ x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

2024-04-18 16:02 UTC, MarianoCampetella requested changes

2024-05-21 19:15 UTC, aldoEMatamala commented on modules/rup/internacion/internacion.routes.ts
> +    } else { organizacionId = Auth.getOrganization(req); }
corregido gracias!

2024-05-22 14:28 UTC, negro89 approved these changes
codigo ok

2024-05-28 16:07 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/api/assets/123381977/7c1e6930-3c95-4c2a-a75e-3d5ae52f9492)

2024-06-18 14:47 UTC, MarianoCampetella approved these changes

2024-07-18 16:07 UTC, merged