MAT - Implementar mockup guia profesional
andes/api pull request #1885
Opened 2024-04-10 17:32 UTC by aldoEMatamala

### Requerimiento

https://proyectos.andes.gob.ar/browse/MAT-164
https://github.com/andes/matriculaciones/pull/216
### Funcionalidad desarrollada 

1. Se agrega atributo 'habilitado' para el get de guiaProfesional

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2024-04-11 15:24 UTC, AgosLizzi requested changes
Aldo, hay posibilidad de achicar un poco el tamaño de los cards? y de agregarle el color, por fa? 
![image](https://github.com/andes/api/assets/72876985/468edb4e-8662-4f93-89ea-35092c33cf20)

- Otra cosita que vi, cuando cambio de filtro estaría bueno que se limpien los datos, para que no se genere confusión. Te dejo video: https://www.loom.com/share/bb61a1298c1146c48e6633e2b4475a41

2024-04-25 17:43 UTC, aldoEMatamala commented
> Aldo, hay posibilidad de achicar un poco el tamaño de los cards? y de agregarle el color, por fa? ![image](https://private-user-images.githubusercontent.com/72876985/321687251-468edb4e-8662-4f93-89ea-35092c33cf20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTM5OTksIm5iZiI6MTcxNDA1MzY5OSwicGF0aCI6Ii83Mjg3Njk4NS8zMjE2ODcyNTEtNDY4ZWRiNGUtODY2Mi00ZjkzLTg5ZWEtMzUwOTJjMzNjZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE0MDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NDIxN2UwZTFjM2I2NjRhNTRhNTJkMzYxOWY1ZGE5NWFjNTBkYWQyMjI3NTg3NTdkNTM2MDdhZWQ0MWQ1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aoo_U6Ajth1Qd3jnbC3dDvFqI5lS7Hmy618ECQ77i3k)
> 
>     * Otra cosita que vi, cuando cambio de filtro estaría bueno que se limpien los datos, para que no se genere confusión. Te dejo video: https://www.loom.com/share/bb61a1298c1146c48e6633e2b4475a41
Hola Agos! gracias por las observaciones, se modificó lo siguiente
1- Se limpia listado cuando se modifica el filtro de opción
2- Se cambia tamaño de los plex-card al agregar una columna al grid. Quedan 4 columnas.
3- Se cambian colores de contorno de los plex-card dependiendo del estado de la matricula
![imagen](https://github.com/andes/api/assets/123381977/2eba90b4-044a-445e-8565-c9bb43919bd8)

2024-06-04 13:05 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/api/assets/123381977/2db845f9-de8d-4751-8376-07a5dacfdfb9)

2024-08-15 13:09 UTC, MCele approved these changes

2024-08-15 15:51 UTC, merged