AM - Renovacion Matricula: act. datos de contactos
andes/api pull request #1928
Opened 2024-07-22 00:00 UTC by Fabio-Ramirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/AM-296

### Funcionalidad desarrollada 

1. Se realizan cambios de contactos en las colecciones authUsers, Profesional y pacienteApp.
2. Al momento de renovar la matricula, el profesional tenga la posibilidad desde la mobile, modificar su contacto

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2024-10-23 14:19 UTC, silviroa requested changes

2024-10-23 14:19 UTC, silviroa commented on core/tm/routes/profesional.ts
>              profesional.domicilios = req.body.domicilios ? req.body.domicilios : req.body.domiciliosMobile.domicilios;
Si se llama desde matriculaciones el campo domiciliosMobile no llega, por lo que habría que agregar un control. 
En el caso. de domicilios si no llega ese campo. se va a pisar con un null lo que tenga registrado. el profesional antes del update

2024-10-25 17:31 UTC, Fabio-Ramirez commented on core/tm/routes/profesional.ts
>              profesional.domicilios = req.body.domicilios ? req.body.domicilios : req.body.domiciliosMobile.domicilios;
Genial chichi, queda subido el cambio.

2026-04-16 14:59 UTC, negro89 approved these changes

2026-04-16 16:47 UTC, merged