feat(CIT-293)Cerrar demanda insatisfecha
andes/api pull request #1937
Opened 2024-08-06 18:34 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/CIT-293
https://proyectos.andes.gob.ar/browse/CIT-276

### Funcionalidad desarrollada 

1. Se agregan nuevos controles para poder almacenar el cierre de las demandas insatisfechas. 
2. 
3. 

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

2024-08-13 13:47 UTC, negro89 requested changes

2024-08-13 13:47 UTC, negro89 commented on modules/turnos/routes/listaEspera.ts
> +            data.save((errUpdate) => {
acá tambien debería usarse await

2024-08-13 13:47 UTC, negro89 commented on modules/turnos/routes/listaEspera.ts
> +    listaEspera.findById(req.params.id, async (err, data: any) => {
En api siempre se priefiere el uso de await https://github.com/andes/andes/wiki/5---Gu%C3%ADa-de-desarrollo#async-vs-promises

2024-08-13 13:47 UTC, negro89 commented on modules/turnos/routes/listaEspera.ts
> +                        const turnoAgenda = agenda.bloques.map(bloque => bloque.turnos.find(t => t._id.toString() === req.body.turno.id));
Esta búsqueda no es correcta ya que el map no tiene condición de corte, por lo tanto va a recorrer todos los bloques y el arreglo resultante va a ser un array con 'undefined' en la posición de los bloques que no lo encuentre y el valor correcto en la posición del bloque que el find sea true.

2024-08-16 12:06 UTC, MarianoCampetella commented on modules/turnos/routes/listaEspera.ts
> +                    await Agenda.findById(req.body.turno.idAgenda, (error, agenda: any) => {
Corregido!

2024-08-16 12:07 UTC, MarianoCampetella commented on modules/turnos/routes/listaEspera.ts
> +            data.save((errUpdate) => {
Agregado!

2024-08-16 12:07 UTC, MarianoCampetella commented on modules/turnos/routes/listaEspera.ts
> +    listaEspera.findById(req.params.id, async (err, data: any) => {
Corregido!

2024-08-16 12:07 UTC, MarianoCampetella commented on modules/turnos/routes/listaEspera.ts
> +                        const turnoAgenda = agenda.bloques.map(bloque => bloque.turnos.find(t => t._id.toString() === req.body.turno.id));
Corregido, se remplazo por un flatMap!

2024-08-26 15:49 UTC, negro89 approved these changes

2024-08-27 15:24 UTC, JuanIRamirez approved these changes
Funcionam. OK

2024-08-27 16:03 UTC, merged