AM - Nuevas rutas efectores Region Araucanía (Chile)
andes/api pull request #1950
Opened 2024-08-25 18:57 UTC by JuanIRamirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/AM-312

### Funcionalidad desarrollada 

1.  Nuevas rutas (resouceBase) en ./core/tm/areaAraucania.routes.ts
2.  GET todos los efectores: /api/core/tm/areaAraucania
3.  GET un efector: /api/core/tm/areaAraucania/id

### UserStories llegó a completarse

- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

2024-08-26 13:22 UTC, silviroa requested changes
La ruta de get, al menos, debería esta liberada.. no debería requerir autenticacion

2024-08-27 12:16 UTC, JuanIRamirez commented
> La ruta de get, al menos, debería esta liberada.. no debería requerir autenticacion. Los datos de longitu y latitud deberían ser Double, no int

Listos los cambios.

2024-09-04 14:20 UTC, silviroa approved these changes

2024-09-05 13:07 UTC, negro89 approved these changes

2024-09-05 13:08 UTC, merged