IN - Eliminar ingresos duplicados
andes/api pull request #1991
Opened 2024-11-08 17:18 UTC by Fabio-Ramirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/IN-598

### Funcionalidad desarrollada 

1. El script elimina las internaciones con egresos duplicados que quedaron en base.
2. En caso de egreso duplicado, se elige el egreso con la fecha mas reciente.

### UserStories llegó a completarse

- [x] Si
- [ ] No

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

2024-11-13 18:39 UTC, MarianoCampetella commented
A modo de comentario, en la BD tengo cargado un egreso duplicado con fecha del 06/11/2024 pero al momento de ejecutar dentro de mi terminar node jobs/manual.js scripts/IN-598.js 2024-11-01 2024-11-31 no me lo modifica. Si a nadie le sucede lo mismo entonces el PR se encontraría aprobado.

2024-11-19 15:58 UTC, Fabio-Ramirez reviewed
Compa, utilizando la BD de Demo, no encuentro la internación en la fecha que mencionas, en todo caso si me podés compartir el registro que utilizaste, quedo atento.

2024-11-19 16:01 UTC, Fabio-Ramirez commented
> A modo de comentario, en la BD tengo cargado un egreso duplicado con fecha del 06/11/2024 pero al momento de ejecutar dentro de mi terminar node jobs/manual.js scripts/IN-598.js 2024-11-01 2024-11-31 no me lo modifica. Si a nadie le sucede lo mismo entonces el PR se encontraría aprobado.
Compa, utilizando la BD de Demo, no encuentro la internación en la fecha que mencionas, en todo caso si me podés compartir el registro que utilizaste, quedo atento.

2024-11-29 13:30 UTC, MarianoCampetella commented
[egresoDuplicado.txt](https://github.com/user-attachments/files/17959734/egresoDuplicado.txt)
Fabi ahi te dejo un ejemplo donde pongo el comando que dejaste en la descripcion: node jobs/manual.js scripts/IN-598.js 2024-11-05 2024-11-09 y no me esta borrando el egreso duplicado. Cualquier cosa escribime en privado o si alguien mas lo prueba y le funciona entonces estaría bien!

2024-12-06 13:47 UTC, Fabio-Ramirez commented
> [egresoDuplicado.txt](https://github.com/user-attachments/files/17959734/egresoDuplicado.txt) Fabi ahi te dejo un ejemplo donde pongo el comando que dejaste en la descripcion: node jobs/manual.js scripts/IN-598.js 2024-11-05 2024-11-09 y no me esta borrando el egreso duplicado. Cualquier cosa escribime en privado o si alguien mas lo prueba y le funciona entonces estaría bien!

Compa, gracias por la observación, tenias toda la razón, en este ejemplo en particular q enviaste, sucedía que no estaba contamplando el caso de egresos duplicados que además de la misma fecha, tengan el mismo horario. Además, me sirvio para agregar una modificación donde el script abarque todo el dia que ingresa en el parametro de "fecha fin".

2024-12-19 14:09 UTC, negro89 requested changes
Fabio, estan bien detectados los movimientos duplicados pero dejo un par de sugerencias en el código. Además recordar que el movimiento que debería prevalecer es el que tiene misma fecha que la prestación. Con respecto a esto ultimo..
1. La prestación debería existir, de lo contrario hay un error.
2. Si ninguno de los dos movimientos coincide con la prestación, modificar alguno para que coincida.

❗IMPORTANTE: Al recorrer los estados/movimientos buscando duplicados, tener en cuenta que pueden existir anulados (deletedAt: Date) que deben ser omitidos.

2025-01-03 13:48 UTC, Fabio-Ramirez commented on scripts/IN-598.ts
> +        ? moment(paramFin).endOf('day').format('YYYY-MM-DD HH:mm:ss')
agregado

2025-01-03 13:48 UTC, Fabio-Ramirez commented on scripts/IN-598.ts
> +                    return (fechaConvertida === fecha && e.extras?.idInternacion?.toString() === idInternacion.toString()
Agregado.

2025-01-27 18:49 UTC, negro89 reviewed
Fabi, dejo comentarios segun lo charlado en la meet.

2026-04-08 13:44 UTC, closed without merging